### ISSUE TITLE
Automatically create and use settings.ini file in user-specific location

### ISSUE THREAD

**Issue by FichteFoll** [Bionus/imgbrd-grabber#1018]
Note that I'm running Arch.

This is the only application I know where you have to manually copy some files to your home folder in order to get persistent settings storage (according to the wiki). It shouldn't have to be this way.

1. Configuration should, by default, be stored in `$XDG_CONFIG_HOME/Grabber` or, as a fallback, in `$HOME/.config/Grabber` (not `$HOME/.Grabber`).
2. The required configuration file, `settings.ini`, should be created and saved to automatically by the application and not require user interaction.
3. (Optional) load other resource files from this configuration dir if they exist, otherwise fall back to installation default (platform-dependant).

I don't know how this is implemented for Windows. From what I read in the context of a few commits, it appears this is mostly designed as a portable application, saving configuration and stuff in adjacent paths, while still having workarounds for "installations" in Program Files, which requires admin privileges to write.
I suggest to implement a proper portable mode and a default mode, where configuration is read from a user-specific configuration directory, much like I suggested for Linux systems. On Windows, that would be `%APPDATA%\Grabber`.

(Btw, #1012 isn't on the `master` branch yet, which is why everyone installing this from the AUR cannot have their settings saved, regardless of whether `~/.Grabber/settings.ini` exists.)

**Comment by Bionus** [comment]
> Configuration should, by default, be stored in $XDG_CONFIG_HOME/Grabber or, as a fallback, in $HOME/.config/Grabber (not $HOME/.Grabber).

So you mean make install should copy the files in `~/.config/Grabber` instead of `/share/Grabber`?

> The required configuration file, settings.ini, should be created and saved to automatically by the application and not require user interaction.

It is, but the "default" location can vary that's why the install process is to put it wherever you want your other config files to be loaded from. It doesn't necessarily need user interaction and could be done in the install step.

> (Optional) load other resource files from this configuration dir if they exist, otherwise fall back to installation default (platform-dependant).

That's the case for a few files already actually, notably the language files, which are (on Windows) in Program Files (as in "same folder as the binary") while the rest of the configuration is in the default configuration folder (AppData).

> I don't know how this is implemented for Windows. From what I read in the context of a few commits, it appears this is mostly designed as a portable application, saving configuration and stuff in adjacent paths, while still having workarounds for "installations" in Program Files, which requires admin privileges to write.
> I suggest to implement a proper portable mode and a default mode, where configuration is read from a user-specific configuration directory, much like I suggested for Linux systems. On Windows, that would be %APPDATA%\Grabber.

In all versions you have a choice to make the application portable by putting everything in the same folder. The location of most configuration files is determined by where the `settings.ini` file is located.

It itself if discovered in folders in this order:
* Binary location
* Current location
* `~/Grabber`
* `~/.Grabber`
* `$PREFIX/share/Grabber`

> (Btw, #1012 isn't on the master branch yet, which is why everyone installing this from the AUR cannot have their settings saved, regardless of whether ~/.Grabber/settings.ini exists.)

Yeah my bad, I'll be merging that along the 5.5.0 release very soon.

**Comment by FichteFoll** [comment]
>So you mean make install should copy the files in ~/.config/Grabber instead of /share/Grabber?

No, make install cannot do this. `$HOME` is holy land for package managers and never to be touched. 

Consider this: packages are installed as root. The root user's `$HOME` dir is `/root`. Every other user's home dir is a folder in `/home`. Because packages are bundled for the root user to be installed, they do not know about any other users on the system and do not know where to put user-specific files (i.e. they cannot access, say, `/home/fichte`). As a result, no user-specific configuration files can be created during installation.

Now, what *can* access `$HOME` is the application itself, because that will be run by the user (and not root), which is why it should take care of creating the initial configuration file (or just saving it when asked to).

`$PREFIX/share/Grabber` just serves as a folder for non-binary resource files used by the application. That's a policy of the [Linux Filesystem Hierarchy](http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/c23.html) (nore that `$PREFIX` is usually `/usr`). From the application's point of view, this can be considered the binary location (i.e. the installation directory). 

Maybe @Flat can explain this better. I'm only starting to use this program.

**Comment by Flat** [comment]
I believe what @FichteFoll is trying to convey is Grabber should automatically create `$XDG_CONFIG_DIR/Grabber/settings.ini` (or in the case `$XDG_CONFIG_DIR` isn't set `~/.config/Grabber/settings.ini`) if it does not already exist instead of failing to load. This file cannot be installed by the package as files in a user's home on Linux are not to be touched by any system processes including program/package installation. This would need to be a function inside of grabber. It should also automatically create and manage any other settings files - resources that are static or shouldn't be written to by the program are fine to load from `/usr/share`

**Comment by Bionus** [comment]
So from what I understand, the `install` step should not change, copying everything in `/share/Grabber/`.

Then, on first run, if Grabber cannot find any settings file, it should create it in the config directory (for `~/.config/Grabber/`). Afterwards, when Grabber needs a resource file, it should check first in `~/.config/Grabber/` and if it's not there (static read-only resources) in `/share/Grabber/`.

Is `XDG_CONFIG_DIR` a standard or distribution-specific?

**Comment by Flat** [comment]
Correct. The `XDG_CONFIG_DIR` is a standard https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html not all desktop environments implement it but most do.

**Comment by FichteFoll** [comment]
Btw, note that the variable name is `XDG_CONFIG_HOME`, not `XDG_CONFIG_DIR`.

I saw that you "fixed" this in a commit, though it doesn't address the non-standard paths for the config location. Should I add that as a new issue or will this issue remain open?

**Comment by Bionus** [comment]
You can see that the default path used is `QStandardPaths::AppConfigLocation`:
https://github.com/Bionus/imgbrd-grabber/blob/develop/lib/src/functions.cpp#L232

This path respects `XDG_CONFIG_HOME`:
https://github.com/qt/qtbase/blob/5.8/src/corelib/io/qstandardpaths_unix.cpp#L104-L117

It will also default to `~/.config` if empty.

**Comment by FichteFoll** [comment]
Nice, didn't think of looking up `QStandardPaths::AppConfigLocation`. All good then 👍 

Eagerly awaiting the next release to finally be able to use this program properly.

**Comment by Bionus** [comment]
The release should be this weekend, either Saturday or Sunday. :+1:

**Comment by FichteFoll** [comment]
Unfortunately, this doesn't work correctly because [the check for PREFIX + "/share/Grabber"](https://github.com/Bionus/imgbrd-grabber/blob/95e15939ca4db8d4f368107916002da724ea75bb/lib/src/functions.cpp#L234) always succeeds, since this is created on installation but not writable. Considering this is within a function called `savePath`, this probably shouldn't be there.

**Comment by Bionus** [comment]
Have you tried it and it didn't work or is that theoretical?
And if you tried, which part failed? I don't have access to my VM right now.

Because since the check is based on the presence of the `settings.ini` file, unless the `exists` parameter is set to true, it shouldn't look into "/share/Grabber" for most files.

**Comment by FichteFoll** [comment]
I have tried it. Settings are only saved if `~/.Grabber` exists. If I rename that folder and restart it, settings are not stored anywhere, i.e. not in `~/.Grabber` and not in `~/.config/Bionus/Grabber`.

**Comment by Bionus** [comment]
Ok thanks for the info! :smile:
I can see why this would happen. I'll do some more testing and push a fix.

**Comment by FichteFoll** [comment]
Still a problem on `v7.1.1.r3.1254e59f-1` when I was wondering why my settings weren't saved.

**Comment by FichteFoll** [comment]
Fixed by #1797 from a quick review of the code paths of `savePath`.
