### ISSUE TITLE
Negative numbers and crashes during large downloads

### ISSUE THREAD

**Issue by alicemargatroid** [Bionus/imgbrd-grabber#1022]
### What steps will reproduce the problem?
Search for "hakurai_reimu" on all boorus, do a mass download

https://i.imgur.com/mUenR7O.png

### What is the expected behavior? What do you get instead?
I get negative numbers as the actual amount of images (probably due to too many images causing the integer type to overflow). This also causes crashes on basically every booru if parallel downloads are enabled

### How often does this problem occur?
Every time

### What version of the program are you using? On what operating system?
5.4.2, Windows 10 and Ubuntu 16.04

### Please provide any additional information below
A larger integer type needs to be used for the number of possible images to download.
A consistent integer type should be used, so the UI doesn't display negative numbers.
If parallel downloads are enabled on large downloads, maybe just disable them rather than crash?

**Comment by MasterPetrik** [comment]
How many images are you downloading before crash?

**Comment by alicemargatroid** [comment]
@MasterPetrik It's relatively random. Let me get those for you.

**Comment by alicemargatroid** [comment]
IGL file

**Comment by alicemargatroid** [comment]
[main.txt](https://github.com/Bionus/imgbrd-grabber/files/1220539/main.txt)

main.log

**Comment by alicemargatroid** [comment]
[3fd6c5ae-a719-4365-8826-cc3e2837fca2.txt](https://github.com/Bionus/imgbrd-grabber/files/1220540/3fd6c5ae-a719-4365-8826-cc3e2837fca2.txt)

crash log

**Comment by Bionus** [comment]
The `int` integer type being used is 32 bytes (built on my machine), so I doubt it would overflow in normal circumstances. On the default build, the number can reach 2^31 without issues. I could replace instances of `int` in this situation by `long` or `qint32` to enforce 2^31 max value, but given Qt internally uses the `int` type in many places, it wouldn't really fix much.

Is your OS x86 and are you building the program yourself? Since you mention "Windows 10 and Ubuntu 16.04" and are providing a W10 screenshot I'm not sure.

>  If parallel downloads are enabled on large downloads, maybe just disable them rather than crash?

I'm not sure I understand this point.

I'll take a look at your log and see what could have caused the crash.

**Comment by alicemargatroid** [comment]
I did not manually build this, both OS's are 64 bit, I'm getting negative numbers which usually indicates a signed int rolling over.

**Comment by alicemargatroid** [comment]
@Bionus Still happening

![](https://i.imgur.com/EcvQ2g5.png)

**Comment by MasterPetrik** [comment]
Try to enable https on Gelbooru source
