### ISSUE TITLE
Keep a local database of tags to prevent unnecessary requests

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#1033]
From issue #995.

Note that the tag databases can already be used as a beta feature using the new tool available in the "Tools" menu. It shouldn't cause bugs but note that this database doesn't update by itself and not all sources work with this tool. So as always use at your own risk. It's also unnecessary for sources that provide complete tag information (danbooru.donmai.us & e621).

**Comment by InfernalUnderling** [comment]
> the tag databases can already be used as a beta feature using the new tool available in the "Tools" menu.

Can these databases be used on other sites by copying the database file to the correct locations at the moment?
I'm runnig a self-compiled build of the January 29th commit, and I tried making a db for gelbooru and copying it to both the sites/Shimmie dir, and creating the "rule34.paheal.net" dir inside Shimmie and copying them there as well, but tag info still doesn't seem to work on paheal with the "tags.txt" and "tag-types.txt" from gelbooru in either location.
Not sure if I'm just doing something wrong, or if not all sites try to load a local types db yet.

**Comment by Bionus** [comment]
Normally yes, as long as the tags.txt / tags.db file and the tag-types.txt match.
Make  sure to close the program before you do any operation on the files though.

> creating the "rule34.paheal.net" dir inside Shimmie and copying them there as well

If you already added this source and already set some settings, the directory should already exist. Are you sure you're looking in  the right folder?

**Comment by InfernalUnderling** [comment]
Editing a setting for the site did make the directory show up on its own. Thanks.

Strangely, the tags look like they're getting recognized on the list of tags on the left pane (when the gelbooru db is copied over, the tags now have color, where they where all black before). When downloading an image, however, the image gets put into "anonymous" instead of the artist's name folder.
Additionally, when clicking on an image, the tags in the new window have color for a split second, and then revert to the plain black of an generic tag. (Program is possibly still attempting to get categories, but failing?)

Also, paheal seems to use tags with uppercase, and thus many tags don't get recognized since the gelbooru tags are lower case.

If you'd like, I can put this stuff into an issue of its own instead of posting in this one, now that I know that the tag db's are, indeed, supposed to work.
