### ISSUE TITLE
Slower Gelbooru Downloads

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#1037]
### What steps will reproduce the problem?
Download (Possibly .webm)/nopicture heavy tags from Gelbooru, possibly using one's account details

### What is the expected behavior? What do you get instead?
I've noticed that downloading from Geblooru has become increasingly slow, prone to freeze meaning I have to exit the download entirely or press skip to possibly get a download working

### How often does this problem occur? On which sources?
Gelbooru, it's pretty frequent, and I've not noticed any other sources acting like this, I've tried with and without the proxy I use, so it doesn't seem to make a difference

### What version of the program are you using? On what operating system?
5.5.0 Win7HomeE

**Comment by MasterPetrik** [comment]
Are you sure, that the problem is on the Grabber side? 
More likely it's problem on the server side.

Anyway, if you think that problem is in last grabber version, try to download previous version https://github.com/Bionus/imgbrd-grabber/releases/tag/v5.4.2
and tell me, does the problem still occurs. Thanks.

**Comment by Xathos** [comment]
I had the same issue uninstalling, restarting my pc and then installing it again fixed it.

**Comment by MasterPetrik** [comment]
looks similar to https://github.com/Bionus/imgbrd-grabber/issues/1042 issue
try to turn on HTTPS in gelbooru source settings, it may help
