### ISSUE TITLE
Use IDs instead of dates for the favorites "last viewed" information

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#1058]
Since IDs are chronologically ordered (unless some very big problem with your source), instead of storing the last time the favorites where viewed, Grabber could store the highest ID of each source.

This could help supporting sources that do not provide date information.

Follows #1041.

**Comment by Bionus** [comment]
Removed from 7.0.0 as the cost is much higher than planned.

Will be done at the same time as the favorite re-work.

**Comment by FichteFoll** [comment]
I think this strongly relates to #1416.
What are the planned changes for the favorites feature? I've only started using it today, because documentation on it was rather sparse. After having used it for a bit, they feel more like a "follow" list, though I guess that's just a naming thing.

Regardless, while the favorites feature was something I was looking for, it certainly has a couple rough edges. For example, when there is a huge-ish list or even just 400 images total, it may take a while to browse through all of them. From how the feature currently works, it makes sense to start with the oldest image and then move backwards as you adjust the "Last view" setting to when the last image you viewed has been added. However, there is no shortcut or context menu on an image to say "please mark this as the last viewed image", so you have to fetch the image's upload time and insert it into the favorite setting manually. 

I'm not sure if commenting on this issue is correct or whether I should open a new one.

**Comment by Bionus** [comment]
> I think this strongly relates to #1416.

I don't think so, as this issue is purely a technical one to avoid a potential bug on a few sources, while the one you mention is about quality of life improvements / new features around favorites.

> Regardless, while the favorites feature was something I was looking for, it certainly has a couple rough edges. For example, when there is a huge-ish list or even just 400 images total, it may take a while to browse through all of them. From how the feature currently works, it makes sense to start with the oldest image and then move backwards as you adjust the "Last view" setting to when the last image you viewed has been added. However, there is no shortcut or context menu on an image to say "please mark this as the last viewed image", so you have to fetch the image's upload time and insert it into the favorite setting manually.
>
> I'm not sure if commenting on this issue is correct or whether I should open a new one.

Your suggestion indeed makes sense, however I suggest opening another issue as one issue should only be about a single thing. Otherwise your suggestion might be lost once the initial subject of this issue is resolved.

> By the way, what does the "Note" field do or represent? It's not intuitive and not documented.

It's a value from 0 to 100 that you can use for sorting.
Can be useful to sort your favorites in whatever way you want.

**Comment by FichteFoll** [comment]
> I don't think so, as this issue is purely a technical one to avoid a potential bug on a few sources, while the one you mention is about quality of life improvements / new features around favorites.

I think you're right. This issue here (#1058) only tangentially relates to my issues for the "use this entry as the base for a filter" feature, which I copied to #1970. 

It's only my other broader problem (#1971) that would be solved by #1416.
