### ISSUE TITLE
Favorite Counter Notification Icon

### ISSUE THREAD

**Issue by SteelCognito** [Bionus/imgbrd-grabber#1060]
[SUGGESTION] I want to share an idea!

![ideabot](https://user-images.githubusercontent.com/31747256/30187195-e76d6036-9428-11e7-941f-23ab29e980b6.png)

**Comment by Bionus** [comment]
Well that certainly looks like a good idea!

However, that would require actually making requests to the server every X period to check for favorite updates. If you have a lot of favorites, that could quickly cause a lot of requests at once, especially at startup where all counters will expire at the same time. So on a technical point of view, this would require some thinking to not cause an instant 100 requests at startup.

* One option would be to trigger it manually only,  but that would be counter-intuitive and make the feature useless.
* The expiration times could also depend on the favorite "activity" (number of new images per day in average), but I'm not a big fan of hidden "magic" in programs.
* Another option could also to simply make let's say 1 favorite "check" query per second since startup until all favorites are checked. That sounds like the most reasonable option.

**Comment by MasterPetrik** [comment]
Yes, that's a good idea. 
But It require a proper implementation:

1. Of cource this counter icons should can be disabled/enabled in settings.
2. Also should be settings to set refresh interval for that.(and something like "-1" interval for not auto refreshing)
3. Counters data should be stored in separate file(like tabs or session file), so after programm startup just load values from this file, and time to time refreshing one by one all favourites with instant changing values in the file too. So user always will see mostly relevant info without extra system load.
4. Place of the icons is a discussable question.

**Comment by SteelCognito** [comment]
I'm glad you like the idea. but the most important part is thanks to you I have the best booru experience I've ever had with Grabber! thank you bionus.
