### ISSUE TITLE
'You can’t open the application “Grabber_5.5.0_mac.app” because it may be damaged or incomplete.'

### ISSUE THREAD

**Issue by NavinF** [Bionus/imgbrd-grabber#1066]
OS: macOS Sierra 10.12.6 (16G29)

1. Download https://github.com/Bionus/imgbrd-grabber/releases/download/v5.5.0/Grabber_5.5.0_mac.app.zip  
2. Double-click to extract the zip with the default app (Apple's Archive Utility)  
3. Run Grabber_5.5.0_mac.app to get this error message:

> You can’t open the application “Grabber_5.5.0_mac.app” because it may be damaged or incomplete.

If I rename "Grabber_5.5.0_mac.app" to "Grabber.app" (The same filename used by older releases because the older zip contained a "Grabber.app" folder while the latest release doesn't), I get a different error:

> Grabber cannot be opened because of a problem.
> 
> Check with the developer to make sure Grabber works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.
> 
> Click Report to see more detailed information and send a report to Apple.

> Termination Reason:    DYLD, [0x3] Wrong version
> 
> Application Specific Information:
> dyld: launch, loading dependent libraries
> 
> Dyld Error Message:
>   Library not loaded: /usr/local/opt/qt/lib/QtMultimedia.framework/Versions/5/QtMultimedia
>   Referenced from: /Applications/Grabber.app/Contents/MacOS/Grabber
>   Reason: Incompatible library version: Grabber requires version 5.9.0 or later, but QtMultimedia provides version 5.8.0
> 
> Binary Images:
>        0x10f6dd000 -        0x10f9c0ff3 +Grabber (0) <9F021272-9AF4-39F1-BF9A-88923E2901D9> /Applications/Grabber.app/Contents/MacOS/Grabber
>        0x118a8f000 -        0x118accdc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
> 

I fixed that by running `brew upgrade qt5` and it looks like everything works again :)

I also noticed that `otool -L Grabber.app/Grabber` prints lots of stuff under `/usr/local/opt/`. Was that intentional? I think those deps should be static-linked or included in the .app and referenced as `@executable_path/../Resources/lib/lib*.dylib`.

**Comment by Bionus** [comment]
So from what I understand, instead of having directly the contents of the app, `Grabber_5.5.0_mac.app` should contain a single folder named `Grabber.app` (as in previous releases) to work properly?

What about the `Contents` / `MacOS` / `Info.plist` and others?
I have to admin I have little knowledge of the MacOS app structure.

> I fixed that by running brew upgrade qt5 and it looks like everything works again :)

Yeah, the Mac build is always done using the very latest brew Qt release in Travis. I could try to force a given version (such as 5.4.0) but I'm not sure there'd be much to gain from it.

> I also noticed that otool -L Grabber.app/Grabber prints lots of stuff under /usr/local/opt/. Was that intentional? I think those deps should be static-linked or included in the .app and referenced as @executable_path/../Resources/lib/lib*.dylib.

That must be the Qt libs? Those are being dynamically linked, which is why you got the other error that you fixed by updating the Qt libs through brew.

From what you say, they should be bundled within the app? (I'd rather not use static linking with Qt as the license becomes blurry) This has the pros of not needing to install Qt through brew, but the cons of having the app taking useless space if you already have Qt installed. Is providing the `dylib` files the way it's commonly done on macOS ?

**Comment by BarryMode** [comment]
I've had no issues building it, once I got set up.

**Comment by Bionus** [comment]
@BarryMode but can you run the app file provided in the release's downloads? :smile:
ex: https://github.com/Bionus/imgbrd-grabber/releases/download/v5.5.0/Grabber_5.5.0_mac.app.zip

**Comment by NavinF** [comment]
Yep, the zip file `Grabber_5.5.0_mac.app.zip` must contain a single folder named `Grabber.app`.

>What about the Contents / MacOS / Info.plist and others?

It seems to work without that folder structure: Double-clicking `Grabber.app` runs the `Grabber.app/Grabber` executable. 

That said, I just realized why the text is really blurry and unreadable on mac: You need an `Info.plist` file with `<key>NSHighResolutionCapable</key><true/>` inside it. 

I'll go ahead and send a PR soon for generating the OSX zip with an `Info.plist` :)


> Is providing the dylib files the way it's commonly done on macOS ?

Yes, unfortunately. 

Personally, I would just static-link Qt and call it a day. No more dependency woes and the file sizes are a lot smaller because of dead code removal by the compiler. 

There are no licensing issues because Qt is under the LGPL and this project already satisfies the LGPL's requirements by making source available for its binaries. This project's license can remain Apache.

**Comment by BarryMode** [comment]
The file provided is not the right structure. The user can language the grabber binary directly, but in order to use a .app file, the contents have to follow a specific structure.

Attached is the minimum for what is required. There are additional things to do if you want to set an icon.

[Grabber_5.5.0_mac.app.zip](https://github.com/Bionus/imgbrd-grabber/files/1304389/Grabber_5.5.0_mac.app.zip)

Here's a quick breakdown:

```
*.app/Contents/MacOS/binary
*.app/Contents/Pkginfo
```

That's all you need to make it functional. The contents of the Pkginfo file can be empty, it's just something the OS looks for.

**Comment by BarryMode** [comment]
I have a tad bit more information in info.plist, which is that it is required if you don't have the Pkginfo file, however, the reason I instructed it the way that I did is because the Pkginfo file can be empty, whereas info.plist has to follow a specific format to get it to run correctly.
