### ISSUE TITLE
MD5 list fixer doesn't appear to be updating the paths of images

### ISSUE THREAD

**Issue by BarryMode** [Bionus/imgbrd-grabber#1074]
Edit: After running the MD5 list fixer, it appears that the md5s list is the same as before, including the path to the files in it. If I put the files in the original folder they were downloaded into, the program sees that it has already been downloaded, however, if I move them back and run the list fixer, it doesn't fix this. This appears to be an issue with the list fixer, rather than having anything to do with symlinks at all.

~~Is this a possibility?~~

~~`grabber-points-to-this-folder/symlink/images-in-here`~~

~~Currently, the images I have stored through a symbolically linked folder are not detected to already exist.~~

**Comment by Bionus** [comment]
What do you mean they are "not detected to already exist"?

When trying to save already existing images, they are downloaded anyway? Are they also saved properly afterwards, overwriting the already existing one?

**Comment by BarryMode** [comment]
They are detected in a normal folder, but not in a symlinked folder. This is under the assumption that Grabber will detect files within subfolders, in which case it's not able to search within that symlink from what I can see. It does, of course, still detect it via MD5. I suppose that may be satisfactory if this isn't a simple thing to implement.

#### More on symlinks
I don't know the command on Windows but for Mac, it's `ln -s source destination`. It's basically a shortcut, but I don't know if it works the same way or not. I know it's different than an alias. They're all kind of the same idea though.

**Comment by Bionus** [comment]
> Is there a chance I messed it up by moving the files after download? Maybe that's why it's not working right. I noticed that the md5s file is also including the path to the file, so maybe I did. I'll try running the list fixer when I get back to my network drive.

If you moved the files, they will not be known by Grabber unless you run the MD5 fixer list. That might be the root cause of the issue here, because Qt by default follows, lists, and recurses through symlinks.

Please tell me if running the fixer fixed your problem, and if not, I'll investigate some more. :smile:

**Comment by BarryMode** [comment]
@Bionus after running the MD5 list fixer, it appears that the md5s list is the same as before, including the path to the files in it. If I put the files in the original folder they were downloaded into, the program sees that it has already been downloaded, however, if I move them back and run the list fixer, it doesn't fix this. This appears to be an issue with the list fixer, rather than having anything to do with symlinks at all.

**Comment by Bionus** [comment]
Can you tell me (feel free to obfuscate some parts if you wish):
* The original location of the files
* The new location of the files
* The save filename (before & after if you changed it)
* The save directory (before & after if you changed it)
* The filename used for the MD5 tool
* The directory used for the MD5 tool
* Whether you used "force MD5 calculation" (if you didn't, the tool will only add the files matching the filename, instead of adding all the files in the directory)

**Comment by BarryMode** [comment]
This has been long enough that I'm going to assume that I made some sort of mistake. Sorry for leaving this open for so long. Been using the October release for quite a while with no issues.
