### ISSUE TITLE
Problem with copying file to database

### ISSUE THREAD

**Issue by Flarisande** [Bionus/imgbrd-grabber#1111]
### What steps will reproduce the problem?
Download image from any imagebooru .

### What is the expected behavior? What do you get instead?
Copying file into database.

### How often does this problem occur? On which sources?
Every time.

### What version of the program are you using? On what operating system?
Program's version 5.51. Arch Linux_x64. Last version of LAMP (MariaDB as database implementation).

### Please provide any additional information below
So, at first thank you for your program, it makes really great things! And sorry for my terrible  English.

Sometimes in your release page you publish ready, compiled Linux and Windows programs' version. For example version 5.5.0 and it work properly, even with database copying. There is no issues with it. 
But in v5.5.1 user must compile program from source by myself and there is problem. I tried to use two ways to solve problem, but results is same.
At first I tried just run build.sh from terminal, it compile without any errors but in release folder I have shared library file instead of executable. It was very similar to this issues:
https://unix.stackexchange.com/questions/348983/gcc-g-compiles-code-to-shared-library-instead-of-executable
From terminal this library work fine, but it won't copy file to database.
At the second way I was using AUR:
https://aur.archlinux.org/packages/imgbrd-grabber-git/
It gives me same results - no executable file, just shared library.
I've tried to compile source version of 5.5.0 but the errors are same (but your linux-ready version work fine at this time, so problem is by my side and I just can't figure out what's wrong).
From Grabber log we have such output:
https://pastebin.com/J0nHtztp
And from the terminal emulator:
https://pastebin.com/eueUWmva

**Comment by Bionus** [comment]
You're mixing a lot of stuff so I'm not sure I understood it all.

> Sometimes in your release page you publish ready, compiled Linux and Windows programs' version. For example version 5.5.0 and it work properly, even with database copying. There is no issues with it.

Yes, it depends on the CI build system, my FTP server status and other stuff, so sometimes it's not available. Also, sometimes I simply forget to upload them since they are finished compiling after I published the release 🤷‍♂️ 

>  At first I tried just run build.sh from terminal, it compile without any errors but in release folder I have shared library file instead of executable. It was very similar to this issues:
> https://unix.stackexchange.com/questions/348983/gcc-g-compiles-code-to-shared-library-instead-of-executable
> From terminal this library work fine, but it won't copy file to database.
> At the second way I was using AUR:
> https://aur.archlinux.org/packages/imgbrd-grabber-git/
> It gives me same results - no executable file, just shared library.
>  I've tried to compile source version of 5.5.0 but the errors are same (but your linux-ready version work fine at this time, so problem is by my side and I just can't figure out what's wrong).

Definitely sounds like a problem on your end. The whole compilation is handled by CMake, which is supposed to avoid these kind of issues. Also I don't see why it would generate a shared lib for Grabber.

Especially since other users have successfully built the program on Arch before. Are you checking the right file? I just checked and the result of `file` after compilation is:
```
Grabber: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=50f672c211162ab977152ea18f13d6735055f054, not stripped
```

>  From Grabber log we have such output:
> https://pastebin.com/J0nHtztp

How did you manage to get an output from Grabber if you couldn't build it?

In any case, `Error executing command (return code: 1)` means that the command you put in Grabber settings is invalid, and its return code is 1 (instead of 0).

> And from the terminal emulator:
> https://pastebin.com/eueUWmva

Well as it says in there, `Could not open input file: UploadToShimmie.php`.

I guess you followed the [tutorial in the wiki](https://github.com/Bionus/imgbrd-grabber/wiki/Shimmie) for Shimme? It seems that the program cannot find the `UploadToShimmie.php` file. You can try to change the command to provide the full path to that file (for example, `/user/bionus/Grabber/UploadToShimmie.php`).

**Comment by Flarisande** [comment]
Yeap, seems you're totally wright. Problems were only on my side, but now, after fresh linux update, they gone for some reason. So thank you very much for answering and sorry for bothering you such newbie type of questions!
