### ISSUE TITLE
--rc(return count) option always returns wrong number

### ISSUE THREAD

**Issue by tom5079** [Bionus/imgbrd-grabber#1122]
### What steps will reproduce the problem?
grabber -s "gelbooru.com" -t "<TAG> --rc
tested tags and result:

**1girl**
real count: 2317107
--rc count: 97318116

**aqua_hair**
real count: 50609
--rc count: 2123856

**fuu_fuu**
real count: 101
--rc count: 101

### What is the expected behavior? What do you get instead?
It multiplies around 41.9 to real count. result with some tags with few images is good. but others are ...meh

### How often does this problem occur? On which sources?
ALWAYS on gelbooru.com. I didn't tested other one.

### What version of the program are you using? On what operating system?
Raspbian Wheezy, Grabber 5.5.1

**Comment by Bionus** [comment]
I can see where it could from since the source is Gelbooru and has 42 images per page (explaining the 41.9 ratio). On small searches, Gelbooru might provide the exact count, while on bigger ones Grabber will only be able to obtain the page count and guess the image count from it, and that's, where the problem seem to lie. I'll take a look and see to push a fix.

**Comment by Bionus** [comment]
This should be fixed in the last commit.

Note that you might still find some discrepancies on some big searches, where Gelbooru might report more images than Grabber. That's because a bunch of images are simply not returned by Gelbooru but still counted in their sidebar (for example some deleted images).

**Comment by tom5079** [comment]
Sounds good! Should I close this issue?

**Comment by Bionus** [comment]
If you confirm it working on your end, yes.

CLI is mainly used by people who compile the program themselves, so it doesn't really need to wait for next release (it'll be closed automatically when I release 5.5.2 otherwise).
