### ISSUE TITLE
Default preset name

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1132]
In current version, default preset has no name, and can't be renamed. That's a bad idea.
![image](https://user-images.githubusercontent.com/22294259/32331037-e1483a28-bff2-11e7-81aa-89907a41e0f3.png)

It would be better to name it as "Default" or something, and also enable renameing for it.

**Comment by Bionus** [comment]
The fact is that it's not the "Default" preset, it's the "No preset selected" option. It's made to be used when you're not using any preset, like when you're randomly selecting sources.

Hence the inability to edit/rename it. I guess I could name it as such: "_No preset selected_" instead of just blank. But it wouldn't really make sense to allow to rename/remove it with the way presets work.
