### ISSUE TITLE
I would like to know when the chan.sankakucomplex site will be supported

### ISSUE THREAD

**Issue by LucasBorgesC** [Bionus/imgbrd-grabber#1146]
### What steps will reproduce the problem?
trying to download anything on the site

### What is the expected behavior? What do you get instead?
it is loading but not low

### How often does this problem occur? On which sources?
sankaku complex

### What version of the program are you using? On what operating system?
5.5.2

### Please provide any additional information below
Sorry for my bad english

**Comment by MasterPetrik** [comment]
oh god... another one.
read this carefully - https://github.com/Bionus/imgbrd-grabber/issues/997
Sankaku devs doesn't want to Grabber support their site. And they contacted grabber dev to warn about continuins supporting sankaku.  I can understand them.
And they also changed their API to prevent that.
That's why it currently not supported in Grabber, and nobody knows will it be supported in the future.

**Comment by Bionus** [comment]
ikr?
In addition to what MasterPetrik said, you can also check #1128 for possible workarounds.
I'll be closing the issue for duplication. 😃
