### ISSUE TITLE
chan.sankakucomplex.com Issues

### ISSUE THREAD

**Issue by Scooty-BootyMan** [Bionus/imgbrd-grabber#1147]
### What steps will reproduce the problem?
Have "chan.sankakucomplex.com" activated for image searching with or without other sites, doesn't matter all that much.

### What is the expected behavior? What do you get instead?
Behavior is unpredictable. Possible outcomes being:
Just having downloads from "chan.sankakucomplex.com" will either A: hang the downloads, or B: skip and not download at all.
Odd page display behavior being "Page 1 of 0 (20 of max 0)" which is just confusing
Will also seem to crash the program altogether if left alone long enough (crashed while making this post, will have dmp file if it would help).
EDIT: Found another issue, clicking on the pic to see a bigger version will automatically default to a small preview when you first see the pic. i.e. looks really pixilated.
when disabling the site as well, the search still has it being searched (if that makes sense). This also means this will be included in downloads as well.

I should get the expected behavior of just, normal viewing and download.

### How often does this problem occur? On which sources?
Happens every single time. If by sources you mean site, then that's self-explanatory.

### What version of the program are you using? On what operating system?
I'm using Grabber 5.5.2 and Windows 10

### Please provide any additional information below

[441a956e-e6ad-48a4-85aa-5af8772157fd.zip](https://github.com/Bionus/imgbrd-grabber/files/1469623/441a956e-e6ad-48a4-85aa-5af8772157fd.zip)

**Comment by MasterPetrik** [comment]
That's because Grabber officially not sopported this source.
read this carefully - #997
Sankaku devs doesn't want to Grabber support their site. And they even contacted grabber dev to warn about continuing supporting sankaku. I can understand them.
And they also changed their API to prevent it's correct work in Grabber.
That's why it currently not supported in Grabber, and nobody knows will it be supported in the future.

**Comment by MasterPetrik** [comment]
Seriously....
![2017-11-14_165106 win7 mastercore](https://user-images.githubusercontent.com/22294259/32783329-650156d4-c95c-11e7-9838-4689a856bc9f.png)

**Comment by Scooty-BootyMan** [comment]
Oh rip, didn’t see. My bad, still though, there’s an issue with it still being in the list of images to grab, even if it’s removed from the sources list.

On Nov 14, 2017, at 8:54 AM, MasterPetrik <notifications@github.com<mailto:notifications@github.com>> wrote:


Seriously....
[2017-11-14_165106 win7 mastercore]<https://user-images.githubusercontent.com/22294259/32783329-650156d4-c95c-11e7-9838-4689a856bc9f.png>

**Comment by MasterPetrik** [comment]
>  there’s an issue with it still being in the list of images to grab, even if it’s removed from the sources list.

What do you mean " list of images to grab"? Is it a list of batch downloads? If so then it's a good question indeed.

**Comment by Bionus** [comment]
As long as the `model.xml` is not removed or the `sites.txt` file not cleared, the source is still here, even if not working.

Sankaku should no longer be included in new installations but it won't get force-removed by updates. That's because there's always workaround for issues. So if you used an old version of Grabber then updated, it will still be there. And as long as it's there, the batch downloads also.

However, if it's absent from the "Sources" window, any batch download from this site will simply be ignored from an IGL file. It may require a restart after deleting a site though.

**Comment by MasterPetrik** [comment]
Well, then not because of sankaku, but for any source would be good to make auto removing downloads from this source from batch downloads list when you delete this source. It would be very logical.

**Comment by Bionus** [comment]
Moving bug-related discussion to #1153.
Closing this issue as Sankaku-related for duplication.
