### ISSUE TITLE
Typo in about grabber.

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#1154]
![image](https://user-images.githubusercontent.com/19770864/33151259-533454ac-cfa5-11e7-9be5-174a7134ec29.png)

In the bottom, It says byr instead of by.

**Comment by MasterPetrik** [comment]
about that window... I recommend to rework it.

considering that there are more than one translation now...

**Comment by Bionus** [comment]
Any suggestions? :smile:

What I was thinking was removing the whole credits part at the bottom.
Or replace it by a more exhaustive list of contributors. However, determining who does or doesn't deserve to be in it would be a little bit too arbitrary. Plus, they may not want to be explicitly listed in it, so it would require asking permission for every single one. And limiting it to [code contributors](https://github.com/Bionus/imgbrd-grabber/graphs/contributors) would undermine the work of people who contribute via issues, so it would need to also include for example users with more than n comments/tickets in the issue tracker for example. Which is also pretty arbitrary.

**Comment by MasterPetrik** [comment]
> Any suggestions? :smile:

Yes.

> What I was thinking was removing the whole credits part at the bottom.

Very bad idea, also cropping readme is a bad idea too~
It's always better to have more info than needed than have none at all.

> Or replace it by a more exhaustive list of contributors. 

Sounds better

> However, determining who does or doesn't deserve to be in it would be a little bit too arbitrary. 

Yes, but only you should decide it.

> Plus, they may not want to be explicitly listed in it, so it would require asking permission for every single one. And limiting it to code contributors would undermine the work of people who contribute via issues, so it would need to also include for example users with more than n comments/tickets in the issue tracker for example. Which is also pretty arbitrary.

Oh... You are thinking too much about not relevant things in this case. Don't try to solve teoretical problems, when you even not sure that they would happen. It's a wrong way. Also trying to define contributors by comments/tickets is also bad idea, because tickets could be only questions and comments can be only talking, the same problem with code contributors, one guy changed one grammatical error and he is already code contributor. So trying to define contributors by checking some stats is a bad way.

## How everyone else doing Credits page(according to my user expirience):
First of all, order of this page should show decreasing importants of participants, the order:

0. One-line programm description(optional)
1. Autor info
2. Autor links(optional)
3. List of translators(all of them!) [language - translator's nickname]
4. Thanks to valuable code contrinutors(2-3 names) you check their contributing and define most valuable guys
5. Thanks for suggestions and bug reporting(2-5 most valuable persons) That's even easier to determine, try to remember who helped you the most with non programming support, in any enough big project like this always exists 2-3 active users who helping significantly much more than the others, you should mention them. 
5.1 And then you should thank all other users for contributing.(existing of this part is very important! because any not mentioned small contributor would see that you didn't forgot about his help) 
5.2 And after that you should thank all common users for using this programm.(it's another important part)
6. Mentioning all frameworks names(better in weblinks format) that used in programm: installer, icons, custom libraries etc. (optional)

And also you can add short license info at some place in the window.(optional)

That's all. You also could use scrollable textbox for items 3-6 if there will be too much info(but better evede it). Also, if some contributor good enough to for doing different help, will be fair to repeat his name in all placed he deserved. And remember that your goal is not mention everyone, don't think about what will feel not personally mentioned guys. Their not enough activity is not your problem, if the last place, they will be satisfied by text in the item 5.1 . And remember even thank without names will be much better than not mentioning community help at all. And mentioning most active participants names always motivates them and other helpers for more activity.
