### ISSUE TITLE
Fetching URL pages uses HTTP instead of HTTPS

### ISSUE THREAD

**Issue by YukiSakuma** [Bionus/imgbrd-grabber#1158]
### What steps will reproduce the problem?

Use a packet sniffer program like Wireshark

### What is the expected behavior? What do you get instead?

When fetching pages using grabber it uses HTTP instead of HTTPS and in effect you see the GET HTTP method and the plaintext URL in the packet sniffer.

### How often does this problem occur? On which sources?

This happens on any image sources that uses TLS/HTTPS

### What version of the program are you using? On what operating system?

5.5.2 Win 7

### Please provide any additional information below
I think this is more of a privacy issue.

**Comment by Bionus** [comment]
> Use a packet sniffer program like Wireshark

Note: you can use the `-d` flag to see all requests in the log.

> This happens on any image sources that uses TLS/HTTPS

Do you mean sources that accept it (which Grabber may not always respect indeed), or sources that have it enabled in their respective settings?

![image](https://user-images.githubusercontent.com/882719/33350120-75fa61c8-d49d-11e7-822b-d2ccde2cee73.png)

Because given all requests go through this code:
https://github.com/Bionus/imgbrd-grabber/blob/2843b586ee56a029fff89271ed74c6b99241c5d7/lib/src/models/site.cpp#L285-L286

It seems surprising some would keep being run on HTTP if this setting is enabled (I could not reproduce on my end).

**Comment by YukiSakuma** [comment]
I see the 'Use a secure connection' is not enabled by default, I never checked if there was such a setting, it seems the problem is resolved for now. Thanks.
