### ISSUE TITLE
the download crashes

### ISSUE THREAD

**Issue by fatzebo** [Bionus/imgbrd-grabber#1163]
### What steps will reproduce the problem?

on every 91000 file download happens

### What is the expected behavior? What do you get instead?

its crashes

### How often does this problem occur? On which sources?

everytime it gets to 91000 files

### What version of the program are you using? On what operating system?

grabber 5.5.2 Windows 10

**Comment by MasterPetrik** [comment]
Well, it's pretty common to crash after too many downloads for grabber, I wonder why it's not crashed earlier.
Of course no technical info provided. Classic.

@Bionus good moment to suggest you in second time to show a warning window those users, who want to download more than 20000 files in one try, with text about not garanteeing stable work of the programm with such big amount of files, maybe then there will be not so many so similar useless crashreports caused by overuseage of Grabber. Considering that you planning to implement https://github.com/Bionus/imgbrd-grabber/issues/1023 ideas, you don't need to think anymore about 
such overusers crash problems. Just reminding:

> Almost 80% of all sended crashes of grabber happens when user is trying to download an extreamly big amount of images(all images with very popular tag like "touhou" or all images from one booru, or even all images from all boorus). It means that fair-use users almost not face with such problems, but not-fair-users are causing problems for them by themselfs and causing problems for Dev, who need to check every single crash.
