### ISSUE TITLE
Gelbooru incorrect image url parse with .jpg extension

### ISSUE THREAD

**Issue by owrayoverfl** [Bionus/imgbrd-grabber#1179]
### What steps will reproduce the problem?
The grabber seems to default to .jpg on all urls from Gelbooru when pulling as a batch or just single selection. This doesn't reflect the actual image url for .png images on gelbooru.

### What is the expected behavior? What do you get instead?
On a download attempt, the grabber recognizes that the image cannot be retrieved and attempts to retry with a .png extension though the url string isn't actually changed according to the logs.

Note: Image is NSFW

Here's one example from my logs:
[Info] Loading image from https://simg3.gelbooru.com//images//7e/cb/7ecb37068e99b92aac65a78c83abec5a.jpg 1
[Info] Loading and saving image in (...)
[Info] Image not found. New try with extension png (https://simg3.gelbooru.com//images//7e/cb/7ecb37068e99b92aac65a78c83abec5a.jpg)...
[Error] Unable to open file (2)

The actual url should be https://simg3.gelbooru.com//images//7e/cb/7ecb37068e99b92aac65a78c83abec5a.png

### How often does this problem occur? On which sources?
Seems to occur 100% of the time for Gelbooru

### What version of the program are you using? On what operating system?
5.5.2
Gelbooru model 0.2

**Comment by Bionus** [comment]
> though the url string isn't actually changed according to the logs.

The log simply logs the new extension and the old url.
Doesn't make much sense so I'll change that. :+1:

> The grabber seems to default to .jpg on all urls from Gelbooru when pulling as a batch or just single selection. This doesn't reflect the actual image url for .png images on gelbooru.
> On a download attempt, the grabber recognizes that the image cannot be retrieved and attempts to retry with a .png extension

This happens when Grabber has to fallback to Regex parsing, as the HTML pages of Gelbooru do not provide image extension information.

However, by default, Grabber should use the XML API which should not have this issue. What's your source order settings? Those should prioritize the XML API, which provide extension information:

![image](https://user-images.githubusercontent.com/882719/35184814-b13ca882-fdfa-11e7-80fc-2c138fba5a56.png)
