### ISSUE TITLE
No results for Shimmie source "https://callista.su/equine/booru/"

### ISSUE THREAD

**Issue by Johanze** [Bionus/imgbrd-grabber#1185]
### What steps will reproduce the problem?
Following the standard procedure to adding other boorus
### What is the expected behavior? What do you get instead?
Gaining access and seeing pictures; Not, gaining access
### How often does this problem occur? On which sources?
I've tried them all and with various modifications of the URL - "https://callista.su/equine/booru"
### What version of the program are you using? On what operating system?
5.5.2. on Win 10

**Comment by Bionus** [comment]
Indeed, I could reproduce the issue, that source was not getting parsed properly. It should be fixed in the next release.

You can either wait for it or download the updated `model.xml` file [here](https://github.com/Bionus/imgbrd-grabber/blob/develop/release/sites/Shimmie/model.xml). Just replace the one in `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber\sites\Shimmie` with this one. Also, you'll have to use the [nightly](https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly) version as there was another bug that was fixed for that source.

Note that for that source, it also seems that you need to set some referrers for the images to load:

![image](https://user-images.githubusercontent.com/882719/35183624-ae6b9b1a-fde9-11e7-99a5-080ee04adc39.png)
