### ISSUE TITLE
Searching my Danbooru favorites gives no results

### ISSUE THREAD

**Issue by MemeTroubadour** [Bionus/imgbrd-grabber#1189]
### What steps will reproduce the problem?

Searching my Danbooru favorites (fav:BHopp) in any tab gives no results, even though my account is still working on the website.

### What is the expected behavior? What do you get instead?

Normally, my favorites would appear as they do on the website. Here, neither Danbooru nor hijiribe give results.

### How often does this problem occur? On which sources?

This always seem to happen for danbooru and any other source that imports favorites from it. However, it only seems to happen with my account.

### What version of the program are you using? On what operating system?

5.5.2, Windows 10

### Please provide any additional information below

I have no idea how this thing works, honestly, so I'm sorry if I'm not giving enough info.

**Comment by Bionus** [comment]
You can only view an user's favorites if you're in one of those two situations:
* This user has "Privacy mode" disabled
* The user has "Privacy mode" enabled and you're logged in as this user

In your case, it seems your account has this mode enabled and you are not logged in with Grabber. So from here, you have two options to access your favorites from Grabber:
* Disable "Privacy mode" on Danbooru. Go to "My account > Settings > Advanced".
* Login on Danbooru with Grabber. See [WebsiteLogin](https://github.com/Bionus/imgbrd-grabber/wiki/WebsiteLogin) on the wiki.

_PS: I'm closing the issue since the question was answered. If it wasn't, tell me and I'll re-open. :smile:_
