### ISSUE TITLE
Fails to work on XP x64 SP2 (NT 5.2)

### ISSUE THREAD

**Issue by ghost** [Bionus/imgbrd-grabber#1199]
### What steps will reproduce the problem?
1. Install
2. Open Grabber.exe with HEX editor and patch 0x06 byte to 0x04 at offsets 0x0158 and 0x0160 (otherwise it will throw "This is not a Win32 executable" error).
3. Launch

### What is the expected behavior? What do you get instead?
The application is supposed to work.

Instead, it throws "No source found. Do you have a configuration problem? Try to reinstall the program." error, then flashes the fully rendered window for a second and shuts down.

### What version of the program are you using? On what operating system?
Grabber v5.5.2. OS: Windows XP x64 SP2 (NT 5.2)

**Comment by billsargent** [comment]
Run it on Windows 7. Xp is way too old to be messing with on any machine, let alone one that has a connection to the net.  You'll get much better performance too. I mean I'd recommend Windows 10, but seeing as you're running XP, I doubt you want to even think about 10. Otherwise run it on Ubuntu or something.

**Comment by dsp2003** [comment]
I'm running XP x64. X64. It has very little to do with the "XP" you think of. Aside proper hardware support and much better security mechanisms internally (because it's 2003 Server under the hood with "Server" part removed), it allows me to record sound on my hardware, unlike 7 which fails to do so. In fact, "security" in Windows 7 is **much** worse, all "thanks" to "TrustedInstaller" and task scheduler which prevents admin account to shutdown/delete vulnerable/malicious tracking and Samba services.

I'm not going to run a dedicated Linux machine just to use a booru grabber that has absolute zero reason to make NT 6.x as a mandatory requirement.

Sad to see this application deleted from my hard drive, but it seems I don't have much choice.

**Comment by Bionus** [comment]
> Instead, it throws "No source found. Do you have a configuration problem? Try to reinstall the program." error, then flashes the fully rendered window for a second and shuts down.

This is unrelated to Windows XP or a build issue (else the program wouldn't even start up).

This only means that Grabber cannot file some configuration files on your system. If you used the installer to install Grabber, they should be in `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber`.

If they are present, you can try to make the program portable (see [here](https://github.com/Bionus/imgbrd-grabber/wiki/PortableVersion), you just have to put the files from the install folder and AppData in the same writable location).

If they're not, maybe the installer didn't run properly or didn't have the writing rights for some reason. In that case, you can file most files [here](https://github.com/Bionus/imgbrd-grabber/tree/master/release) (it might be a pain to download them one by one on Github so I'd advice downloading the whole repo as a zip and copying the `release` folder from there).

**Comment by dsp2003** [comment]
Okay, after short investigation:

1. The files were written by installer.
2. Coping or moving them to Grabber's installation directory (differs from "Program Files") didn't help.
3. Copy-pasting them straight from repo archive didn't either.

Conclusion: I don't know how you've coded the path resolving for the resources (no C/C++ knowledge), but it appears the application simply fails to locate its own files on 64-bit XP regardless of their location.
