### ISSUE TITLE
Issue with privileged install w/error: no source found (run installer as admin, run program as user)

### ISSUE THREAD

**Issue by AriinPHD** [Bionus/imgbrd-grabber#1218]
### What steps will reproduce the problem?
Download and install Grabber. Windows requests elevation by/to an Administrator-account for permission to install apps as user is non-admin; administrator-account and password entered. Program installs. Requests Visual C++ stuff, click "Yes". Once installation is done simply run the program as the non-administrator account that user is logged on to. Program does not start, returns error pop-up:
title: No source found - Grabber.
body: No source found. Do you have a configuration program? Try to reinstall the program.
options: X and [OK] buttons.

Edit: To avoid confusion or assumptions, please note that the program itself functions. Running the program as the administrator account works as intended. No error, program starts up and requests the initial setup sources and save path (etc). The issue is running the program as a regular user, as people should do (quite surprised this issue hasn't popped up before; couldn't find anything related in issue:search).

### What is the expected behavior? What do you get instead?
Expected: Program opens and lets non-admin user set sources.
What happens: Program does not open; fails to open with error:
title: No source found - Grabber.
body: No source found. Do you have a configuration program? Try to reinstall the program.
options: X and [OK] buttons.

### How often does this problem occur? On which sources?
Every time.

### What version of the program are you using? On what operating system?
v 5.5.2 on Windows 10 Pro, 64-bit, 10.0.16299

### Please provide any additional information below
![grabbererror](https://user-images.githubusercontent.com/5846389/37271046-8ef46efa-25d1-11e8-88e2-211ddce7c99c.png)

**Comment by Bionus** [comment]
The issue must come from the fact that some program settings are written in the user's AppData directory during installation, in `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber`. Because those files are to be overwritten by the program during runtime (so they must be in a writable location, so not `Program Files`).

Since you installed it as another user, those files must be in the administrator's AppData directory instead of the "normal" user. If you copy those files from the administrator's AppData to the normal user's AppData, I believe it should fix the problem?

> quite surprised this issue hasn't popped up before; couldn't find anything related in issue:search

I believe most people use an administrator account even for everyday tasks and therefore don't need to install the program using another user than the one they use for running the program.

**Comment by AriinPHD** [comment]
`I believe most people use an administrator account even for everyday tasks and therefore don't need to install the program using another user than the one they use for running the program.`
If true that's horrible.

`If you copy those files from the administrator's AppData to the normal user's AppData, I believe it should fix the problem?`
Great tip. I'll give that a try! Thanks! :)

**Comment by yy970852414** [comment]
i have same problem as AriinPHD #1218.
win7 64bit 
whether or not i using as administrator,it occur everytime.
but  5.5.1 version have no problem.
until I updated the version to 5.5.2 or the latest release 6.0.6,they all have the same problem.
i have checked _C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber_,found grabber folder,and i doesn't found any other "normal user".
please help me...
