### ISSUE TITLE
Not downloading indicated files...

### ISSUE THREAD

**Issue by mlmmt3** [Bionus/imgbrd-grabber#1241]
### What steps will reproduce the problem?
Attempt downloading from danbooru with various combinations of tags (always more than 2)

### What is the expected behavior? What do you get instead?
Tags: width:>1000 height:>1000 date:>2018-01-26 ratio:16:9..10
search returns correct images, but when it downloads, instead of the images indicated in the search panel, grabber appears to attempt to download everything...

### How often does this problem occur? On which sources?

Danbooru, whenever attempted

### What version of the program are you using? On what operating system?

5.5.2 windows 10 x64

**Comment by mlmmt3** [comment]
I just went and tested, and it seems no matter what tags I put in, the search results come up correct, but the program appears to just start from the most recent danbooru post and start downloading, which is really strange....

**Comment by Bionus** [comment]
So, from what I understand, if you search more than 2 tags (which is the limit for free users on Danbooru):
* When browsing: it works properly and show relevant results
* When batch downloading: it somehow downloads all images without taking the input tags into consideration, starting from the latest image and trying to download all of Danbooru's images

I get that you're using a premium/gold account (or whatever it's called) on Danbooru?

One reason could be that Grabber fails to login during batch downloads, but in that case the Danbooru API should return an error instead of fallbacking to showing all images:
* XML: `<result success="false">You cannot search for more than 2 tags at a time</result>`
* HTML: `You cannot search for more than 2 tags at a time`

**Comment by mlmmt3** [comment]
Yeah, you would think, except it actually *does* work... sometimes
though the amount of images it downloads... often makes no sense... it somehow downloaded 1,401 images (including a number of duplicates) from a search that should only return 1,140 results... 
Also, it might have something to do with the fact that I am using a bunch of complicated tags that each have variables attached to them...

(and yes, I have a Platinum account, which leads to all sorts of fun with downloaders because I can use up to 10 tags in a string when searching, which breaks all sorts of stuff in fun ways)
