### ISSUE TITLE
Sources all broken - Version update false positives

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [Bionus/imgbrd-grabber#1290]
### What steps will reproduce the problem?
Seemingly installing the new 6.0.1 update causes this- none my geblooru or other sources work, the total page count is not loaded, and to top it all off, the Grabber version update changes from 6.0.0. to 6.0.1 to 5.5.2- currently on 5.5.2 here- despite it being 6.0.1 -this is about as broken as the program has ever been.

**Comment by Bionus** [comment]
Where do you see "5.5.2"?

It would seem that the `.exe` file you used was from the old version, asthere's no way the version in the about window can change, as it's fixed at compile time.

Are you using multiple versions on the same computer?

For Gelbooru page count, see #1280 and #1283, it will be fixed in next release (very) soon.
