### ISSUE TITLE
Downloading images will now create for each image a tmp file in your folder destination

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1293]
### What steps will reproduce the problem?
Downloading images from a source will now create tmp files which isn't something it did before in the destination folder. (Don't know if it is something that you intended with this update). Here a screenshot:
[https://i.imgur.com/4WfVLZl.png](https://i.imgur.com/4WfVLZl.png)

### What is the expected behavior? What do you get instead?
Not getting those tmp files created in my destination folder like it was before.

### How often does this problem occur? On which sources?
Always and the source doesn't matter.

### What version of the program are you using? On what operating system?
Version 6.0.2 with windows 10

**Comment by Bionus** [comment]
What's wrong with those files?

They are created during downloads and will be renamed once the download is finished into the correct filename.

**Comment by MrAndre96** [comment]
Now it will create the tmp files inside the folder with all your maps and not it the final destination place. So it will have to be moved every time the download is finished.
As you have for example '%copyright%/%character%/%md5%.%ext%'

**Comment by Bionus** [comment]
I'm not sure what the problem is.

Indeed, in your example the temporary file will be created in `C:/Users/name/GImages`. But when it finishes downloading the file, it will be moved to `C:/Users/name/GImages/whatever_you_searched/copyright/character/md5.ext`.

It's been made like this in case you use for example `%md5%/%id%.%ext%` as filename, and no MD5 is provided by the source (for example for Zerochan). In that case, Grabber first needs to download the file, calculate its MD5, and only then can it generate the correct filename.

I could make it that this feature is only used when considered useful (i.e. `%md5%` or `%filesize%` are used but empty), but I'm not sure what's wrong with temporary files. Moving a file on the same drive is (almost) free on most filesystems.

**Comment by MrAndre96** [comment]
Nah it just seemed a bit weird to me since normally when you download something it is directly put in the right folder. But it is true that it isn't really a problem.

**Comment by Bionus** [comment]
I'll disable this feature when not necessary (i.e. %md5% or %filesize% are used but empty), it's true that it might not be very clear.
