### ISSUE TITLE
Portable?

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#1297]
Is grabber portable?

I've been wondering that if it is portable why would it need an installer?
Sorry for the probably obvious question, it's been a long time since I actually used/updated/moved it.

**Comment by Bionus** [comment]
Yes, it's portable. You have to put the settings folder and the install folder in the same place (see [wiki page](https://github.com/Bionus/imgbrd-grabber/wiki/PortableVersion)) and you should get a portable version.

As for why there is an installer since it's portable, I'd say it's for convenience? Plus, the installer also installs the MSVC dependencies, which is nice.

**Comment by brodycas3** [comment]
Alright, Thanks. May I know why settings are not stored with the application?

**Comment by Bionus** [comment]
Because the program doesn't have writing rights on the Program Files folder, so he can't save the settings here (that's why most Windows programs save their stuff in AppData).

The alternative would be to do like Chrome and simply have everything in AppData, including the program itself, but that's quite dirty.
