### ISSUE TITLE
What does this mean

### ISSUE THREAD

**Issue by bluefiberbread** [Bionus/imgbrd-grabber#1330]
[Info] MD5 "47e2929b4cbb9eca00de7958e88961f8" of the image https://danbooru.donmai.us/data/47e2929b4cbb9eca00de7958e88961f8.jpg already found in file D:\1\abigail williams (fate grand order) date 2017-12-01.\47e2929b4cbb9eca00de7958e88961f8.jpg

Does it keep a list of my downloaded images  and skips it if it has already been downloaded at some point? Does it skip downloaded images if it's in the download folder?

**Comment by Bionus** [comment]
> Does it keep a list of my downloaded images and skips it if it has already been downloaded at some point?

Yes, Grabber keeps a list of your downloaded images and their file hash to be able to not re-download an already downloaded file, even if it's in another folder.

You can change this setting in the options:

![image](https://user-images.githubusercontent.com/882719/42420920-7430b886-82cd-11e8-82c6-11675128e789.png)

> Does it skip downloaded images if it's in the download folder?

Separately from the global MD5 list, if a file already exists in your target folder, Grabber will not overwrite it and will skip the download. That's why you should use an "unique" filename (using `%md5%` for example).

**Comment by Bionus** [comment]
I'm pretty sure it has nothing to do with this setting.
You might have changed the "simultaneous downloads" setting though (on the same page).
