### ISSUE TITLE
tags show me 262 post, but actual post show me 228

### ISSUE THREAD

**Issue by jaejunghan** [Bionus/imgbrd-grabber#1336]
### How often does this problem occur? On which sources?

gel,dan - booru

### What version of the program are you using? On what operating system?

grabber 6.03

### Please provide any additional information below
[try - gelbooru](https://user-images.githubusercontent.com/41049446/42549675-5f0edf04-8508-11e8-96ba-e55c6c19db75.png) (**NSFW**)

[masami_chie - danbooru](https://user-images.githubusercontent.com/41049446/42550544-5d8f5ece-850d-11e8-99f0-a636bc55e426.png) (**NSFW**)
[masami_chie  - gelbooru](https://user-images.githubusercontent.com/41049446/42550548-6117182a-850d-11e8-9932-4adef21f8201.png) (**NSFW**)

**Comment by Bionus** [comment]
> [try - gelbooru](https://user-images.githubusercontent.com/41049446/42549675-5f0edf04-8508-11e8-96ba-e55c6c19db75.png) (**NSFW**)

That's because Gelbooru doesn't know how to count. You can file a bug on their end, but AFAIK they know of this issue already.

If you actually count the number of images, the count given by Grabber at the top is correct, and the count given in the "tag" area is the one provided by Gelbooru.

> [masami_chie - danbooru](https://user-images.githubusercontent.com/41049446/42550544-5d8f5ece-850d-11e8-99f0-a636bc55e426.png) (**NSFW**)

That's a bug because it seems to fail to parse the tags for some reason and therefore can only provide an approximate count of images based on the page count. But that approximation is correct (14 pages of max 20 images -> ~280 images)

> [masami_chie  - gelbooru](https://user-images.githubusercontent.com/41049446/42550548-6117182a-850d-11e8-9932-4adef21f8201.png) (**NSFW**)

What's the problem here?
