### ISSUE TITLE
Images being skipped 

### ISSUE THREAD

**Issue by ninjahunter950** [Bionus/imgbrd-grabber#1341]
Hello and, sorry for a potentially silly question, but while doing a mass rip I noticed a number of files being skipped and I could not discern why or how to attempt to redownload them. This is happening to a not insignificant number of images and I don't want to redo 4000~ files because I didn't catch this.
Thanks in advance!
<img width="288" alt="snap 2018-07-14 at 08 41 42" src="https://user-images.githubusercontent.com/41234256/42724527-df88e8a6-8741-11e8-97ec-adcd5d74dc17.png">

**Comment by Bionus** [comment]
If you check the log to get the full reason why images are skipped.

Usually it's because the file already exists at the destination or because you already downloaded it somewhere else, or because a tag is blacklisted.

If you're not sure of the reason, you can also simply share your log (after such images are skipped) here and I can have a look. :+1:
