### ISSUE TITLE
Filename settings not working correctly

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1370]
**Bug description**

When I download from a batch download it will by some searches not create a crossover like you would aspect (which is by default enabled and I haven't changed those settings) but it will for some reason create a different folder with a longer name.

First use this filename: %search_1%/%copyright%/%character%/%md5%.%ext%
Then enable the source sankaku complex and search imouto_paradise!
After this do get all and start the batch download
When it start you see directly by the first image that it creates the folder imouto_paradise!_2 while it should make a folder crossover

It isn't by all the batch downloads like this so a specific problem

**Expected behavior**

I aspect that it will create a crosssover since it has the imouto_paradise! and imouto_paradise!_2 tag

**System information**

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
Do you have the "use shortest if possible" option enabled?

![image](https://user-images.githubusercontent.com/882719/43964068-535bf932-9cbc-11e8-8fc4-1e66f785ddda.png)

On which image did this happen exactly? (the MD5 would be perfect)
Because I just tried to download `imouto_paradise!` on Sankaku with these settings and they were properly saved.

Do you have the `imouto_paradise!` added to your ignored tags lists? (there's no UI for editing them, but the full list can be found in the `ignore.txt` file in the settings directory)

**Comment by MrAndre96** [comment]
@Bionus I don't have any tags inside my ignore.txt and habe the shortest if possible enabled. But it should go to the crossover since it has the imouto_paradise! and imouto_paradise!_2 copyright tag so that shouldn't matter I think.

For example take this one with md5 3e2dbd3da279c69165008e246e2576f1 with the link to it: https://chan.sankakucomplex.com/post/show/7092009. it shows that it has both imouto_paradise! and imouto_paradise!_3 but it will now save inside the imouto_paradise! folder and not make a crossover when it should since I have 'If more than n tags' on 1

**Comment by MrAndre96** [comment]
Hmm I see and for some reason it doesn't make the imouto_paradise!_2 folder anymore (idk why) so I can't reproduce it anymore. So thanks for explaining and will close it for now
