### ISSUE TITLE
Opening a image by zerochan will first load a sample image

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1384]
**Bug description**

When you open the image viewer by zerochan it will first let you see the sample images and after downloading the fullsize image

**Expected behavior**

Like with the other sources you espect it to load directly the full size image (althought not yet loaded)

**Screenshots**

[https://i.imgur.com/8KPCqYS.png](https://i.imgur.com/8KPCqYS.png)
[https://i.imgur.com/KCDnE4c.jpg](https://i.imgur.com/KCDnE4c.jpg)

**System information**

Windows 10 with nightly version 797a4010

**Comment by Bionus** [comment]
That's expected behavior 👌

By default, the image viewer will show the thumbnail image (the one from the results view), and resize it to the size of the image. If no size is found, it will simply take the double of the thumbnail size by default. That explains the very low quality of the image in your screenshot (as it's a small image that was upscaled and not the sample image).

The main issue is therefore that zerochan doesn't give the size information, so moving to issue #1385 :+1:
