### ISSUE TITLE
Can I download images from a certain date to another ?

### ISSUE THREAD

**Issue by Amazingduf** [Bionus/imgbrd-grabber#1434]
I've browsing the issues here and doing some googling and all I know is how to download to and from a certain date "date:<=dd.mm.yyyy" and "date:>=dd.mm.yyyy" right ? and it helps tremendously, but can I download from certain date to another ?

Thank you in advanced

**Comment by brazenvoid** [comment]
There are two ways:
- Some sites support such filters so you can add those for source specific downloading
- If you are downloading from multiple sources then you would be better off using the post filter feature found under the "+" button on the right of the search bar. There you can use Danbooru's filters as post filters for most sources. There are caveats to this like some sources which do not provide date unless one downloads the image, I only know of rule34.paheal.net.

**Comment by Bionus** [comment]
Since you're already talking about sources that allow the use of `date:>=` and `date:<=`, you can either:
* Use both: `date:>=begin date:<=end`
* Use a range: `date:begin..end`

See [Danbooru cheatsheet](https://danbooru.donmai.us/wiki_pages/43049).

As @brazenvoid said however, if your source doesn't support it, you can use a post-filter, and Grabber support both suggestions above as long as the source provides the date information.
