### ISSUE TITLE
Wrong result count indicators when more than one tag

### ISSUE THREAD

**Issue by Kuroonehalf** [Bionus/imgbrd-grabber#1445]
Whenever you query more than one tag, apparently regardless of the server, Grabber will display the wrong number of results and result pages. It seems to be simply taking the number of results and pages from querying just the first tag, and not taking into account the results that get culled from the other tags.

This is obviously not good, but also creates buggy behavior when you click to go to the last page. Since it took its results from just the first tag, what it thinks is the last page will be a higher number than the actual last page for this multi tag query, and return an empty page.

**Comment by Kuroonehalf** [comment]
Hm, or maybe this problem runs deeper. I just tried querying only "Unagimaru" on gelbooru through grabber, and it says there's 6 pages of results, when actually there are only 4 pages, and the same problem happens when you click to go to the last page.

**Comment by Bionus** [comment]
That's the good old "Gelbooru doesn't know how to count" bug.

Keeping your example for the tag "unagimaru", Gelbooru reports:
* 224 images
* 42 images per page
* 4 pages

There's a clear discrepancy in numbers. On most boards, the page count is not reliable as they usually don't give it for tags with a lot of results.

Which is why Grabber currentlygives priority to the image count, which is supposed to be more reliable than others. The other option would be to consider 4 pages, and "guessing" `42*3+1` to `42*4` images. But while this might fix the paging issue on Gelbooru, it will make other sources have to "guess" image counts while they already have a reliable one. 🤔

The bug is more than Gelbooru reports the wrong number of images.

> could this be related to issue mentioned in this thread? #1412

Nope, those are unrelated.

**Comment by Bionus** [comment]
Ok my bad, while what is said above is true, I actually fixed this behavior in an old issue, but it seems that the "last page" parsing is broken for Gelbooru HTML API.
