### ISSUE TITLE
gelbooru does not return results from searches

### ISSUE THREAD

**Issue by Tokyo-All-Ready** [Bionus/imgbrd-grabber#1452]
before the update it was downloading fine from gelbooru then after it gives error:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
        <posts count="0" offset="0"/>

and i found the reason
when it inputs "md5" into search bar its missing " : "

so gelbooru returns no result

im on windows 7 64 bit

also my download speed reduced from that site

could that be that instead of ip ban they are restricting traffic?

**Comment by Bionus** [comment]
The API was disabled for a while, which might have been the problem?

However, Grabber should automatically fallback to regex mode, so it should still find things. The find that your link was to the XML API means that it didn't fallback. Did you change the Gelbooru source settings? If you removed the Regex source from the list, since the XML one was disabled, you were without any source left for Gelbooru.

**Comment by Tokyo-All-Ready** [comment]
i left it all defaults for the sourcing.  Only changes i make is on  the search bar to enable/disable sources.

The only changes i made to the settings was simultaneous downloads = 1

Is there an ini file with the settings i can upload?
