### ISSUE TITLE
Showing images in image viewer and downloading images not working

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1460]
**Bug description**

When I click on a image and open it, it shows that it downloads it but after that still displays a blurry image (The image of the thumbnail). When you try to download it afterwards for example with the 'save as' button it will give a error.

**Steps to reproduce**

First search for nekopara for example (Source doensn't matter)
After that click on a image
You will see that the image stays blurry (If you haven't already downloaded it on your pc)
After that click 'save as' and you will receive a error

**Expected behavior**

Displaying and downloading the image like normal

**Screenshots**

[https://i.imgur.com/yUs43le.png](https://i.imgur.com/yUs43le.png)

**System information**

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
Indeed, it seems that because of a bug, the loaded image is immediately deleted after being downloaded. I'm investigating, thanks for the heads-up!

With all the changes I'm working on, there had to be some weird bugs 😅

**Comment by brazenvoid** [comment]
Oh finally its gone! I can use the nightlies again! (hope so)
I had been of the notion that you were in the midst of changing something major for the images as I skimmed through the commits.

**Comment by Bionus** [comment]
Yes, nightly got some huge changes in the past few days in order to properly support galleries, which change the whole data model ("pages containing images" becomes "page containing images and galleries" + "galleries containing images"). I also dropped the legacy `model.xml` files, re-written the authentication code, etc.

I also had to pretty much re-write the batch downloading page loading from zero, so there might be some issues there (but hopefully mainly improvements 😄).

There are still some big planned changes before 6.1.0, in order to support "gallery tokens" (i.e. `%gallery_name%`, `%gallery_id%`, etc.), so there might be some bugs arriving later (but hopefully I'll catch them before it arrives in nightly).
