### ISSUE TITLE
No source found

### ISSUE THREAD

**Issue by yy970852414** [Bionus/imgbrd-grabber#1461]
i have same problem as AriinPHD #1218.
win7 64bit
whether or not i using as administrator,it occur everytime.
but 5.5.1 version have no problem.
until I updated the version to 5.5.2 or the latest release 6.0.6,they all have the same problem.
i have checked C:\Users%USERNAME%\AppData\Local\Bionus\Grabber,found grabber folders,and i doesn't found any other user.
please help me...

**Comment by yy970852414** [comment]
:(

**Comment by Bionus** [comment]
Whoops, missed your issue sorry 😄 

>  i have checked C:\Users%USERNAME%\AppData\Local\Bionus\Grabber,found grabber folders,and i doesn't found any other user.

So this folder properly contains the necessary files?
Have you tried making a [portable version](https://bionus.github.io/imgbrd-grabber/docs/portable-version.html) of Grabber? Copy both the contents in Program files and in AppData to some folder and it should find it properly.

* What version of Windows do you have? The full version if possible, you can find it by right clicking on "This Computer" and selecting "Properties" (under "windows edition").
* Is your user an admin account? (from what you said it seems to be)
* Did you install Grabber with the same user account you are trying to use it with?

I will check all the changes between 5.5.1 and 5.5.2 and see what might have caused that.

**Comment by yy970852414** [comment]
![image](https://user-images.githubusercontent.com/43989008/47262771-fc674c80-d523-11e8-84cc-5a45f9a5bb3f.png)

here is a little translation:
win7 home basic
....
64bit
pen and touch  :  none
.....
windows status: activated
===================
yes ,i am an admin account
===================
yes
===================
and i tried to copy old version(5.5.1) file "C:/Users/%USERNAME%/Grabber" to latest version(6.0.6) "C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber" and it still "No source found",like default installation i already said.
thank for your help :)

**Comment by Bionus** [comment]
Ah, I think I know why.

You must have been using Grabber for a pretty long time! `C:/Users/%USERNAME%/Grabber` is not used since version 3.5 / 4.0, which is more than 4 years old! 😱

Make sure to delete your `C:/Users/%USERNAME%/Grabber` folder, or, if you want to keep your settings, move it to `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber`, **then re-install** to update your sources (it won't overwrite your settings).

> and i tried to copy old version(5.5.1) file "C:/Users/%USERNAME%/Grabber" to latest version(6.0.6) "C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber" and it still "No source found",like default installation i already said.
> thank for your help :)

Ah that's not what I meant. What I suggested was to:
1. Create a new folder somewhere on your computer, for example on your desktop, named "Grabber"
2. Copy everything from `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` to that new folder
3. Copy everything from `C:/Program Files/Grabber` to that new folder
4. Make sure there's a `settings.ini` file in that new folder, and if there isn't, create one
5. Run the `Grabber.exe` from that new folder

That's the procedure for making a portable Grabber version, but in your case I think simply deleting your `C:/Users/%USERNAME%/Grabber` folder should be enough.

> don't known why is the word so big...

Using `========` makes whatever is before a title in Markdown, see the [documentation](https://daringfireball.net/projects/markdown/syntax#header) for more info.

**Comment by yy970852414** [comment]
yes,i using Grabber for very long time.
i have used some other software,like ox163,178download,moeloader.but Grabber is the longest time i have used,and i'll keeping use it.thanks for your software!
i following your suggestion to

> Make sure to delete your C:/Users/%USERNAME%/Grabber folder, or, if you want to keep your settings, move it to C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber, then re-install to update your sources (it won't overwrite your settings).

and now i can use 6.0.6 ,thanks for you help! :)
![image](https://user-images.githubusercontent.com/43989008/47478143-1756fb00-d85b-11e8-8a86-4eaf706e1f65.png)

**Comment by Bionus** [comment]
That's great to hear! 😄

I'll be closing the issue then, and I'll see to maybe put a warning or a fix in the program for other users that might be in the same situation.
