### ISSUE TITLE
Middle-clicking tag doesn't carry over source

### ISSUE THREAD

**Issue by Kuroonehalf** [Bionus/imgbrd-grabber#1482]
Say you're doing a gelbooru search and open up a picture and want to see more pictures from that artist, if you middle click the artist tag a new tab will open with the artist name as the query, but the sources of that query won't be the same as the one where the image was, often leading to empty search results, and making you do more work to get what you wanted.

In the title of the grabber image popout window it lists the image's source host at the top, so it should know what source to set when you middle click a tag.

**Comment by Bionus** [comment]
I just tried middle-clicking a tag from an image window generated from a multi-source search, and the opened tab kept all my sources selected, providing the expected results.

Is there something more I should do to reproduce the issue? (fore this test I had only one tab)

Or could it be that you want Grabber to open the new tab with **only** the image's source selected, instead of the original tab's? If that's the case, I have to admit that I don't really see /why.

**Comment by Kuroonehalf** [comment]
Ah, huh. Now it's indeed working right for me. But I'm pretty sure it's happened before on more than one occasion. I created the post right after it happened again, but now I forgot what query that was. I'll do more thorough testing and report back. Apologies for the trouble.

**Comment by Bionus** [comment]
No worries! If it happened every time for you and not me, I might have not understood the issue, so I was just making sure. 👌 

If you're saying it doesn't happen every single time, there must be a problem in the code, so I'll investigate on my end and see what could cause that.

**Comment by Bionus** [comment]
The bug can be reproduced by:

1. Have two tabs open: one with source A, one with source B
2. Open an image from the first tab (source A)
3. Switch to the second tab (source B)
4. Go to the opened image window (from source A)
5. Middle click a tab
6. The loaded tab will have source B selected

It seems that new tabs are inheriting the sources from the currently active tab, instead of the one the image is originally from.

**Comment by Kuroonehalf** [comment]
Ah, that makes a lot of sense! I usually open up a bunch of new images from different queries/hosts and then do a single sweep through them, so I get that scenario often. I hadn't thought that that could be it, so I was just opening and checking one image at a time, and that explains why I wasn't able to reproduce it in tests.
 
Thanks for looking into it!

**Comment by brazenvoid** [comment]
Thanks! Finally a long time bug got fixed!

**Comment by brazenvoid** [comment]
@Bionus So I tried this fix, the it works fine but I am experiencing another bug now. Randomly, an image window will stop responding to the middle click. 
- The first time this happens, the main window gets focus momentarily but then looses it. 
- After that, however times you middle click on it, will not trigger any reaction.
- Even right clicking and explicitly trying to open the tab in new window will stop working. 
- Left clicking the tag will also not work
- All image windows opened from that specific page will now exhibit the same behavior. 

The only means left is to copy the tag and explicitly open a new tab to search it.

**Comment by brazenvoid** [comment]
So the above bug happens when the original search tab is closed. Previously, even if the original tab was closed, it still did open the new tab, now it doesn't.

**Comment by Bionus** [comment]
Indeed, the link between the image window and the tab system was done through the tab itself, and when it's closed/destroyed, the link was destroyed too. I'll push a fix for this bug, thanks :+1:
