### ISSUE TITLE
Tag Syncing

### ISSUE THREAD

**Issue by BarryMode** [Bionus/imgbrd-grabber#1483]
**Is your feature request related to a problem? Please describe**
Not a problem with Grabber. Just a feature idea.

**Describe the solution you'd like**

Since tags can be stored any number of ways (and I'm sure many users don't store them at all), this may be too difficult to standardize. This also may be too big of a haul on the servers for people with large libraries. I was just wondering if it you had any ideas for how to sync image tags so that if the source tags change, the image would update. This would be relevant on images where tags have a "tagme" tag or that sort of thing. Over time, tags can change. Maybe an image could be manually updated, or maybe you could update all images that have X tag.

Again, no idea how you would even code this since there's not really a standard for downloading and storing the tags. I just wanted to throw this out there in case you had any thoughts. I want to respect the servers, so this may not be realistic.

Let me know what you think. Feel free to close this if it's an obvious no. I just wanted to pick your brain and hear what you had to say @Bionus. **Thanks for all you do on this project!**

**Comment by Bionus** [comment]
> Since tags can be stored any number of ways (and I'm sure many users don't store them at all), this may be too difficult to standardize

Indeed, but technically you wouldn't store the tags. What you would want to do is store when you last checked if the tags changed.

> This would be relevant on images where tags have a "tagme" tag or that sort of thing

For those images, that would definitely be a good thing. For example, if someone were to setup some monitoring on their favorites, and automatically download new images as soon as they are added, he would end up with sub-par tagging for most images, as they are very often uploaded with minimal tags.

> This also may be too big of a haul on the servers for people with large libraries

This is the big pain point of your suggestion. For people that have millions of images, this would be a huge burden on the server: you'd have to make as many requests to the server as the user has images.

-----

Here's how your suggestion _could_ technically be done (note that I have no plans to do this yet):
* Keep a database of `(file, re-check date)` pairs
* Every time an image is downloaded, add it to the database, with a re-check date of `now + PERIOD`, with `PERIOD` changing depending on how much time passed since the image was created, how many tags it has, and if it has a `tagme` tag
* Every minute, Grabber checks if any re-check date was passed, and if so, take the **first image only**,  re-check its tags, and moves/renames/updates the image accordingly, then re-add the image to the re-check database

With this, even if the user has thousands of images, they will all be checked eventually, without overloading the servers (limit to 1/minute). This is actually how the favorite monitoring works (except with searches instead of images).

Issues with this solution:
* You need to keep Grabber open
* If you have really a lot of images, you'll reach a point where Grabber doesn't check images fast enough
* The "every minute" should take into account websites, instead of being done globally (i.e. if you have 3 images from 3 different sources, there's no need to wait 1 minute between each check)

**Comment by BarryMode** [comment]
Thanks, those are some good ideas. I also didn't realize that you could monitor favorites, so that's cool. I need to look at Grabber in more detail because it sounds like there are some great features that I'm not taking advantage of.
