### ISSUE TITLE
%all% in filename would lead to duplicates from different sources

### ISSUE THREAD

**Issue by baraa272** [Bionus/imgbrd-grabber#1484]
**Bug description**

%all% in filename save  would lead to duplicates from different sources

**Steps to reproduce**

Name : %character%/%md5%_%filename%_%all%.%ext%

**Expected behavior**

Grabber to be able at least to detect files and skip duplicate 

**Context**

* Provide your `main.log` file to see if any obvious error occured. (not an crash)
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration. ( vanilla settings)

**Screenshots**

![githubissue](https://user-images.githubusercontent.com/32843097/47602628-4485e380-d9ea-11e8-849c-3961c905cab1.png)

**System information**

- OS: windows 10
- Grabber version:6.0.6

please point me if i'm doing something wrong
also why you remove %tag% it was good and without duplicates 
how can someone have tags of image in its filename if %all% would lead to duplicate??

**Comment by Bionus** [comment]
> please point me if i'm doing something wrong

You're not doing anything wrong, this is the expected behaviour.

>  also why you remove %tag% it was good and without duplicates

I don't remember ever having a `%tag%` token? `%tags%` exists however, and is the exact same as `%all%`.

I'm not sure what you mean by "without duplicates" either. The tags are loaded from the image's source, so if you have the same image from two different sources, they would have different tags most of the time (since sources have different tagging policies).

> how can someone have tags of image in its filename if %all% would lead to duplicate??

Most people don't put tags in the filename because Windows will cut your filename after a certain length anyway.

-----

However, if you **do** want to prevent duplicates that have different filenames (which is your situation), you can use the global duplicate setting: simply set it to "Don't save", and you'll only download images once (the duplicate test is based on the images' MD5).

If you do this, you can keep having tags in the filename, only the first image will be downloaded, and duplicates will be skipped.

![image](https://user-images.githubusercontent.com/882719/47616036-a2ccc800-dab7-11e8-9f72-288ae23044c1.png)

* **Save**: download and save the image twice (as if it's not a duplicate)
* **Copy**: save the image twice, but copy it from the original image to prevent an useless download
* **Move**: move the original image to the duplicate location (useful for example if you're re-downloading an image that has changed a few tags)
* **Link**: create a shortcut with the duplicate image's name, pointing to the original image (useful if you often have duplicates in different folders, with each folder having an useful meaning)
* **Don't save**: skip duplicate images

**Comment by baraa272** [comment]
Thank you for clear explanation <3 
you can close the question
