### ISSUE TITLE
How to use blacklist?

### ISSUE THREAD

**Issue by bluefiberbread** [Bionus/imgbrd-grabber#1486]
How do I blacklist a tag and move those blacklisted tags to a subfolder?

**Comment by Bionus** [comment]
Isn't the point of a blacklist to **not** download blacklisted images?

By subfolder, what do you mean exactly? Given the folder `D:/Grabber` and the filename `%search%/%md5%.%ext%`, where would a blacklisted image end up?

For your use case, why not use a conditional filename?

**Comment by bluefiberbread** [comment]
I want to add the tag "comic" to the blacklist. but I don't know how to do it. It's bothersome to include "-comic" on Danbooru because of the 2 tag limitation

**Comment by Bionus** [comment]
If what you want is not downloading the images, simply use the blacklist:

![image](https://user-images.githubusercontent.com/882719/47618631-922b4a80-dad5-11e8-8633-96853b847615.png)

Then you shouldn't see any images with the "comic" tag in your search results (unless you explicitely add "comic" in your search, in this case Grabber will ignore your blacklist, because otherwise you'd get no results).

**Comment by bluefiberbread** [comment]
if I add "date:2018-06-05..", would it exclude any picture uploaded after that date too?

**Comment by Bionus** [comment]
Yes, this would blacklist all images after 2018-06-05, for boards that provide date information (you can see if the tooltip of an image has a date).
