### ISSUE TITLE
Not loading any images by favorites

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1488]
**Bug description**

When I was checking out this feature I saw that a lot of sources don't show images while it says that it has results while others do show results.

**Steps to reproduce**

Add for example the azur_lane tag to favorites
Now go to the favorite page and enable for example to following sources: danbooru, gelbooru, konachan, rule34 and sankaku complex
When you now go to the page you will see that only sankaku complex show images while the others just say the amount of images there are and the amount of pages.

**Expected behavior**

Also show the images

**Screenshots**

![https://i.imgur.com/L5l8Id3.png](https://i.imgur.com/L5l8Id3.png)

**System information**

Windows 10 with the latest nightly version

**Comment by Bionus** [comment]
It is indeed a but with the way image count is shown: those sources indeed have images, but they were all filtered because they were too old (older than the favorite's "last viewed" value).

Sources that do not provide date information, such as Sankaku Complex, or Shimmie-based boards, are the only ones with results.

I'll push a fix to properly show the reason why no images are shown.

**Comment by MrAndre96** [comment]
@Bionus When I checked the details by sankaku complex I do see a date

**Comment by Bionus** [comment]
Yes, if you open the image, then check the details, because opening the image will load missing information from the `https://chan.sankakucomplex.com/post/show/ID` page. When you're in the image list, if you hover a thumbnail, you'll see there is no date information. Grabber _could_ load details for images to find their creation date, but that'd be very resource-heavy (even with a dichotomy).
