### ISSUE TITLE
When you have a lot of tabs open the quick tab navigator automatically closes when opening

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1504]
**Bug description**

When you open the quick tab navigator (where you can quick acces all the tabs) when you have a lot of tabs open (it was for my by 41) it automatically closes and opens the favorites tab.

**Steps to reproduce**

First you need to have a large amount of tabs open (for me it was 41. Depends I think on the resolution since this appears when the list is at the bottom of the screen)
After that click on the quick navigate button (The one with the tab count)
You will see that it automatically closes after opening

**Expected behavior**

That you can chose where you want to navigate to like it is with 40 tabs and below (for me)

**System information**

Windows 10
Nightly version e0846be9

**Comment by brazenvoid** [comment]
Well as my tab list always has about ~100 tabs, I thought that this was how it was expected to work... Even though it makes me curse it whenever I have to use it... The Favorites item is the first one so that's why it opens it as your mouse button leaves the pressed state.

Workaround:

It requires for you to hold your click from whence you first clicked the quick navigate button. Keep holding it  while you scroll through them. Only leave it on the item you want to navigate to.

**Comment by Bionus** [comment]
Indeed, it seems that the "open tab under mouse in the menu" was triggered when the mouse was released, even if the original click was when the menu was closed.

I fixed the bug just now. Weird that it didn't occur when I implemented it, maybe the bug was introduced afterwards. 🤔
