### ISSUE TITLE
Blacklist Fixer Tool: Add Option To Only Add Missing MD5s

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1510]
**Is your feature request related to a problem? Please describe**

Since a certain update quite a while ago, the MD5 list is not updated till the program closes gracefully. Thus, I have to run the fixer tool after every crash. But as I filter images in the general dump folder, the images deleted also get their MD5s deleted from the list due to the tool rebuilding the list. Thus, I end up browsing all the images again whenever they come around. 

**Describe the solution you'd like**

Add an option to the blacklist fixer tool to not delete entries from the MD5 list, only add any not found.

**Describe alternatives you've considered**

Perhaps a separate Sync tool could be added also to coup with such crash related issues.

**Comment by Bionus** [comment]
> Since a certain update quite a while ago, the MD5 list is not updated till the program closes gracefully.

This should again be the case with 8f9bd691b6978a2ef4d43e41c5389637b2cae412, where the list is written every 100 new MD5 or every second since the last MD5 addition (whichever comes first). This is to prevent doing too much I/O. In case of a crash, you would therefore have **at most** have 99 missing MD5s.

> Add an option to the blacklist fixer tool to not delete entries from the MD5 list, only add any not found.

Are you talking about the MD5 list fixer or the blacklist fixer? I don't see the relation between the MD5 list in your description and the blacklist fixer?

> But as I filter images in the general dump folder, the images deleted also get their MD5s deleted from the list due to the tool rebuilding the list.

Neither the MD5 nor the blacklist fixer re-builds the MD5 list. The blacklist fixer only deletes files with blacklisted tags (without removing them from the MD5 list), and the MD5 fixer only adds new MD5s to the list.

> Perhaps a separate Sync tool could be added also to coup with such crash related issues.

What would it do?

**Comment by brazenvoid** [comment]
Well, it seems that I misunderstood the purpose of the tools. Yes, I was talking about the MD5 fixer tool.
