### ISSUE TITLE
Question about MD5 filenames

### ISSUE THREAD

**Issue by bluefiberbread** [Bionus/imgbrd-grabber#1527]
I was downloading a bunch of images from Sankaku and Yande.re, and I noticed most of their images are either corrupted/edited but they have the exact same MD5 filenames as the images on Danbooru/Gelbooru. 

When I download images from Sankaku or Yande.re with Grabber, what will %md5% do? Does it hash the images and assign it to the filename, or does it grab the MD5 from the boorus?

**Comment by Bionus** [comment]
> corrupted/edited

What do you mean by that? You mean that they were changed before being updated to Sankaku but have kept their MD5?

> When I download images from Sankaku or Yande.re with Grabber, what will %md5% do? Does it hash the images and assign it to the filename, or does it grab the MD5 from the boorus?

If the source provides the MD5, Grabber uses it. Grabber only generates the MD5 when none is provided, which AFAIK only happens on Zerochan.

**Comment by bluefiberbread** [comment]
Sankaku, Yande.re and other boorus tend to corrupt the images when they rip it from Danbooru, so when you run a hash check on those images, it's not identical, but the filename is.

**Comment by Bionus** [comment]
So that must mean that they change the image (resizing, jpg artifacts, etc) but still say the image has the original md5. Is that an issue?

I guess it would be possible to add a switch to always force md5 calculation, or another token/option for the MD5 token, but that would make the global duplicate list less efficient as you would need to download the image to know whether you already downloaded it somewhere else. Also, you would be left with quasi-duplicates.
