### ISSUE TITLE
When you try to download a lot of images from a source they will limit you at a certain point

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1530]
**Is your feature request related to a problem? Please describe**

When you download a lot of images by some sources you will reach a limit to which page grabber can reach (this is also with just searching) which has the same limit on their website.

**Steps to reproduce**

For example enable gelbooru
Search idolmaster -rating:safe
Go to page 1001 (You will see results) (Same with this: [Gelbooru with results)](https://gelbooru.com/index.php?page=post&s=list&tags=idolmaster&pid=19992)
Now go to the next page (There aren't any results anymore) ([Gelbooru without results)](https://gelbooru.com/index.php?page=post&s=list&tags=idolmaster&pid=20034)

**Describe the solution you'd like**

As you can see above there is a limit on how far you can go. However you can use `id:<` to go back past that limit, I would like it if it is possible that grabber automatically can see that it can't go any futher and use such a method with batch downloading to go past that limit.

**Images**
[With results on grabber](https://i.imgur.com/mL335qO.png)
[Without results on grabber](https://i.imgur.com/qBmZ78W.png)

**Comment by Bionus** [comment]
That should already be done by switching to ID pagination mode, which uses the lowest image ID in the previous page to try to load the next one. It doesn't even require the `id:` syntax since most sites simply have URL parameters for those. In Gelbooru's case, the limit is the 20,000th image for the HTML source, so given each page has 42 images, that's between the 470th and 480th page. For the XML API, it seems they recently changed it to the 1,000th page.

If it doesn't work it's a bug. I'll have a look when I'm back home, because it seems that the "biggest/lowest" IDs are indeed not being passed properly to the source's parser/URL generator.
