### ISSUE TITLE
Unable to save due to a period in title

### ISSUE THREAD

**Issue by Tyrindor** [Bionus/imgbrd-grabber#1532]
Using filename: %copyright%/%md5%.%ext%

When a series ends with ".." and it tries to make the %copyright% folder, it fails because windows doesn't support a period at the end of a folder. %copywrite% should detect if a show ends with "." and remove them.

**Comment by Bionus** [comment]
Indeed, it would seem that Grabber only support the removal of a single dot at the end of a filename part, instead of removing them all:

https://github.com/Bionus/imgbrd-grabber/blob/56818e04e51b7c425a16d9ad9444fe06110d6ee0/lib/src/functions.cpp#L583-L585

I'll push a fix when I'm back home, thanks for reporting this 👍
