### ISSUE TITLE
anime-pictures.net shows already viewed images in favorites tab

### ISSUE THREAD

**Issue by Tyrindor** [Bionus/imgbrd-grabber#1537]
Search for anything using anime-pictures.net, grab them and add that search to favorites, then search using favorites tab. The images will show up even though they were already viewed. Clicking "Mark all as viewed" does not work either. Seems to only happen with anime-pictures.net.

Normal behavior for that site?

**Comment by Bionus** [comment]
Yes that's because that source doesn't provide date information. The same problem is also present on Sankaku (see issue #1041).

ID favorites need to be implemented for those sources to work I believe (issue #1058). Since there's now multiple sources that are broken because of this, I'll up the priority of that ticket.

**Comment by Bionus** [comment]
Closing in favor of #1058
