### ISSUE TITLE
Nozomi.la support?

### ISSUE THREAD

**Issue by zearmhot** [Bionus/imgbrd-grabber#1538]
https://nozomi.la/

This is a really good site but I can't seem to get it to work with grabber. Does it need official support?

**Comment by brazenvoid** [comment]
@DonaldTsang Its a gallery site, the support of those is currently in beta. You can use Free Manga Downloader for downloading the galleries one by one.

**Comment by SMylk** [comment]
So what about the original question, support for nozomi.la before the thread was hijacked? :D

**Comment by DonaldTsang** [comment]
@SMylk actually both links are owned by the same people so not really a hijack.

**Comment by SMylk** [comment]
So does it mean nozomi is supported?

**Comment by DonaldTsang** [comment]
No, both are not supported (yet), but they are similar in some way since they are owned by the same people, could be tackled together.

**Comment by AhmedAhmedEG** [comment]
Nomozi.la uses javascript to dynamically load the images and modify the html of the site on the fly, the original html of site has no images at all, I have to look at the javascript code to figure out how it communicates with the backend, it's you will laugh how trash they did it, I wrote a python script to automate the download process and it worked, I already downloaded over 108GB of media from it (288k+ media files).

**Comment by AhmedAhmedEG** [comment]
For every tag, the frontend sends a request to https://j.nozomi.la/nozomi/{url_encoded_tag}.nozomi, the response is surprisingly a stream of bytes rather than a normal json, you have to take every 4 bytes and convert them to an 32-bit integer, you will end up with all the post ids for all the posts in the whole site that matches that tag, which is highly inefficient for their servers.

This explains why they send the post ids as bytes rather than json, because their backend implementation is limited to only sending all the search results at the same time, if they used json, it would take ages to load. 

After that, the front end does this funny process for all the tags, combining the results in a list and it manually removes the duplicates rather than using a data structure specified for this task like sets lol, then it does the same for negative tags an manually remove any of the results that matched the negative results manually in a loop too lol, as it doesn't use a set, it can't do any efficient difference operations.

Then they use a custom regex that results in the correct url path for every media based on the post id, along with the extension of the media, all their iamges are either jpg or png, but the site just renames their extension to webp, even thought they are not.

They have 3 ftp servers, w.nozomi.la that holds all jpg and png images, v.nozomi.la/ that holds all mp4 and webm videos and g.nozomi.la for all gif animations.

accessing the media download link directly will mostly result in an 403 negix error, they require to add an extra info in the HTTP header 'Referer': 'https://nozomi.la/' to access any media download link

**Comment by visiuun** [comment]
> Nomozi.la uses javascript to dynamically load the images and modify the html of the site on the fly, the original html of site has no images at all, I had to look at the javascript code to figure out how it communicates with the backend, it's you will laugh how trash they did it, I wrote a python script to automate the download process and it worked, I also used async programming for fast downloading, I already downloaded over 108GB of media from it (288k+ media files).

can you send the python please?
