### ISSUE TITLE
Is there a filenaming tag for gallery name?

### ISSUE THREAD

**Issue by zearmhot** [Bionus/imgbrd-grabber#1552]
I checked the documentation but didn't see anything. With the nightly supporting e-hentai, I would like to separate my galleries and then number them 1 through infinite. Aka something like:

/%gallery%/%gallerycount%.%ext%

Is this possible yet?

Also, is there any plans to support exhentai (the off site of e-hentai). Seems very complicated to get access to, so not sure how grabber would handle it. https://pastebin.com/nh9RyrUf

**Comment by Bionus** [comment]
See issue #917 for progress on gallery support.

I'm currently working on adding said tags, and in nightly the only supported gallery tags for EH should be `%gallery.id%` and `%gallery.name%` (note the dot `.` notation). Grabber will say that those tokens don't exist, but just ignore the warning, they should work.

The `%gallerycount%` you suggest does not exist yet, but it's definitely planned as otherwise galleries wouldn't be sortable properly. But it would likely be called %position% or %index% instead (maybe with a gallery_ prefix too).

Also, note that those tokens were literally added a few hours ago, so I can't guarantee that everything works perfectly.

**Comment by Bionus** [comment]
I just added a `%position%` token, which is the position of the image in the results.
Useful for galleries :+1:
