### ISSUE TITLE
No results when restoring a page above the page limit

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1555]
**Bug description**

When you search on sankaku on a page above 50 (so 51 and up) it will give again the 4 populair images (which were filtered away in the pages below 51). 
The second problem is that it will not give any results when you restart grabber when the page is above 50. It will give results again when you go to the next page and go back now as a workaround.

**Expected behavior**

Filter those 4 images away like with the other pages and have results when the page is above 50 without having to do the workaround.

**System information**

Windows 10
Grabber version: 7036bbbf

**Comment by Bionus** [comment]
> When you search on sankaku on a page above 50 (so 51 and up) it will give again the 4 populair images (which were filtered away in the pages below 51).

Let's move this to #1543 as they're the same root (and the same fix: def662cb2031efdba1179d127c8f182fc77444e1).
So I renamed this issue to reflect the second issue you described.

> The second problem is that it will not give any results when you restart grabber when the page is above 50. It will give results again when you go to the next page and go back now as a workaround.

Indeed, this actually applies to most sources that switch to a secondary ID-based paging system after reaching some value, likely because of their database system or indexing performance limitations.

I can indeed reproduce this, if you keep going page by page from page 1 to let's say 60 on Sankaku, on restart you'll have to re-start from page 50 to have correct results. I'll see to fix this, likely by storing the full page URL and loading it on startup instead of re-generating it from the search.
