### ISSUE TITLE
Grabber isn't able to load images with the webp format

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1562]
**Bug description**

Grabber doesn't seem to recognize and correctly load the images from the webp format.

**Steps to reproduce**

Enable the anime-pictures source
Search pest_(mondaiji) and click on any of those 4 images
You will now see that it isn't able to load those images

**Expected behavior**

Properly load those images and probably convert them from the webp format to the normal one when downloading it.

**System information**

Windows 10
Grabber version: 278ead2b

**Comment by Bionus** [comment]
It seems to be caused by a bug in their JSON API:
https://anime-pictures.net/pictures/view_post/256301?lang=en&type=json

If you check the `file_url` field, it's invalid because it contains an unescaped `?` character.

I'll push a fix to correct this in the model file, but I think they should fix this on their end.
