### ISSUE TITLE
conditional filenameing/folder

### ISSUE THREAD

**Issue by drakkillen** [Bionus/imgbrd-grabber#1569]
i been trying for 1.5h to make a conditional to put images containing a specific tag in a specified folder and its not working.
i follow the wiki and tried numerous combinations but it just don't work, and the examples aren't really clear on how to do it:
tested conditionals
<%tag:contains="TagName">
<"TagName">
"TagName"
<TagName>
TagName
<%tag% "TagName">
<%tag% TagName>
<tag = "TagName>

might tested more variations i don't remember
any clarification would be much much appreciated

**Comment by Bionus** [comment]
What are you exactly trying to do?

`<"tag_name"/>%md5%.%ext%` will generate `tag_name/%md5%.%ext%` if "tag_name" is present, and `%md5%.%ext%` if it's not, which looks like what you're trying to do.

The same thing applies with a `%token%`, where `<%artist%/>%md5%.%ext%` will generate `%artist%/%md5%.%ext%` if the image has any artist, and `%md5%.%ext%` otherwise.

Also, in most cases I would suggest to use a full conditional filename instead:

![image](https://user-images.githubusercontent.com/882719/51627621-fd54b380-1f42-11e9-9912-1a66d6edef5b.png)

Where you don't have to complicate your filename with conditions.

Also, both conditionals will get totally re-done for Grabber 7, with a much clearer syntax.

**Comment by drakkillen** [comment]
ah i see
