### ISSUE TITLE
Incorrect paging behavior when browsing multiple sources

### ISSUE THREAD

**Issue by GiovanH** [Bionus/imgbrd-grabber#1579]
**Bug description**

When browsing multiple sources at once (not "merge results" mode), Grabber's page cap is set to the lowest shared cap, instead of continuing to load.

For example:

If tag "dragon" has 900 pages on booru A, and 10 pages on booru B, Grabber will be unable to page beyond 10 pages. 

When source A has only X pages, it should display as having 0 images on pages > X. Instead, it resets the page number to page X, causing undesired behavior when viewing multiple sources. 

**Context**

No errors reported; behavior is simply incorrect.

**System information**

- OS: Windows 10
- Grabber version: 6.0.6

**Additional context**

None

**Comment by MrAndre96** [comment]
This has been fixed already for some time in the nightly version of grabber. 6.0.6 is pretty outdated and has a lot of bugs

**Comment by GiovanH** [comment]
Well that's good to hear. I'm sorry I wasn't able to find the ticket about the issue already.

One problem, though. I'm not seeing a archive of nightly builds, just the one most recent build, and apparently it's failing some tests. Are there any plans on updating the stable branch?

**Comment by MrAndre96** [comment]
the build that is failing isn't for windows but a other system since appveyor is the one for windows (which passes the test). You can see [here](https://github.com/Bionus/imgbrd-grabber/releases/nightly) the current nightly version

**Comment by Bionus** [comment]
Yeah I remember having solved a similar issue a while back, so it should be fixed in nightly.

I'd love to release a new version but given the number of breaking changes currently on `develop`, I think it will have to wait until end of February~beginning of march for finishing up the issues marked as `v7.0.0` and stabilizing a few things I just added (notably the new improved filename parser).

I should really start following [git flow](https://nvie.com/posts/a-successful-git-branching-model/) to be able to have multiple versions in the works at the same time 😅
