### ISSUE TITLE
Duplicates and overwriting(data loss), how to awoid?

### ISSUE THREAD

**Issue by Mad-onanist** [Bionus/imgbrd-grabber#1588]
Right now my path is:

> %copyright%/%character%/%md5%.%ext%

So if any tags for copyright or characters is different on different sourses(right now i use two sites), will i get duplicated files(in the different folders)? 

And if i just put them all into one folder, here is shall be a chance that md5 of different files will be same and so i lost some info, right?

Since i creating small DB(BTW, cool the feature!) for the tags and md5, am i good in any case, or there is a huge chance to screwup?

I want just minimize downloading of the downloaded before, and keep all that already downloaded.

**Comment by Bionus** [comment]
> will i get duplicated files(in the different folders)?

This depends on your "Global duplicate list" setting.

![image](https://user-images.githubusercontent.com/882719/47616036-a2ccc800-dab7-11e8-9f72-288ae23044c1.png)

* **Save**: download and save the image twice (as if it's not a duplicate)
* **Copy**: save the image twice, but copy it from the original image to prevent an useless download
* **Move**: move the original image to the duplicate location (useful for example if you're re-downloading an image that has changed a few tags)
* **Link**: create a shortcut with the duplicate image's name, pointing to the original image (useful if you often have duplicates in different folders, with each folder having an useful meaning)
* **Don't save**: skip duplicate images

> And if i just put them all into one folder, here is shall be a chance that md5 of different files will be same and so i lost some info, right?

Very, very, **very** unlikely. MD5 collisions are extremely rare, to the extent that you don't need to worry about this at all. That's even why those MD5 are used as a "unique image identifier": if anything in the image changes, even the slightest modification of one pixel, the MD5 will be completely different.

You can read more about it [on Wikipedia](https://en.wikipedia.org/wiki/MD5).

> Since i creating small DB(BTW, cool the feature!) for the tags and md5, am i good in any case, or there is a huge chance to screwup?

No problem here AFAIK.

> I want just minimize downloading of the downloaded before, and keep all that already downloaded.

Then make sure to use the "global duplicates" setting properly, and you won't have any problems here (as long as you don't manually move images around, otherwise Grabber can't keep track of them).
