### ISSUE TITLE
Feature request: Be able to set the images per page in the settings

### ISSUE THREAD

**Issue by MrAndre96** [Bionus/imgbrd-grabber#1597]
**Is your feature request related to a problem? Please describe**

When you click 'get all' all the sources now set the images per page to the max limit. Which is by gelbooru for example by default 1000. It would be nice if this can be by default set lower without having to change it each time (you do 'get all') by the download page.

**Describe the solution you'd like**

Currently there is nowhere in the settings for a source a image per page limit. It seems now to be hardcoded in the model class. But since you are now able to restore previous batch downloads when it goes over this limit it would be nice if this could be set by default lower.

**Comment by Bionus** [comment]
> But since you are now able to restore previous batch downloads when it goes over this limit it would be nice if this could be set by default lower.

Are you making this suggestion only because of this?

With this you'd lower the setting to let's say 100, which means you'll be able to "restore" the downloads with a better granularity, but that also means that you'll have to download 5 more pages, which is more costly than the duplicate checks of a bunch of images.

As said in #1529 however, this limit is currently only technical, and soon it will disappear, which means that if you have 500 images per page and only downloaded 100, it will soon be able to re-start the download at the 100th image. Would this suggestion still be relevant then?

**Comment by MrAndre96** [comment]
Ah then not. Thought the way it was implemented now would be the finnal result and then I thought that this may be a good idea. (Otherwise the restore function would only work for large image results).
