### ISSUE TITLE
Multiple Copyrights result only in "crossover"

### ISSUE THREAD

**Issue by Htlrddnthngwrng** [Bionus/imgbrd-grabber#1599]
I'm a total dumbfuck when it's about coding and playing around in options on a lot of programs, sp please have mercy.
My question is, if there are multiple copyrights and i use %copyright% it ends up with just crossover instead of all copyright tags in the booru (in my case rule34.xxx). Online i found nothing about it and i wanted to know if there's a way to get all copyrights. Especially annoying when its stuff like Naruto and Naruto: Shipuuden.
Ty in advance, love the programm otherwise.

E: same goes for %character% and the "group" tag
E2: damn thank you for the fast answer, ♥ u mate

**Comment by Bionus** [comment]
Indeed, the defaults in the current version is to use `crossover` when there are multiple copyrights. That's because Grabber was (heavily) inspired by the [Danbooru Downloader Firefox add-on](https://web.archive.org/web/20181102055646/https://addons.mozilla.org/en-US/firefox/addon/danbooru-downloader/) (now discontinued), and all defaults have been taken from that add-on. Defaults will change in the next version, see issue #1512.

This is easily changeable in the settings (Save > Copyright tags):

![image](https://user-images.githubusercontent.com/882719/54138928-c0744b80-4420-11e9-8903-a1ec83720cc1.png)

**Comment by Htlrddnthngwrng** [comment]
So i switch it to keep all tags?

**Comment by Bionus** [comment]
If that's what you want it to do, yes.
Don't forget to set the separator to a space or a comma if you don't want a plus symbol.

**Comment by Htlrddnthngwrng** [comment]
thanks
