### ISSUE TITLE
Show downloaded status on image thumbnail

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1603]
When someone uses the right click download option and the file gets fully downloaded, there is no visual change on the thumbnail itself unless one explicitly right clicks it. To show such status, a small icon/marking can be overlayed on top the thumb or the thumb can be given a different outline/style. 

Such change can have many usability benefits:
- This same highlight can also be used on already downloaded images showing them distinctly in the search results. 
- It will save users from right clicking an image when in doubt that it got downloaded.
- Usually when one is using the context menu to hand pick images, it is possible to delete an existing image as the delete option comes in place of the download option. For me, who does this really fast, I am distinctly acquainted with this issue.

**Comment by Bionus** [comment]
I don't have anything against this, however the issue is how to represent it.

You mention an image overlay or an outline, but the outline is already used for too many things, so those may overlap (if for example you have an already downloaded image with a favorite tag, it will only be able to show one information).

As for the overlay, given there is already kind of one for galleries, it would be better to re-use it. The problem being that it's ugly AF. I guess cutting a corner would be less ugly.

Current:
![image](https://user-images.githubusercontent.com/882719/54960936-0cfe7180-4f5f-11e9-8c23-12548a5b3a2f.png)

Corner:
![image](https://user-images.githubusercontent.com/882719/54960928-07089080-4f5f-11e9-9d2f-3018c1e6e5d1.png)

Which would allow using multiple corners, for example another one if the image is saved:
![image](https://user-images.githubusercontent.com/882719/54960916-f9530b00-4f5e-11e9-9634-1217d3b96d73.png)

_(those are from paint and are only to show an idea)_

**Comment by brazenvoid** [comment]
If we have no plans to add a checkbox or any other action sometime in the future then the left corner is good. But I consider the top corners as prime for actions so the bottom left corner will be good for the indication, perhaps with a disk/folder icon.
