### ISSUE TITLE
Please keep track of milestone progress

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1605]
It has been too long since a release and new users will have to scour the issues to know that there is also a nightly release which has many issues resolved. Usually they will be either living with the released version cursing the devs or would have already abandoned the app. 

Grabber is very stable now in nightly. It has been many weeks that I have experienced any crashes at all. 

Either present the nightly link on the front page as an alternative or at least keep proper track of the milestone progress. I mean close the issues which are done, they will remain in that list, you will still be able to see them but you and all of us will know how much is done and what is left till v7 release.

**Comment by Silvia-Rose** [comment]
:o where is nightly release? im pretty bad at github

**Comment by Bionus** [comment]
I absolutely agree with this on principle, as it's not easily visible what's the next release's status.

However, the problem with closing the issues that are done in nightly is that users will say "why is this closed", or simply won't find the issues (as Github hides closed issues by default) and create duplicates.

If you have suggestions/examples of how other repos/projects manage that I'd gladly have a look, but having looked around and following a few projects, none of the options feel really satisfying (using Github projects, or by labeling "done" options). The only good way is to simply make releases more often (which I'll hopefully do starting 7.0.0), or having intermediate states between "open" and "closed", which Github doesn't do.

I purposely left 7.0.0 in nightly for a long time because I'm doing lots of big technical changes in how Grabber works internally, which, while maybe not visible to you as an user, can cause lots of weird bugs and crashes. The gallery system, filename parsing, and authentication re-write are good examples of this.

But you'll be happy to know that the 7.0.0 version should be released on Sunday. Since you ask for progress status for issues, just know that all of those [flagged as 7.0.0](https://github.com/Bionus/imgbrd-grabber/issues?q=is%3Aissue+milestone%3Av7.0.0) are already done in nightly.

> Either present the nightly link on the front page as an alternative

> :o where is nightly release? im pretty bad at github

The link is in the [readme](https://github.com/Bionus/imgbrd-grabber#download):
https://github.com/Bionus/imgbrd-grabber/releases/nightly

**Comment by brazenvoid** [comment]
Git is well not for normal users so essentially it does not have tools which may help users who purposefully do not search both open and closed issues. Usually other repos who use github as a bug tracker and support forum have at least one or two moderators working to cleanup the issues. Tagging them duplicate or already resolved etc.

**Comment by brazenvoid** [comment]
But the recent beta look up feature does show matching issues (stack style) whether open or closed so it is getting there albeit slowly.
