### ISSUE TITLE
Linux build fails to create the 'Grabber' executable

### ISSUE THREAD

**Issue by DukeValentine** [Bionus/imgbrd-grabber#1612]
**Bug description**

On the release directory only a symbolic link named Grabber is present, which points to a non-existent 'Grabber -7.0.1'. The same problem happens with the 7.0.0 version.
No errors during the building process.

**Steps to reproduce**

Execute the build.sh script

**System information**

- OS: Linux Manjaro
- Grabber version: 7.0.1

**Comment by aTosser** [comment]
cd imgbrd-grabber
rm "release/Grabber"
mv "build/gui/Grabber-7.0.1" "release/Grabber" 

When the symlink is created it should be created with the path:
../build/gui/Grabber-(version_number)
otherwise when it is moved by the build script it will move the link but keep the old path (pointing to the same directory that the symlink now resides in)

**Comment by Bionus** [comment]
For some reason `cmake` decided to add the version number to the resulting binary then make a symlink to it. I just removed the version information to revert this 👍
