### ISSUE TITLE
Unable to add pixiv, ehentai, and twitter sources

### ISSUE THREAD

**Issue by j4anon** [Bionus/imgbrd-grabber#1618]
Just downloaded new update, trying to add new sources but it cannot identify the site type. Can someone tell me what I'm doing wrong?

**Comment by LatvijaSuido** [comment]
Yes, I have had similiar problem. I am unsure but maybe the problem is on the type of Login pixiv is currently using for Grabber, OAuth 2. Do we need a software or browser based authentication app to be able to get the "Consumer Key" and "Consumer Secret"?

**Comment by j4anon** [comment]
I just have trouble adding the sources. I am not sure what type they are suppose to be, as they are not showing up any results in the grabber.

**Comment by LatvijaSuido** [comment]
What do you mean adding the sources? Regardless, can someone explain what, "POST" Login means? I've got all the cookies I think I need added but I don't have header and don't know what "POST" is from? Is that just username and password to EX or E hentai? I searched previous issue with the keyword, "POST" and found nothing. 
![cookies](https://user-images.githubusercontent.com/49381798/55695863-7c755780-5988-11e9-9e57-edb7a8e625b8.png)

**Comment by j4anon** [comment]
If you wanted to add sources like another site. That is what I meant when I said adding the sources. Also, what are the steps in being able to use ehentai and twitter and pixiv? Do i need to input something into cookies? I'm just very lost right now.

**Comment by LatvijaSuido** [comment]
I'm not quite sure what cookies you need for sites. I'm more interested in what "POST" method of login is. Because it doesn't work even if I have the right credentials included. However if there's an option for "Through URL" I works just fine, I don't even need to add cookies.

**Comment by Bionus** [comment]
> Just downloaded new update, trying to add new sources but it cannot identify the site type. Can someone tell me what I'm doing wrong?

You're not supposed to add anything. If the update installed properly, they should show-up when Grabber starts (they are added by default). They are called `api.twitter.com`, `e-hentail.org`, and `www.pixiv.net` respectively.

Also, if you were to try to add them yourself, you have to enter the site type manually, they can't be "guessed".

> Yes, I have had similiar problem. I am unsure but maybe the problem is on the type of Login pixiv is currently using for Grabber, OAuth 2. Do we need a software or browser based authentication app to be able to get the "Consumer Key" and "Consumer Secret"? I understand OAuth 2 is a standard of authorization for users to grant information to websites and other things but I don't understand how to personally use it.

The consumer key and secret are setup by default, using Pixiv's mobile app values. All you have to do is provide your username/password, but because of issue #1622, the fields don't show up (will be fixed in next update).

> Regardless, can someone explain what, "POST" Login means? I've got all the cookies I think I need added but I don't have header and don't know what "POST" is from? Is that just username and password to EX or E hentai? I searched previous issue with the keyword, "POST" and found nothing.

You don't have to add any cookie, Grabber does the logic for you. IIRC, the login for e-hentai always shows "failed" for some reason even if it works, so just put your username and password in the "POST" login settings, click "Test", then try to use the source, it should work.

"POST" means the logic is done by a HTTP POST request (as opposed to passing the credentials in the URL like Danbooru, or via OAuth2 for Pixiv), sending your credentials to the server, which will then answer by sending back cookies (for E-Hentai, the `ipb_member_id` cookie and some others).

> Bionus should add a "through url" option if that's possible for pixiv and e hentai. For e621 all you need is your normal login details.

That's not possible. Which options are available depend on the source and I can't do anything about it.

> If you wanted to add sources like another site. That is what I meant when I said adding the sources. Also, what are the steps in being able to use ehentai and twitter and pixiv? Do i need to input something into cookies? I'm just very lost right now.

Just install the update, open the "Sources" window, edit the source you want to use (E-Hentail / Pixiv), go to the "Login" tab and add your credentials there.

Cookies are for some advanced usage or if the login features provided by Grabber don't work. You're not supposed to use them in a normal usage.

> I think a lot of the sources are only available to people are have moderate understanding on how coding and interacting with websites works so I'm just gonna stop. Would've been convenient but I'm just going to delete the ones that only offer a GET or POST request instead of normal "through url" for login. Maybe if Bionus or someone makes a quick guide how to gather the 3 types of information you need, Login, Header and Cookies, I'll re add those but currently they're useless.

You litteraly only have to enter your credentials in the "Login" tab, I don't see what "coding" you have to do here. Ignore the "Headers" and "Cookies" tab unless you know what you're doing.

![image](https://user-images.githubusercontent.com/882719/55995681-6f70a500-5cb5-11e9-8157-6f9609a1b7d5.png)

**Comment by LatvijaSuido** [comment]
Sorry for the late reply, thanks for the information. I will use this when I get a chance, I have been busy lately.

**Comment by j4anon** [comment]
quick question, where would i find api.twitter.com, e-hentail.org, and www.pixiv.net?

**Comment by Bionus** [comment]
They should be in the "Sources" window after the update. If they're not, can you check if you have the Twitter, E-Hentai, and Pixiv folders in `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber\sites`?

**Comment by LatvijaSuido** [comment]
> They should be in the "Sources" window after the update. If they're not, can you check if you have the Twitter, E-Hentai, and Pixiv folders in C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber\sites?

Not sure if this is only me so I don't want to make a new issue, Pixiv works fine now, ExHentai has some issues however. Auth was a success, username and password were accepted, sources are in default, nothing is in cookies or headers. I can search a keyword, for example, "western"
Everything comes up normally. 
![screen1](https://user-images.githubusercontent.com/49381798/56464545-2bb72300-63ba-11e9-9450-ef31b3065bd1.png)
However once I click on an actual gallery nothing loads. 
![screen2](https://user-images.githubusercontent.com/49381798/56464554-5012ff80-63ba-11e9-89bd-c764a18a1120.png)
Can you reproduce this? If not do you recommend I just reinstall?

**Comment by j4anon** [comment]
Im still getting no results in e-hentai. I tried looking for it in the sites folder, but I don't really see it. Unless it is in a more specific folder. When I type western, it said no valid source of the site returned results. I think I might need to redownload the grabber, unless im doing something wrong.
