### ISSUE TITLE
File Size + Resolution Limit

### ISSUE THREAD

**Issue by sterelok123** [Bionus/imgbrd-grabber#1633]
Hi,

I'd like to see some kind of configuration for file size limit; for example, to be able to search files only below or above a certain range when searching for keywords or tags.

I would also like to see a similar limit or range indicator for resolution.

Some of the files are too heavy. Some of the images have absurd resolutions. A sort of system to control the range for such files can be helpful. Keep up the good work.

Thank you.

BW,

**Comment by Bionus** [comment]
Hello,

Which sources are you searching on?
Many already have this feature implemented, usually via a `filesize:` "meta-tag". For example, searching `test filesize:<200kb` on Danbooru would only show images tagged "test" whose size is lower than 200 kb. Same thing for `width:`, `height:`, etc. You have Danbooru's full list [here](https://danbooru.donmai.us/posts?tags=help%3Acheatsheet).

Since not all sources have this feature, Grabber has what's called "post-filtering", which means that it can filter out results itself, without relying on the website doing it. If you click the `+` button on a search tab, you'll see that field. `filesize`, `width`, `height`, etc. are also supported there.

**Comment by sterelok123** [comment]
Thanks for the prompt reply.

I'll try to look it up when I have the time.

Thanks again.
