### ISSUE TITLE
Can't download from E-Hentai/Ex-hentai

### ISSUE THREAD

**Issue by TidusFH** [Bionus/imgbrd-grabber#1648]
Was trying to download from both sites lately but the downloads wont just start, i was sure checking the configurations and the configuration seems to work but when i go or to e-hentai or ex-hentai not only the download wont start if i click on a individual picture and compare on what i would see in the individual picture from another site it seems that there is some sort of problem 

and i'm also unable to download individual pictures

A pic comparing when i click on a individual image from ex-hentai and one from sankaku complex 
![problem](https://user-images.githubusercontent.com/50292972/57193483-f3632900-6f11-11e9-9e71-5fcf88fa7dca.png)

Also nothing i do when its related to these sites generate any kind of log most of time,only when i try to download batchs but it says that its loading images but it will completely stops at an exact number of images that the log claims its loading(in my case it stops after loading 6)

**Comment by asdffadasd** [comment]
Same issue here. Only thumbnails load from E(-/x)hentai. When I right click the image and select "reload" a progress bar appears at the bottom of the page, but it stays at 0%.  Nothing shows up in the log about the failure either. 

Only shot in the dark I have is that it could possibly be related to https enforcement, because I have previously had problems loading images through H@H in my browser with a plugin that refused http connections, but that's pure speculation, and toggling the site https option does nothing to help.

**Comment by mattiiz** [comment]
exactly the same issue. also can't download from pixiv. stuck on "Downloading pages.please wait..." 
i'm on ver. 7.1.1 Win10 pro 1803

**Comment by d-mmmy** [comment]
+1 Issue still here. 7.2.1 (linux AUR build)
![grabbernograbbing](https://user-images.githubusercontent.com/44706270/75614780-46256580-5b62-11ea-8aa6-2c351f67650b.png)

**Comment by CobaltSpace** [comment]
From what I can tell, it looks like it is trying to get the image thumbnails instead of loading the actual images from the H@H network.  My guess is that the image retriever for this site needs to be rewritten to get the image that the site gives when the page loads.

v7.2.1.r157.97bda680 from AUR
