### ISSUE TITLE
Qt Warnings

### ISSUE THREAD

**Issue by frebeee** [Bionus/imgbrd-grabber#1661]
**Bug description**

I'm seeing these in the logs. What do they mean, and are they a problem?

1. [Warning] [Qt][default] QIODevice::read (QNetworkReplyHttpImpl): device not open
2. [Warning] [Qt][default] libpng warning: iCCP: known incorrect sRGB profil

**Steps to reproduce**

1. Download files
2. Check logs

I know that's not so helpful. I don't know what causes the errors.

**Expected behavior**

Qt warnings do not appear in the logs.

**System information**

- OS: Win 7 x64
- Grabber version: 7.1.0 x64

**Comment by Bionus** [comment]
Hello

Most messages labelled as `[Qt]` can be safely ignored, unless of course you also see some weird behaviors from the program at the same time. In your examples:

> [Warning] [Qt][default] QIODevice::read (QNetworkReplyHttpImpl): device not open

Usually happens when a network request was aborted but Grabber is still waiting for something from it. It's caused by some faulty code in Grabber. It can be ignored by end users, but I should try to get rid of it.

> [Warning] [Qt][default] libpng warning: iCCP: known incorrect sRGB profil

This is caused by showing PNG images with an invalid ICC profile.
[More info on StackOverflow](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile/43415650)

While it's not caused by some issue on Grabber's side but rather on the files served by the sources, this warning can be safely ignored and should be "eaten" by Grabber and not shown in the log (or only in debug mode). So something I have to change.
