### ISSUE TITLE
How can I scrape images off a board from 4chan/8chan? Apparently the source to add it isn't there.

### ISSUE THREAD

**Issue by apriom** [Bionus/imgbrd-grabber#1690]
I want to automatically scrape all the images from an entire board on 4chan/8chan however everytime I try to add it to the source list, it says it's unable to get the site's type. What can I do to fix this? I put https://boards.4chan.org/b/ as the url for the source.

![screencap](https://user-images.githubusercontent.com/51178205/58616941-e75a5500-828c-11e9-85ad-476e87ddc00d.PNG)

**Comment by jwshields** [comment]
I could be wrong, but as far as I know, grabber does not support 4chan/BBS styled imageboards

**Comment by Bionus** [comment]
> I could be wrong, but as far as I know, grabber does not support 4chan/BBS styled imageboards

Indeed, they aren't supported yet.
But since v7, they could be added without too much of a problem I guess.

**Comment by Tumultuous-RGR-SiM** [comment]
What I want to do is plug in a specific 4chan thread in the search bar, and selectively download specific images in the thread. 

Is that possible in the vurrent version of the program?
Should I make a new issue to talk about this feature, or is this close enough to "4chan board ripping" to leave here?

**Comment by FichteFoll** [comment]
FWIW, I wrote a small utility to download all images of a 4chan thread a couple years ago by collecting various code samples over the net because I was unsatisfied with everything I found. I intended to filter out the things I didn't like later on-disk.
Not sure if it still works, but [it's here](https://github.com/FichteFoll/dotfiles/blob/master/tools/tools/4ch-downloader.py).
