### ISSUE TITLE
Gelbooru: Specific images not loading

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1705]
**Bug description**

I was exploring a tag when I randomly clicked an image which threw an error in the log. I was able to consistently reproduce the issue across program restarts. The image loaded fine on the website. Perhaps this is an isolated case or indeed a bug. Still I am sharing so you can see for yourself. 

**Error logged:**
[Error] Loading error for 'index.php?page=post&s=list': Protocol "" is unknown

**Image (NSFW):**
dae3b6faf71dfe4d368c166fab2f8778
aee7521d7ebe2d231297d6af38393253

I will add more as I discover them.

**System information**

- OS: Windows 10
- Grabber version: Nightly

**Comment by Lanilor** [comment]
I have the same problem with various images since yesterday or the day before. I also couldn't find a pattern for this on a quick search, like certain tags, image formats or such.

I found these two very similar images where one loads and the other doesn't. Maybe helpful for further research (nsfw):
Not loading: 3627ffe001ebe451e9431a0778093726
Loading: 0fcc95c967fe831058f1d26ad8990b3a

System information:
OS: Windows 7
Grabber version: 7.1.1 (x64)

**Comment by KuroPon** [comment]
Can confirm this problem, I also managed to get some sort of pattern.
All images containing the tags "loli" or "shota" fail to download.

Clicking on "save as..." fails, right clicking and choosing "Open in browser" fails, but choosing a site under "Web services" shows that the application has the correct link.

Downloading this correct link with tools like wget or curl works too.

**Comment by Lanilor** [comment]
It seems that gelbooru has (temporary) blocked the search for those tags for non-logged-in users. Open this link in a browser to see the error message:
https://gelbooru.com/index.php?page=post&s=list&tags=loli

SOLUTION:
Create an account (only needs a name and password, no email address), add those login data to grabber  (under "sources") and it works.
