### ISSUE TITLE
Searching in e-hentai/ex-hentai

### ISSUE THREAD

**Issue by j4anon** [Bionus/imgbrd-grabber#1725]
It shows up as no valid source of the site returned. I put in the info for the POST login in site options. Unless there is a different way for searching since its a gallery type site. Also I have the latest version 7.1.1. I want to test it for looking for something like this: https://e-hentai.org/g/1451735/7771dd4c43/.

**Comment by Cascaisdude** [comment]
Exhentai is gone dude, try searching it up on 4chan /h/, I guess it was some legal stuff that in the end didn't really turned out be i'm not really sure, people are saying the owner just wanted to throw it all away. Exhentai is gone but e-hentai is working, kinda buggy and slow but working, though the owner said it will be gone in a few months.

**Comment by j4anon** [comment]
ok, just found that out. damn, but I want to download some artbooks from e-hentai. I know that the grabber supports this now, but im a little confused on how to search.

**Comment by Bionus** [comment]
Indeed, it would seem that Grabber was unable to search for non-h categories, as it used to use the default categories for searching:
![image](https://user-images.githubusercontent.com/882719/70555905-39572e00-1b80-11ea-80ab-b8c3e2efe611.png)

I pushed a fix to use all categories by default, with an option to override it using the `cats:` modifier. Now, the results show up properly:
![image](https://user-images.githubusercontent.com/882719/70555886-32302000-1b80-11ea-804a-2a337fa8440c.png)

**Comment by Seg22** [comment]
Hey there, sorry to reopen that issue, but exhentai isn´t gone and i would love to use the Grabber for that site too. I filled in the cockies to exhentai and that works or well i see "No results" instead of "Possible reason: Server offline No valid source of the site returned result" so maybe you have to do the same like for E-Hentai. That would make sense to me, hope you will try it. :)
