### ISSUE TITLE
Favorites across multiple sources.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#1733]
**Is your feature request related to a problem? Please describe**

Not a problem really, but could it be a way to get image with same tags frome multiple boards ? Like "League of Legends" from Gelbooru and E621 at the same time ? At the time of 7.1.1 it is only possible to have one source for a request.

**Describe the solution you'd like**

Something like having the possibility to add wich board should the favorite task get image by checkboxes ? And maybe a form to input a save-path for each entry (because in some case board use different tags from each other (like : species frome e621 or artist/model)) but his look rubbish.

Maybe the best solution would by to accept duplicate entry for "favorites" but with the source included like :
 ```Favorites : "League of Legends (e621), League of Legends (gelbooru), etc"```
So we know wich board the favorite survey, the name of the board would be added from the json ?
Then the program would just proceed as normal 
**Describe alternatives you've considered**

I tried using different case but it does not work. My only solution for the time being was using "league_of_legends" for Gelbooru and "league_of_legend riot_games" for e621

**Comment by Bionus** [comment]
I think you could already use multiple sources in favorites in 7.1.1, they were just applied to all favorites and had to be changed every time.

With issue #1977 included in 7.3.0 (with a bug that will be fixed in 7.3.2), it should be solved now since you can now link specific favorites to specific sources. In addition, the monitors tab should also help.

>  So we know wich board the favorite survey, the name of the board would be added from the json ?

Yes, the sources are now included in the JSON if present. For example:
```json
{
    "lastViewed": "2020-07-25T12:21:09",
    "note": 75,
    "sites": [
        "danbooru.donmai.us",
        "gelbooru.com"
    ],
    "tag": "test"
},
```

> And maybe a form to input a save-path for each entry

This is why I don't think a favorite should contain different tags or too much different settings. For this case, you should just do multiple favorites before it gets too complicated 😅 

Also, if you often use multiple boards and stuff that requires multiple filenames, I'd say it'd be more convenient in the long run for you to use conditional filenames and/or conditions inside your filenames so that you don't have to change it too often.
