### ISSUE TITLE
Nesting Copyright Folders

### ISSUE THREAD

**Issue by ghost** [Bionus/imgbrd-grabber#1737]
I apologize if this is obvious or basic, but I'm not a programmer, so this kind of thinking isn't familiar to me. I read through the filename documentation and couldn't find any way to do what I wanted, so I figure the next step would be to ask people that **do** know.

My current preferred organizational structure revolves around a hierarchy of copyright folders, wherein the pictures are then separated by artist, where the images are then placed. For example:
`Main Folder/Video Games/Nintendo/Pokemon/artist`

My primary question is whether or not it is possible to specify certain tags as being parents of others. I also would like to know if I can have a parent tag automatically assumed based on that association. My goal is to maintain my current organizational structure while utilizing this handy program that I wish I knew about sooner.

Given my previous example, I would want any file with "Pokemon" to automatically go to the folder in Nintendo which is in Video Games, regardless of the presence of Nintendo in the tags. Certainly without "video_games" in the tags, as I am certain no one tags that.

Similarly, are tag "translations" possible (make "Porkyman" into "Pokemon" in file names for instance. Or at least have them both go to the same folder.

**Comment by Bionus** [comment]
Hello

It is possible to do that using basic filenaming, but it's pretty hard to read and painful to write.

> My primary question is whether or not it is possible to specify certain tags as being parents of others. I also would like to know if I can have a parent tag automatically assumed based on that association.

From what I see, you need "tag implication" as they call it on some boards (and where it's already implemented), meaning that the presence of "tag A" (in your case some pokemon's name) causes the presence of "tag B" (in your case Nintendo). Some sources already do it (such as Danbooru), but many do not.

Grabber, at the moment, does not support this feature, at least not in an easy way. You can make use of the "custom tokens" to imitate it however. For example, you could create a "%is_pokemon%" custom token, containing all the tags related to Pokemon. Then, the "%is_pokemon%" will not be empty if one of those tags are present. Then, in your filename, you could use conditionals to only show the "Nintendo" part if the token is not empty, with for example "<-%is_pokemon%Nintendo>" (see https://bionus.github.io/imgbrd-grabber/docs/filename.html). The same thing can be done for the "Video Games" part.

But to be honest, that sounds like a pain to do if you have many tags like this. However, if you only have one, it's not that big of a problem.

> Similarly, are tag "translations" possible (make "Porkyman" into "Pokemon" in file names for instance. Or at least have them both go to the same folder.

Never heard about "Porkyman" being used instead of "Pokemon", but for this kind of use case, you can also use conditionals, like `<"Porkyman" || "Pokemon" ? Pokemon>`.

-----

While I feel like you can definitely use the current filenaming system to reach your goal, to be honest I would instead suggest you to try simply scripting your filename with JavaScript.

All the tags and everything else are passed to your script, then you can generate whichever filename you want with a clearer JavaScript syntax.

**Comment by somestupididiot53918** [comment]
Thank you for your reply.

I would certainly be willing to try programming it in JavaScript, but I wouldn't know where to begin. It has been awhile since I took that programming class in high school and I don't remember much of it. I think we used C++, but I don't know which version.

Regardless, we never actually saw how our scripts would work outside of the coding environment, when we ran them it was always through there. Any assistance would be appreciated in this area, although I understand that if you helped everyone individually with custom code and/or coding directions that you wouldn't be able to program for yourself.

**Comment by Bionus** [comment]
If you're relatively new to programming, I would suggest instead using Grabber built-in features. It might be more annoying, but at least you wouldn't have to learn a whole new language.

Otherwise, if you want to stick to JavaScript, it's not very hard to learn, and all tags are available in the filename as the "allo" variable (IIRC). Then, using for example `allo.includes("some_tag")` will return true or false depending on whether it's found or not.

I suggest playing around in some online JavaScript playground before running the script in Grabber. Also, note that Grabber's JavaScript is quite old and therefore does not support most newer ES6 features/standard library methods.

**Comment by somestupididiot53918** [comment]
Yeah, I have only done the one programming class and it was awhile back. I don't think we ever had our scripts interact with any other files, either, so this would be a new thing for me. Is there a basic example or template script available for this program that I could then add the specific sorting/naming elements to?

Also, I have never heard of online JavaScript playgrounds, so would it be able to simulate a program utilizing the script to sort and manipulate files? Or is it a general "mess around with the language and learn its syntax and such" kind of thing? Do you have one that you would suggest, in particular?

**Comment by Bionus** [comment]
> Is there a basic example or template script available for this program that I could then add the specific sorting/naming elements to?

If you already have a filename in Grabber, switching to JavaScript in the settings will try to automatically convert it for you.

> Also, I have never heard of online JavaScript playgrounds, so would it be able to simulate a program utilizing the script to sort and manipulate files? Or is it a general "mess around with the language and learn its syntax and such" kind of thing? Do you have one that you would suggest, in particular?

JavaScript doesn't manipulate files, only variables and stuff. Same thing for Grabber, the JavaScript part is only used for generating the filename, nothing else.

I usually use [jsbin](https://jsbin.com) for quick prototyping.

Here's an example you can use for creating a JS filename (just edit the "Actual filename" part):
https://jsbin.com/yibeqilicu/edit?js,console

**Comment by somestupididiot53918** [comment]
> If you already have a filename in Grabber, switching to JavaScript in the settings will try to automatically convert it for you (it doesn't handle conditionals and stuff though).

Oh nice.

> Here's an example you can use for creating a JS filename (just edit the "Actual filename" part):
> https://jsbin.com/yibeqilicu/edit?js,console

Alright, thank you for all of your help! I will see if I can expand this to encapsulate my current system sufficiently.

**Comment by somestupididiot53918** [comment]
All right, so I think I understand the basic way that it works. I have set up a large list of variables for specific series (using the previous example, Pokemon), each with one or more tags that will set them (I am assuming it's a true/false thing - if tag1 is present then true, else false.) Then I have a variable that has all of the applicable series-variables as activators for potential copyright groupings (Nintendo), and then the primary folder (Video Games).

What I would like help understanding is how I would make it so that the applicable variables (one per folder level) are what is used for the folders in the return statement so I don't have to have massive or statement chains for each in the return statement. If there are no matches, then it would default to an "Unsorted" folder on the same level as the other primary folders for me to then create new variables for.

My thoughts are that I would make three folder variables, one for each level, and then have it store the first series-variable found and the folders that hold it. Then the three folder variables would be called in the return statement.

I would still need to associate a folder name with each of the folder tags, another thing I don't know how I would do. My programming skills have always been horribly spotty (at best), as I am certain is shown in this post. Assuming my nonsense can be understood at all, at least. If you are willing to help again, it would be appreciated.
