### ISSUE TITLE
Grabber isn't showing full results anymore for some boorus

### ISSUE THREAD

**Issue by bluefiberbread** [Bionus/imgbrd-grabber#1747]
On Gelbooru's site, it says there are more results for the tag and Grabber is showing a small part of it

I'm not sure if I'm logged in on Grabber but I have put in my credentials and it still won't show all of the results

**Comment by bluefiberbread** [comment]
bump

**Comment by RiabikovR** [comment]
To check if you're logged in:
1 View a gelbooru page in grabber
2 Go to "Log" tab and look for link that starts with ``https://gelbooru.com/index`` and contains ``login=YOURLOGIN`` ``password_hash=DIGITS`` copy those values.
3 Go to ``https://gelbooru.com/index.php?page=account&login=YOURLOGIN&password_hash=DIGITS``
4 If it displays your profile, it means grabber can log in, otherwise you did something incorrectly when checking or grabber can't log in for some reason
This process really needs to be automated.

As for your issue. Try going to sources>gelbooru>options>cookies>add. Set cookie name (left column) to "fringeBenefits" and value (right) to "yup". If it works, you shouldn't even need to login.

**Comment by savarast** [comment]
Hello, i'm actually having the same issue. Even when I put in my pw and username and test successfully, I still get a portion of tagged images (in one case, only 714/1109 images). In the Log tab, there are not instances showing my login or hashed PW. I tried with the cookie as well to no avail.

**Comment by RiabikovR** [comment]
I don't really think this has to do with registration. You're both browsing Gelbooru, right? They blur "fringe content" in browser, but on my memory it never had any effect on grabber.
Either way, you should either share the contents of your logs or examples of searches that don't return all the results.

**Comment by savarast** [comment]
You are right, it has nothing to do with the grabber. Gelbooru just doesn't change the tagged image total if an image is removed so the total in the left-hand tag tab and how many grabber can actually grab can be different
