### ISSUE TITLE
%all:unsafe% and %allo% do not return the same text

### ISSUE THREAD

**Issue by FallenMei** [Bionus/imgbrd-grabber#1751]
**Bug description**

%allo% and %all:unsafe% do not return the same output when used in the Image option to insert a list of tags into a database. This causes problems for tags that contain multiple words. %allo% returns an images tags like `this_is_a_tag this_is_another_tag` with an underscore between each word in a tag. %all:unsafe% returns an images tags like `this is a tag this is another tag` without any distinction between the words in a tag.

**Steps to reproduce**

1. Setup everything exactly as detailed in the [gelbooru setup guide](https://bionus.github.io/imgbrd-grabber/docs/commands/gelbooru.html).
2. Open Options > Commands > Database
3. Replace %allo% with %all:unsafe% in the Image option.
4. Tags no longer have any meaningful separation between words

**Expected behavior**

%all:unsafe% should return a list of tags with underscores between each word in a tag.

**Context**

I am trying to use Grabber with a local instance of Gelbooru. I wanted to also save tag types, which are not covered in the Gelbooru setup guide. In order to save tag types I modified two options from the guide:

- Commands > Database > Image:

`INSERT INTO posts(creation_date, hash, source, image, height, width, ext, rating, tags, directory, active_date) VALUES(NOW(), "%md5%", "%url_page%", "%md5%.%ext%", %height%, %width%, ".%ext%", "%rating%", " %all:includenamespace,unsafe% ", "1", "20110619");`

- Commands > Database > Tag (after):

`INSERT INTO tag_index(tag, index_count) VALUES("%type%:%tag%", 1) ON DUPLICATE KEY UPDATE index_count = index_count+1;`
In theory this should have allowed me to save tags as normal except before every tag the tag type would be written separated by a `:`. However, when using %all% if the tag had multiple words an underscore would not be placed between each word in a tag, instead was a space. This breaks Gelbooru because it uses spaces to separate tags and every word in a tag needs to be separated with an underscore. %allo:includenamespace% does not appear to be a valid option.

**System information**

- OS: Windows 10
- Grabber version: 7.1.1

**Additional context**

Add any other context about the bug report here.

**Comment by Bionus** [comment]
> %allo% and %all:unsafe% do not return the same output when used in the Image option to insert a list of tags into a database.

While I see where you're coming from, that is not the case.

`%all%` should behave like other tag lists (such as `%character%` and `%artist%`) and follow the user settings for "tag separator" and "use blanks instead of underscores". This is expected and wanted:

https://github.com/Bionus/imgbrd-grabber/blob/1254e59f42f70795295134f128493349f92920c3/tests/src/models/filename-test.cpp#L678:L682

However, as you stated, for inserts in the database, we do **not** want to follow said settings and want to always have underscores and a space separator. Which is how the (now deprecated) `%allo%` variable came to be. I call it deprecated, because at the time token options didn't exist, but now you should reproduce its behavior with `%all:unsafe,underscores,separator= %` (and you'll want `includenamespace` as well for DB inserts).

> %allo:includenamespace% does not appear to be a valid option.

Indeed, it's not. `%allo%` is pre-generated and does not allow any options (except string options). It'll be removed in future versions, so you should avoid using it.

**Comment by FallenMei** [comment]
Thanks, that worked perfectly.

Unfortunately, I am actually having one more problem relating to the same issue. I'm sorry if this isn't the appropriate place to ask.

You've suggest adding `excludenamespace=general` to prevent the general tag type from being written. I would be fine doing that except for it causes inconsistencies in how my tags are stored when inserting into the `tag_index` table. 

This is the command I use to insert into the `tag_index` table

- Commands > Database > Tag (after):
`INSERT INTO tag_index(tag, index_count) VALUES("%type%:%tag%", 1) ON DUPLICATE KEY UPDATE index_count = index_count+1;`

I am having two problems with this current configuration:

1. I cannot exclude the tag type from being inserted if it is a specific type, like general.
2. The string inserted into the tag column is surrounded by single quotes, e.g., `'general':'1girl'`. This happens too back when I was just inserting `%tag%` to the column but now that I am using two properties there are single quotes around the separator. Ideally the tag inserted should look like this: `'general:1girl'` with no single quotes around the separator. The extra single quotes make the string different than what is stored inside the tags column on a post meaning my tag counts are always returned as 1.

Thank you again for helping with the first issue, I did not expect such a fast response!
