### ISSUE TITLE
Most sources will fail until I restart the program and then it'll repeat itself

### ISSUE THREAD

**Issue by pencilbook** [Bionus/imgbrd-grabber#1762]
**Bug description**

There are 0 results unless I restart the program. After a while, it'll fail again and I have to restart again. Rinse and repeat.

**Steps to reproduce**

1. Search for something
2. Get results
3.  Search for something else 
4. No results
5. Restart program
6. Search again
7. It shows up
8. Search for something again
9. No results
10. repeat

**Comment by Bionus** [comment]
Does this happen on every sources, or on a specific one?

Could you share your log for after the program fails to get results? There might be some useful information inside.

**Comment by artyfox** [comment]
I've had this happen on Zerochan using 7.1.1. I did a search, stepped forward a few pages, then try to step back to the first page and it failed to load anything until restart.

**Comment by pencilbook** [comment]
It happens on Gelbooru, Danboru and Yandere for me

**Comment by pencilbook** [comment]
Pls fix

**Comment by Bionus** [comment]
From issue #1828

> new log https://pastebin.com/KzuE08Em

**Comment by Bionus** [comment]
Seems to occur with aborted queries never releasing their "lock" in the [NetworkManager](https://github.com/Bionus/imgbrd-grabber/blob/develop/lib/src/network/network-manager.cpp) class, causing it to be unusable after 10 aborted queries (10 being the maximum concurrent downloads the NetworkManager class does).

It's confirmed by the logs showing:

> Could not find image related to loaded thumbnail

Which usually happens when a page load was aborted by going directly to the next page without waiting for all thumbnails to finish loading.

**Comment by brazenvoid** [comment]
#1698

**Comment by brazenvoid** [comment]
#1698

**Comment by brazenvoid** [comment]
There are more such issues left, like when for example, the connection gets lost, the same locked state results. Even if it comes back the other second, the sources will remain stuck. 

Sometimes the image windows will get stuck but all other areas will continue to successfully connect and query just fine.
