### ISSUE TITLE
A couple of questions/needing help

### ISSUE THREAD

**Issue by bhbobby** [Bionus/imgbrd-grabber#1768]
First of all, awesome app, I love it. I do have a couple of issues I'm running into and I do apologize if they are easy fixes, but I can't seem to figure them out.

1. Anytime I try to download anything from Sankaku Complex's site, it downloads like 40-50 images and then just hangs and never wants to finish. Is there any setting I can change or need to change to fix this?

2. Anytime I search for anything more than 2 tags, I get error results saying I've tried to search for too many tags. Is this also fixable or something I need to change to correct this?

Other than these two issues, the app works great. Any help would be appreciated, thank you.

**Comment by Catinks** [comment]
1. Sankaku Complex has a limit on how many images you can view/download at a time, I'm not sure of any way to increase or remove this. You can see this if you download a number of images with grabber and then attempt to view one through a web browser, it'll simply display text saying you've gone over the limit for now, or something.

2. You probably need to login through grabber, click on sources and then the options button next to the website in question, then click on the login tab and input your login details and hit test, it should login successfully, otherwise post back here with the log output (log tab). Once its successfully tested hit confirm and you should be good to go.

**Comment by Bionus** [comment]
1. In addition of what @Catinks said, I'd like to add that Sankaku is not supported anymore in Grabber.
2. I guess you are trying to load images from Danbooru. Non-gold users have a tag limit of 2, which is why you might get this message if you search with too many tags. See: https://danbooru.donmai.us/wiki_pages/43574

> Is there any setting I can change or need to change to fix this?

If the issue comes from too many requests per second, you should set up some throttling in your source settings.

**Comment by RiabikovR** [comment]
I wonder if something like rotating proxy could be used to bypass sankaku's limits. 🤔
It would obviously have to be set-up by user, but Grabber could have something like "run a command X if error Y is encountered".

**Comment by RiabikovR** [comment]
By the way, why is it not supported anymore?
Because of the limit?
