### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by ilovesi** [Bionus/imgbrd-grabber#1780]
Installed a proxy, it worked. Then I tried to download the Internet through a modem. Does not work. (I myself am from Russia, where this site is prohibited). Is there any way to clear the grabber cache? I think it would help, maybe.

**Comment by Bionus** [comment]
Not sure what you mean.

The proxy system in Grabber should work with SOCKS proxies, and if you don't set any, should use your system's default connection. Since you "installed" a proxy, I guess it would have overriden this connection and therefore Grabber would also use that proxy.

> Is there any way to clear the grabber cache? I think it would help, maybe.

I don't think it would help, but you can find the cache directory in `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber`. Just delete the whole `cache` folder.

**Comment by ilovesi** [comment]
The problem is solved, I just wrote the proxy incorrectly, thanks for the answer.
