### ISSUE TITLE
Favorite Autodownloads via Monitor only grab 20 most recent images

### ISSUE THREAD

**Issue by sbobbo** [Bionus/imgbrd-grabber#1784]
**Bug description**

If the last check of a favorite was weeks ago and more than 20 posts have been made since then, then the monitor will only grab the 20 most recent images rather than all images since the last check. This seems to be set in the URL itself with no way to customize, per this line in the log:

[10:37:01.547][Info] [rule34.xxx][Xml] Parsed page https://rule34.xxx/index.php?page=dapi&s=post&q=index&limit=20&pid=0&tags=tracer: 20 images (20), 0 tags (269), 3969 total (3969), 199 pages (199)

**Steps to reproduce**

1. Add popular favorite. 
2. Check back in a week
3. Only the 20 most recent images will download 

Alternatively, edit "lastCheck" for the tag in favorites.json to a date further in the past, save, and relauch Grabber. Check log.

**Expected behavior**

Grab all images since last check, or allow a user editable limit that prevents overrun

**Context**

* Provide your `main.log` file to see if any obvious error occured.
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
[main.log](https://github.com/Bionus/imgbrd-grabber/files/3648049/main.log)
[settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/3648055/settings.ini.txt)

* If the bug occured during a download, make sure to provide said download as an `.igl` file that Grabber can generate by clicking the `Save` button of the `Downloads` tab.

Note that both `main.log` and `settings.ini` files can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` in Windows, and in the installation directory on Linux.

**Screenshots**

**System information**

- OS: Windows 10
- Grabber version: 7.1.1

**Additional context**

Add any other context about the bug report here.

**Comment by sbobbo** [comment]
Any chance of making this configurable? Is it possible it already is and that I am missing something?

**Comment by Bionus** [comment]
Hello!

Sorry for the delayed answer as I was busy in the past month, and I wanted to take some time to investigate this issue properly. Indeed, only the latest 20 images are getting downloaded. That's because of a limitation in the code and not something that can be customized by some setting currently.

> "limit=20"

This is actually not completely related. Even if you could increase this limit, some sources don't respect it and always return a fixed number of images, or some other have a maximum limit. So you wouldn't be able to download more than that fixed limit either.

Also, in most cases there are quite few new images since the last check, so doing a check with a high limit can use bandwidth for no reason.

-----

I'm working on a solution to fix this issue without changing the limit parameter, and it should land in the next release.

**Comment by sbobbo** [comment]
Awesome, thanks for the update! Looking forward to the next version.

**Comment by sbobbo** [comment]
I'm running the nightly and this seems to be working just fine now. Thank you!
