### ISSUE TITLE
So... new issue with Danbooru

### ISSUE THREAD

**Issue by bhbobby** [Bionus/imgbrd-grabber#1787]
So I have a gold account with Danbooru and everything was working fine until last night. Now, no matter what tags I search for, I am limited to only 200 results. Is this a bug or a setting I changed by mistake and is there a fix for this? I've provided a couple of examples of what I'm talking about if that helps any. Any help would be appreciated, thank you. Also I'm kinda slow with this app, so please provide as many steps to fix as possible. Thank you.

https://imgtc.ws/i/IIL7Qzi.jpg

https://imgtc.ws/i/RfgDnrp.jpg

**Comment by bhbobby** [comment]
So it seems it's not an issue with any tag with Danbooru, but any tag with a significant amount of images. The results will bring back 1 of ? and the downloads will be limited to just 200. Any fix for this please?

**Comment by Bionus** [comment]
This just happens when Grabber doesn't know what's the total number of images for a given tag/search. It defaults to the number of images per page. However, nothing is stopping you from increasing this number, all fields in the "Downloads" tab are editable. If you know how many results there are, you can write it manually, and Grabber will download as much.
