### ISSUE TITLE
Skipping errors automatically.

### ISSUE THREAD

**Issue by sterelok123** [Bionus/imgbrd-grabber#1813]
Hi,

Does the software have the feature to automatically skip images it can't download? There are too many images when we're mass downloading and it's likely some errors pop up and obstruct the whole process. 

What should I do? If it's not there, will you add the feature to just automatically ignore errors and download ther rest of the ones it can?? Thank you.

**Comment by yami-no-tusbas** [comment]
I approve, i had this two night in a row loosing like 7-10h of download time because the program couln't create an image. It is so painfull, maybe it was a connection fluke, maybe the filename was wrong, don't know. But it's harrassing me to loose so much hours of download because one single file ine the night could not be downloaded.

Here is a sample of the log (since the log is so long and there is only this error) :

`[04:16:21.678][Info] Loading and saving image from `https://img2.gelbooru.com/images/0c/43/0c4332008e7470cde6932829a649915d.jpeg` in `J:\batch\no_original\no_1girl no_1boy\+tenshi_no_shippo\hamster_no_kurumi\upskirt	eyeball_(artist) - questionable - 1458280 - 0c4332008e7470cde6932829a649915d.jpg`
[04:16:21.679][Error] Unable to open file
[04:16:21.679][Info] Pausing downloads...
[11:12:38.790][Info] Skipping downloads...
[11:12:40.614][Info] Recovery of downloads...
`

I lost 7hours this time, when you have a limited bandwitch on day (12-00) it is verry annoying that you lost most of the night bandwitch on a such little problem. There should be a toggle like "auto skip error" on batch.
