### ISSUE TITLE
New filename not applying after stopped download

### ISSUE THREAD

**Issue by WiredG1** [Bionus/imgbrd-grabber#1819]
When pausing and stopping a download, changing filename and starting again the new filename will not be used, instead the old filename will be used.

Recreate:
1. Start a file download of some random files
2. Pause it midway and close the download window
3. Delete any files it downloaded before it paused
4. Change the filename or the destination (same issue with both)
5. Start downloading again, making sure to not continue the old download

The newly download files will follow the name and file destination from the first download "session". This issue persists when saving to link list.

**Comment by Psywing** [comment]
I'm having the exact same issue, I'm surprised this hasn't been resolved yet

**Comment by yami-no-tusbas** [comment]
It is because changing filename or destination via the "destination" pannel is not retro-active. You have to change the filename and folder from download list directly according to the change. Same for monitors btw, it can be a little annonying but it is the way it work acually. Changing this retro-actively would be a pain, plus if you make a mistake it can broke the monitors system. But I agree that for download a "default" path and filename should be a thing, the program see "default" then read the values into the ini. If there is another path and name, then it does not change it.
