### ISSUE TITLE
Add a post filter to pick pending single file downloads

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1820]
I usually have a long list of files to download which takes hours, perhaps due to load balancing on the source end; only one animated file can be downloaded at a time.

Nonetheless, I cannot search the results without them, thus I usually end up browsing the same files over and over again. This wastes a lot of my time and I still skip many worthy media which remain in the background with all the glitter.

So please add a filter which can perhaps setup a md5 list of the pending downloads and filter/limit the search results. Perhaps like: 

grabber:InDownloadQueue

**Comment by Bionus** [comment]
Indeed, I see where you're coming from with this suggestion, and it would indeed be doable by adding it to the Grabber filters, such as `grabber:inDownloadQueue`.

The issue is that this information is technically hard to fetch in the code where the "grabber" token is computed. I'll see what I can do.
