### ISSUE TITLE
A way to "fusion" tag ?

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#1832]
For example, let say i would like to get all the "pokemon" images. I look for pokemon on a booru, press get all. But... This will make a mess with folder. I can "ignore" some with the "ignore" hidden feature 😛 but... 

**Describe the solution you'd like**

I want to be able to alias some tag, like in the case of pokemon i would like to have a list of tag exemple : 

- pokemon_(anime)
- pokemon_(classic_anime)
- pokemon_bw
- pokemon_bw2
- pokemon_gsc

you get it, and have them aliased to "pokemon". And if pokemon is also a tag (like : pokemon pokemon_(anime) ) Just save it as "pokemon".
So when it saves the images and process the %copyright% tags, it just wrote pokemon instead of "pokemon pokemon_(anime)"

This could be so usefull when look for big series with a lot of spinoffs like the "fire_emblem" series.

**Describe alternatives you've considered**
I've tried custom token, not the good thing for this problem.

**Comment by Bionus** [comment]
## Use shortest if possible

There actually exists a "Use shortest if possible" setting, specific for copyright tags. Not really a "hidden" feature _per se_, it can be found in the option window, in the "Save > Tokens > Copyright" category (a checkbox at the bottom).

IIRC, this feature was actually created specifically for the "pokemon" tag.

It takes all tags marked as "copyright", and remove all those which are another copyright + a suffix. So "pokemon pokemon_(anime)" would be simplified as "pokemon". It will work with all tags which are simply a suffix to an existing tag (in this case, "_(anime)", "_bw", etc.).

## Ignore tags

Another option would be to "ignore" (right click on a tag then "ignore") all alternative spellings, which would flag all those as "normal" (general) tags instead of copyrights. Then, using the `%copyright%` token will only return non-ignored tags.

But you have to ignore them all manually, which is a pain, so I can't really suggest this option. But that's the only way if your copyrights don't look like each other / don't share a common "root".

## Custom tokens

As for custom tokens, you could in theory do it, by adding all tags to the custom token, then using a token conditional, such as `<%pokemon_tags% ? pokemon>` or the like. But once again, it's more complicated than just checking a box in the settings.

**Comment by yami-no-tusbas** [comment]
Well, I just checked, "Use shortest if possible" was already check. So maybe it doesn't work as intended ?
[settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/3901987/settings.ini.txt)

I double checked on the settings.ini it is "copyright_useshorter=true" so it should be ok.

I have for the moment use de "ignore" function, but yeah it was a bit painfull and now my ignore list is... well "long".

____________

I just made a test to be "sure", so i erased my "ignore.txt" list and try with your feature.

tag is : pokemon
filename is : 
> %websitename%\%search%\%copyright%\%character%\%artist% - %rating% - %id% - %md5%.%ext%
It did work... for the pokemon_*, still have "nintendo" "game_freaks", etc

This why I thinked about custom token, but It's a bit painfull, can it "override" %copyright% ? Because if not it's pretty hard to use it in batch

and yeah, for copyright like "pretty_(series)" It don't work at all, because well... here is an exemple of %copyright% output : 
> idol_time_pripara kiratto_pri_chan pretty_(series) pripara

So I'll stick with ignore list for the time being. But a tag merging feature would be loved 😍 (like for the "pretty_series") I know custom token can work, but I think it will be longer than just "ignore" the terms I don't need.

Thx anyway.
