### ISSUE TITLE
Thumbnails staying big, images per page not working, downscaling not working right too

### ISSUE THREAD

**Issue by Kamikaze1903** [Bionus/imgbrd-grabber#1840]
As per title

below picture shows 5 images per page, but shows more than 5 images per page
![grabber1](https://user-images.githubusercontent.com/58660927/70391327-ec077f00-1a0e-11ea-88a1-dd7b9227c215.PNG)

Below 2 pictures show downscaling not working
100%
![grabber2](https://user-images.githubusercontent.com/58660927/70391347-3be64600-1a0f-11ea-9369-e695e9a592ee.PNG)
10%
![grabber3](https://user-images.githubusercontent.com/58660927/70391353-47d20800-1a0f-11ea-9ae9-dc504077337b.PNG)

**Comment by Bionus** [comment]
> below picture shows 5 images per page, but shows more than 5 images per page

Some sources don't follow the images per page setting, such as all Shimmie-based sources. Which source does this happen on?

There used to be some client-side paging that was implemented, but it was removed a while ago because it caused more issues than anything.

> Thumbnails staying big
> [...]
> Below 2 pictures show downscaling not working

From what I can see, both issues come from you not having the "Use a fixed-image-width layout" setting on. It should be on by default, did you disable it? With this, all images are guaranteed to always have the same size. With a 100% upscaling (i.e. none), they should be boxed to 150x150 pixels. If your upscaling is 10%, it will be a 15x15 pixels box. With 200%, a 300x300 pixels box (useful for 4K screens).

Actually, this setting should be removed and always on. It was only added for the transition period to the new layout, but now it's unnecessary I guess.

**Comment by Kamikaze1903** [comment]
>Some sources don't follow the images per page setting, such as all Shimmie-based sources. Which source does this happen on?

I was using chan.sankakucomplex.com, changing that to danbooru fixed the problem! Though i'd like to know if there was a way to enable infinite scroll on it

>Actually, this setting should be removed and always on. It was only added for the transition period to the new layout, but now it's unnecessary I guess.

Actually I do quite like that it's able to close up the spaces in between the pictures as compared to the one with fixed-image-widith layout so maybe it can stay as another setting

Thanks alot!

**Comment by Bionus** [comment]
> Though i'd like to know if there was a way to enable infinite scroll on it

There's no reason you wouldn't be able to.
All sources support it AFAIK if you 

> Actually I do quite like that it's able to close up the spaces in between the pictures as compared to the one with fixed-image-widith layout

You mean the fact that they don't show up as a perfect grid, and that if a few "vertical" images follow each other they won't show any white space?

Indeed, I guess for this use case it would make sense to keep it.

But in that case it should be updated to allow using the upscale setting. And have some way to still normalize image sizes to 150x150 (before upscale). Otherwise, when you load images from multiple sources with different thumbnail sizes, you'd get a mess.

**Comment by Kamikaze1903** [comment]
>There's no reason you wouldn't be able to.
All sources support it AFAIK if you

Yeah I don't think chan.sankakucomplex.com is working well with the infinite scroll then..

At the start of the page
![grabber4](https://user-images.githubusercontent.com/58660927/70398781-f13deb80-1a59-11ea-8645-ad8a3a349688.PNG)

At the end of the page(infinite scroll doesnt continue)
![grabber5](https://user-images.githubusercontent.com/58660927/70398788-0155cb00-1a5a-11ea-81ee-9bfd26013406.PNG)

**Comment by Bionus** [comment]
While I could reproduce your other issues, I have no problem with infinite scroll on Sankaku:

![image](https://user-images.githubusercontent.com/882719/70663489-bbbb1d00-1c68-11ea-993d-85fa66af27cb.png)

But please note that Sankaku is **not** officially supported anymore, so if it only affects this source, I won't invest on it. But if other sources are impacted (and therefore is a global problem and not a source-specific one), I'll definitely check in more depth.
