### ISSUE TITLE
Revamp Conditional Filenaming

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1871]
**Is your feature request related to a problem? Please describe**

The conditional filenames need not have a separate utterly confusing interface. Even its existence confuses the user about what will be used as the final filename, after all there is a dedicated filename builder and other options elsewhere.

Also please remove the nested conditional example in the wiki. Its in error state as written under the same heading, why make an example out of it.

**Describe the solution you'd like**

1. Change the concept of the conditional tag/token filename to instead a clear and simple directive; if found / not found = add this to the filename. Meaning the token or tag being found or not actually adds different parts to the filename, it does not return the tag/token's original value, instead returns nothing when the condition fails. 
- Current implementation defines a default unchangeable behavior for the conditional which is counter intuitive and with no representation in the file mask. Instead it requires the user to remember its existence and purpose.
- The user may want to have the tag/token in the filename and use its existence status to display more parts in it as well. 
- Having different file parts in different order can play havoc with sorting and grouping in a folder.
- Though the file mask may become verbose but the user will now have to think about it in parts. This way the syntax will show exactly what it does without leaving anything to interpretation.

2. This function can be embedded in the filename builder itself with the following syntax:
- Equals serves as separator to signify the separation of condition from the injectable part.
- Found:
`<{tag or token}={add this if found}>`
`<%character%= - %copyright%>`
- Not Found:
`<!{tag or token}={add this if not found}>`
`<!%character%= - %all%>`

3. I don't endorse a full true/false syntax on parallels of a ternary operation as then it would be too user unfriendly. Nor do I endorse a multi-tag/token conditional as it would be too complex and may even need a conditional builder to make sense to a normal user.

**Examples**

- If I want to add all tags in the filename if and only if the character token is not tagged at all, I will use the following format:
`%character% - <!%character%=%all% - >%md5%.%ext%`
This will help greatly when one wants to manually move the character name from all tags part. It is a usual case when there are sources which do not have character type tags. The file order will also be preserved.

- Further building on previous one, if I want to add artist only if character is tagged:
`%character% - <%character%=%artist% - ><!%character%=%all% - >%md5%.%ext%`

**Comment by Bionus** [comment]
Actually, I'm currently testing out a new format `<condition ? if true>` / `<condition ? if true : if false>`, where the condition part could allow `&` and `|` operators and parenthesis, as well as inversion with `!`. I feel like this would match what you suggest?

I didn't update the documentation yet as it's only in the nightly release.
Maybe you try it out in nightly and tell me your opinion?

**Comment by brazenvoid** [comment]
Note: It doesn't work in nightly (gives error on file creation).

I don't really need the function but the concept stroke me intrigued and the implementation left me disappointed. So I cooked some ideas to ease some difficulties I encounter and some other things others will like too.

**Syntax Problems**

1. The syntax is too code like. Normal users will instead be deterred to use it. Like see the very simple example below:
`%character% - <%artist%?%artist% - :%copyright% - ><!%character%?%all% - >%md5%.%ext%`
Not adding spaces around operators is something that will be very expected from a user as each space does matter in the result cases. 
2. It draws misguided analogy from ternary coding syntax, which assumes that the true/false parts are wrapped up in quotes or in a variable, ensuring code clarity. But your syntax doesn't do that. It maybe fine at the time of creation but later reviewing it will be hard.
3. Essentially some wrapping needs to be done to make a clearer syntax. 
4. You already know how the programming community is completely divided on ternary syntax being evil (I use it though). And we are dealing with end users here.
5. The other issue is for example, if your implementation still returns the real value of the token when condition fails, the user will have to curb it using a `<condition?something:>` clause which as you can see looks more like a hectic hack. To a user it may even look like some mumbo jumbo after he does finally write it.
6. Building regex for a truly user friendly syntax will be hell on earth. Even your current suggestion is by no means easy. 

In retrospect I believe that a two part solution will entail a simpler implementation now and later a revamp of the filename builder.
1. Why not limit the syntax as I suggested to only exists or not exists clauses that return nothing when false. 
`<{token or tag} yes: {add this if found}>`
`<{token or tag} no: {add this if not found}>`
These will be able to do everything aside from complex nested conditions which are hard to implement.
2. If there is enough demand, you can enhance it with nested conditions after releasing a stable build.
3. Later you may consider removing this syntax building altogether and move to a more GUI centric approach for building filenames. That way you will only need to make UI controls to add parts to the file mask and not bother about regex and syntax rules. Such GUI will be a boon for normal users and the file mask could be made complex to any degree.
- Believe me though it seems to be a hard thing to do but its very easy to find parallels and ways to automate stuff in UIs. While all rules get to be in multidimensional arrays, which easily get processed through recursive functions.
- Further you can make optimizations in the rule set and cache a minified version.

**Comment by Bionus** [comment]
> Note: It doesn't work in nightly (gives error on file creation).

Strange, when I tried it yesterday it was working fine. Maybe something related to using tokens in conditions.
I'll check it out and add more unit tests for it. 🤔 

> 1. Not adding spaces around operators is something that will be very expected from a user as each space does matter in the result cases.

Maybe my example was confusing as I took it from memory instead of trying it out directly from the program, but there is indeed no spaces around the `?`. Spaces on the "condition" side are ignored IIRC, and on the right side would be treated as an actual space.

I thought about trimming them when I implemented the feature, but it would make it impossible to have actual spaces at the beginning of the "if true" so I decided against it.

> 2. It draws misguided analogy from ternary coding syntax, which assumes that the true/false parts are wrapped up in quotes or in a variable, ensuring code clarity. But your syntax doesn't do that. It maybe fine at the time of creation but later reviewing it will be hard.

I don't think I understand your point. You mean that the absence of clarification of where the "if true" begins and ends might be confusing? From what I see, most use cases do not have any "if false" (else) part, so the syntax is simply `<condition?something>` in most cases.

The `?` is indeed inspired from ternary syntax of programming, but makes senses as a "question" too. "Is this tag present?" / "Is this token empty?" / etc.

> 3. You already know how the programming community is completely divided on ternary syntax being evil (I use it though). And we are dealing with end users here.

They're mainly considered evil because they harm clarity. Most people dislike ternary (including me) because compared to a "clearer" if block, they're harder to read for no other gain than saving a few lines. They're also a pain to evolve.

But in this case, any other syntax (even the one you suggest with yes/no) would receive the same idea. I think it could be compared with using "inline" conditionals (using `<...>`) and using conditional filenames in the options?

And except for the use of `?`, if we ignore the possibility of adding a "else" case at the end with `:` (which is optional, but indeed could be removed if considered confusing), wouldn't either your suggestion or the current implementation count like a normal "if" rather than a ternary?

> 4. Essentially some wrapping needs to be done to make a clearer syntax.

I'm not sure how `<condition yes: `

> 5. The other issue is for example, if your implementation still returns the real value of the token when condition fails, the user will have to curb it using a <condition?something:> clause which as you can see looks more like a hectic hack. To a user it may even look like some mumbo jumbo after he does finally write it.

Sounds like a bug more than anything TBH 😅 

> 6. Building regex for a truly user friendly syntax will be hell on earth. Even your current suggestion is by no means easy.

The parser does not use regular expressions but a recursive descent parser to generate an AST since the 7.x version. So handling any kind of syntax is pretty easy.

> <{token or tag} yes: {add this if found}>
> <{token or tag} no: {add this if not found}>

You'd have to remove the spaces after the `:` to prevent confusing it for an actual space no? So it'd be more like:

```
<{token or tag} yes:{add this if found}>
<{token or tag} no:{add this if not found}>
```

While I can see how it's more easily readable / understandable for a beginner, it's still quite close from:
```
<{token or tag}?{add this if found}>
<!{token or tag}?{add this if not found}>
```

> If there is enough demand, you can enhance it with nested conditions after releasing a stable build.

I haven't unit tested them yet, but given the kind of parser and AST used, it might already support nested conditions.

> Later you may consider removing this syntax building altogether and move to a more GUI centric approach for building filenames. That way you will only need to make UI controls to add parts to the file mask and not bother about regex and syntax rules. Such GUI will be a boon for normal users and the file mask could be made complex to any degree.

While I have no issue doing this kind of UI in HTML / JS, the issue here is that doing this with Qt / natively is a huge pain 😓

**Comment by brazenvoid** [comment]
Yes, majorly you can't really stray from the ternary syntax but only make it more explicit to bring in clarity. 

If Qt development has any parallels with Delphi, I understand your plight. Even if I wanted to I will not be able contribute in development in the short term.

Still another idea popped in terms of easier GUI implementation: 

Why not create something like buttons to introduce specific syntax in a file mask input after the cursor. The input will still allow user edits. This way current function is preserved.
1. Add token button will open a dialog with a click to open drop down list of supported tokens. 
- The searchable list for clarity will not have syntax specific % around the token name. 
- If the token has configurable options, those will be displayed below the drop down upon selection. 
- This eliminates the need for the user to remember or cross check token names from the wiki.
2. Add condition button opens an interface very similar to existing conditional filename builder but with clearer UI. 
- "Condition" will take the condition (this could be enhanced with similar token builder used earlier)
- There will be a help text below it, informing about supported operators
- "If true (optional)" will take the output for satisfied condition 
- "If false (optional)" will take the output for unsatisfied condition
3. A help text describing the file mask in words will go a long way here.

Concluding, I am just trying to get this feature out in a user friendly way. I am a developer I don't need it...

**Comment by Lovewyrm** [comment]
I don't like the conditional system at all, it is very unintuitive to me (of course I know that intuition is learned, etc).

For example, as my destination filename I have `%search%/%search%_%artist%%md5%.%ext%`

I have not the slightest idea what would happen if I set up a conditional filename, all the examples in the documentation use "%md5%.%ext%", can I just use this to replace, let's say an aliased artists name?

I don't even know how to formulate what I mean with this because this approach is so ...obtuse to me.

So I'm not even gonna try but instead offer a suggestion, something not tied to tokens or whatever, but to the software itself that goes beyond the tokens, or has power over them.

alias token: test_artist
list of aliases:foofoo, barbar, bazbaz

Searching for any of these would fill the artist token with "test_artist"

That should be the first line of defense when it comes to conditionals, no voodoo, save the voodoo for crazy cases.
Do a simple check and replace first.

That way users (like myself) could keep their 'destination file scheme' and have simple customization tasks done by the grabber.
I don't know why there has to be a hullaballoo with "shortest if possible" weird options with num tags and syntaxes and rigamaroles.

I searched similar wishes of mine and found one about pokemon franchises https://github.com/Bionus/imgbrd-grabber/issues/1832 and all of this would be solved with the simple first line of defense of a simple check and replace, while leaving standard tokens intact so they can be used for a 'catch all generic destination filename'
