### ISSUE TITLE
Global Post Filters do not get included in batch downloads nor shown in search

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1875]
**Bug description**

Previously global filters got included in searches explicitly (shown in the post filter input) automatically whenever search was made and thus also made their way to batch downloads.

Now for some reason that does not happen and they get applied silently in the background. Similarly they don't get added to any batch downloads as well. I assume here that batch downloads copy the post filters from the post filters input box of the search.

I have to copy paste them for all batch downloads manually. 

**Steps to reproduce**

1. Add some global post filters
2. Search something
3. Use get all to generate batch download
4. The post filtering area will not have the global post filters.

**Expected behavior**

The global filters must get added to the batch downloads as well. 

Showing them explicitly in search post filtering box can also be beneficial if someone wants to modify them on the fly but people may also like them to not be shown. Perhaps a setting for this?

**System information**

- OS: Windows 10 1909
- Grabber version: Nightly a95b5e76

**Comment by Bionus** [comment]
This whole thing is strange because from what I can see after checking the code, it shouldn't even have worked in the first place, but clearly it did. So I might be missing something.

> Previously global filters got included in searches explicitly (shown in the post filter input) automatically whenever search was made and thus also made their way to batch downloads.

I would argue that it was a bug, given the idea was to always do it in the background. However, it might also be counter-intuitive so I'll add a setting for that. I always considered it to behave the same as "global tag addition", which if explicit would be more confusing than anything.
