### ISSUE TITLE
No idea how to install/run.

### ISSUE THREAD

**Issue by Panickedd** [Bionus/imgbrd-grabber#1898]
Couldnt find an appropriate place to ask thing, presumably because there is none. But i can not figure out instillation, or when i run CDR.exe in the /release folder nothing happens. Im extremely confused as to even start the program. No crashes i can see, just a whole lot of nothing.

**Comment by Wryyyong** [comment]
You're supposed to run `Grabber.exe`, not `CDR.exe`.

**Comment by Panickedd** [comment]
> You're supposed to run `Grabber.exe`, not `CDR.exe`.

i can not find grabber, its not in the folder. I even searched for it.

**Comment by sbobbo** [comment]
Download the exe from https://github.com/Bionus/imgbrd-grabber/releases

**Comment by yami-no-tusbas** [comment]
First, try to pause your anti-virus for the installation and first run, some maybe see grabber.exe as a menace and shoot first. Then if it work, just add grabber to the whitelist of your antivirus software and you should be good.

**Comment by Bionus** [comment]
It seems like you tried to run the program by cloning it instead of installing it? Either that or as suggested above, your antivirus blocked the installation.

Make sure you install the program using the installer found in the releases page:
https://github.com/Bionus/imgbrd-grabber/releases

For example for Windows x64:
https://github.com/Bionus/imgbrd-grabber/releases/download/v7.2.1/Grabber_v7.2.1_x64.exe
