### ISSUE TITLE
Existing images on clean install?

### ISSUE THREAD

**Issue by notacompletemoron** [Bionus/imgbrd-grabber#1900]
**Bug description**
Clean installed Grabber (deleted appdata folder), made a search, downloaded images, and download says there's existing images?

**Steps to reproduce**

1. Download images
2. Clean install Grabber (delete/rename appdata folder)
3. Download images from step 1
4. Downloader says images exist

**Expected behavior**
Non-existing images so downloader doesn't skip them.

* If file exists is set to Save

**System information**

- OS: Windows 10 
- Grabber version: 7.2.0. nightly (623c8cae)

**Comment by yami-no-tusbas** [comment]
As far as I know, if you don't change the destination folder, neither the structure, and you didn't delete the images files, grabber will say they exist.
It is because before saving a image I'll try to create the file, see the file exist, then skip to the next. Have you check the destination folder and emptied it ? Because if there is file in there and they are with the same name and folder structure, obviously grabber will see them as existing. If you move them, then it will download them again, it should. 

(btw : you just have to delete the md5.txt files as far as I know, because grabber use it to remember what it have downloaded or not. (And it removes md5 not found except if the rule ("keep deleted files in the MD5 list") so deleting md5.txt should be more than enough to make it try to download again, but then if the file already exist ine the destination folder, it will skip it.).

**Comment by notacompletemoron** [comment]
The downloads are separated by the %SEARCH% option. So, each search gets it's own directory. Are you saying that I need to remove that folder from the root folder that these are getting saved to?

Also, yes, by clean, I mean NOTHING existing from the previous installation as far as the appdata folder goes. Don't mean to be abrasive, but I did mention that in my first post.

**Comment by yami-no-tusbas** [comment]
Then, what does the logs says ? It'll be easier to find the problem with the log file.

**Comment by Bionus** [comment]
As said above, there are two ways for images to be detected as "already existing":
* They are in the MD5 list (the `md5s.txt` file in `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber`)
* They actually already exist wherever you're trying to save (i.e. you are trying to save an image in a folder where said image already exists

To exactly know what happened, the log would indeed be the simplest solution.
