### ISSUE TITLE
No way of safely inserting SQL

### ISSUE THREAD

**Issue by FallenMei** [Bionus/imgbrd-grabber#1902]
**System information**

    OS: Win 10 x64 1909
    Grabber version: 7.1.1 x64 (I cannot test for this issue on Grabber 7.2.1, more below)

**Bug description**

When adding tags to the database, using `%all%` in the setting `Commands > Database > Image`  returns SQL unsafe characters
 `...," %all:includenamespace,unsafe,underscores,separator= % ",...`

Here is an example of a query Grabber might try and fail to insert into the database:
`SQL execution of "INSERT INTO posts... , general:tag general:tag2 general:unsafe"tag"3 general:tag4 general:\o/`

Unsafe characters (including quotes and backslashes) typically occur when a tag is meant to represent a person/face e.g., \o/.

Additionally, backslashes don't always make the SQL insertion fail (which is worse) because they end up escaping the next character. This creates posts that have slightly different tags from how grabber received from the source and no way to detect and fix them.

I would really appreciate it if this issue got some sort of acknowledgement, I've seen other similar related questions go unanswered so I hope to confirm someone is looking into/working on this issue.

I cannot test if this is still an issue in Grabber 7.2.1 [because of a bug](https://github.com/Bionus/imgbrd-grabber/issues/1892) that prevents the loading of the database drivers in that specific version of Grabber.

**Steps to reproduce**

1. Configure Grabber exactly as described in the [wiki tutorial for gelbooru](https://github.com/Bionus/imgbrd-grabber/wiki/Gelbooru)
2. Download an image with a tag that includes unsafe characters

**Expected behavior**

Grabber should escape SQL queries before attempting to insert them in the database

**Comment by Bionus** [comment]
> %all:includenamespace,unsafe,underscores,separator= %

Just to be clear, this was written by you and is not taken from the tutorial right? (to know whether I should update a tutorial somewhere)

> Grabber should escape SQL queries before attempting to insert them in the database

There is actually an `escape` option which apparently is not documented in the [Filename](https://bionus.github.io/imgbrd-grabber/docs/filename.html) documentation. I'll add it ASAP. So in your case you'd have to use `%all:includenamespace,unsafe,escape,underscores,separator= %`

Note that I went with this solution rather than escaping everything because the escaping method I use ([QSqlDriver::formatValue](https://doc.qt.io/qt-5/qsqldriver.html#formatValue)) encloses the result in quotation marks. So you'll have to remove those from your command as well.

**Comment by FallenMei** [comment]
> Just to be clear, this was written by you and is not taken from the tutorial right? (to know whether I should update a tutorial somewhere)

Yes, this is changed from the tutorial. I would recommend updating the [Gelbooru tutorial](https://github.com/Bionus/imgbrd-grabber/wiki/Gelbooru) because it still instructs you to use `%allo%`, which is deprecated. [See](https://github.com/Bionus/imgbrd-grabber/issues/1751).

Thanks for documenting the `escape` option, I was not aware it existed.
