### ISSUE TITLE
rule34hentai.net not avaliable

### ISSUE THREAD

**Issue by HyperScorpio** [Bionus/imgbrd-grabber#1921]
Hello. Here's a new request.
https://rule34hentai.net/
This website is not added yet, so it needs to be added because it have important database to download. Remember, this website have video and flash animations too.

Thanks.

**Comment by ayoits0913** [comment]
I already made a post about this: https://github.com/Bionus/imgbrd-grabber/issues/1858

They added cloudflare, so it blocks programs like this. In order to fix this, Bionus said and I quote, "that would require a huge re-write in Grabber." Maybe that would be a good idea since more sites will likely do this in the future.

I added it manually a while back and used it all the time, had loads of good content. It's very unfortunate, but I don't see any way around this unless Bionus decides to make a move or they remove cloudflare.

**Comment by Bionus** [comment]
What he said.
I'll close this as a duplicate of #1858. Feel free to continue the discussion there.

A rewrite would mean using a real browser to access the website and parse stuff, which while feasible isn't at the top of my roadmap. My backlog for Grabber is unfortunately quite big 😞

**Comment by HyperScorpio** [comment]
This is a different website, remember.
