### ISSUE TITLE
Crashes upon second search request.

### ISSUE THREAD

**Issue by Merthew** [Bionus/imgbrd-grabber#1925]
Basically, I downloaded the new version today, 4/4/2020, I open it up, search for something. No problem, then I type in a new search and it crashes. It has done this three times now.

**Comment by brazenvoid** [comment]
For me, it is crashing if I download something through the context menu and then change the page.

**Comment by Wiiplay123** [comment]
Can you upload main.log and settings.ini?

If you run CrashReporter.exe from Grabber's install location, you should be able to see the paths to each one. On my PC they're in %localappdata%\Bionus\Grabber.

The log should have some information about what's causing the crash.

**Comment by Bionus** [comment]
@Merthew by "new version you mean [v7.2.1](https://github.com/Bionus/imgbrd-grabber/releases/tag/v7.2.1) and not [nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) right?
Can you share your log? (after a crash) I couldn't reproduce your crash, so I don't think it's only caused by doing two searches, there must be other factors.

-----

@brazenvoid that's an issue only in nightly from what I can see.
I could reproduce it and I just pushed a fix.

**Comment by Merthew** [comment]
I ended up going back to a previous version so I don't have the logs, but yes it was a release not a nightly build.
