### ISSUE TITLE
download speed

### ISSUE THREAD

**Issue by lilthigh** [Bionus/imgbrd-grabber#1935]
16 kb/s and between, download speed sometimes 7 or 5 kb/s
![Capture](https://user-images.githubusercontent.com/42845509/79107706-90168380-7d7d-11ea-862c-6a393a344c88.PNG)
I'm using 7.1.1 version windows 7, I have no lag, and I'm not downloading anything anything else.
any tips or trick to increase the download speed.

**Comment by Ashteroide** [comment]
Same happening here, I don't this has been managed a lot lately

**Comment by yami-no-tusbas** [comment]
Is it the same on every board ? Just tested on my side with gelbooru got 11mb/s download speed.
Looks like sankaku on your image, ok, sankaku seems to be the problem here : https://i.imgur.com/sWgEZQ5.png

It cannot go over 1mb/s Maybe their serveur limit us, or maybe too much people on their website. Ok worst on idol.sankaku, not more than 100kb/s

Just for comparison here is my speed on Gelbooru.com : https://i.imgur.com/kUSxc54.png
Don't thrust the speed in grabber, it is way off by the way. Use taskmanager or other tools But yeah, sankaku is slow as hell.

**Comment by Ashteroide** [comment]
For me I reinstalled the Grabber which didn't help, but might of just been bad wifi or too many people as yami-no-tusbas mentioned. After that in the morning I was receiving about 1 to 2mb/s and got my downloads done

**Comment by lilthigh** [comment]
i tried to copy the media links and download it from jdownloader 2 and it make a difference, but it download every video or pic in a single folder, that's sucks, so what do you guys recommend me a tool to download faster

**Comment by yami-no-tusbas** [comment]
Well sankaku isn't supported anymore as far as I'm aware, maybe sankaku is limiting grabber. But if you can get all the image from Jdownloader, get them, then use grabber Tool to rename every file. 

Since sankaku admin is an ******* there is not much solution, use a fast downloader, then organise the files with grabber letting it calculate md5 and pray this work.
