### ISSUE TITLE
[Nightly] Strange Menu Display Corruption

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1962]
![Untitled](https://user-images.githubusercontent.com/8722533/81755882-7dee4900-94d3-11ea-92d8-41c5e5801e19.png)

So this happens every now and then. It comes and goes by itself.

**Comment by Bionus** [comment]
Weird, I've never seen this in Grabber, though I saw it happen in Firefox a few times 🤔

Do you use any particular Windows theme?
Or any special Grabber theme? (Options > Interface > Theme)

The randomness makes me feel it's more likely a bug in Qt/Windows rather than Grabber itself (especially since the way this menu is created is the "official" one).

How often would you say it occurs?

**Comment by brazenvoid** [comment]
I don't use any themes whatsoever for grabber nor windows. 

I think its more or less an issue due to GPU state change. As it happens when I am rendering videos in some video editor (filmora/da vinci) or have a game paused in background.

**Comment by brazenvoid** [comment]
No it is an old bug, I guess started from v7.
