### ISSUE TITLE
Pixiv doesn't load all pages for downloading

### ISSUE THREAD

**Issue by sonic0207** [Bionus/imgbrd-grabber#1975]
Whenever I want to download images from pixiv.net, there is only 30 pictures available to download. Perhaps, I am doing something wrong, but every other source I've tried had successfully recognized the total amount of pictures from a given source. 
<img width="73" alt="Capture" src="https://user-images.githubusercontent.com/65637235/82727455-9282cc00-9c9f-11ea-947a-e7ff6906d6df.PNG">

**Comment by Bionus** [comment]
I don't see how there are only 30 images for download.

It just says that it couldn't get the total number of images, because Pixiv's API does not provide this information. That doesn't mean you can't go to the next page or set a batch download with a custom size.

**Comment by SMNarutoXD** [comment]
if I'm allowed to add something to your comment, Bionus.

I recently started to use your tool and it works great but I also noticed this with pixiv.

I'm just assuming that sonic0207 has the same problem as me but the keyword is downloading after all and not the view when you search.

Currently, if I search something - naturally with the Japanese tag to get the most results for a search query - let's use 春野サクラ - Haruno Sakura as an example - when I search it and press "Get all" it indeed adds the pixiv group with 30 for image per page and image limit. If I understood the tool correctly the "Get all" is the batch download command.

Like this, it only will download the first 30 of the first page. 
Even when I change the download limit to 30000 - as I can look up that the character has at least 26000 images has not the effect of downloading all images as expected.

I'm also pretty sure that it also does not get all pages with this - as my test only downloaded the around 3000 pictures.

(Also to add: I have been searching but you can I make it so that the Grabber actually saves my login for while longer? Like getting the right cookie inside it?

**Comment by HelpSeeker** [comment]
I'm facing the same problem as the previous posters. Grabber's search fetches the same results as on pixiv, but when trying to download those images it will only discover a fraction of the previous results. For example "Helltaker" nets a few thousand pictures, but when you download them with "Get all" then it will only grab 65.

This is only an issue in more recent versions. v7.2.1 is the last one where the download works correctly for me.

**Comment by ayoits0913** [comment]
Yep, same here. Only grabs a small amount of the images. 40-60

**Comment by corncheeto** [comment]
I think I might have a roundabout solution (It worked for me as I'm typing this). In the downloads tab, click `Add` then input the tag/user you want to get, then you can set the image limit to however high you need it and it should scrape all the images from the tag. Doing this let me download all ~8000 images from an artist on pixiv.
