### ISSUE TITLE
How do I download images and have their tags in the file properties?

### ISSUE THREAD

**Issue by Kelhsy** [Bionus/imgbrd-grabber#1981]
I've been using the program for a while but only now I noticed that the images I download do not have tags in their properties, can I somehow enable enable the program to add tags for new images I download and to add tags to the images I already have?

**Comment by Bionus** [comment]
Seems to duplicate of issue #258 (and [a bunch of others](https://github.com/Bionus/imgbrd-grabber/issues?q=is%3Aissue+metadata)).

The problem with this suggestion is that Windows tags do not work for many file formats, a big example being the very commonly found PNG. While there exists workaround for many file formats (embedded XML and other stuff), few of them are reliable and work with all file formats.

This is a request that often comes on the table, which is why multiple issues already asked for it. But the conclusion is always the same: if only a few formats support it, it's not really a good option (unless converting all images to JPG before saving them).

But if you know of a solution, I'd gladly implement it. I'm sure everyone would love being able to leverage the native search of the OS to find images based on their tags.

The commonly suggested alternative is to use https://github.com/hydrusnetwork/hydrus for browsing, with Grabber for downloading using the "External text file" feature, with for example this format:

```
rating:%rating%
%all:includenamespace,excludenamespace=general,unsafe,spaces,separator=\n%
```

**Comment by PaxiTheAlchemist** [comment]
Could you go into more detail on this "External text file" feature? this is apart of grabber I'd assume? I've looked into Hydrus and i have managed to set it up so that it can accept tags for an image/file through an accompanying "tag" file, however, I'm having trouble figuring out what this "External text file" feature is and or how to get it to work. If there are some reliable sources or guides, that would be great as well! The feature is probably in plain sight in the options menu, but thank you in advance for your assistance!

**Comment by PaxiTheAlchemist** [comment]
Thank you very much! I legit went over that feature thinking that this was definitely where the feature was but couldn't figure out which location type to use. Originally used "unique file" thinking that a unique file would be created with each image. In any case thanks for the clarification!

**Comment by FichteFoll** [comment]
Just a quick question, can log files be requeried for already downloaded files, e.g. by their md5 hash?
