### ISSUE TITLE
Google picture search (feature request or looking for a GUI software with that functionality)

### ISSUE THREAD

**Issue by syakz** [Bionus/imgbrd-grabber#1982]
Hi,
Is it possible to add a feature to google search images from a folder and save them in highest-res possible? Or maybe there is a better software or script that exists already that does that? I have a folder of low-res material and its a pain in the ass to sort them manually ;-(
Sorry if this is an off-topic in any way or form...

**Comment by Bionus** [comment]
Hello

While indeed it sounds like an interesting software idea, and I did a quick search on Google and Github and didn't find any software that does this. It doesn't seem too hard, maybe you can ask on some programming forums as a programming idea?

But I'm not even sure if it would work with the Google results since they don't even include the resolution, and I don't even know if they have an API for reverse image search. But if your images come from boorus, you can also use IQDB I think? Or TinEye otherwise.

And indeed, it doesn't really fit with what Grabber does currently, so it won't be included, sorry.
