### ISSUE TITLE
twitter problems take 2

### ISSUE THREAD

**Issue by DraGoran** [Bionus/imgbrd-grabber#2013]
it still doesnt work to download certain twitter galleries for example NikkiSapphire cannot catch any media, only retweets if i do retweets:no it shows Twitter No results

I have changed the line 
![grafik](https://user-images.githubusercontent.com/17236196/84576744-61d21600-adb7-11ea-9c46-f574f688a4ef.png)
like the fix suggests , but it doesnt work still i updated to new grabber still doesn´t work

version is newest 7.3.0

There is also problems with other galleries, which either have the same problem or just download 15 out of 200  pictures.

For certain other galleries it works

**Comment by sos440** [comment]
I had a similar issue with twitter search. Here is what I noticed:

1. If there are no images in the current page, Grabber cannot proceed to the next page. This is no issue for Danbooru-based site because the search results are always images. However, this is problematic for Twitter, since some search results do not contain media.

2. The current version of Javascript helper uses the ID of the original tweet, not the one of the retweet, for the tag "id". However, Grabber uses the minimum of IDs to compute the next search. This is problematic if there is a retweet of an ancient original tweet. For example, if an original tweet posted on year 2010 is retweeted on year 2020, then Grabber tries to find tweets older than Jan 1 2020 in the next page, missing everything between years 2011 and 2019 (and more)!

I was able to make a hot fix for this. We need to modify two functions `parseTweetMedia` and `parseTweet` in the Javascript helper model.js:

![img_013](https://user-images.githubusercontent.com/71863632/94226217-e995e900-feab-11ea-841e-652a6f955239.png)

![img_014](https://user-images.githubusercontent.com/71863632/94226219-ea2e7f80-feab-11ea-8602-87a259b81de2.png)

**Comment by Bionus** [comment]
Thanks for the help pinpointing the issue @sos440 ! (and sorry for not answering sooner)

I just merged it in Nightly, together with something to not show images that only have an ID, otherwise the results looked weird. It will land in the new version soon.
