### ISSUE TITLE
Can I somehow automatically look up a list of tags and add them to the download queue

### ISSUE THREAD

**Issue by Kelhsy** [Bionus/imgbrd-grabber#2047]
Since I have a list of artists who's work I'm keeping backups of I have a lot of them and manually looking up ~80 artists/series takes a long time. Is there a way to somehow make a list of tags that the program could look up and add to the download queue?
Since if I save a download list it only saves the currently added images to the queue and doesn't add new ones.

**Comment by Bionus** [comment]
I'm not sure what exactely you're trying to do.
* If you just want to download those tags, you can add them all to the batch download list, and launch them whenever
* If you only want to track those tags, getting all new images that come out, you can use monitors for that.
* If you want to check and choose the images one by one before downloading them, you can use favorites

>  Since if I save a download list it only saves the currently added images to the queue and doesn't add new ones.

Batch downloads are linked to tags, not images, so if there are new images for a given tag, they will be fetched.

**Comment by Kelhsy** [comment]
I'm trying to use the "Save download list" feature to try and load all the relevant tags I want but it only loads the previously queued images (As in the same number) without adding the new images that have been uploaded since the time I made the list. Sorry if I'm making things unclear.

**Comment by Justwanttoaskaquestion** [comment]
I think I asked about this before, the problem I faced was:
Adding to a download list sets the images limit to the _current_ amount of pictures matching the tags.
However, when new images are added, that limit increases, and downloading with a download list won't work.
One thing that did work for me, was to just set the image limit to something ridiculously high using regular expressions, since the download list file is human readable.
