### ISSUE TITLE
Images start to mass download after a period of time leaving the program open

### ISSUE THREAD

**Issue by DonGaponni** [Bionus/imgbrd-grabber#2051]
**Bug description**

After leaving Grabber open for a period of time, images start to mass download, seemingly at random. I do not believe I have any auto download settings on, and this behavior has not happened before. Seems to happen every time I launch the software, will not happen if closed quickly enough.
[files.zip](https://github.com/Bionus/imgbrd-grabber/files/4964239/files.zip)

**Steps to reproduce**

opening the application then leaving Grabber open for a while.

**Expected behavior**

just for an image to be saved and nothing more.

**Context**

* Provide your `main.log` file to see if any obvious error occured.
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
* If the bug occured during a download, make sure to provide said download as an `.igl` file that Grabber can generate by clicking the `Save` button of the `Downloads` tab.

Note that both `main.log` and `settings.ini` files can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` in Windows, and in the installation directory on Linux.

**Screenshots**

**System information**

- OS: Windows 10
- Grabber version: 1.3.0 (x64)

**Additional context**

Add any other context about the bug report here.

**Comment by yami-no-tusbas** [comment]
Can you add your "monitors.json" file too ? You can rename it as a ".txt" to upload it here directly.

**Comment by DonGaponni** [comment]
[monitors.txt](https://github.com/Bionus/imgbrd-grabber/files/4964319/monitors.txt)
is this correct?

**Comment by yami-no-tusbas** [comment]
Yep, your problem is right there, maybe you missclicked on "monitor" instead of "get all" or "get this page" at one time.
Your first two monitors are the same, set to download everything from multiple boards. The two others are the same too and set to download all of a tagged content.

What you have to do is to go in the "**Monitors**" tabs, right click on the one you don't want, likely the two empty first, and on the one if not both of the tagged ones, and click on "remove" (with the minus sign)

**Comment by DonGaponni** [comment]
Oh wow, what a simple fix! I didn't realize that's what "monitor" did. Thank you so much for your help!
