### ISSUE TITLE
Program fails to start - Qt5Core.dll error

### ISSUE THREAD

**Issue by Tumultuous-RGR-SiM** [Bionus/imgbrd-grabber#2097]
I can no longer start up the program. I think this happened after I updated from 7.2.1 to 7.3.0, or from 7.3.0 to 7.3.2, but I'm not sure. Running the installer for the older version of the software did not fix the issue. I was "installing" the old program version over top of the existing installation. The program was working just fine when I last used it a few weeks ago.

I had several tabs open, and I usually leave these tabs open for later downloading in between sessions.

What happens is that I try to start up the program. I get the message that says "it looks like the program didn't shut down correctly last time. Do you want to restore your last session?". Regardless of whether I click yes or no, a blank window with the Grabber titlebar opens up for a second, and then shuts down.

- - -
The main.log file has been attached here.
[main.log](https://github.com/Bionus/imgbrd-grabber/files/5121370/main.log)
- - -
The Windows Event Viewer gives the following Application Error:

```
Faulting application name: Grabber.exe, version: 0.0.0.0, time stamp: 0x5f25d7b9
Faulting module name: Qt5Core.dll, version: 5.12.6.0, time stamp: 0x5dc59681
Exception code: 0xc0000005
Fault offset: 0x0000000000039da0
Faulting process id: 0x5560
Faulting application start time: 0x01d67a98d80d2130
Faulting application path: E:\Programs\Grabber\Grabber.exe
Faulting module path: E:\Programs\Grabber\Qt5Core.dll
Report Id: 0306113d-ed44-4be3-8600-9b66bb09e55b
Faulting package full name: 
Faulting package-relative application ID: 
```

The Windows Event Viewer gives the following information in the Windows Error Reporting source

```
Fault bucket 1430630432807207873, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Grabber.exe
P2: 0.0.0.0
P3: 5f25d7b9
P4: Qt5Core.dll
P5: 5.12.6.0
P6: 5dc59681
P7: c0000005
P8: 0000000000039da0
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8BC1.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8DE5.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8E05.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8E03.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8E43.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Grabber.exe_c5f39273df4ed63317c9fbd701c2979ea62a94_31dce014_91dd8585-d06e-4571-81ea-d99c361e7cc8

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0306113d-ed44-4be3-8600-9b66bb09e55b
Report Status: 268435456
Hashed bucket: 515608785821a750d3da9ecc805643c1
Cab Guid: 0
```
- - -
Settings.ini file here (note: settings.ini was not a supported file type, so I renamed it settings.log
[settings - Copy.log](https://github.com/Bionus/imgbrd-grabber/files/5121381/settings.-.Copy.log)

**System information**

- OS: Windows 10
- Grabber version: 7.3.2, but I have tried running the installers for 7.3.0 and 7.2.1 to downgrade to an earlier version to fix the issue, and it didn't work.

**Other Info**
I used an old version of Grabber that was still compatible with SankakuComplex, and I made that critical file read only so that Grabber would stop auto-deleting it. This was working fine for a long time, but it's a possible confounding factor. I have also added a small handful of source websites which worked fine, but at least one of them was taken off the internet in the last couple months.

*-*-*-*
In the very short term, I would like to know how I can restore _most_ of my settings. I want to keep the naming scheme for the files, and the auto-sorting for them. How can I extract that? I assume the database of already-downloaded files isn't going to be an issue.

**Comment by Bionus** [comment]
I'll investigate your crash. The fact that downgrading Grabber doesn't work is worrying though.

It seems to be caused by the monitoring, would you be able to share your `favorites.json` / `monitors.json` files? If it's not convenient, you can also send them to me by email (bio.nus@hotmail.fr).

> I used an old version of Grabber that was still compatible with SankakuComplex, and I made that critical file read only so that Grabber would stop auto-deleting it. This was working fine for a long time, but it's a possible confounding factor. I have also added a small handful of source websites which worked fine, but at least one of them was taken off the internet in the last couple months.

It shouldn't be related. Even if a source disappeared, it shouldn't cause a crash, at best a few 404 errors in the log.

> In the very short term, I would like to know how I can restore most of my settings. I want to keep the naming scheme for the files, and the auto-sorting for them. How can I extract that? I assume the database of already-downloaded files isn't going to be an issue.

All your settings are located in `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber`.
I'd suggest making a backup of this folder then deleting it, as well as deleting your installation of Grabber in `C:\Program Files\Grabber` (or wherever you installed it).

Then, install Grabber and check if Grabber can start properly.

Afterwards, you can start restoring your settings either all at once or step by step:
* `settings.ini`: contains the settings that are edited in the "options" window (so most of them)
* `md5s.txt`: the duplicate database of already downloaded files
* `restore.igl`: batch and single images downloads
* `tabs.json`: your opened tabs
* `monitors.json`: your monitors
* `favorites.json`: your favorites (together with the `thumbs/` folder that contain their thumbnail)
* `viewitlater.txt`: the "kept for later" tags
* `ignore.txt` / `blacklist.txt`: the ignored and blacklisted tags

There's also site-specific settings you might want to restore, in `sites/%SOURCE%/%SITE%/settings.ini`. It contains stuff such as your identifiers, throttling, etc.

**Comment by Tumultuous-RGR-SiM** [comment]
Email sent.

I've transferred over my file renaming stuff and my metadata file configuration stuff.
Thank you for the list of where the settings are and what they do. It helped me get back up to speed faster than I would have been able to do otherwise.
