### ISSUE TITLE
What is the "_symbols.zip" download for?

### ISSUE THREAD

**Issue by Tumultuous-RGR-SiM** [Bionus/imgbrd-grabber#2099]
The .exe file is for installing the program, but I don't see what the _symbols.zip file is for. I just see "Grabber.pdb" and "Grabber-cli.pdb". I don't know what this filetype is. At a guess, it means something like "picture database", and it might somehow add more icons to the program.

If I want to use these to experiment a bit, how do I do it?

Placing this in the "issues" category didn't seem quite right, but I haven't been able to find any sort of general forum for this program.

**Comment by Bionus** [comment]
Those are debug symbol files for the Windows .exe file.
As a user, you don't need them.

They are uploaded together with the release because the releases are not generated by me but by [AppVeyor](https://www.appveyor.com/). I could download them as soon as the release is made then delete them, but maybe some users might find them useful to debug some things, so I just left them as is.

They are used to investigate crashes, either by having them directly downloaded when running Grabber before it crashes, or afterwards together with a crash dump (.dmp file) that is generated by Grabber. Without the symbol files, I won't be able to know where in the program the crash occurred. With, I can see exactly in which line of which file / function, which is a very important thing for fixing the issue.
