### ISSUE TITLE
Make Grabber add a _ after illegal folder names

### ISSUE THREAD

**Issue by Vike91** [Bionus/imgbrd-grabber#2106]
**Is your feature request related to a problem? Please describe**

When saving images in folders (ex. by artist), you sometimes get an artist name that is actually an illegal Windows folder name, thus halting the download.
Illegal folder names:

**Describe the solution you'd like**

Make Grabber add a _ after the name in this case.

**Describe alternatives you've considered**

To just put all images in one folder, regardless of artist.

**Comment by Bionus** [comment]
Do you have an example of illegal folder name that doesn't work?

Because Grabber already has this logic, although it adds a `!` rather than a `_`:
https://github.com/Bionus/imgbrd-grabber/blob/7bdb03be02204cc143da5f904882551e7f5cc122/src/lib/src/functions.cpp#L629-L631
https://github.com/Bionus/imgbrd-grabber/blob/7bdb03be02204cc143da5f904882551e7f5cc122/src/tests/src/functions-test.cpp#L100

**Comment by Vike91** [comment]
To reproduce this, from Gelbooru, get something from artist com2 or com6 (NSFW) and make the path to insert the artist name as a folder name.

From https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

`Do not use the following reserved names for the name of a file:

CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. `
