### ISSUE TITLE
mirror default sources between linux/windows/mac

### ISSUE THREAD

**Issue by clink86** [Bionus/imgbrd-grabber#2128]
**Is your feature request related to a problem? Please describe**
yes I noticed some sources in the linux version (both sankakucomplex url's are present in the linux release which is not present in windows release
It's hard to determine a list of sources between the two versions so i can add it to the windows version by default
**Describe the solution you'd like**

first off what file list the sources maybe copying the file on the linux version to the windows version will do just fine for now but maybe a master list can be used for all 3 versions?

**Describe alternatives you've considered**
copying the said sources txt from linux version to windows/mac

**Additional context**

**Comment by Bionus** [comment]
Windows uses the official sources list.
Linux uses all sources found in the source code, including unfinished and deprecated ones.

The difference is due to how the installer/tar.gz are generated. On linux it's just a huge copy/paste, while on Windows files are picked one by one by the InnoSetup installer generator.

You mention for example Sankaku, whose files are still in the git repository, causing it to be included in the Linux tar.gz file. However, it's not supported anymore, hence its absence in the Windows installer.
