### ISSUE TITLE
I can't launch Grabber after the build

### ISSUE THREAD

**Issue by Sc0utb0t** [Bionus/imgbrd-grabber#2133]
I'm new to Linux. I downloaded Grabber via the **AUR** package and then I clicked on build and when it was finished I couldn't run Grabber.

**System information**

- OS: Linux **Arch** Manjaro (Mikah 20.1)

**Steps to reproduce**

1. I click on the build button. 
![oBJaI1u](https://user-images.githubusercontent.com/72149018/95001961-79841300-05cf-11eb-809a-e5fe210c2e50.png)

2. I launch Grabber by clicking on the App Icon. 
![vzhEImn](https://user-images.githubusercontent.com/72149018/95001997-b94afa80-05cf-11eb-88b2-bc1dcd3e3fd0.png)

3. I get an error Message 
![uT2p8uG](https://user-images.githubusercontent.com/72149018/95001885-bb608980-05ce-11eb-9a07-7bf6607ec122.png)

**Expected behavior**

I can launch and use Grabber.

Maybe you can get some information from this picture:
![Vm4pAXm](https://user-images.githubusercontent.com/72149018/95001694-b13d8b80-05cc-11eb-8fd6-dc77a25f2967.png)

**Comment by Bionus** [comment]
I'm not very familiar with linux packaging stuff, and I don't maintain that one.
Very likely this is caused by the move of sources I did in a refactor earlier. If the maintainer sees this, they should use `./scripts/package.sh DIR` to copy all necessary files to a given directory (or `package-linux.sh` to create a tar.gz then extract it somewhere (it will be portable).

It seems that your settings are being stored in `/usr/share/Grabber/`, so what I would suggest is to simply copy the source files there. If the git was cloned somewhere during build, that would mean simply copying all of `src/sites/` to `/usr/share/Grabber/sites/`.

Otherwise, you can also just use the pre-built binaries and put them anywhere on your computer. For example for the last release:
https://github.com/Bionus/imgbrd-grabber/releases/tag/v7.3.2
Just download the `tar.gz` file.
