### ISSUE TITLE
[Question] Confusion about downloading and image limits

### ISSUE THREAD

**Issue by Justwanttoaskaquestion** [Bionus/imgbrd-grabber#2143]
Heya there, sorry if this is obvious, or documented somewhere .-.

I wanted to download/archive the images by a few artists (f.e. ginhaha), from R34. And I thought that grabber would just download all images by a tag, but I think I got that wrong?

Is there some way to set up grabber in such a way that I don't have to manually expand the image limit or search the tag again?

I hope this makes any sense... grateful for any answer in advance

For now I think I made a temporary fix by running a regular expression that replaces all lines that contain "total" in the download list, but I think I am overlooking some functionality.

Just adding this here, in case someone reads this, I'd love to know whether the blacklist can also utilize NOTAND?
Like, "Furry NOT interspecies", so if an image has only the furry tag, it gets ignored, but if it also has the interspecies tag, it doesn't.

**Comment by SvyraCosmix** [comment]
What's wrong with furries my dude

**Comment by Bionus** [comment]
> I wanted to download/archive the images by a few artists (f.e. ginhaha), from R34. And I thought that grabber would just download all images by a tag, but I think I got that wrong?

It should. What's wrong? If it only downloaded the first page, you might want to increase the "image limit" setting.

On most sources, when clicking "get all" the "images per page" is set to the current images per page setting, or depending on the source a fixed value. As for the "image limit" one, it uses the one detected from the source. If it didn't for some reason (which can be seen during search because it says something like "page 1 of ?", then it might limit itself to the first page as it doesn't know how far to look.

There's a plan in the roadmap to change that logic to instead "keep looking until hitting a 404 or 0 images", but that's not implemented yet.

> Just adding this here, in case someone reads this, I'd love to know whether the blacklist can also utilize NOTAND?
> Like, "Furry NOT interspecies", so if an image has only the furry tag, it gets ignored, but if it also has the interspecies tag, it doesn't.

You can use the same syntax as post-filters, which tries to follow common search syntax, so you can use a caret to negate an expression:
```
furry -interspecies
```
See https://bionus.github.io/imgbrd-grabber/docs/search.html for more details.

**Comment by Justwanttoaskaquestion** [comment]
Ok, sorry for the delay, had some other trouble.
What I meant was that I think it only sets the download limit of the tag, to the amount of images there are with that tag, at that moment.

So f.e. I tell it to "get all" images with a certain tag, which would be 154, and then a new one gets uploaded, it still only downloads 154.

It doesn't only download the first page, it downloads everything, but only everything that was present when I told it to get all.

Can I just set some default image limit to override this?

**Comment by Bionus** [comment]
> So f.e. I tell it to "get all" images with a certain tag, which would be 154, and then a new one gets uploaded, it still only downloads 154.
>
> It doesn't only download the first page, it downloads everything, but only everything that was present when I told it to get all.

Yes. However, as long as you sort "newest first", it should download the new one and "miss" the last one, which should normally already have been downloaded.

Not sure why you mention the first page though? If you want only the first page, you can limit it or just click "get this page" instead of "get all" in the search tab.

> Can I just set some default image limit to override this?

Not currently, but it's in the roadmap to allow a limit such as "all" that will loop through all images (i.e. until hitting a HTTP 404 or a page with no images).

**Comment by Justwanttoaskaquestion** [comment]
I'm sorry English isn't my native tongue.

I don't mean the page as shown in the browser but rather the "images per page" setting, which I am a bit confused about.

The problem I have specifically is that I would have to input all the things I want to download, so it refreshes the count of images, and does get all images. Which I think is what you meant with your second paragraph.
Thanks in any case, for now I'll just set the image limit to some extremely high number, and so far it worked.
