### ISSUE TITLE
Question regarding downloading Characters in a %copyright%

### ISSUE THREAD

**Issue by AkatsukiiDesu** [Bionus/imgbrd-grabber#2145]
Hi there :)

Just a quick question. Is there an automated way (if possible) to only download characters in a copyright that belong to that copyright

Example:
New_game! (only download characters that belong in this series according to the wiki)

My filenaming is `%search%\%character%\%md5%.%ext%` where `%search%` is "new_game!". Upon looking into the folders, I noticed that it downloaded other characters from the copyright (e.g. characters from "kantai_collection", "samus", etc).

If not, i'm happy to continue adding them manually.

**Comment by yami-no-tusbas** [comment]
it's because the boards sends you crossover results, you can filter them appart using %copyright%, so if there is two copyrights (like in a crossover) It would make a folder "kantai_collection new_game!" then you delete that folder.

I use `%search%\%copyright%\%character%\%artist - %rating% - %md5%.%ext%`

so it's easy to delete the folder with multiple copyright, you can also use the copyright tag setting to set it to put all the 1+ copyright images to a "crossover" folder. Then you delete the crossover folder. But to not "download" thoses images I can't see a way, maybe blacklisting "crossover" tag would help, but not if the tag is not present on the source.

To be clear, when you search "new_game!", Grabber will get every image with the tag that the boards send to it, they can be frot crossover, grabber have no way to tell. So simply blacklist "crossover" will make grabber to refuse the images tagged as such, for the rest you can filter using the "copyright" tag setting to have it put thoses multi-copyright images in a sepparated folder.

So you can make it semi-automated at least.
