### ISSUE TITLE
huge(&growing) DL list, used for repeated occasional dl's - unable to organize/sort

### ISSUE THREAD

**Issue by bunnyEscapism** [Bionus/imgbrd-grabber#2151]
Hi, new here :)

I've been using the app for quite some time, found it really useful and mostly intuitive.

One thing i'm having trouble with is being unable to sort the downloads list - i didn't want to use monitoring or going over each artist to save and set in the favorites list. i thought it would just add another few steps, and since i wish to run an occasional-repeated full/partial batch download (relying also on the md5 db to prevent server hogging and repeated file cleanups for me..), the download list already has the folders+relevant sources in it so it seemed to be the winning option.

Is there a way to sort the downloads list ? couldn't find anything from within the app and i couldn't figure out if the .igl file is structured to some common format that could be edited efficiently with some external app.. 
Help would be highly appreciated - i'm slightly ocd and we're talking about a possibly non-sort-able list with a few 1000's of group entries... 0_o

thanks !

**Comment by yami-no-tusbas** [comment]
Well, the format look Json alike to me, but the download list was never intended for this use. As far as I know, each time you re-order it, grabber have to save a .igl file in his directory, but if this file is hyge, that could take time and slow everything down. Plus download list doesn't know if t here is a new image, they only know how many images it is supposed to have. Luckily, since boards ads new images on the newer id, you will always get the new one. Then the download will skipp because of md5 I assume.

But there is the big catch, when you use download list like that, you are attacking servers with undreds of thousands of request ! Because if the download item has for exemple 1000 items, only two are new... Then you'll make 998 useless server requests... If it was a monitor, only one request would be done.

You should really take care here, some boards would want to blacklist your ip because of that. (like e621,danbooru,sankaku, etc)

And as you can always copy and past information to a monitor, you really should create a thousand monitors. Unfortunatle it is not possible to convert a .igl to a monitors.json, informations are not the same, it may be possible, since they are both json, but @Bionus is the only one knowing enough of the structure to tell if it is possible. For the fun i just tried renaming a .igl to a monitors.json, and it doesn't work.

If you want to give a try, you can test editing the files with notepadd++ or another raw text editor, or anything that can edit and parse json files.

And alway remember, you're the one that created this mess :p I've myself had to redo one by one hundreds of favorites to monitors when the features came, I know how you feel, but the solution for now, is to manually re-create every entry to a monitor. By the way, you don't need to use favorite anymore, just go to monitors, copy the tags/artists, then the source, put the same "filename" and "path" as ine your download, then add.

Cannot help you more, I don't see a fast way to do this, but right now your method of download list is harmfull for the servers you download from.
