### ISSUE TITLE
[question] e621.net pool download numbering

### ISSUE THREAD

**Issue by wizoxo** [Bionus/imgbrd-grabber#2152]
Hi, I've been trying to figure this out for 2 days and no luck so far.
Some pools have messed order of images when you order them by id.
Is there a way to download o pool and number the images (01,02,03...) not in order they load in downloader but in order they are supposed to be read/the way they show on e621.net?

**Comment by KeyboardCoomer** [comment]
Yes, it's not mentioned explicitly as an example, but amongst the list of save options, there should be %position% to form %position%.%ext% . This should allow you to download them as numbers. It will give you a warning, but I usually only ever download a list once and move on, so I've never encountered an issue writing it this way.

Using [how you're organizing]/%position%.%ext% 
you can download any list in the order that it is displayed on any of the websites.

**Comment by KeyboardCoomer** [comment]
The warning is only to say that if you don't set it up correctly, it could overwrite old files of the same name (hence using %md5% to generate a random name), but that's very unlikely to happen since most of these sites don't delete pictures very often.

Do keep that in mind though. Hope this helps!
