### ISSUE TITLE
programm don't download from chan.sankakucomplex.com

### ISSUE THREAD

**Issue by VanTuz5** [Bionus/imgbrd-grabber#2153]
When I try to download files from this site, not images are downloaded, but a warning that the link is expired

**Comment by yami-no-tusbas** [comment]
sankaku complex is not supported as far as i know (and at least for idol.sankakucomplex.com) , the webmaster of the website do all it can to block/prevent mass download. Grabber was able a long time ago, but nowadays it is not supported, see : https://github.com/Bionus/imgbrd-grabber/issues/2128#issuecomment-697037426 .

Since it is not supported anymore, feel free to close the issue. Next version won't come with sankaku at all, you may have it left from older installation.
