### ISSUE TITLE
the new android to pc

### ISSUE THREAD

**Issue by swedishchicken** [Bionus/imgbrd-grabber#2166]
Would be nice with a possibility to mark items(images/gifs etc) on the android version but have them added to the pc version with some kind of sync.

**Comment by Bionus** [comment]
There's no plan for any kind of synchronization between the mobile and desktop version at the moment.
Especially since in the future, they should both have the same features, so it wouldn't be necessary.

The most that will be implemented in the near future is settings import.
You can see the roadmap and discuss it in issue #2147.
