### ISSUE TITLE
Can not put images into certain folders from hypnohub

### ISSUE THREAD

**Issue by PandaMan1110** [Bionus/imgbrd-grabber#2173]
**Bug description**

When trying to make the subfolders such as %author% or %copyright% the grabber can not get the images. The images can be saved, but not if you try to make the subfolders such as %author% or %copyright%. This only happens when saving images from hypnohub.net

**Steps to reproduce**

1. Make the folders with %author% or %copyright% (or any other tag related folder)
2. Attempt to save an image from hypnohub
3. Can't download image

**Expected behavior**

The images downloaded 

**Context**

[main.log](https://github.com/Bionus/imgbrd-grabber/files/5511563/main.log)

**System information**

- OS: Windows 10
- Grabber version: 7.3.2

**Comment by Bionus** [comment]
If you're getting " Service Temporarily Unavailable" errors in your logs, that's likely because of Cloudflare.

Their API is accessible outside of Cloudflare, but since your filename uses the `copyright` token, Grabber needs to know which tags are copyright, which the API does not say. So Grabber has to load the image details page, which is Cloudflare-protected, and Grabber is blocked.

So from here you have two options:
* Add the Cloudflare cookies in Grabber to "bypass" Cloudflare
* Load hypnohub's tag database into Grabber so that it doesn't need to open the details page (cf [doc](https://bionus.github.io/imgbrd-grabber/docs/tools/tag-loader.html)). You can do this using the "Tag loader" option of the "Tools" menu.
