### ISSUE TITLE
Where are the nightlies?

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#2175]
I am stuck in a dilemma, I need that rule34 fix but there is no latest nightly available. The nightly tag I followed before now has an older nightly, even older than v7.3.2. Mine is newer than that!

**Comment by Bionus** [comment]
I don't know why, but the nightly is sometimes getting pushed as a draft on Github releases for some reason, even though all jobs explicitly say not to push drafts. I just pushed it manually.

Next time, you can also check the [Github nightlies](https://github.com/Bionus/imgbrd-grabber/releases/nightly-github) which will replace the existing nightlies after the next release.

Note that they're pretty recent and since nobody uses them except for the Android version, they aren't as well-tested. But I at least tested the Windows version and it worked with no issues on my machine, the included SSL libs as well.
