### ISSUE TITLE
Nightly builds not available

### ISSUE THREAD

**Issue by GiovanH** [Bionus/imgbrd-grabber#2177]
The readme.md file says that nightly builds should be available at https://github.com/Bionus/imgbrd-grabber/releases/nightly, but the last release under that tag is years older than the latest commit to the develop branch.

Note that there is also a https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly-github tag but it is not up-to-date either.

It looks like that link should simply point to https://travis-ci.org/github/Bionus/imgbrd-grabber/builds instead.

**Comment by Bionus** [comment]
The tag itself (whether `nightly` or `nightly-github`) does not really matter.
The tag doesn't get updated, it's simply using the latest commit from the `develop` branch.

The nightly build is currently broken (as seen in AppVeyor and Travis), and it seems it caused the release to get de-published, hence the lack of downloads in https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly. I just pushed a fix so you can find the downloads there again. I don't know why it's doing that, and I'll migrate the nightlies to Github once I fixed the last few issues with it.

As for https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly-github, since the build was broken the downloads were not totally up-to-date, but they were only a few days old (2020-11-11T11:20:05Z), as seen with [Github API](https://api.github.com/repos/Bionus/imgbrd-grabber/releases/32675106).
