### ISSUE TITLE
Is there a way to 'reset' monitored downloads?

### ISSUE THREAD

**Issue by Lil-Sassy** [Bionus/imgbrd-grabber#2181]
**Is your feature request related to a problem? Please describe**

I basically deleted an entire folder of tags that I had been monitoring to see if this was possible. I thought that by emptying out the .md5 file that maybe it would just attempt to re-download everything from all my tags but that didn't happen.

As I found out though, it just continues to download new things since the previous monitoring time.

**Describe the solution you'd like**

I'd like to re-download everything from every tag in my Monitors list. As in have Grabber think that everything is new again and try to download it all.

**Comment by Bionus** [comment]
There's no way to do that currently since you can't change the "last check" of a monitor in the UI.

I'd suggest opening the settings directory, and editing the "monitors.json" file there, and changing the "lastCheck" date of the monitor you want to reset. Put it to something a long time ago and it should re-check everything when the monitor triggers next time.

**Comment by Lil-Sassy** [comment]
> 
> 
> There's no way to do that currently since you can't change the "last check" of a monitor in the UI.
> 
> I'd suggest opening the settings directory, and editing the "monitors.json" file there, and changing the "lastCheck" date of the monitor you want to reset. Put it to something a long time ago and it should re-check everything when the monitor triggers next time.

Can do. Thank you!
