### ISSUE TITLE
Pixiv Login Error, again

### ISSUE THREAD

**Issue by corncheeto** [Bionus/imgbrd-grabber#2184]
I see pixiv has been a problem previously, so I tried using the solutions in #1765 and #2035. The error Message I receive is slightly different than what was posted in #1765. It reads...

`[Warning] [www.pixiv.net] No OAuth2 token type received: {"has_error":true,"errors":{"system":{"message":"103:pixiv ID\u3001\u307e\u305f\u306f\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9\u3001\u30d1\u30b9\u30ef\u30fc\u30c9\u304c\u6b63\u3057\u3044\u304b\u30c1\u30a7\u30c3\u30af\u3057\u3066\u304f\u3060\u3055\u3044\u3002","code":1508}},"error":"invalid_grant"}`

The main difference I see is the "invalid_grant" at the end of the error. I haven't seen that being reported before

**Comment by Bionus** [comment]
This message means:
> pixiv ID、またはメールアドレス、パスワードが正しいかチェックしてください。

Or in English:
> Check that your pixiv ID, email address, and password are correct.

Are you sure the email adress and password you are using to login are correct?

Some people also say it might be caused by a password being too short / simple and the API would not allow it. If you're sure your password is correct, maybe you can try to change to a longer/more complex one.

**Comment by fuck2ky** [comment]
Simple password is not allow to pass after api upgrade.

**Comment by corncheeto** [comment]
Alrighty, it turns out my password was too short. Thanks for the input.
