### ISSUE TITLE
Move icon to /usr/share/pixmaps per the freedesktop Desktop Entry spec

### ISSUE THREAD

**Issue by txtsd** [Bionus/imgbrd-grabber#2189]
**Bug description**

At the moment, no panel or launcher is able to find the icon for Grabber. Moving `grabber.png` to `/usr/share/pixmaps` makes panels and launchers able to find the icon.

**Steps to reproduce**

1. Install Grabber on a linux distro of your choice
2. Regenerate your app menu if you have to
3. Look at the Grabber menu entry in your panel or launcher of choice
4. It does not have an icon

**Expected behavior**

The menu entry should be able to fetch the icon correctly

**System information**

- OS: Arch Linux
- Grabber version: 6f4d5c11bd008ba8ca5530ae706623a998655910

**Additional context**

Tested on Openbox with obmenu-generator, budgie-panel, and lxqt-panel.

**Comment by Bionus** [comment]
Hello!

I was trying to fix this on Ubuntu without using `pixmaps` (since it doesn't seem to be recommended), and succeeded by putting the images in the correct size folder (and adding a few alternative sizes). Can you try the latest commit on develop and check if installs now have a proper icon?

If not I'll simply _also_ copy it in `pixmaps` as a backup for other systems, similar to what you did in PR #2191 but simply putting it in both to allow other shells to use the multi-size feature.

**Comment by txtsd** [comment]
Yep. Works for me now. Not sure why it didn't work when *I* put in a size folder.
