### ISSUE TITLE
Grabber crashes when hitting X on the main window or any subwindow

### ISSUE THREAD

**Issue by txtsd** [Bionus/imgbrd-grabber#2190]
**Steps to reproduce**

1. Open Grabber
2. Click on the X in the WM
3. Segfaults

##### Alternatively
1. Open Grabber
2. Search for anything
3. Click on a thumbnail to launch a subwindow
4. Click on the X in the subwindow
5. Segfaults

**Context**

* There is no error in `main.log`
*  Happens with a blank `settings.ini` too
* The coredump is 311MB. Let me know if you need it.

**System information**

- OS: Arch Linux
- Grabber version: 6f4d5c11bd008ba8ca5530ae706623a998655910

**Comment by LeaflessMelospiza** [comment]
I'm having the same issue on Debian testing with the develop branch. The reason why coredump is so large is because it's a stack overflow caused by createWinId()
```
#0  0x00007ffff7a283a2 in QWidget::setAttribute(Qt::WidgetAttribute, bool) () at /usr/lib/libQt5Widgets.so.5
#1  0x00007ffff7a28259 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#2  0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#3  0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff7a28337 in QWidgetPrivate::createWinId() () at /usr/lib/libQt5Widgets.so.5
<snip>...
```
Using git-bisect the issue was introduced by commit 25d501fa85ccde483e988a78a4eb3621fb71d14b .
For now I am able to fix this by Deselecting "Use built-in video player" in Tools->Options->Interface->Image window

**Comment by Bionus** [comment]
I can reproduce on a self-built version, but note that [nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly)'s AppImage does not seem to have this issue.

**Comment by txtsd** [comment]
I'm on Arch, so building is the way instead of using AppImages.

**Comment by Bionus** [comment]
Seemed to be some weird behavior when the [QVideoWidget](https://doc.qt.io/qt-5/qvideowidget.html) was being deleted automatically as a child from the image window.
Removing it from the widget tree and deleting it manually seems to fix the issue.

Very strange issue, especially since it works using AppImage but not when self-building. Maybe a different version of the video player library that doesn't like the way it was being deleted? 🤔
