### ISSUE TITLE
Possible to download from URL ID downwards?

### ISSUE THREAD

**Issue by Kastralis** [Bionus/imgbrd-grabber#2198]
One common occurrence that prevents a smooth and complete download of images from a site (for example Gelbooru) is the fact that they limit the page search down to the 20,000 searched image through page by page. However, one way to circumvent that is to download the original images from a sequential list of URL's (example: https://gelbooru.com/index.php?page=post&s=view&id=5716920 to https://gelbooru.com/index.php?page=post&s=view&id=0). This would in theory be possible to download all 5 million+ images without being hindered by the 20,000 image search limit since what you're doing is individually looking into the URL to grab the original images. Would this be possible to implement as an option, or is there a feature already designed to do exactly this? Thanks!

PS. I have yet to really dive into the source code to see how it is exactly that the program is downloading the original images to begin with. However, it does seem that you are somehow going directly the the original image URL to download.

**Comment by brazenvoid** [comment]
The Gelbooru API makes it possible to get original images per a search query. 

I would not recommend downloading Gelbooru's whole database due to a number of issues, including the fact that sifting through it is an endless chore, believe me I have tried and failed many times. 

Best you make an exhaustive blacklist, define some meta tag based exclusions like exclude gifs or webms or perhaps define a minimum resolution. Another would be filtering based upon score, it really makes it so that most low quality stuff does not get downloaded. And you can also limit the results to X previous years.

With all of the above, I still have over 400k images and videos left to sift through in my archives. I only do about 10k a week while against those about 3-4k new ones get downloaded.

If you are bent on downloading the whole DB it can be done with many searches with most prevalent tags. When I did it last time, there were less than 20 such searches for non-safe works.
