### ISSUE TITLE
Cannot Download Same Image Multiple Times

### ISSUE THREAD

**Issue by cloudywings2** [Bionus/imgbrd-grabber#2210]
**Bug description**

It is impossible to save a copy of the same image to two different sources. This makes it extremely difficult to save batches of overlapping tags. If, for example, you have previously downloaded images for a niche tag, and later attempt to download all the works of an artist, then the artist's works with that tag will be skipped. 

**Steps to reproduce**

1. Search for a tag from any source, such as "1girl."
2. Download an image from that source to a folder based on that tag. (such as %search%/%md5%.%ext%)
3. Search for a different tag on the same image, such as  "black_hair"
4. The image cannot be downloaded, and will link to that other image if the Destination Folder button is clicked.

**Expected behavior**

Two copies of the image should exist. 

- one in 1girl/%md5%.%ext%
- one in black_hair/%md5%.%ext%

**Comment by yami-no-tusbas** [comment]
Can you send your settings.ini and logs ? Have you set the options to copy, instead of link when an image already exist ?

**Comment by Bionus** [comment]
Looks like you're using the global MD5 list but actually don't want it.
I'd suggest setting it to "save" or "copy" instead of "don't save".

See [How to avoid duplicates](https://bionus.github.io/imgbrd-grabber/docs/faq.html#how-to-avoid-duplicates) in the docs.
If you already have the setting set to "don't save" but stilll cannot save (can you expand on what exactly it says?), it would be helpful to have your settings file / logs. Feel free to re-open in that case.
