### ISSUE TITLE
Make it possible to see the HTTP response for a request, or at least the response code

### ISSUE THREAD

**Issue by index-eab** [Bionus/imgbrd-grabber#2215]
**Is your feature request related to a problem? Please describe**

The grabber is fantastic, and I'm really appreciative of all the work yall have put in! Thank you!

The first time I used it a couple of days ago, I got a vague error after downloading 14,591 images from e621, waiting 1 second between each download: "_An error occurred saving the image. Please solve the issue before resuming the download._" In the log it said "_[Error] Unable to open file_". I ensured the media I'm saving to was fine and decided I was probably booted for downloading too fast, so I waited.

Yesterday I was allowed to continue, and I increased the timer to two seconds. Again, after 14,591 images I was booted. Now I'm thinking e621 has a hard cap of exactly 14,591 images per day, but because I can't see the server's response I'm not sure. Maybe it's something else?

**Describe the solution you'd like**

Being able to read the latest HTTP response (or at least response code) would ease troubleshooting for any potentially server-related issues. As it stands I can't tell if the problem is on my end or not.

**Comment by yami-no-tusbas** [comment]
Ok, I tested the tag "hyaenid" from e621 this tag should have 17906 results, I adjusted the image limit value accordingly because grabber think there is only 200 results while using json api. Using 200 result per page, I let it run and...

First, I'm logged with an account, I use json for e621 instead of html since i prefer their api over brute html result oftend ending with tag type error.
Second, I don't think e621 will put a random limit on the 14591'th image. You most likely had encounter a not friendly name, i've seen that happen when tags contain bizzare characters. (like : ߷-✩✩|✩✩✩✩✩|✩✩|✩ ) as mentionned in the issue there : #1595 

ok after the download i got only 10k image since a lot was blacklist, so I ran the batch again this time time getting the blacklisted ones; In total i would download more thant 17906 image, so...

I got every images, no problem, nothing like a limit on 14591 images. Can you check the file name grabber attempt to create ?
