### ISSUE TITLE
Grabber can't save image file when file name longer than 260 character

### ISSUE THREAD

**Issue by ebony317410** [Bionus/imgbrd-grabber#2217]
I try to save some image with all tag as file's name.
and I already set win 10 With a Registry Hack  “LongPathsEnabled”

and set Grabber's options >> save >> filename >> Max length 

but when I set value over than 260 Grabber always return me a error message

any idea to solve it? or I need to set something else?

Best regards and THX for this amazing tool

**Comment by ebony317410** [comment]
OOPS~!!
after i new this issue and i found it is already solution at.

https://github.com/Bionus/imgbrd-grabber/issues/1838

**Comment by yami-no-tusbas** [comment]
Well, your logs may help first.

I tried reproducing that on grabber nightly 975102b0 and it worked, kinda.

My logs show errors, but files are where they are supposed to be. This is the "date error" that unrelated to this.

`[11:54:17.260][Info] Loading and saving image from https://img2.gelbooru.com/images/f8/4e/f84e22c9854f67663cf02ef50f743f6a.jpg in J:\Avatars\Gelbooru\mH8wnBEDKo5gYGxSC3BOFdS2CyCjlcIDoYgiqvYoFKzCIJLUXNkjrBrxu5FCAYpQqDhXdrtmZYe7ho09ywW1jU48x8ytsthkYWeCCHxMUsy4BtN5BkNbmhrILFSfow1txOgronwmpSx3j6o0RqTwwr1FXq35BajVZP9pci3Hi2bNpmtNyGgHwFhAWAJX6XiGIob3gExn\re_zero_kara_hajimeru_isekai_seikatsu\re_zero_kara_hajimeru_isekai_seikatsu\ram_(re_zero)\anonymous - 5772836 - safe - f84e22c9854f67663cf02ef50f743f6a.jpg
[11:54:17.386][Error] Unable to open file to set creation date (3 - Le chemin d’accès spécifié est introuvable. ): J:\Avatars\Gelbooru\mH8wnBEDKo5gYGxSC3BOFdS2CyCjlcIDoYgiqvYoFKzCIJLUXNkjrBrxu5FCAYpQqDhXdrtmZYe7ho09ywW1jU48x8ytsthkYWeCCHxMUsy4BtN5BkNbmhrILFSfow1txOgronwmpSx3j6o0RqTwwr1FXq35BajVZP9pci3Hi2bNpmtNyGgHwFhAWAJX6XiGIob3gExn\re_zero_kara_hajimeru_isekai_seikatsu\re_zero_kara_hajimeru_isekai_seikatsu\crusch_karsten\anonymous - 5772842 - safe - 276d00076c6e6306b7dd5480556130b8.png`

But the file are downloaded just fine and windows have no problem, the only difference I see is the pathing : 

Normal (under 260) :  

> J:\...\anonymous - 5772842 - safe - 276d00076c6e6306b7dd5480556130b8.png

and long path (over 260) : 

> \\?\J:\...\anonymous - 5772845 - safe - 0dfd975b88f19054116636d83f33652c.png

But as far at what i can see, grabber handle long path just fine. Assuming it is set in windows correctly. (I'm on Windows 10 20H2 build 19042.685)

**Comment by VanishingBlaze** [comment]
Was there ever a solution for this?

**Comment by KasumiArai** [comment]
I have NTFS drives without long filename support. I would prefer not to enable it. I am on Windows 10. I am saving images from Sakugabooru with this filename string: %md5% %all% %rating%.%ext%

Some images entirely fail to download, I assume because when .tmp is appended it makes the filename too long despite being cropped otherwise. (Downloading images with a short filename string like %md5%.%ext% and using the "Rename existing files" option with the  %md5% %all% %rating%.%ext% does work)

Here is an error message from the log when downloading rather than renaming: Unable to open file 'C:\L\52b1ea01c42d0c624ff74a7d6aaad321 animated character_acting effects fabric hair princess_connect_re_dive princess_connect_re_dive_season_2 princess_connect_re_dive_tv shuhei_fuchimoto shuhei_nishitani takahiro_watabe yosuke_fukumoto yusuke_soen safe.mp4.tmp': The filename, directory name, or volume label syntax is incorrect. (5)

![image](https://user-images.githubusercontent.com/8582123/167750741-00e82a1e-beda-4640-a4ac-f34a3f51a292.png)

The path with just the extension is 257 characters, which just sneaks under the Windows default 260 character limit. The appended ".tmp" pushes it over to 261

A search query on Sakugabooru where this can be seen is "princess_connect_re:dive_season_2". 

I am totally fine with the rating and some later tags being cut from the filename, but this prevents some files from downloading at all without the rename workaround. (Another potential workaround is setting the filename length to 256 instead of the default 0, which might allow room for the appended .tmp to hit 260. but I haven't tried this)
