### ISSUE TITLE
Tag loader disapear when putting old settings files from previous installation.

### ISSUE THREAD

**Issue by yami-no-tusbas** [Bionus/imgbrd-grabber#2238]
**Bug description**

After looking what make the tag loader disapear I isolated the culprit, my settings.ini in "sites\Gelbooru (0.2)\gelbooru.com" Don't know why, but when I restore that file the tag loader disapear, I tried to reproduce it from a new one, putting my login, cookies, things like that, and after rebooting everything was fine, it only appear with the old file.

culprit file : 
_[REMOVED by @Bionus]_

**Steps to reproduce**

Put my file, load the tag loader and voilà, no gelbooru.

**Expected behavior**

Tag loader not to be dependend on this file ?

**Context**

Log don't log this, maybe they need to be more verbose.

**System information**

- OS: Windows 10
- Grabber version: Nightly 1fe84600

**Comment by Bionus** [comment]
That's because you disabled HTML in the source's settings.
Gelbooru doesn't have any XML API for loading tags, so Grabber relies on HTML parsing to load them.

On one hand, that's indeed confusing that the tag loader uses the same rules as the normal search. On the other hand, having different behaviors can be confusing as well, if you disabled the HTML API but then Grabber still uses it for the tag loader.
