### ISSUE TITLE
Safety?

### ISSUE THREAD

**Issue by mathus333** [Bionus/imgbrd-grabber#2245]
**Bug description** Windows is warning me not to use it. Is it safe? How would I know?

**Comment by Bionus** [comment]
Yes it's safe, but as the developer that's natural for me to say so.
I haven't heard of anyone having an issue with it out of the thousands of users, except one who was using some weird proxy through Grabber.

The source code is available so you can see it doesn't do anything it shouldn't.
Also, I guess you can simply use some kind of online antivirus? Windows also has one bundled (Defender), you can scan the EXE with it too and see before running it.

What does Windows say exactly?
AFAIK Windows warns for all EXE from the internet.

**Comment by brazenvoid** [comment]
I suspect OP is referring to the error that comes when you try to install it:

![Screenshot 2021-01-27 222011](https://user-images.githubusercontent.com/8722533/106028496-d7dc8080-60ed-11eb-9810-2552b597a8e5.png)

You said many months ago that it was due to some windows installer validation/license or such... It does not occur anymore in the latest nightlies.

**Comment by brazenvoid** [comment]
I just downloaded the latest nightly and it has the above yet again.

**Comment by Bionus** [comment]
I believe it's some Windows security that is triggered when not enough people ran the application / had it scanned by defender.

There were no major changes since that one 🤔
Nightly is very likely to always have this issue since they're re-created quite often, so I guess "fresh" ones will always have this warning

Signing might help for updates since you only need to trust it once, but it will always block the first install. Installing the main release shouldn't have this problem though?

**Comment by brazenvoid** [comment]
The current main release has it.

**Comment by yami-no-tusbas** [comment]
Don't think @Bionus can do a lot about it since it's on microsoft side : 
https://docs.microsoft.com/en-us/archive/blogs/vsnetsetup/windows-smartscreen-prevented-an-unrecognized-app-from-running-running-this-app-might-put-your-pc-at-risk

and to appeal : 
https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/submission-guide

**Comment by mathus333** [comment]
Good enough for me. Thanks guys
