### ISSUE TITLE
Tool to convert Download list to Monitors

### ISSUE THREAD

**Issue by TempMonkas** [Bionus/imgbrd-grabber#2247]
**Describe the solution you'd like**

I have nearly 1000 entries in my Downloads list and would like to convert them to Monitors automatically.

**Additional context**

See issue #2246 for context. It's where I'm taught how Monitors work. Would be great to be able to simply convert my downloads to monitors, as opposed to manually making monitors.

**Comment by Autissima** [comment]
I've actually written something like that, since it's just a JSON table and I had exactly the same problem, if you still need it.
The template.json contains a path of mine, and you should change the variable "path" to the path you want.

The following is Javascript:

```
const fs = require("fs");
var res = new Object();
res.batchs=[];
var src = require("./monitors.json");
var template = require("./Template.json");
i=0

for (entry of src.monitors){
    template.query.tags=entry.query.tags
    
    for (ent of entry.sites){
        template.site=ent
        newTemplate = JSON.parse(JSON.stringify(template));
        res.batchs.push(newTemplate)
    }
    
}
res.uniques=[]
res.version=3
const data = JSON.stringify(res, null, 4);


fs.writeFileSync("./result.json",data,"utf-8");
```


and here is the template, if you want a different filename you should change that one as well. Forward slashes in paths are doubled.
```
{
    "filename": "%md5%.%ext%",
    "galleriesCountAsOne": true,
    "getBlacklisted": false,
    "page": 1,
    "path": "",
    "perpage": 100,
    "postFiltering": [
    ],
    "progressFinished": false,
    "progressVal": 0,
    "query": {
        "tags": [
        ]
    },
    "site": "",
    "total": 100000
}
```
