### ISSUE TITLE
Embedding image tags as actual Windows "tag" metadata

### ISSUE THREAD

**Issue by iPathos** [Bionus/imgbrd-grabber#2258]
**Is your feature request related to a problem? Please describe**

I think it would be at least partially helpful to have an option to embed downloaded image tags into the actual metadata "tags" field, more methods of organization without having to rely on folder/title specificity.

**Describe the solution you'd like**

Ideally, an option to choose if you would like the image's booru/imageboard tags embedded into the "tags" metadata field for the image in question.

**Describe alternatives you've considered**

I will say it's by no means a required addition, but based on the idea the only alternatives I can really offer are the ones already dealt with - eg adding tags to filenames or folders.

**Additional context**

Nothing else major here, I do not know the difficulty of implementing this kind of request as it's far and away outside of my area of expertise - I do think it would be a positive feature for the project to have though.

**Comment by sstabeler** [comment]
You can't embed them automatically in the actual image currently as far as I am aware- and I happen to agree it would be a nice feature- but it is worth noting it **is** possible to create a separate log file for each image than contains the image's tags, which is more convenient than using the filename, since you can get all of them, instead of being limited by the maximum filename length.

**Comment by brazenvoid** [comment]
This has been discussed many times before and is not sustainable. Look for other solutions like Hexus Network or deploy your own booru.

**Comment by iPathos** [comment]
> You can't embed them automatically in the actual image currently as far as I am aware- and I happen to agree it would be a nice feature- but it is worth noting it **is** possible to create a separate log file for each image than contains the image's tags, which is more convenient than using the filename, since you can get all of them, instead of being limited by the maximum filename length.

Thank you for the explanatory reply, even the log files in that regard would be helpful as I'm fairly certain you could use external tools to then transpose those tags onto said images, though I won't say that with certainty.

> This has been discussed many times before and is not sustainable. Look for other solutions like Hexus Network or deploy your own booru.

I use Bionus's program because I find it to be the most intuitive and useful, to the point of not wanting to use them over this, and the entire intent of downloading items from these boorus is to allow me offline, non-booru access to them. This position should be evidenced by the very first word in the title. Please also elaborate as to why it isn't sustainable? My understanding from sstabeler's reply above was that it wasn't possible in the context that I asked, which is an entirely different issue. I do see in #1233 that there's a workaround possible by saving the tags as a logfile and then doing (as I said above) the transposing using an external program. This would not be an issue were it not for the filename limits that have plagued us for so long, but there's little that *we* can do about it.

**Comment by brazenvoid** [comment]
You can search the issues here to find the arguments against, there are about 2-3 here. I have argued for the same thing.

Also in nowhere in my comment does it say that you will not have non-booru access to the files. In both cases you have to have them on your disk. They are essentially file managers, just like windows explorer. The key information here is that the tagging is accomplished by them in a separate db.

Rather than going with log files, Grabber can be extended with making the md5 SQLite DB (available in nightly) also store the tags and make it manage/browse/search the target folders as sources. That way you will get best of both worlds. You will be able to view them on disk and search them as needed through grabber. That will also allow for mass export features for other uses.

**Comment by iPathos** [comment]
> You can search the issues here to find the arguments against, there are about 2-3 here. I have argued for the same thing.
> 
> Also in nowhere in my comment does it say that you will not have non-booru access to the files. In both cases you have to have them on your disk. They are essentially file managers, just like windows explorer. The key information here is that the tagging is accomplished by them in a separate db.
> 
> Rather than going with log files, Grabber can be extended with making the md5 SQLite DB (available in nightly) also store the tags and make it manage/browse/search the target folders as sources. That way you will get best of both worlds. You will be able to view them on disk and search them as needed through grabber. That will also allow for mass export features for other uses.

As I have done, since my posting the issue (further searching if the issue). Admittedly I did not do my due diligence by searching every possible accurate term, considering "tag" and "tags" return 254/693 and 184/499 for issues/closed respectively. You also made no mention of those who have no experience in this area, as is evidenced in the initial post. I do not know how to initialise any of this, and if I can help it I will avoid it for my personal use. Again, this comes back to the title and my state of posting the issue, which I take at least partial blame for the lack of specificity. This however relates to your statement of my "lack of mention of my non-booru access - is that not the intent of the program as a whole, while allowing migration as a secondary function?

Regardless. I have since specified that I have no experience in the field and I will also clarify in clear terms "I do not have the experience, drive or need to create my own database, booru or hosting service simply to enable the use of tags.
I will also mention that your initial response was in no way accurate to the given parameters, as it's very clearly stated in the final paragraph that I do not have the expertise to be working with these programs: thus I requested the aid of those with more accurate and appropriate knowledge than I.

To clarify on my intent, I am not trying to avoid duplication. I already have programs I run often for that considering the vast number of folders I currently use, to ensure duplicates aren't an issue. I want to apply accurate tags to individual images for my own reference. I am aware that people can add and remove tags as an image ages in each booru, however that is not my concern. Mine is being able to accurately catalogue the images I have, without having to set up something even resembling the structure it was deployed from. Yes, I am aware that this won't be infinitely accurate - that is not my intent, nor my suggestion.

**Comment by brazenvoid** [comment]
Duplication, consistency etc was not something I addressed nor wanted to do anything with. Let me try to clarify it again. In current setup with grabber, what you are proposing is not possible. 

I completely understand that you do not want a system like how boorus manage the files. I proposed extending grabber because you seemed to like how grabber organizes/manages/searches them.

To allow tagging and assuming searching through them, you will have to have a parallel system, in all cases. It simply cannot happen in windows explorer. Unless you can manually tag all the images one by one by hand.

**Comment by iPathos** [comment]
> Duplication, consistency etc was not something I addressed nor wanted to do anything with. Let me try to clarify it again. In current setup with grabber, what you are proposing is not possible.
> 
> I completely understand that you do not want a system like how boorus manage the files. I proposed extending grabber because you seemed to like how grabber organizes/manages/searches them.
> 
> To allow tagging and assuming searching through them, you will have to have a parallel system, in all cases. It simply cannot happen in windows explorer. Unless you can manually tag all the images one by one by hand.

I will await your response.
https://archive.codeplex.com/?p=filemeta

**Comment by brazenvoid** [comment]
I have tried the software just now and for the first time in my life I had to use system restore to stop my PC going repeatedly into safe mode... I understand this could be a one in a billionth occurrence that such happened.

Still in concept, that program adds tag handlers to file types not supporting it by default. And if it works to correctly add the tag handlers, grabber in concept can attempt to add them.

**Comment by brazenvoid** [comment]
@Bionus Perhaps a method can be added which can try adding tags which activation can be flipped in options. All encapsulated in an error handler to show an error and abort otherwise.

**Comment by iPathos** [comment]
> I have tried the software just now and for the first time in my life I had to use system restore to stop my PC going repeatedly into safe mode... I understand this could be a one in a billionth occurrence that such happened.
> 
> Still in concept, that program adds tag handlers to file types not supporting it by default. And if it works to correctly add the tag handlers, grabber in concept can attempt to add them.

That's certainly interesting as a result of installation - assuming you're running W10 though, which build/version?
I have encountered no such issue, though I'm not currently at my PC so specifying the version must wait.

**Comment by brazenvoid** [comment]
I though you gave up lol. BTW I am on W10 20H2. But as I said, it could just be me. Though I am not going to try again, I have not reinstalled windows in years... I am developer myself and I take great care in maintaining my computers. :)

But as I said, it is working for many as evidenced by the many issues listed on their git repo. Though it has not seen updates since May last year.

**Comment by Penguin-Guru** [comment]
Just for the record, it is possible to add arbitrary metadata to files in many operating environments. I'm not sure how much additional space it would use for files with an average amount of tag data but personally I would prefer that. The problem is that it's probably extremely slow to read and write, so it wouldn't really be useful for Grabber. The only benefits I see is as a way to access tag data from a different application and to share it with someone else along with the file. Technically, both of those are possible, though perhaps not in such an elegant way. Another problem is that there just aren't many programs that you could use to access that data, so you would probably want to use Grabber for it anyway if Grabber did support it.

https://en.wikipedia.org/wiki/Extended_file_attributes

https://en.wikipedia.org/wiki/Semantic_file_system

**Comment by Penguin-Guru** [comment]
I think iPathos was imagining this as an alternative to using any database. That's why I said it would be extremely slow in comparison. Correct me if I'm wrong.

This issue caught my eye because I would like to use xattrs to store tag data rather than trying to add some subset of them to the file names. It's probably not very practical but it would be nice, mostly in the interest of interoperability with other programs and simplifying synchronisation/backups between systems. Hopefully more userspace applications will use this feature in the future and the data format will be consistent between applications, but I imagine this isn't a priority.

**Comment by brazenvoid** [comment]
Yes, any solution not using a DB will always be substantially slower, after all you are competing with something specifically made and optimized for the purpose for literal decades. 

Jack hasn't been very receptive of big sweeping changes for sometime now and its fine as there is no one sharing his burdens. Usually open source stuff attracts contributors but that hasn't been the case for Grabber. Perhaps a few more patrons or donations will motivate him more. I am also in the same boat with my patrons and a new patron really motivates me to do the big things, I have hinted about but didn't really put an effort for.

**Comment by Penguin-Guru** [comment]
No pressure intended. I just wanted to weigh in on the topic since it's here. :)

For what it's worth, I did just submit some minor changes for the installation scripts. There are things I would like to add to the program if I can figure out how Qt works but I don't want to make any promises. Graphical applications terrify me.
