### ISSUE TITLE
Pixiv login failed. API changed.

### ISSUE THREAD

**Issue by issuesmaker** [Bionus/imgbrd-grabber#2263]
see https://github.com/upbit/pixivpy/issues/158
Pixiv change its login API. this program can't login pixiv too.

**Comment by markedone66** [comment]
Im having the same problem: 
`[15:20:02.159][Info] [www.pixiv.net] Logging in...
[15:20:03.222][Warning] [www.pixiv.net] No OAuth2 token type received: {"has_error":true,"errors":{"system":{"message":"Invalid grant_type parameter or parameter missing","code":1508}},"error":"invalid_grant"}
[15:20:03.222][Info] [www.pixiv.net] Login finished: failure.`
using email and a new password with special chars too

**Comment by markedone66** [comment]
Any news yet? :(

**Comment by Foldz** [comment]
I've just recently encountered this issue myself, not really much we can do except for a hotfix. As in for news, it seems the developer has recognized the issue, but hasn't pushed out anything yet.

**Comment by Bionus** [comment]
@op8867555 would you be open to making a PR with your change if it's working?
That seems to also be the workaround suggested in pixivpy (using the refresh token forever).

**Comment by op8867555** [comment]
@Bionus I just rebase my change and made a PR for it. It is somehow working but I'm not sure about it.

**Comment by Bionus** [comment]
Thanks! It should now be fixed in the [Nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly) version, as long as you find a way to get an access and a refresh token.

If you've used Pixiv with Grabber before, they should already be pre-filled. Otherwise, this script should do the trick:
https://gist.github.com/upbit/6edda27cb1644e94183291109b8a5fde#file-readme-md

**Comment by DavidCreegan** [comment]
Traceback (most recent call last):
  File "C:\WINDOWS\system32\pixiv_auth.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

All of this is foreign to me so i have no idea what I'm doing wrong..but line 6 definitely says "import requests"
Also not sure why it made me put it in system32, because if i didnt i just got an error

**Comment by HelpSeeker** [comment]
It might be a good a idea to mention this script somewhere in the documentation, because it took me a quite a while to figure out what these tokens were and how to get them.
