### ISSUE TITLE
Danbooru 200 image limit

### ISSUE THREAD

**Issue by DeetrixReed** [Bionus/imgbrd-grabber#2275]
**Steps to reproduce**  (Danbooru only)
1.search any tag that give a result over 200 images
2.click 'get all'
3.go to download tab

**Expected behavior**
Expect to see: Image Limit = xxxx (the Max images from the site, just like the other results, see Screenshot) 
Instead I see: Image Limit = 200 

**Context**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/6075265/main.log)
[settings.ini.txt](https://github.com/Bionus/imgbrd-grabber/files/6075271/settings.ini.txt)

**Screenshots**
![Danbooru returns](https://user-images.githubusercontent.com/77783894/109793022-fc35ec00-7bc8-11eb-96e7-bc892154d244.png)

**System information**
- OS: Windows 8.1
- Grabber version: 7.3.2 (x64)

**Additional context**
Has been working fine for the last 6+ months.  Started a week or two ago, I didn't catch it immediately.
Downloads all the images from the other Booru sites that practically mirror the image sets. (but Danbooru has proper tagging!)
Also love your work I'm very glad to have shown my support.  :)

**Comment by J3loodz** [comment]
cant you ust write manually into the image limit (200 limit) a new limit, like 1000000?

**Comment by Bionus** [comment]
Reproduced on 7.3.2:
![image](https://user-images.githubusercontent.com/882719/110236235-f3307c00-7f34-11eb-9f0f-bab9193fb1e9.png)

Seems to be working fine on [Nightly](https://github.com/Bionus/imgbrd-grabber/releases/nightly), likely thanks to f2009a6b:
![image](https://user-images.githubusercontent.com/882719/110236207-d3995380-7f34-11eb-89ac-f7a85e42db7a.png)

Otherwise, as said by @J3loodz you can override the image limit manually in the downloads tab.
