### ISSUE TITLE
Log tab truncates lines when it encounters certain characters.

### ISSUE THREAD

**Issue by Penguin-Guru** [Bionus/imgbrd-grabber#2306]
I did this: `log("shelfDrawerDiff < 0");`

This is what was printed: "shelfDrawerDiff "

Console log prints the full line as expected: "shelfDrawerDiff < 0"

Operating system is linux.

**Comment by Bionus** [comment]
It should print fine in your console / debug output (you might need the `-d` flag for Grabber, I don't remember precisely), but I can see why this would happen in the Log tab, since it's being shown as HTML.

The output should be escaped before being shown I guess, in the logToHtml function:
https://github.com/Bionus/imgbrd-grabber/blob/321954b522ef62aee90f158fb4bfd5aa5044ddae/src/lib/src/utils/logging.cpp#L43

I guess replacing `<` and `>` by `&lt;` and `&gt;`  should be enough to do the trick.
I'll have a look.

**Comment by Penguin-Guru** [comment]
It also trims leading whitespace, so "    example" would print as "example". That whitespace might be useful for indentation.

Apparently Github also squeezes multiple spaces into one...
