### ISSUE TITLE
Missing translations in 7.5.x releases

### ISSUE THREAD

**Issue by sky-cyh** [Bionus/imgbrd-grabber#2323]
main.log:
[10:01:18.241][Warning] [Qt][qt.network.monitor] Could not get the INetworkConnection instance for the adapter GUID.
[10:01:18.250][Warning] [Qt][qt.network.monitor] Could not get the INetworkConnection instance for the adapter GUID.

And this software kept crashing this morning (saying "It seems that the application was not properly closed for its last use. Do you want to restore your last session?")  until I deleted the "Bionus" folder.

**Comment by Bionus** [comment]
Is the `languages` directory there in your install directory?

![image](https://user-images.githubusercontent.com/882719/115293436-9a6d1980-a157-11eb-9e22-410c29c14098.png)

Because that's where the language files are located:

![image](https://user-images.githubusercontent.com/882719/115293528-bb356f00-a157-11eb-9953-02ccd077c588.png)

**Comment by sky-cyh** [comment]
I have this folder, but I dont have those qm files. It seems that my Grabber cant download qm files from the server.

**Comment by Bionus** [comment]
Those files aren't downloaded, they're supposed to be included in the installer.
Seems like they're missing from the 7.5.x releases.
