### ISSUE TITLE
"Don't save" Setting in "Save" not working.

### ISSUE THREAD

**Issue by shiosakun** [Bionus/imgbrd-grabber#2372]
**Bug description**

I have activated the option "Do not save" in "if a file already exist globally", but when downloading, if I move those downloads to another place, it re-downloads those images that are already in the global list. 

**Steps to reproduce**

1. I download a group of images.
2. I save those images in other folders.
3. Then I run the same search again to download new images.
4. It also re-downloads the previous images despite having the option "Do not save". 

**Expected behavior**

Skip the previously downloaded images, even if they are not already in the same download folder. 

**Screenshots**

https://imgur.com/a/1rGdX2g

**System information**

- OS: Windows 10
- Grabber version: Grabber Nightly 7.5.1

**Comment by Bionus** [comment]
That's because of  the "If it's in the same directory: Save" setting you have.

If you download the files in some folder, then move them out, then try to re-download them in the same folder, it will check the MD5 list, which will say that the file was already downloaded and in which folder. And since the folders are the same, it will apply the rule for "If it's in the same folder" rather than the "Globally" rule.

In most cases, you want to have both of those setting matching, unless you want to do something peculiar.

**Comment by shiosakun** [comment]
https://imgur.com/a/DdMKlr8

Now I activated both, but still doing the same behavior.
