### ISSUE TITLE
Any way to input a large number of userid's from pixiv into downloads as well as monitoring.

### ISSUE THREAD

**Issue by onmymomma001** [Bionus/imgbrd-grabber#2374]
Im trying to import a large list of userid's from pixiv to download as well as monitor, is there any way that this can be sped up as it is very time consuming considering the load times for each time you search for a userid in the search tab. Any help would be appreciated thanks.

**Comment by Bionus** [comment]
You can't through the UI, but you can edit the `monitors.json` file manually in the settings directory.

**Comment by blackcatemoji** [comment]
I know android has a ton of apps meant just for downloading tons of images
from pixiv. You could always just manually set the user IDs as the save
file names and then tag your fav artists to monitor. I hope that helps 💖

**Comment by blackcatemoji** [comment]
Also, sorry to bother any of you but since I only have a mobile phone I
figured I'd give a tip, if that's what you're also stuck with. Soul Browser
is great for customization and usability (especially when it comes to tabs,
since you can set it to swipe left or right or up to close a tab
altogether) and I find that's the easiest method for opening lots of images
I've bookmarked for later tagging. So if you have a ton of images you want
to tag that's the easiest way you're gonna be able to on mobile.

Also it was the option to download all the image files on a page or let you
select each file individually and so if you really want to download a ton
of images that's another great option.

Hope this helps and sorry I'm normally not included much in email threads
like these. Thank you for your time and I hope you find the
simplest solution for you 🥰💞
