### ISSUE TITLE
"Unable to test" message when tring to login to e621

### ISSUE THREAD

**Issue by AtariPlayer** [Bionus/imgbrd-grabber#2403]
**Bug description**

"Unable to test" error while trying to login with API key

**Steps to reproduce**

1. Go to Sources
2. Click on e621's options
3. Click on Login
4. Try to login with your e621's account

**Expected behavior**

Successful login with synced favorites and etc.

**Screenshots**

![image](https://user-images.githubusercontent.com/86890819/124363635-e2c7ae00-dc55-11eb-8703-ac3ddb92c9f0.png)
.

**System information**

- OS: Windows 10
- Grabber version: 7.5.1

**Comment by Bionus** [comment]
Hello

The login should actually work. It's just that it's not possible to test whether the credentials you entered are correct or not.
In this case, the issue is more that you shouldn't even see the "Test" button in the first place.

> with synced favorites and etc.

Grabber doesn't sync favorites. Grabber's favorites are a separate system 🙂
