### ISSUE TITLE
./Grabber: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by ./Grabber)

### ISSUE THREAD

**Issue by General-Trident** [Bionus/imgbrd-grabber#2404]
**Bug description**

Can't tell whether this is bug or not, but after fixing so many errors and installing all the missing packages, this is what I got.

root@uservm:/home/user/Programs/imgbrd-grabber/release# ./Grabber
./Grabber: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by ./Grabber)

**Steps to reproduce**

1. Go to /home/user/Programs/imgbrd-grabber/release
2. Executte ./Grabber
3. See error

**Expected behavior**

Grabber app running perfectly, I suppose.

**Screenshots**

![image](https://user-images.githubusercontent.com/52889250/124370445-17615700-dca2-11eb-967e-6c2bc530a484.png)

**System information**

- OS: [Linux MInt XFCE]
# uname -a
Linux izzyvm 5.11.0-22-generic #23~20.04.1-Ubuntu SMP Thu Jun 17 12:51:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Li

- Grabber version: [LATEST 7.5]

**Additional context**

This error happens after so many package installing

**Comment by Bionus** [comment]
Any reason you're not just using the AppImage rather than building anything? You wouldn't have to download that many dev packages this way.

In any case, it looks like your installed Qt package is old. Grabber requires a quite recent version, I recommend the 5.15 one. You can find repositories for that here: https://launchpad.net/~beineri

The docs on the website seem to not have this change yet, but you can find the updated compilation docs here:
https://github.com/Bionus/imgbrd-grabber/blob/develop/docs/_docs/compilation.md
