### ISSUE TITLE
adding websites to the list 

### ISSUE THREAD

**Issue by 0d1nAndl0k1** [Bionus/imgbrd-grabber#2449]
how would i add https://realbooru.com to the list every time i do it doesnt work please help

**Comment by SvyraCosmix** [comment]
Yeah doubtful he will add it, I asked for inkbunny to be added but nothing, but extreme picture finder worked for me if you want the cracked download I have and the template for realbooru let me know

**Comment by 0d1nAndl0k1** [comment]
> Yeah doubtful he will add it, I asked for inkbunny to be added but nothing, but extreme picture finder worked for me if you want the cracked download I have and the template for realbooru let me know

Yah sure

**Comment by SvyraCosmix** [comment]
> > Yeah doubtful he will add it, I asked for inkbunny to be added but nothing, but extreme picture finder worked for me if you want the cracked download I have and the template for realbooru let me know
> 
> Yah sure

Simple install setup don' open program yet replace the file in the directory with the one in "fix" folder and this program downloads by pasting the link so if you want to download all the anal images click on the anal tag then copy the link it's pretty straight forward heres the download

https://mega.nz/file/SpggzCQa#fM0MOv1LZo1_jI3VKfE5DWH5jpz-62LyCvqG2N3kOcw

This is the template it tells you how to install it 

https://www.webimagedownloader.com/templates/553-realbooru.com-generic-template/

**Comment by yami-no-tusbas** [comment]
You can add it yourself too, it's tree clicks...
click on : source in the bottom left.
Then : Add, same bottom left.
Enter url : https://realbooru.com/ let "guess" checked
Since the board is a Gelbooru 0.2 it's supported with no more steps. Just select it and browse.

it work : 
`[13:41:43.274][Info] [realbooru.com][Html] Receiving page https://realbooru.com/index.php?page=post&s=list&tags=&pid=42
[13:41:43.276][Info] [realbooru.com][Html] Parsed page https://realbooru.com/index.php?page=post&s=list&tags=&pid=42: 0 images (0), 0 tags (0), -1 total (707868), 16854 pages (16854)
[13:41:43.289][Info] [realbooru.com][Xml] Receiving page https://realbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=1&tags=
[13:41:43.299][Info] [realbooru.com][Xml] Parsed page https://realbooru.com/index.php?page=dapi&s=post&q=index&limit=20&pid=1&tags=: 20 images (20), 0 tags (154), 732772 total (732772), 36639 pages (36639)`

**Comment by Bionus** [comment]
Yes, this is a Gelbooru 0.2 source, so it can be added very easily as said above 👍
