### ISSUE TITLE
Not enough information to directly load the image

### ISSUE THREAD

**Issue by srcdecay** [Bionus/imgbrd-grabber#2459]
I just installed the newest version and it's exhibiting behavior the older versions didn't.  For most files I try to download (more than 75%), the log shows the error message **Not enough information to directly load the image (from blacklist: 0 / from file url: 0 / from filename tags 1/1)** and does not download the image.  It does download some images as long as they aren't on the blacklist or already in the grabbed database, but mostly it throws the above error.

I'm using the same configuration/blacklist I used on the older versions of Grabber and I'm thinking my previous setup conflicts with new features introduced in the newest version, but I can't figure out why.

I don't do anything fancy with file saving like conditionals, etc.  I just have Grabber save images to a specific folder with **%search_1%\\%rating%\\%character%_-%copyright%-_(%artist%)_%md5%.%ext%** as the filename.  I have Grabber shortening file names to 256 characters as to not exceed Windows' 260 character filename limit.

The only thing that's changed about my PC since using the older versions of Grabber is I'm now running the Windows 11 Beta from the insider program.  I am using version 7.6.1 of Grabber.

What causes the issue I'm having and how can I fix it?  

Thank you for any help.  If any more information is needed, just ask.

**Comment by Bionus** [comment]
Those aren't errors (hence the `[Info]`  log level).  This message just means that there is currently not enough information to **directly** load the image, so Grabber will just load the details page first.

This means that when this happens, your log should look something like this:
```
[17:07:59.307][Info] Not enough information to directly load the image (from blacklist: 0 / from file url: 0 / from filename tags: 1/1)
[17:07:59.308][Info] Loading image details from https://...
[17:07:59.448][Info] Loading and saving image from https://... in ...
```

And when loading the details isn't necessary, the log is much simpler (the two first lines disappear):
```
[17:07:59.448][Info] Loading and saving image from https://... in ...
```

In your case, this is very likely because you're using tokens that require typed tag information (character/copyright/artist)  which might not be provided in the "listing" page. This happens for example on Gelbooru.

What source are you using in this case?
And why are you saying that it causes the image to not be loaded at all?
