### ISSUE TITLE
Grabber Keeps Crashing

### ISSUE THREAD

**Issue by d-mmmy** [Bionus/imgbrd-grabber#2465]
**Steps to reproduce**

1. "Get All" on the tag 'lpip' on gelbooru
2. Go to the download's tab to download it.
3. Goes till image 156. Shows a '?' symbol instead of a skip or download symbol.
4. Crashes.

**Additional Context**

Haven't happened with other tags yet. At least like this.
There were also other random crashes, but I don't remember how they happened.

**Files**
[main.log](https://github.com/Bionus/imgbrd-grabber/files/7117053/main.log)
[settings.txt](https://github.com/Bionus/imgbrd-grabber/files/7117078/settings.txt) Had to change file ext to have it uploaded here. Just rename to .ini
[crash_lpip.txt](https://github.com/Bionus/imgbrd-grabber/files/7117084/crash_lpip.txt) Same for this one.

**Screenshots**

https://user-images.githubusercontent.com/44706270/132245143-e4d6cce5-6424-4a91-98e1-3a7769aad6a3.mp4

**System information**

- OS: Windows 10
- Grabber version: 7.6.2

**Comment by yami-no-tusbas** [comment]
You naming scheme is the problem, there is something invalid about it : 

`%artist%/[%md5:maxlength=8%] %rating% - %copyright% %character% - <%search:ignorenamespace=character,rating,artist,copyright% >%general:ignorenamespace=search%.%ext%`

`[10:34:55.611][Error] Unable to open file 'D:\Avatars\lpip\[de6703fc] safe -   - 1girl bangs bare_shoulders blush brown_eyes brown_footwear closed_mouth collarbone dress earrings flower flower_earrings flower_necklace full_body hair_ornament hood hood_down hooded_jacket jacket jewelry knees_up long_hair long_sleeves looking_at_viewer necklace off_shoulder open_clothes open_jacket orange_hair purple_jacket shadow shoes sleeveless sleeveless_dress sleeves_past_fingers sleeves_past_wrists socks solo squatting white_background white_dress white_legwear.png.tmp': La syntaxe du nom de fichier, de rÃ©pertoire ou de volume est incorrecte. (5)`

The filename alone is 497 characters, with the folder you go on more than 500, unless you have specific windows 10 settings for longpath, you may crash because of this. (see : https://www.microfocus.com/documentation/filr/filr-4/filr-desktop/t47bx2ogpfz7.html)

You limit is set to the default of the app (0), making it bigger may work if you do the windows 10 trick for longpath. or you should set it to 260 the max for windows, I also tried your query with the limit and everything downloaded fine. but the names are shortened, if you really need the tags you may wanna remove some with the ignore tag function or save them appart using the separates logs files.
