### ISSUE TITLE
Download presets

### ISSUE THREAD

**Issue by xpscyho** [Bionus/imgbrd-grabber#2467]
**Is your feature request related to a problem? Please describe**

when the software crashes or when I restart or I close Grabber, I lose the list of download groups/images along with the settings per download I wanted to keep for later

**Describe the solution you'd like**

a set of options to make download presets, like a dropdown menu of created presets, a plus button, a minus button, and a duplicate button

- making a new preset clears all the downloads from the list, and as you add stuff to the list, it adds the group/image to the preset
- deleting a preset clears the download list along with the preset from the preset list
- duplicating a preset makes a new preset with the same settings as the original preset, so you can make variations

startup list is empty unless configured otherwise

This would be useful if someone is almost constantly downloading lots of images from different sources and don't want to go through the hassle of setting up the downloads over and over.

I can't necessarily mention other apps off the top of my head that has this enhancement other than Dainapp, a Video interpolation app that can save presets of interpolation settings so you don't have to change them all again every time so you open the software.

A vague comparison would be Adobe Photoshop's Actions, where you record actions in photoshop, when you open the program, open the actions window, select an action and run it, then it does everything that happened in the recording again with the same files.

**Describe alternatives you've considered**
I'm not too familiar with the world of booru grabbers, so I'll assume this means workarounds
- saving them as favourites and running through them one by one, and setting them to download again, then editing the download settings from there again. 
- making a batch script that downloads the images with the correct settings, although I haven't gotten the command line version to work yet.

**Comment by yami-no-tusbas** [comment]
What about monitors ? They are groups you set to do a specific task, like downloading all images for a certain tags, you can set when the search fo new items, if they can or can't re-download an image (using post-filter), they accept multiples tags, save images on the path you want, etc. You still have to set them one by one, but they stay forever in the app. (But you still wanna make a backup of the json file just in case...)

And sadly there is no documentation for them, but t hey are powerfull at setting up list of download that can be triggered manually or on timer.

So simple explaination for making a monitor : 
- Search what you want like when you setup your download, check the board(s), etc.
- Instead of clicking on "Get all" or "Get this page", etc push "Monitor"
- on the monitor tab you will have a new entry, you can right click it to edit it.

You will get three tabs, 
General : with the search, the filters you can add (note that post-filter are on grabber side, not the board side), when it was last checked, a button to edit the sources, for adding or removing sources, interval for the monitor, and delay for the startup.
Notification : send notification to your system.
Download : Here you can set the path and naming scheme for each monitor, or let it empty to use your default ones. You can also force a monitor to get blacklisted item.

The you can let the program do it's thing, or force the start by using "start now". You can change teh displayed column by right-clicking on a column title.

**Comment by xpscyho** [comment]
Closing since inactive and found Save/Load downloads list.
