### ISSUE TITLE
Grabber using 4k+ Memory just opening.

### ISSUE THREAD

**Issue by DarkIsuka** [Bionus/imgbrd-grabber#2491]
When opening the program it will gradually consume more and more memory, usually stopping at around 4-5k, and temporarily freezing the computer before starting up.

Happens every time, starting around the end of September.

**Comment by Bionus** [comment]
Hello, have you been using Grabber for a long time?
If so, you might be using the old MD5 database version that uses TXT files.

You can see that by checking in:
```C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber```

If there's a (big) `md5s.txt` file in there, you should either (after closing Grabber):
* Delete it (global duplicate detection will be reset)
* Delete it then re-generate it in the new format using the "MD5 fixer" tool (in Grabber's "Tools" menu)
* Convert it to SQLITE via the "MD5 database converter" (in Grabber's "Tools" menu)

If that doesn't fix it, I'll need more info such as your logs.
Otherwise, in most cases clearing the whole settings directory and re-installing should solve the issue.

**Comment by Tiffys** [comment]
I had a similar issue, though the memory on mine was only going to about 2.5 GB. My computer didn't freeze, but grabber would take a solid 2 minutes or so to open then go non-responsive for about a minute before closing. Converting the ~38MB md5s.txt to SQLITE generated a 435MB sqlite file, though then deleting the txt results in it being regenerated as a 75MB txt file. The slow opening time and memory usage remains fixed however. Memory usage now is around 15.5MB.

**Comment by Tiffys** [comment]
> Yes you might need to close the program before deleting the file.

Ah yep, that managed to get rid of the txt file. I'm probably not gonna bother redoing the md5 sqlite from scratch since it seems to be working fine. Though tbh I don't *actually* know what that thing even does.
