### ISSUE TITLE
Simultaneously downloading is not working

### ISSUE THREAD

**Issue by cheez95** [Bionus/imgbrd-grabber#2525]
**Bug description**

Simultaneously downloading is not working on downloads.

**Context**

If the reason is obvious I apologize in adance. Not sure if I missed some settings, but Grabber cannot seem to download multiple images at the same time on Gelbooru and Danbooru etc.

**Screenshots**

![Grabber_BFET0CvWtJ](https://user-images.githubusercontent.com/72521605/143015256-a501160f-0a92-44a2-81ac-2070548f9473.png)
![Grabber_SNzOAOr0oF](https://user-images.githubusercontent.com/72521605/143015266-5a4761c6-2ef1-4403-8fc2-29cd7348c197.png)
https://files.catbox.moe/dvpaty.png
https://files.catbox.moe/gs9bja.png

**System information**

- OS: Windows 11
- Grabber version: 7.6.2 (x64)

**Comment by Bionus** [comment]
Hello

This might be a little bit confusing, but this setting page is about "capping". That means that this number applies to many stuff, such as downloads and thumbnails loading, page loading, etc.

However, batch downloads have their own simultaneous downloads, by default at 1, that you can find in the app settings rather than a single source's settings. But if you set the batch simultaneous downloads to a value higher than the site's max simultaneous downloads, note that it will be capped 👍

So unless the source has some strong call limits, you shouldn't really change the "max downloads" from the source's window. I think the default is 10, which is a reasonable value. It can also be used to "override" (but only to go lower, as you can see) the global setting for a given source. The OS and Qt might even have its own open connections limit as well anyway.
