### ISSUE TITLE
grabber downloads gelbooru webm videos as zip archives with all the frames as jpg files

### ISSUE THREAD

**Issue by jack652** [Bionus/imgbrd-grabber#2627]
**Bug description**

when downloading webm videos from gelbooru, grabber downloads them as zip archives with all the frames as jpg files inside them

**Steps to reproduce**

1. find a webm video on gelbooru using grabber
2. download it via grabber
3. it downloads as a zip archive

**Expected behavior**

grabber downloads the webm video

[main.log](https://github.com/Bionus/imgbrd-grabber/files/8364562/main.log)

**Screenshots**

**System information**

- OS: Windows 10
- Grabber version: 7.0.8

**Comment by Bionus** [comment]
The ZIP files you downloaded were not from Gelbooru but Danbooru (as seen in your log file).
This is expected as they are [ugoira](https://www.pixiv.help/hc/en-us/articles/235584628-What-are-Ugoira-), an animation format which is just a ZIP file with all the frames.

When asking Grabber to download original files, Grabber will download the ZIP since those are the original. For those files, if you want an MP4 you'll need to download the "sample" version of the image.
