### ISSUE TITLE
Page results

### ISSUE THREAD

**Issue by JustAnon** [Bionus/imgbrd-grabber#2689]
Is there an option to combine results from multiple pages to one page? or can i somehow jump from page to page when viewing the full images? The number of results i get per page is very low with my blacklisted tags. I'm trying to figure out a fix to this.

**Comment by Bionus** [comment]
There is no way to do this, however what you could do is:
* Increase the number of images per pages (either via the "+" button near the search field, or in the settings, in the "Sources" section)
* Use the "infinite scrolling" feature, so that you don't need to switch pages that often when searching
