### ISSUE TITLE
Monitoring not syncing

### ISSUE THREAD

**Issue by phantazum** [Bionus/imgbrd-grabber#2698]
How do I setup a monitor correctly so that it keeps in sync with tags?
Lets say I have the 1girl tag. Monitor setup for Gelbooru 5 minute interval and download checked. 
Now I come back a week later and it has 5 images it has not downloaded.
Now I have the 2girls tag and the same setup and I come back a week later and its up to date.
I cant find a pattern at all.  I look in favorites and some tags have the red box with new images found and others dont. Again, the same thing, some with the red box are up to date and others not. The tags with no red boxes, some are up to date and other not.  Just seens like its completely random if its going to work or not.

**Comment by Bionus** [comment]
Did you add a delay to your monitors? If you didn't, it could be that the image was not tagged yet when the monitor ran, especially with such short interval.

Also, what do you mean "red box"?

**Comment by phantazum** [comment]
You mean like at start up? I just leave it running, no reason for a delay.

**Comment by Bionus** [comment]
Images uploaded often start without proper tagging with an additional "tagme" tag.

If you monitor new images every 5min, then if an image is loaded but didn't have the proper tags yet, then it won't be downloaded. When it's updated later, Grabber won't re-check them because the monitor is time-based. It only checks all images until the time it ran.

To prevent this, you can add a delay so that Grabber won't check the most recent images yet, and wait some time so that they have some time to be properly tagged.

_PS: I wouldn't personally monitor the "1girl" tag given the sheer amount of images that represent._
