### ISSUE TITLE
Application crashes when opening image

### ISSUE THREAD

**Issue by FroggyFriend** [Bionus/imgbrd-grabber#2728]
I went to use Grabber and it crashes when I try to load an image, this has only started happening recently
The issue seems to happen on older versions of Grabber, at least for me (tested on 7.8.1)

Grabber Version: `7.9.0`
OS: `Windows 10`; Version: `21H2`
Note: I can't upload the `settings.ini` file itself so I put it and the `main.log` in a zip together
[Log&Settings.zip](https://github.com/Bionus/imgbrd-grabber/files/8976483/Log.Settings.zip)

Note: The program crashed but didn't prompt the `CrashReporter.exe`, so unfortunately I can't provide a crash dump.
(Sorry if I didn't provide enough info, if I need to give anything else please let me know!)

**Comment by Bionus** [comment]
Does this also occur when using the [nightly release](https://github.com/Bionus/imgbrd-grabber/releases/nightly)?
It looks a lot like issue #2721.

**Comment by steawth** [comment]
I can personally confirm that the crash occurs on the nightly release. Here is the backtrace for the crash.
![image](https://user-images.githubusercontent.com/99520694/176579394-b699942b-5a61-4ff8-98d4-acec122a33d4.png)
[grabber_crash.txt](https://github.com/Bionus/imgbrd-grabber/files/9015902/grabber_crash.txt)

**Comment by NukeBird** [comment]
Same here

**Comment by Bionus** [comment]
I could indeed reproduce the original crash thanks to the settings file provided by @FroggyFriend. It was caused by having all image window buttons in the drawer.

However, from the stack trace you provided @steawth, it seems you're having a different issue. I couldn't reproduce, but from the impacted line I made a blind fix of what could have been the issue. Feel free to try on nightly and see if the problem is still there.
