### ISSUE TITLE
Using old version for Sankaku Complex source disabled

### ISSUE THREAD

**Issue by ARDEACT** [Bionus/imgbrd-grabber#2770]
I used an old version to batch download Sankaku as I do always. This shirm of a developer disabled the ability to do so, now the client won't connect to Sankaku at all. Thanks a ton. Don't give in to the threats from Sankaku's end, we're going to batch download page-by-page anyways. Sh*ts ridiculous.

**Comment by NEO-SPECTRUMAN** [comment]
and why you still use old version?
last grabber for legacy OS can't grab sankaku by years

**Comment by ARDEACT** [comment]
> and why you still use old version?
> last grabber for legacy OSs can't grab sankaku by years

I’ve been using an old version, i forgot the version number but it’s been working since the release. Just now it stops fetching pages entirely. Either Sankaku’s API changed (which is entirely plausible since the servers and website seemed to went through an overhaul), or this dev for grabber prevents it OTA. I’m thinking the latter, i just wished this developer wasn’t so scared of Sankaku, they really can’t do anything here.

**Comment by Oleksandrigo** [comment]
I didn't update the garbber version, and the sankaku died. So I think the problem is on the sankaku side.

**Comment by Bionus** [comment]
> I didn't update the garbber version, and the sankaku died. So I think the problem is on the sankaku side.

Yes, they must have definitely changed something on their end, breaking the old integration.

> This shirm of a developer disabled the ability to do so, now the client won't connect to Sankaku at all. Thanks a ton.
> or this dev for grabber prevents it OTA. I’m thinking the latter, i just wished this developer wasn’t so scared of Sankaku, they really can’t do anything here.

And why would I even bother with OTA updates for old versions, when they're not even implemented yet on the current version? Given you can see the whole [change history](https://github.com/Bionus/imgbrd-grabber/commits/master) since Grabber is open source you'd  know your accusation is baseless, and if that's how you ask for help with your problem I have bad news for you. I'm not in kindergarten anymore so stuff like "you scared?" isn't gonna work on me.

Especially given how easy it is to edit sources (so in this case, fix it), just by editing a single JS file.

_PS: using an old version is not necessary, recent versions still support "old" source files._

**Comment by ARDEACT** [comment]
> > I didn't update the garbber version, and the sankaku died. So I think the problem is on the sankaku side.
> 
> Yes, they must have definitely changed something on their end, breaking the old integration.
> 
> > I found a problem, now you can't upload more than 50 pages without SankakuPlus and it causes an error
> 
> You mean browse after page 50? This would definitely be an issue for batch downloads 😅
> 
> > This shirm of a developer disabled the ability to do so, now the client won't connect to Sankaku at all. Thanks a ton.
> > or this dev for grabber prevents it OTA. I’m thinking the latter, i just wished this developer wasn’t so scared of Sankaku, they really can’t do anything here.
> 
> And why would I even bother with OTA updates for old versions, when they're not even implemented yet on the current version? Given you can see the whole [change history](https://github.com/Bionus/imgbrd-grabber/commits/master) since Grabber is open source you'd know your accusation is baseless, and if that's how you ask for help with your problem I have bad news for you. I'm not in kindergarten anymore so stuff like "you scared?" isn't gonna work on me.
> 
> Especially given how easy it is to edit sources (so in this case, fix it), just by editing a single JS file.
> 
> _PS: using an old version is not necessary, recent versions still support "old" source files._

I’ve been resenting your decision to implement the files for Sankaku to be deleted if it’s not read only, even then I still have problems with latest versions, the old versions worked “flawlessly”.

**Comment by Bionus** [comment]
> I’ve been resenting your decision to implement the files for Sankaku to be deleted if it’s not read only

This was only on v7.2 for the transition (cf 21cc7ea3f313bdf52684841eba9c8be0c2e89e23). I just tried it out and they are not deleted.

Once again, the program is open source so you can see the code for the installer here:
https://github.com/Bionus/imgbrd-grabber/blob/master/scripts/windows-setup/setup.iss

As you can see,  there's 0 mention of "Sankaku" anywhere, be it to add it or remove it.

**Comment by NEO-SPECTRUMAN** [comment]
> Especially given how easy it is to edit sources (so in this case, fix it), just by editing a single JS file.
> 
> _PS: using an old version is not necessary, recent versions still support "old" source files._

XP droped before grabber has moved to JS...

but now one core api can run ~latest Grabber on XP
in other hand one core api is very unstable
and for now installing it on main system is bad idea...

**Comment by ARDEACT** [comment]
It's not that you can just loophole around the issue, it's that you're no longer supporting using Sankaku. Therefore, the issue with the sites API will never be fixed.

**Comment by Bionus** [comment]
> XP has droped before grabber moved to JS...

Yes, but XP is not supported by anyone for more than 10 years now, so I'd say it's fair for me to drop support 😅
https://docs.microsoft.com/en-us/lifecycle/products/windows-xp

Not sure why you'd keep using it, although I'm sure you have your reasons.
XP support has been dropped in more recent versions of Qt, on which Grabber is based. In Qt 6 they even dropped support for x86 (32-bit), which is the only reason I haven't migrated Grabber to it yet.

> It's not that you can just loophole around the issue, it's that you're no longer supporting using Sankaku. Therefore, the issue with the sites API will never be fixed.

Grabber supports sources via user-editable JS files, in the same way most browsers support "extensions" or "modules". It's actually all documented here, so anyone can go and implement new sources (or fix existing ones in this case):
* [General documentation](https://bionus.github.io/imgbrd-grabber/docs/sites/source.html)
* [Step-by-step example](https://bionus.github.io/imgbrd-grabber/docs/sites/source-example.html)
* [Source registries](https://bionus.github.io/imgbrd-grabber/docs/sites/source-registry.html)

I'd even gladly support anyone asking for help on how to implement or edit an existing source here or on Discord, as I believe user-generated sources are the future of Grabber (which is why I added source registries recently).

**Comment by NEO-SPECTRUMAN** [comment]
> by anyone

who is "anyone"?

10 years ago XP drops only M$ZOG henchmans
and only after 2018 it drops "anyone" with vista in same time...

**Comment by Bionus** [comment]
Well, yes. There are no more official updates to XP since 2014, as far as I know. Maybe a few private companies still have some off-network XP machines, but otherwise it's an unsupported system.

And just like Grabber doesn't support Windows 2000, it doesn't support XP. If you're still using XP, I highly doubt this is the only software you can't use. Many software also dropped x86 support for a while as well.

So while you must have your reasons for running an outdated system, since Qt doesn't support it, Grabber doesn't either.

**Comment by ARDEACT** [comment]
> > XP has droped before grabber moved to JS...
> 
> Yes, but XP is not supported by anyone for more than 10 years now, so I'd say it's fair for me to drop support 😅 https://docs.microsoft.com/en-us/lifecycle/products/windows-xp
> 
> Not sure why you'd keep using it, although I'm sure you have your reasons. XP support has been dropped in more recent versions of Qt, on which Grabber is based. In Qt 6 they even dropped support for x86 (32-bit), which is the only reason I haven't migrated Grabber to it yet.
> 
> > It's not that you can just loophole around the issue, it's that you're no longer supporting using Sankaku. Therefore, the issue with the sites API will never be fixed.
> 
> Grabber supports sources via user-editable JS files, in the same way most browsers support "extensions" or "modules". This is how you are able to have it working so far. If it was totally built into the code, you wouldn't be able to simply drag and drop old sources and have them working on recent versions.
> 
> It's actually all documented here, so anyone can go and implement new sources (or fix existing ones in this case):
> 
> * [General documentation](https://bionus.github.io/imgbrd-grabber/docs/sites/source.html)
> * [Step-by-step example](https://bionus.github.io/imgbrd-grabber/docs/sites/source-example.html)
> * [Source registries](https://bionus.github.io/imgbrd-grabber/docs/sites/source-registry.html)
> 
> I'd even gladly support anyone asking for help on how to implement or edit an existing source here or on Discord, as I believe user-generated sources are the future of Grabber (which is why I added source registries recently).

Could you manage to get it working on your end, I'm afraid if Sankaku implemented some sort of protection against software like this, it would just be a waste of time for me to learn and set up a new site if it doesn't even work.

**Comment by NEO-SPECTRUMAN** [comment]
> There are no more official updates to XP since 2014

SO WHAT?
How does this relate to open source community?


about sankaku i tryed 7.6.2
and looks like it removed from support list
no wonder
sankaku all time resist to avoid mass download
and now most part of content is for registered users only...

**Comment by NEO-SPECTRUMAN** [comment]
> since Qt doesn't support it, Grabber doesn't either.
its degrading for XP
without changing Qt

7.6.2
![2022-08-01_005437](https://user-images.githubusercontent.com/88002487/182046882-9ec21ff5-c6b7-4bb2-8f62-5237dd1c3c0d.png)

7.7.1
![2022-08-01_005303](https://user-images.githubusercontent.com/88002487/182046889-37463cce-9192-4152-8a57-ea0870eef060.png)

**Comment by ARDEACT** [comment]
> > There are no more official updates to XP since 2014
> 
> SO WHAT? How does this relate to open source community?
> 
> about sankaku i tryed 7.6.2, 7.7.1, 7.8.1, 7.9.1 and looks like its removed from support list and no wonder sankaku all time resist to avoid mass download and now most part of sankaku content is for registered users only...

Sankaku has always worked but I wanted to use the old version just because I didn't want to deal with the auto delete issues. The site folder just had to be copied over to a newer version. But that isn't the issue, the issue is that Sankaku's website has made some changes that fixed the 404, wrong thumbnail and loading issues that's been happening this year, which is great, but it also means that Grabber at the moment doesn't work.

**Comment by NEO-SPECTRUMAN** [comment]
there is any sankaku on 7.5.1

**Comment by ARDEACT** [comment]
> there is no any sankaku on 7.5.1

I forgot which version but it does come with the Sankaku site folder. But it doesn’t matter because it doesn’t work. I have yet to see if Bionus can get it working.

**Comment by NEO-SPECTRUMAN** [comment]
7.1.1 has sankaku
but ripper script is outdated
and doesn't works....

**Comment by HanatakeYurii** [comment]
(Can we please get back to the issue? XP was great but it's definitely not worth nor relevant to argue since it has been outdated for a long time)

Concerning the drop of native support of Sankaku, some years ago the owner battled against multiple software accessing his site that he doesn't manage to limit on his own end (yes, his fault, but whatever...). Grabber was one of the targets and as I recall Bionus decided to drop official support to avoid useless quarrels (Sankaku is known to be on the blinkered side).

But as Bionus said it's an open-source software that bet on user created scripts to expand on any image-board, so users are free to do so. Using the old script is definitely a starting point to repair it if possible, but not the remedy on itself, nor saying it's not worth trying.

So far, to fix it, what I found is that the login no longer works in Grabber, but it does work on browser, so my guess is something has been changed there. No cookie helped at all, thus it doesn't seem relying on those. I have yet to read the documentation and example kindly provided by Bionus but I will try to fix it (hoping I can figure it out).

**Comment by Bionus** [comment]
For what it's worth, I just tried using [this model.ts file](https://github.com/Bionus/imgbrd-grabber/blob/develop/src/sites/Sankaku/model.ts) and it was working fine.
Although it needs to be compiled in JS for it to work in Grabber.

**Comment by ARDEACT** [comment]
> For what it's worth, I just tried using [this model.ts file](https://github.com/Bionus/imgbrd-grabber/blob/develop/src/sites/Sankaku/model.ts) and it was working fine (using the JSON source only). Although it needs to be compiled in JS for it to work in Grabber.

I don't know how to do that.

**Comment by NEO-SPECTRUMAN** [comment]
> with the latest update

with the latest SANKAKU update

**Comment by Oleksandrigo** [comment]
> with the latest SANKAKU update?

Yes. Now it outputs the same thing for date:01/01/2021 order:quality and date:01/02/2021 order:quality queries. However, if you change the first digit, the pictures change...

**Comment by ARDEACT** [comment]
Has someone compiled his model.ts to JavaScript yet?

**Comment by ARDEACT** [comment]
> > Has someone compiled his model.ts to JavaScript yet?
> 
> Not sure if I did it right but I copied his model.ts code and compiled it thru an online javascript compiler, renamed it to model.ts and replaced with original file after backup. It still did not work.

Yes i tried that but it doesn't show up in sites. Not sure why Bionus is reluctant to create a working version.

**Comment by Vixal** [comment]
`
[model.zip](https://github.com/Bionus/imgbrd-grabber/files/9245025/model.zip)
`
Replace model.js in sites\Sankaku with attached file for json version to work, json version requires you to set edit sankaku settings in grabber  and set source to json and login to oauth. Then fill username and password

**Comment by ARDEACT** [comment]
> `[model.zip](https://github.com/Bionus/imgbrd-grabber/files/9245025/model.zip)` Replace model.js in sites\Sankaku with attached file for json version to work, json version requires you to set edit sankaku settings in grabber and set source to json and login to oauth. Then fill username and password

Awesome, it works. Thanks a billion

**Comment by ARDEACT** [comment]
Actually, I finished my batch download and I realized that tags aren't working for everything. My tag format goes as follows: %artist% %copyright% %character% %md5%.%ext%
and it didn't pick up any of it

**Comment by Vixal** [comment]
[model.zip](https://github.com/Bionus/imgbrd-grabber/files/9245240/model.zip)
Try this version by oleks, seems to be a bug with with automatic tag matching using tag-types.txt

**Comment by ARDEACT** [comment]
> [model.zip](https://github.com/Bionus/imgbrd-grabber/files/9245240/model.zip) Try this version by oleks, seems to be a bug with with automatic tag matching using tag-types.txt
Worked great, thanks again. Hopefully no issues arise later, closed and solved.

**Comment by Tenome** [comment]
> `[model.zip](https://github.com/Bionus/imgbrd-grabber/files/9245025/model.zip)` Replace model.js in sites\Sankaku with attached file for json version to work, json version requires you to set edit sankaku settings in grabber and set source to json and login to oauth. Then fill username and password

I added this, and while it gives me a Success! response and clicking on the URL in the search results opens the window with the searched tag correctly, none of the image results are displayed within Grabber (it says "no result"). Any idea how to fix that?

**Comment by D4RKN35547** [comment]
I replaced the json file. Go to sankaku option and set the sources  to Json, don't see the option to set login to auth. Images are loaded now but can't login when filling the form. Click test and it says failed every time. Any idea?

**Comment by HanatakeYurii** [comment]
Please take care to use [](<https://github.com/Bionus/imgbrd-grabber/files/9245240/model.zip>) from the latest messages and not [](https://github.com/Bionus/imgbrd-grabber/files/9245025/model.zip) as bugs are encountered with that one.

**Comment by Reberebe** [comment]
First of, thanks for the reply and apologies for taking so long 
was just trying to replace the model but inside the sites folder there isn't any "Sankaku" folders for me to replace the model with, 
While in the grabber application chan.sankaku remains selected and my login info remains there from the past
