### ISSUE TITLE
Increase filename limit for both classic and javascript filenames

### ISSUE THREAD

**Issue by rgnski** [Bionus/imgbrd-grabber#2805]
The filename limit is pretty good but not long enough for very complex filenames, especially when javascript is used. Could you please increase the limit on the filename to at least a million characters, or remove the limit altogether? If there are performance penalties there is no worry because a good filename saves time. If this change would impact general usage then making it an option would help, like "remove filename limit" or "set filename limit to ____ characters"

Long javascript would enable some cool things!

places impacted:
Options then Save then Filename. 
The Destination pane on the left side.

**Comment by Bionus** [comment]
Hello, I guess you're using Windows?
The filename limit is set to 260 by default because that's Windows' filename limit unless you have long paths enabled: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry.

If you _do_ have long paths enabled or want to bypass Grabber logic, there's already a setting in Grabber (in the "Save" settings) to set the max limit. Setting it to 0 will use the default value (`MAX_PATH` on Windows, 255 on other platforms), but you're free to set it to 99999 or similar.

**Comment by rgnski** [comment]
I think I was confusing, sorry!!

The limitation I was talking about is not with the OS but with the code you can use to make the program determine the file name from tags and other meta data. It is the input that takes the tokens from here [https://bionus.github.io/imgbrd-grabber/docs/filename.html](https://bionus.github.io/imgbrd-grabber/docs/filename.html). The input cuts text off after about 50 thousand characters. Both "classic naming" and "javascript" naming forms have this problem. Test this by pasting over 100 thousand characters into the file name parser and it will be cut off when saving it. It is hard to do complex javascript involving meta data because the limit is too small.

the places impacted again:
Options then Save then Filename.
The Destination pane on the left side.

I am trying not to be confusing this time! Thanks for your help!
