### ISSUE TITLE
Order of images in the favorites tab.

### ISSUE THREAD

**Issue by Moizevitch** [Bionus/imgbrd-grabber#2810]
Hello. 

I'm a Grabber user, and first of all, I'd like to thank and congratulate you for the program. Fantastic! 

This is not a issue, just a question. I apologize for the likely use of the wrong place. I didn't see where to post my question among the three options, it was what I found most viable.

I have just one question at the moment: to add a search to favorites, just position the mouse over the search field, right-click, and add to favorites. Okay, I already do that. However, the image that goes, is always the first of the images that appears in the window (Please, see the image below). What if I wanted the second or fifth image, for example? Is there any way to choose which image I want to be represented in Favorites? 

![search-basic](https://user-images.githubusercontent.com/80647507/192867791-fa533ddb-045d-4923-ac2e-1cb946e9ff74.png)

This is my doubt. Thank you very much for your attention, and, perhaps, for your help!

**Bug description**

**Steps to reproduce**

**Expected behavior**

**Context**

* Provide your `main.log` file to see if any obvious error occurred.
* Providing your `settings.ini` file will greatly help maintainers reproduce your problem if it may be caused by your configuration.
* If the bug occurred during a download, make sure to provide said download as an `.igl` file that Grabber can generate by clicking the `Save` button of the `Downloads` tab.

Note that both `main.log` and `settings.ini` files can be found in `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber` in Windows, and in the installation directory on Linux.

**Screenshots**

**System information**

- OS: [e.g. Windows 10]
- Grabber version: [e.g. 6.0.3]

**Additional context**

Add any other context about the bug report here.

**Comment by TeKett** [comment]
If open up a image you can favourite the tag and get that image as the thumbnail directly. 

There are 3(?) ways you can change the thumbnail.
1. By right clicking the tag after opening up the image you want, there is a new option called "set as image". 

2. After clicking on a favourited tag, under the favourites tab, so it shows the images you can right click one and set the thumb there. You have to change last seen to see older images then when you favourited/last clicked on it (no idea why, ask bionus).

3. By right clicking the favourited tag and specifying the image path.

**Comment by Moizevitch** [comment]
@TeKett, I am very grateful for your time in trying to help me on this matter. 
Unfortunately I must say it didn't bear fruit. Lol. 
I tried to follow your directions and... nothing. 🤷‍♂️
Well, I'll try more in the future and see what happens. 
I must have done something wrong, maybe. 
But, thanks for your help anyway. 
Thank you very much! 👍

**Comment by TeKett** [comment]
You mean the image doesn't change? or that it is blank? I dont use the favourites, since imo its kinda bad. 

When i tested, it downloads the thumbnail to the thumbnail folder, and correctly swaps them out when you change, but the file path never gets set or in turn stored in the .json. Probably a bug in latest or recent version, since it used to work, but more should have complained by now so its probably on my end.

**Comment by TeKett** [comment]
I have latest version. so if you have the same issue then its more likely to be a bug, and not something else.
![Screenshot_82](https://user-images.githubusercontent.com/64377023/194260229-b176210b-6da4-4d37-b2c4-2619fb3d0e1c.png)
![Screenshot_83](https://user-images.githubusercontent.com/64377023/194260252-0bf4f2de-8fee-4006-8a52-d132ae694042.png)

**Comment by riso38** [comment]
Hello, dm seve.services on instagram for really good grabber. trust me.

**Comment by Moizevitch** [comment]
Thank you @TeKett for your dedication to trying to help me! Much appreciated! 🙏🙏🙏
Well, I don't know which program or version you are using. 
I'm using the one in the image. 
In other words, I have no idea how you got this context menu, because when I right-click on the image or on the favorites tab, that's what happens in the images below. 🤷‍♂️
So, I understand why I can't get what you patiently explained to me. 
I don't think it's a bug issue, do you agree? 
Ah, I'm using the program on the updated Windows 10, ok? Maybe, somehow, this helps. 
Thanks!👍
  
![001](https://user-images.githubusercontent.com/80647507/194591312-04795c98-a2a4-4f0f-b42d-42516d3a3b94.jpg)

![002ff](https://user-images.githubusercontent.com/80647507/194591337-bb62f8ce-56bd-47c0-b1c2-424f9e0e094f.jpg)

![003](https://user-images.githubusercontent.com/80647507/194591349-22c27912-ec5f-4643-a5d7-bf84d41a5eac.jpg)

**Comment by Bionus** [comment]
The methods suggested by @TeKett should work (thanks for it BTW 😄).

His screenshot would be from the favorites tab, when opening one. Then, in the results, you'll have this "Choose as image" context menu option (note that this option needs a restart for the image change to take effect due to a bug):
![image](https://user-images.githubusercontent.com/882719/196033375-8b502fea-ba8c-497f-aad4-2dfe4f1da1ca.png)

Otherwise, you can also find it by opening any image containing the tag in question, then right-clicking the favorite tag in the tag list:
![image](https://user-images.githubusercontent.com/882719/196033437-c2463807-b92a-4d5e-b522-2629a36a8d26.png)

The last option is to simply click "Browse" in the favorite's settings (which you can open by right clicking a favorite in the favorites tab) and choose any image to use:
![image](https://user-images.githubusercontent.com/882719/196033483-57da7fe4-96ae-40bf-ab65-0cd02f85caa5.png)
