### ISSUE TITLE
Is there a blacklist limit?

### ISSUE THREAD

**Issue by kanti852** [Bionus/imgbrd-grabber#2811]
I have a number of tags in my blacklist by default. I wanted to do a search for all posts with the "animated" tag on Danbooru, but I already have a collection of those from previous seraches. I added all the character and copyright tags from previous searches to my blacklist so that I don't download them again, and when I try to do a search I get no results, and under that it says "Possible reasons: all images filtered".

My only guess is that there is a limit to how much the blacklist can hold. Is there another explanation?

**Comment by TeKett** [comment]
My guess is you have some blacklists that should not be there. I use blacklist as favourite since its quicker, and i wrote a simple program to generate monitors based on the tags in the blacklist. I have 12000 tags blacklisted. Its easy to add wrong tag and hard to trouble shoot it.

You can use "grabber" filters in the post filter bar, eg. -grabber:downloaded. In the settings you can pick what happens if a image is already downloaded when saved.

**Comment by riso38** [comment]
Hello, dm seve.services on instagram for really good grabber. trust me.

**Comment by brazenvoid** [comment]
Best to uncheck ignore images for blacklisted tags in options and then load the search. That way you will be able to narrow down the offending tags. They will be shown in grey colour on image window.

**Comment by Bionus** [comment]
The suggestions above are both correct. You can also check in the log tab (or the "main.log" file in the settings directory) to see which images were filtered, and why.

In any case, there is no limit to how many entries you can put in your blacklist, but it can indeed cause all results to get filtered, since the blacklist is applied after loading results.
