### ISSUE TITLE
Question: What does preciseCumulated parameter do in monitor.json? 

### ISSUE THREAD

**Issue by gotr3k** [Bionus/imgbrd-grabber#2950]
As the title says i'm wondering what does preciseCumulated:[true/false] do. It's found in the monitor.json file.

**Comment by Bionus** [comment]
It's whether the "cumulated" value contains the exact value of images since last check, or just a minimum number of values.

For example, if you just want a notification when new images arrive, and suddenly there's 3 new pages of images (let's say 50 images with 20 per page), Grabber doesn't need to load all pages to notify you. So it can just load the first page, notice all the images are new, then mark the monitor as "20+ new images" and notify (precise = false).

On the other hand, in the case of downloading monitors, it'll need to load all pages to add all images to the download queue. Then it would say "50 new images" (precise = true).

Doesn't really matter much, IIRC both of those are only used for the counter in the favorites tab.

**Comment by gotr3k** [comment]
Gocha, thanks for the explanation
