### ISSUE TITLE
[Question] Downloading Pixiv Galleries

### ISSUE THREAD

**Issue by NicolasMcGhee** [Bionus/imgbrd-grabber#2958]
Is there a way to download galleries without opening a new tab for each? 

Just wondering if I'm just missing something since whenever I try to get all, it just gets the first image, but by going directly to the galley page, I'm able to get the rest—just asking to see if I'm not knowledgeable of a more streamlined and convenient option.

**Comment by Triramama** [comment]
I have the same question when mass downloading from pixiv, with artworks that have several slides only the first image gets downloaded, or more accurately the other ones are ignored automatically because the program assigns to all slides exact same names, I'm not sure how to make this thing use different filenames for such a case

**Comment by NicolasMcGhee** [comment]
Tested a couple of ways and it works with position when using get selected and assuming get all. It needs something like position or else it'll skip some. Thanks a lot, considering how powerful this program can be with how much it can automate, I knew I had to be missing something, especially the smallest details.

**Comment by Bionus** [comment]
Glad to hear it worked 😄
Pixiv is a bit needy sometimes since it was definitely not designed with tools like this in mind.
