### ISSUE TITLE
I have a list of artists that I want to batch download

### ISSUE THREAD

**Issue by metasl4ve** [Bionus/imgbrd-grabber#3049]
I originally wanted to script the whole list into the favorites json and then automatically download them with monitors, but I realized that you have to click on every single favorite and manually monitor them. 

Is there a way I can upload the list of artists and grabber will go line by line downloading each one?

Obviously I'd like to avoid typing in thousands of artists names in the search bar and downloading them all one by one.

**Comment by Bionus** [comment]
> I originally wanted to script the whole list into the favorites json and then automatically download them with monitors, but I realized that you have to click on every single favorite and manually monitor them.

Favorites do have a monitoring feature, you can see it by right clicking them, there's an automated monitoring tab:
![image](https://github.com/Bionus/imgbrd-grabber/assets/882719/548b1868-23d5-4821-af11-4226b4850da3)

You could also just directly use monitors as well, and script your list into `monitors.json` instead of `favorites.json`:
![image](https://github.com/Bionus/imgbrd-grabber/assets/882719/7fc29501-a280-4215-a121-b948d3a65a76)

If you really have thousands of them, make sure to use reasonable intervals if you don't want to get ip-banned.
