### ISSUE TITLE
[win10/szurubooru compat] getting error when trying to upload

### ISSUE THREAD

**Issue by CrewMonk33** [Bionus/imgbrd-grabber#3056]
I'm using the portable version of grabber and have installed szurubooru, which is working fine right now, can upload etc... All that on windows 10. But now that I try, following your indications, to set everything up to upload on szuru, not only does the soft gives me a log saying "error 1080 couldn't find axios" even though it is installed locally (could this be that the instance of grabber I'm running is on another disk ?), but when I test the js file again in another folder (without grabber, directly with nodejs console), it throws an error. Here's a screenshot of it :
![Capture](https://github.com/Bionus/imgbrd-grabber/assets/148660809/9e13a99c-113e-44ea-be68-ff76cbb90e71)
This test was made without grabber.

**Comment by SpaghettiMonkey** [comment]
had to create another account because couldn't access my account, took me two weeks and this issue (https://github.com/Bionus/imgbrd-grabber/issues/2886) to figure out I just needed to replace "localhost" in the script url with the actual ip for grabber to be able to get to the api (I have no idea why 0_0 but seeing as typing localhost instead of 127.0.0.1 on firefox seems to force me to use ssl and as I have no certificate or anything related set up on szurubooru, the reason I can't access via localhost may be because localhost means ssl apparently)

**Comment by Bionus** [comment]
I'm not quite sure I understood everything, but glad you managed to solve your issue 😅 

Although if you feel there's anything unclear in the [Szurubooru docs](https://www.bionus.org/imgbrd-grabber/docs/commands/szurubooru.html), feel free to say so!
Although I think this part could have helped you?
> If your Szurubooru instance is not on the same machine as Grabber, or simply not accessible at http://localhost:8080/, make sure to update the URL in the script.
