### ISSUE TITLE
Remux WebM to MP4

### ISSUE THREAD

**Issue by ProtagNeptune** [Bionus/imgbrd-grabber#3092]
Maybe add the option "Remux WebM to MP4" in the Filename below "Replace JPEG by JPG"?
![image](https://github.com/Bionus/imgbrd-grabber/assets/93203147/1e01b9d1-04af-4127-8a90-d917894cb1d8)
https://stackoverflow.com/questions/18123376/webm-to-mp4-conversion-using-ffmpeg/60443156#60443156

This will also solve [ExifTool being incompatible with WebM](https://exiftool.org/#supported) for adding metadata to the downloaded videos in Grabber.

**Comment by Bionus** [comment]
Just pushed a commit to implement this. The setting is in "Save > Format conversion" and requires `ffmpeg` to be present somewhere in the PATH where Grabber can find it.

![image](https://github.com/Bionus/imgbrd-grabber/assets/882719/12edee4d-592c-456b-831e-cae263f1ed5e)

Note that it has one drawback however: the files will be properly detected if you use a MD5 list, as the remuxed path will be stored in the MD5 database, but they won't be found without it. Because if you use `%ext%` to check if the image exists on the disk, it will search for "webm" files, but those won't exist. Working around this would be a quite extensive change, so for now I believe it should be fine.

**Comment by ProtagNeptune** [comment]
I'm wondering if this happens before applying metadata.
So that the ExifTool can apply the metadata to the remuxed mp4?

**Comment by ProtagNeptune** [comment]
> Note that it has one drawback however: the files will be properly detected if you use a MD5 list, as the remuxed path will be stored in the MD5 database, but they won't be found without it. Because if you use `%ext%` to check if the image exists on the disk, it will search for "webm" files, but those won't exist. Working around this would be a quite extensive change, so for now I believe it should be fine.

Maybe add a flag in the MD5 database that this file was "converted" to "mp4"?
So that when searching for it, it finds the "webm" files with the "converted" flag set to "mp4" so it checks if there's an mp4 of that file.
