### ISSUE TITLE
Add "booru.allthefallen.moe" as a "Danbooru (2.0)" source to Grabber.

### ISSUE THREAD

**Issue by ProtagNeptune** [Bionus/imgbrd-grabber#3228]
That's a standard "Danbooru (2.0)" source, so you can add it manually.
https://bionus.github.io/imgbrd-grabber/docs/sites/

Since it's a fork, it won't be recognized automatically with the "Guess" feature, but you can simply enter the site type yourself.

_Originally posted by @Bionus in https://github.com/Bionus/imgbrd-grabber/issues/1826#issuecomment-564150790_

**Comment by Bionus** [comment]
I just tried, and it managed to guess it properly. I guess I remembered wrong when I posted this comment, since clearly support for this source was explicitly added already 😄 

https://github.com/Bionus/imgbrd-grabber/blob/8497191a8a56894419d73dc25258ad1d31fd7c32/src/sites/Danbooru%20(2.0)/model.ts#L419-L424
