### ISSUE TITLE
HTTPS where available

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Bionus/imgbrd-grabber#368]
As far as I can see, Grabber uses plain HTTP to access web. Please make it possible to switch to HTTPS instead (incl. from command line). Danbooru at least supports HTTPS access.

It is more private (what if I don't want my provider to know what I'm doing on the net, with targeted ad companies buying the info) and there's less chance password will be stolen (admitted, who cares about stealing Danbooru accounts, but still).

> Original issue reported on code.google.com by `himse...@gmail.com` on 1 Feb 2015 at 7:24

**Comment by himselfv** [comment]
1. May not be fully working (or I'm doing something wrong). Grabber 4.2.2, the only enabled source is "danbooru.donmai.us", default settings + "Use a secure connection (https)". No login or password.

Issue a search query: "rating:safe".

Captured by Wireshark:
HTTP GET /posts?login=&password_hash=&limit=50&page=1&tags=rating%3Asafe HTTP/1.1
HTTP GET /posts.xml?login=&password_hash=&limit=50&page=1&tags=rating%3Asafe HTTP/1.1

So it seems it would have sent login/pass in plaintext.

The querying of actual images goes through HTTPS like it should.

**Comment by himselfv** [comment]
I think I've found the root of the problem.

When `Site::getAllSites()` in sites.cpp loads the URLs it prepends the protocol like this:
```
QString lineSsl = QString(settings.value("ssl", false).toBool() ? "https" : "http") + "://" + line;
_prependUrl(&details, lineSsl, "Urls/"+sr+"/Tags", "Urls/"+QString::number(j+1)+"/Tags");
```

(after that the url is passed unchanged to Page() which runs parseUrl() -> fixUrl() on it but it's too late, fixUrl() doesn't change explicitly set protocol)

The problem is that `settings` in this context is a global settings.ini, not this site's settings. There's no global ssl flag, so this is always false, and all site URLs (Home, Tags, Pools) end up being `http:\\`s.

There's `sets` slightly above, which is maybe what's needed:
```
QSettings sets(savePath("sites/"+dir[i]+"/"+line+"/settings.ini"), QSettings::IniFormat);
```

If so, the proposed fix is to change `settings` to `sets`.

-----

There's another point where plain http is used: in `Site::loadTags()`. Perhaps it needs `fixUrl()` too instead of hardcoded `http`?

-----

Login and loadTags aside, all page/pool/image requests seem to end up in `get()` or `getAsync()` and both in turn call `makeRequest()`. Maybe it's possible to just do something like this in `makeRequest`?

```
if (m_settings.value("ssl", false).toBool() && (url.scheme() == "http"))
{
  url.setScheme("https");
}
```

As a sort of catch-all net. This breaks the case where otherwise https-enabled source has one request that just has to be in plain http, but are there such cases?

**Comment by Bionus** [comment]
Indeed, everything you say is right, so I replaced the `settings` (global) by `sets` (site-related), and forced SSL on all requests if set so.

Thanks :+1:

> This breaks the case where otherwise https-enabled source has one request that just has to be in plain http, but are there such cases?

Since mixed content is now blocked by major browsers, I highly doubt so. Even so, I think it should be blocked, as it breaks the meaning of using SSL.

**Comment by himselfv** [comment]
It works! Thank you for spending your time to implement this! :)
