### ISSUE TITLE
[REQ] exhentai.org / g.e-hentai.org support

### ISSUE THREAD

**Issue by Gummar** [Bionus/imgbrd-grabber#383]
Before some time, the galleries from those imageboards could be downloaded through nekopaw (https://code.google.com/p/nekopaw/), then, the owner of the imageboard updated those two imageboards with a new layout, one that can't be recognized by nekopaw, good, I reported the issue to the nekopaw's developer, but it's developer has disappeared for 2 months with no message, I don't know when he is going to come back and if he will, I'm requesting that you add support for those two websites on your program, as the website is very popular.

**Comment by Bionus** [comment]
Hello,

The problem with gallery boards such as the two you suggested (or 4chan and many others) is that they do not use the same system as the other boards currently compatible with Grabber, as they are gallery-based.
I don't know Nekopaw very well, but what would you suggest for Grabber to add this? The best solution I see is to load all first thumbnails (gallery thumbnail) and when clicking on them, instead of opening a new window (which would usually contain an image's tag and full size image), loading some kind of pool tab which will then list all of the gallery's images.

**Comment by Boxmanbr** [comment]
Well, the way nekopaw loads the images from exhentai is pretty close to the following manner, may be missing info as I don't know if there is anything "tricky" to do:

1) Connect to the site with an auth cookie to bypass sadpanda image.
2) Check galleries links added in search box or search results (will require link / tag recognition or a switch indicating whether if it is a link or tags to search).
3) Load a gallery page (I mean a group of 20 images) and save a link to each individual image page and advance to each individual group. Direct links to images have a timestamp generated, so I guess you will have a time limit to download the images directly, only load the direct link before needing to download the images, I can guarantee the time limit is higher than 5 minutes, although it can be much higher than it.
4) Load the image page to get direct link, when selecting the images to download, there should be an option to download full size images (nekopaw grabber said those full images costs GP, not sure if it only costs GP if the user downloading actually has GP, I only had credits and I never noticed any credit loss, credits and GP are two different currencies for exhentai) or exhentai rescaled images (only exists if the full size images resolution exceeds a certain number and always are of jpeg/jpg extension, otherwise, the full sized image will be placed in it's place and no link for "Download original * x * *.* MB source" will appear, here the image can be another format and won't cost any GP), images that you will load first (the ones that aren't in those download original image links) will always be downloaded from Hentai@Home users, because of that, the image download counter (explained in "Other info:") wont increase and may not cost any GP, if using the download original image button, it can cost GP and will be counted in the image download counter.
5) Download the image after getting the direct link, if for some reason there is a error, go back to step 4. Part of "Other info:" goes in this step.

Other info: 
http://g.e-hentai.org/home.php , this link have a button that can be used to reset image download counter, there is a limit of images to download for a interval of time, it says it costs GP, but after increasing the images downloaded counter to 1, the currency needed will change to credits (not sure if it only happens if currently not holding any GP, I only needed to reset it with credits until now), that download counter can't be reseted in certain countries (I live in Brazil), so your program will need something to test if reset was really successful and tell to the user use a proxy / VPN or tell if there aren't enough credits if wasn't successful), just now, I found out that the limit is 5000, normally before, it was about 100 ~ 300, I don't know if the 5000 limit is for a special temporal reason or they have increased due to server enhancements. If the limit is exceeded, you still will be able to download rescaled images, although, the image that will be downloaded instead will be a ERROR 50* static gif, I don't have it's md5sum for now, and probably it has changed since the last time I've gotten it, I guess noticing the user that there are images downloaded with resolution different than the resolution reported by the image's page and automatically stopping. I don't think the image counter reset needs to be implemented now as the limit is very high now. The image counter only increases when downloading full size images, I believe.

Credits are something you can get by playing http://hentaiverse.org/ , scanning or translating stuff, there may be other ways. I don't know if you has been thinking that credits are something that only premium users would have.

About the "load all galleries thumbnails then load a pool tab which will then list all of the gallery's images". I can't think about anything better, but as an addition, exhentai does have an option to show 40 images of small thumbnails or 20 images of medium thumbnails, you can implement it to prefer larger thumbnails or manual selection.

I may be assuming some stuff wrong, so to be sure, you can test things by yourself.

English isn't my native language, please tell me if there is something you didn't understand.

**Comment by Noiwex** [comment]
This might help you https://github.com/tommy351/ehreader-android

**Comment by hentman** [comment]
that ehreader-android has any of the functions Boxmanbr mentioned? or has PC client?

**Comment by Boxmanbr** [comment]
Found an alternative that downloads full images from galleries and comes with some options: https://github.com/ccloli/E-Hentai-Downloader/
It is a script for greasemonkey / tampermonkey, looks entirely chinese at first, but in exhentai, it will appear in english.

**Comment by micnorian14** [comment]
Just request to set up a H@H server. Throw the text .hathdl files in your server and after a few hours/minutes the gallery is downloaded. You gotta bake that cake before you "eat" it m8 ;) 
ehentai have dealt with rippers before and have made a post about them. It's a trusted peer system so this program wont ever work. 

Continued ripping will ban the IP used. There are only so many public VPNs before they ban them all (which they are already doing im sure) A hath server is the preferred method to rip ehentai galleries.
