### ISSUE TITLE
Regarding the 'Favorites' functionality

### ISSUE THREAD

**Issue by Twoearle** [Bionus/imgbrd-grabber#397]
I'm sorry in advance if this is how the program is intended to work, i admit that it's been somewhat difficult for me to get to configure the program to suit my needs (besides, im somewhat new to *boorus so that only makes things harder)

Anyway, the problem is the following: im having issues with my Favorites. I've created a folder exclusively for them, and i want them to be saved using the "%artist%/%copyright%/%character%/%md5%.%ext%" syntax, to distinguish them from my non-favorite images.
Thing is: i) They're not being named by that syntax, instead it's using the Default file naming (which is currently "%copyright%/%md5%.%ext%") and ii) They're also being saved in the default folder. This point in particular isn't that much of a problem if it weren't for (i).

Any suggestions? The reason im asking is because i'd like to keep images from a show (for example) all piled together in one folder, while maintaining pictures from certain artists according to the character.

By the way (and this is unrelated to the title of this ticket) i was experiencing a couple of technical difficulties regarding extremely sluggish operation and a lot system resources consumed, basically it was taking too long for Grabber to do anything (even start up) and when it did, it consumed a lot of CPU power. I was unable to pinpoint the source of it, but thankfully it was fixed by un-installing the old version and installing the latest release in the root of the drive (on Windows 7). Maybe it had to do with my settings, i had a long list of blacklisted tags and added sources, but i can't say for sure.

Thanks for your time and all the effort put together into this program

**Comment by Spark-NF** [comment]
Is the problem you're having happening during batch downloads?

And are you talking about the favorites like in the favorite tab or the favorites in the Save settings (where you can decide of a custom filename and file folder).

The two of them are currently not related. The first only decides of what appears on the "Favorites" tab while the second is used for the path and filename when you click the "Save (favorite)" in a details window (when you click a thumbnail in the picture list).

Your suggestion would be to automatically save the pictures in the "Favorites" tab to a different folder with a different filename?

As for your last issue, if you're saying it got fixed by reinstalling I guess it's ok? If you have this issue again please tell me, but I don't see any reason for the program to use a lot of system resources only to start up (batch download is another story though).

**Comment by Bionus** [comment]
Is the problem you're having happening during batch downloads?

And are you talking about the favorites like in the favorite tab or the favorites in the Save settings (where you can decide of a custom filename and file folder).

The two of them are currently not related. The first only decides of what appears on the "Favorites" tab while the second is used for the path and filename when you click the "Save (favorite)" in a details window (when you click a thumbnail in the picture list).

Your suggestion would be to automatically save the pictures in the "Favorites" tab to a different folder with a different filename?

As for your last issue, if you're saying it got fixed by reinstalling I guess it's ok? If you have this issue again please tell me, but I don't see any reason for the program to use a lot of system resources only to start up (batch download is another story though).

**Comment by Twoearle** [comment]
>Is the problem you're having happening during batch downloads?

Precisely, i didn't know that favorites were intended for particular images selected through the details window. Well, now i understand that's the expected behavior (Pick an image, and add it to favorites); makes a lot of sense really.

>Your suggestion would be to automatically save the pictures in the "Favorites" tab to a different folder with a different filename?

My prior understanding was that Favorites applied to tags, such as ('artist_x') and the program would use the settings configured in the Options menu ![Like this](http://a.loveisover.me/uldroc.png) to all pictures containing that tag in the favorites left-panel. Therefore, all images from selected sources (booru1, booru2) with the corresponding tax (artist_x) will be saved with the favorites_filename to the favorite_folder. Something like that.

What i expected out of "Favorites" is probably outside the scope of it. If i understand correctly now, favorites are images picked manually by clicking on the thumbnail and pressing the "+" button and selecting the Save (fav), Save and Close (fav) or Destination folder (fav). 
Therefore, to achieve my original objective i should just change the filename syntax from "Options" directly ![Here] (http://a.loveisover.me/iktpzs.png) instead of using Favorites (please correct me if im wrong)

Maybe what i should have requested in the first place is some sort of Presets: adding the capability of having several different filename and save folder options configured at the same time, and being able to select them as will, so they can be used for different situations. For example Preset 1 would be named 'Artists' with syntax1 (%artists%/%md5%.%ext%) and folder ./Selected Artists; Preset 2 with syntax2, folder ./Series and so on; this way images could be kept organized following different criteria as the user sees fit. What do you think about it? Can it be done with the current set of tools Grabber has, or does it have to be implemented as a new option? If so let me know how hard it is to program so can keep the ticket open or close it.

Thanks again for your time and patience :+1:

**Comment by Bionus** [comment]
> Therefore, to achieve my original objective i should just change the filename syntax from "Options" directly Here instead of using Favorites (please correct me if im wrong)

If your objective is to have a different folder / filename for a specific batch download you can directly edit the batch download table in the "Downloads" tab.

> Maybe what i should have requested in the first place is some sort of Presets: adding the capability of having several different filename and save folder options configured at the same time, and being able to select them as will, so they can be used for different situations. For example Preset 1 would be named 'Artists' with syntax1 (%artists%/%md5%.%ext%) and folder ./Selected Artists; Preset 2 with syntax2, folder ./Series and so on; this way images could be kept organized following different criteria as the user sees fit. What do you think about it? Can it be done with the current set of tools Grabber has, or does it have to be implemented as a new option? If so let me know how hard it is to program so can keep the ticket open or close it.

I guess it would actually be doable currently using a mix of custom tokens as well as token conditionals (see the [Filename](https://github.com/Bionus/imgbrd-grabber/wiki/Filename) wiki page).

You could create a custom token with the tags you want, then add a conditional on that token for a custom filename. Another option would be to simply use Javascript filenaming but that implies knowing basics of Javascript.

My suggestion for you feature is to keep then custom token system, but add optional "filename" and "folder" fields for each custom token. If this field is set and one of the tags is found, it will use this filename and/or custom folder.
What do you think?

**Comment by Twoearle** [comment]
>My suggestion for you feature is to keep then custom token system, but add optional "filename" and "folder" fields for each custom token. If this field is set and one of the tags is found, it will use this filename and/or custom folder.

Sounds like a great solution. Guess it's about time to learn how tokens work, because honestly, i have no idea. It'd be nice if you could update the documentation accordingly, if it's necessary.

Thanks a lot Bionus!
Cheers

**Comment by Bionus** [comment]
Then I guess I'll add this in an upcoming update, 4.1.5 or 4.1.6. Since I have a lot of work on my hands right now I guess it'll be out around next week.

As for the tokens, there's not much to know. They're just the things with the % in them (%artist%, %copyright%, etc.), and they're all pretty much documented on the [Filename](https://github.com/Bionus/imgbrd-grabber/wiki/Filename) wiki, as well as custom tokens.

Cheers

**Comment by Twoearle** [comment]
Don't worry, take your time, this time of the year is really busy for pretty much everyone, and this ticket is a suggestion after all, not a critical bug or anything like that (you've already made me happy with the promise that this will be implemented in the future :smile: )

Cheers
