### ISSUE TITLE
Adding Options Window to Menu

### ISSUE THREAD

**Issue by barryanders** [Bionus/imgbrd-grabber#400]
In OS X I can't seem to open the options window, nor can I figure out how to add it to a menu. I've tried so many ways but nothing seems to work. Not even the shortcut. I know you don't use OS X so this isn't really a problem with the program. I just would like to be able to access the settings ini via the GUI since a lot of the editable settings are not included in the settings ini.

**Comment by Bionus** [comment]
First, I just saw that you added the OS X compilation steps to the wiki, and I'd like to thank you for that. I admit I neither posses a mac or have any background on using it, so I couldn't do it, thank you. :smile:

If I understand the issue correctly, the menu simply doesn't show up in the top bar and Ctrl+P / Cmd+P doesn't open the options either?
Maybe some compilation flags have turned on Qt::AA_DontUseNativeMenuBar. I forced the use of the native menu bar on the latest commit on the develop branch ().
But it's strange that you don't see the menu *at all* since Qt should fall back to using a menu inside the window itself if [this property](http://doc.qt.io/qt-4.8/qmenubar.html#nativeMenuBar-prop) is disabled.

In the meanwhile, here's a settings.ini which should contain most (if not all) settings that are usually editable through the options menu.
http://www.mediafire.com/view/4batdefksa2q16p/settings.ini

**Comment by barryanders** [comment]
Oh, thank you for that settings file. that's excellent! So the menus are actually showing up, but the specific menu item to get to the Options Window does not appear to be anywhere. OS X's default Preferences seems to be paired with toggling the Options widget in the MainWindow rather than the OptionsWindow. I see in mainwindow.ui that actionOption is there (which I think is what I am needing), but it doesn't seem to show up under the "Outils" drop down. I will keep playing with the mainwindow.ui now that I have a better idea where to look.

**Comment by barryanders** [comment]
I figured it out! I changed
`<string>Options</string>` to `<string>Test</string>` and it showed up. Apparently OS X must not allow the use of Options as a menu item.

**Comment by barryanders** [comment]
To go one step further, I set the menuRole of Options to PreferencesRole which makes it the default preferences menu item accessible with the system wide shortcut `⌘,`.
![](https://cloud.githubusercontent.com/assets/5648875/8440105/c08ec58c-1f35-11e5-95f2-9ba3f07c27ab.png)

**Comment by Bionus** [comment]
Ah I see. I'll rename it to settings or something equivalent then, as well as setting it as the preference role, thank you very much.

**Comment by barryanders** [comment]
I'll see about sending one a little later.

**Comment by barryanders** [comment]
So as it turns out, it's not actually OS X that bans the use of Options as a name. It's actually QT trying to help! http://doc.qt.io/qt-5/qmenubar.html If it is named any of these: "config, options, setup, settings or preferences", then it will automatically be made the default program Preferences. This is why the Options widget is defaulting to the Preferences menu item and why my options menu item is disappearing. Because once it found the Options widget, then it was just throwing away anything else it found in favor of the widget. Since I don't know how to prioritize that, I'll just rename the widget too if I can.
