### ISSUE TITLE
Grabber not saving images with long file names

### ISSUE THREAD

**Issue by Ma-ryan** [Bionus/imgbrd-grabber#418]
It seems that Grabber won't save files with a file name that is over 255 characters long. Currently, I have my file name set at %artist% %copyright% %character% %general%.%ext%

After running a batch download, Grabber reports that 200 images were successfully downloaded, but when I check, about half or less are actually saved (no errors reported). if I change the the file name setting to something like %md5%.%ext% it will work fine and all files get saved properly. This leads me to believe that Grabber doesn't shorten the file names to 255 characters or less. Lowering  the character limit (or using the default) in the options doesn't do anything for me either.

I am on Linux (Debian), so this problem may not be present on Windows.

**Comment by Bionus** [comment]
I was indeed not aware of such limitation on Linux systems. According to [this link](http://www.linfo.org/file_name.html) it is indeed limited to 255 characters.

> Lowering the character limit (or using the default) in the options doesn't do anything for me either.
Setting it less than 250 doesn't fix the issue? This feature was originally created for this kind of issue, so I'll see what might cause it not to function properly.
Leaving the default would be useless though, since it currently defaults the Windows limit.

**Comment by Ma-ryan** [comment]
>Setting it less than 250 doesn't fix the issue? This feature was originally created for this kind of issue, so I'll see what might cause it not to function properly.
Leaving the default would be useless though, since it currently defaults the Windows limit.

I tried setting it to 255 and 249 and neither worked to solve the problem.
