### ISSUE TITLE
Gelbooru error loading image

### ISSUE THREAD

**Issue by Commiesrock** [Bionus/imgbrd-grabber#420]
When trying to view any image from Gelbooru the grabber, I get this error message. File path is just an example.

---------------------------
Error
---------------------------
Une erreur inattendue est survenue lors du chargement de l'image (202).
http://simg4.gelbooru.com/images/5c/17/5c171ce853e18319345f9af55b2b841e.png
---------------------------
OK   
---------------------------

I can view the image in my browser fine, and the path is 
http://simg4.gelbooru.com//images/5c/17/5c171ce853e18319345f9af55b2b841e.png
which you can see has '//images' instead of '/images'. Other sources don't have any issues loading images.

**Comment by Keyarose** [comment]
I don't have a complete understanding of the code but I believe this can be fixed by making changes to the ImageUrl regular expression for https://github.com/Bionus/imgbrd-grabber/blob/6d66a91895a7a165458f975cf6fcf0cb539c9517/release/sites/Gelbooru%20(0.2)/model.xml#l18

If I'm right you don't need to install a new build, just edit the model.xml for gelbooru on your system.

Unfortunately I'm horrible at regular expressions so I can't come up with one to replace the old one.  So if someone else makes one please share.

**Comment by Keyarose** [comment]
Did some more poking around, Gelbooru made some changes today so you just need to change some options on your source
http://gelbooru.com/index.php?page=forum&s=view&id=3264

What worked for me was going Sources -> Gelbooru options -> general and changing referer(default) to site.

**Comment by Commiesrock** [comment]
Yup, seems to work fine with that, nice and easy.

**Comment by Bionus** [comment]
Seems like that feature came in handy.
I'll put this setting as a default in the next release so that people don't have to manually change it.

Thanks for pointing the source of the problem so quickly. :smile:
