### ISSUE TITLE
Images in the zoom window and downloads are thumbnails(Gelbooru)

### ISSUE THREAD

**Issue by Keyarose** [Bionus/imgbrd-grabber#421]
All images from gelbooru only show as thumbs, even when downloading.  Making changes to the referers makes no difference.  This might only be a temporary problem as gelbooru seems to have temporarily disabled their API, but I'm not sure.
Using release 4.1.5

**Comment by Keyarose** [comment]
Further information: looking at the details for an image the URL, Sample, and Preview all point to the thumbnail

**Comment by Bionus** [comment]
Indeed, the regex source fallback (which was usually never used since gelbooru's XML api is really nice) seems to not guess the images original urls properly.

I'm working on a long-time fix. In the meantime, here's a hotfix for it (commit 560d8ae8e4519cc17858ddde201f72dab13cb059):
- [Grabber.exe](http://www.mediafire.com/download/0cz1li595zr1349/Grabber.exe)
- [sites/Gelbooru (0.2)/model.xml](http://www.mediafire.com/view/dr7cbhjj3fbq8uu/model.xml)

**Comment by Keyarose** [comment]
Works perfectly, thanks for the quick fix.

**Comment by Warriors-Blade** [comment]
I tried to use the hotfix as well and it borked grabbing from Gelbooru so I reinstalled.

Not sure what the issue is, care to enlighten me on the subject please?

**Comment by Bionus** [comment]
@Warriors-Blade the issue is that Gelbooru has made changes to their XML API and for now Grabber is unable to access it. I'm working on a fix. In the meantime, Grabber detects this and fallbacks to using the Regex system (analyzing the non-API pages to grab as much information as possible) but seems to be unable to capture the full-size images correctly. That's why I made a hotfix for the images and uploaded it above, which should work fine if you put it on top of a 4.1.6 version. What error/issue are you getting?

**Comment by Bionus** [comment]
Actually they just blocked all accesses to their API:
> Our API is being abused at the moment and is disabled.

You can check this Gelbooru forum post for more info:
http://gelbooru.com/index.php?page=forum&s=view&id=3264

**Comment by Warriors-Blade** [comment]
Oh MAN, I was afraid of that.............

I had a feeling that was the issue when it started to malfunction.

Happen to know of a equal/better gelbooru alternative?
Thanks a ton for the help/development Bionus, that is pretty annoying of Gelbooru team since no one has time to scourge through thousands of pics.

**Comment by Bionus** [comment]
Well once I get a fix working there should be no difference if you use Grabber. As an alternative, you've got danbooru (where gelbooru gets a lot of its own images) or sankaku (which also seems to be malfunctioning today with Grabber, and which I'm also working on a fix).

I'll release a new version (4.1.7) when I'm done.

**Comment by Bionus** [comment]
Gelbooru regex analysis should be working fine in the 4.1.7 release. Until they re-open their API, it should be more than enough to use it (it detects most of the image's information and guesses the others).

Please tell me if you still encounter issues with it.
