### ISSUE TITLE
Tag paging is non functional for Gelbooru source

### ISSUE THREAD

**Issue by Keyarose** [Bionus/imgbrd-grabber#423]
Using gelbooru as a source pages 1 - 21 only display the first page of images,
22 - 63 display images starting from the second page of how they are listed on gelbooru.
Keeping the default 20 per page it cuts off the images that come after the first 20 and before the 2nd gelbooru page.
64 - 105 similary display the first 20 of the 3rd gelbooru page.
Version: 4.1.7

**Comment by Newspeak0404** [comment]
me also. more precisely, the number of total pages and number of images are shown as "?"

**Comment by Bionus** [comment]
Ok, this should be fixed now. I did not want to make a new version number for such a quick fix so it's still labelled as 4.1.7 (I uploaded a new installer in the place of the previous one). :smile:

The images/page limit is forced to 42 since you cannot customize it outside the API (which they disabled for now). Make sure to also set it to this value when batch downloading or it'll skip images.
