### ISSUE TITLE
Favorites tab no longer updates

### ISSUE THREAD

**Issue by bumdude** [Bionus/imgbrd-grabber#426]
The Favorites tab no longer updates with new images.  I changed the "last viewed" time to an earlier time and it still doesn't update.  If I add new favorites, they don't update either.  However, I can still manually search the tags in a new tab.  Any ideas?

**Comment by Bionus** [comment]
Did you make sure to use a source that supports date-based search or gives date information when searching?
Since it happens now that Gelbooru [has blocked its API](http://www.gelbooru.com/index.php?page=forum&s=view&id=3264), I guess you're using it? The fallback from the Gelbooru API (regexes) does not give out date information.
I'll try to look for alternates methods for favorites on Gelbooru but in the meantime I advice you switch to another source :)

On the 10/15/15 at 10:47PM, lozertuser said:
> We are working on updating the API to prevent future abuse. It will be some time until this happens though due to me wanting it to be compatible with 0.3's application of access keys. Just waiting on Geltas to commit his working version to the SVN.

**Comment by bumdude** [comment]
Oh, sorry. I forgot to mention that the main source was Gelbooru.  I guess having their API not public anymore would cause this.  Oh well.  I can continue to do manual searches.

Thanks for the reply and great job on the application :smiley:

**Comment by Bionus** [comment]
If you want to keep using Gelbooru for favorites, you have to set-up your credentials in Gelbooru's settings window to access their API.
