### ISSUE TITLE
Gelbooru grabbing only returns one page of thumbnails

### ISSUE THREAD

**Issue by sealclubber** [Bionus/imgbrd-grabber#429]
Trying to get images by tag for gelbooru only loads up a single page of results (42 images) and trying to download anything results in getting only the thumbnails. I have tried with a fresh install and a fresh settings.ini file with the same results. Does anyone have any suggestions... am I doing something wrong, or is this something that just needs to be fixed?

**Comment by techpriests** [comment]
I have exact same issue except that I get actual images instead of thumbnails.
When I try to download images from Gelbooru by using the button "Get all", Grabber can only download a single page per session for some reason. Starting from the first page, I have to set the page number each time although images per page and images limit have been set properly. "Get all" feature does work for other booru websites like danbooru, so my guess is that Gelbooru has updated something that broke Grabber's Images per page funcion.

**Comment by sealclubber** [comment]
Glad to see it isn't just me. By the way, was there anything special you had to do to get the searches to return the actual images?

**Comment by techpriests** [comment]
I am using VPN. Perhaps that made the difference.

**Comment by theHubi** [comment]
The information I got from Bionus was as follows: Gelbooru currently limits the downloads from their servers because of a recent.. probably DDoS which put a huge load on their server.
This information is not 100% proven, but apparently they're changing something related to their servers so that cannot happen again. We do not yet know how it impacts Grabber's performance.

**Comment by Bionus** [comment]
Yes. Gelbooru has blocked public access to its API.

In the upcoming 4.1.8 version, the login on Gelbooru will be added to allow users to login and use the API. Plus, the regex mode will be a working fallback.

**Comment by sealclubber** [comment]
That is great to hear! Thanks for the update

**Comment by Bionus** [comment]
The 4.1.8 release should fix all Gelbooru problems.
If you want to set the "Images per page" to a value different from 42, please login using your Gelbooru account (click "Sources" then "Options" near gelbooru and put your credentials in the "Credentials" tab).
