### ISSUE TITLE
[Request] Numbered Filename Token

### ISSUE THREAD

**Issue by LazyVidya** [Bionus/imgbrd-grabber#433]
Wondering if it would be possible to add a filename token that counts upward for whatever you're downloading.

[ex: If the filename is **%search%_%num%.%ext%** when you're downloading images from the 'glasses' tag, it will save the images as **"glasses_001.png, glasses_002.jpg, glasses_003.gif, ...etc."**]

It would be great if you considered this as an addition to a future version. thanks for your time!

**Comment by Bionus** [comment]
Are you talking about a count for the current session, the current download session, or since the beginning? Or one that detects automatically where it should start from?

By this I mean when should it be reset? From your example I guess it's a download session one, but what about when you re-download with the same search, should it start again from 1 or should it check the already existing images and try to find the one with the bigger number and start from it?

**Comment by LazyVidya** [comment]
yes, if you downloaded a tag with this token in the same destination folder, it would start at whatever number comes next, if it would be a different folder, it would start at 001 again

**Comment by Bionus** [comment]
But that would mean, with your previous example, that if you have the `%search%_%num%.%ext%` filename, if you first download 3 images with the "glasses" search then 3 more with the "girl" search, it would result in something like this:
```
glasses_001.jpg
glasses_002.jpg
glasses_003.jpg
girl_004.jpg
girl_005.jpg
girl_006.jpg
```
Since they would be in the same folder. Is that really what you want? I guess you're looking more for something that would try to always save it with the smaller number possible for a given filename, where it would result in:
```
glasses_001.jpg
glasses_002.jpg
glasses_003.jpg
girl_001.jpg
girl_002.jpg
girl_003.jpg
```
Or am I wrong?

**Comment by LazyVidya** [comment]
yes, the second is what i was trying to explain. sorry for any confusion
