### ISSUE TITLE
Grabber crashing after deleting part of the download list

### ISSUE THREAD

**Issue by theHubi** [Bionus/imgbrd-grabber#436]
I tried around a bit with a fresh install on a new computer and found an error that still persists.

Reproduce as follows:
1. Start Grabber, select a couple files, add 3-4 entries into the download list.
2. Download part of it via "Download Selected".
3. Delete the downloaded entries.
4. Start downloading the rest via "Download"
5. Grabber crashes after loading all pages.

Machine I tested with:
* Intel Pentium E2180 (Dual-Core)
* 4GB DDR2 RAM
* Windows 8.1 64bit
* Samsung 840 EVO 120GB SSD

**Comment by oldfan13672** [comment]
The problem you seem to be having is that you must type in "%md5%.%ext%" (ignore the quotations) in box next to the "Name" folder in the destinations tab. If you cannot see your destinations folder, go to "View" right of "File" and "Tools", and select destination. You must also have a valid folder to save your files to.

**Comment by Bionus** [comment]
Does this issue only applies for single image downloads are also batch downloads? I made a fix in the 4.1.8 for a bug with single images download deleting, did it fix this issue?

**Comment by oldfan13672** [comment]
Sorry for the late reply. Thank you very much for your help and fast responsiveness, I seriously appreciate it. All of the image and .gif thumnails work just fine. I have downloaded all the pages, which are about 2757 and about 55,000 images total for chan.sankaku for the category I chose. Interestingly enough though I noticed that when I was downloading the images only 1332 were downloaded. I am not sure whether this is a protooal to leechers chan.sankaku's, which sometimes I have been timed out in cases of excessive usage with other downloaders. I checked the log and any files that were .gifs or different extensions were successfully downloaded, but I am not sure why there is such a large difference. When I was using other downloaders and loading pages, sometimes there would be a timeout of 60 seconds. This was similar to when I was using a downloader for g.e.hentai and was timed out for a few hours because of excessive usage and the speed of the downloader that activated an anti-leeching protocol, but this only happened when I disabled a function that downloaded an image every 3 seconds. I wonder that for this site if it is maybe a good choice to use an option that downloads page numbers and images with a limit to prevent getting the timeout. If anything, chan.sankaku is the most troublesome due to its complexity. @Bionus
