### ISSUE TITLE
Date tokens not working

### ISSUE THREAD

**Issue by Reinzeto** [Bionus/imgbrd-grabber#459]
I tried to use the %date% and %date:format% tokens in version 4.2.0, not working in any site

**Comment by Bionus** [comment]
I just tried to use it successfully on 4.2.0.
Which source are you using to download your images? Not all sources support the %date% token as some of them do not provide date information, or some require to first login to be able to use it.

**Comment by Reinzeto** [comment]
Mi y OS is windows 8 x64, and i tried to use it in Gelbooru and donmai, the previous version don't have any problem with these sites. Maybe is something with my OS?

**Comment by Bionus** [comment]
I'll investigate these two.

There shouldn't have any changes in Danbooru XML or JSON API so maybe something broke in 4.2.0 or I missed some change.
As for gelbooru, they had some heavy changes since last version that requires to login before using their API. And I think only their API provides the date information (I'll check that too). You should try logging into gelbooru to see if it changes something.

Which source order do you use? The default ans one for danbooru and gelbooru should be something such as "XML > JSON > Regex > RSS".

**Comment by Reinzeto** [comment]
i only use the defaults at install, i don't change nothing else, but, i will change OS and try again.

**Comment by Bionus** [comment]
Do you happen to be using the "Get selected" feature and download images one by one?
If so I just noticed that indeed %date% tokens do not work in this! I'll check that out, thanks.
