### ISSUE TITLE
Logging in to Danbooru w/ Gold account?

### ISSUE THREAD

**Issue by ayyu** [Bionus/imgbrd-grabber#460]
Hi,

Is it possible to search for >2 tags at once if I have a Gold account? I've tried logging in with my username/hashed password under Sources > danbooru.donmai.us > Credentials, but when I press Test it says "Unable to test" and when I search for 3 or more tags at once I get:
![](http://puu.sh/mcYec/d7fc64ef58.png)

Am I doing something wrong?
Thanks

**Comment by Bionus** [comment]
Logging in should be working fine for Danbooru, so it's strange. The "unable to test" is because there's no easy way to check if one's credentials are correct on Danbooru.

When you click the link (in blue), is there anything written on the page? (any error, or results)
Is that link to an XML, JSON or HTML page? (ends in .xml, .json, or something else)
When hashing your password, did you only hashed your password or did you use the "choujin-steiner--PASSWORD--" format? (that should not be necessary anymore)

Could you please share your log file after this problem occurs? (the `main.log` file, located in "C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber") I might be able to locate the source of the incident with it.
Make sure neither your password or hash is contained before uploading it (it should be hidden but things happen).

**Comment by ayyu** [comment]
The link goes to an XML page:
![](http://puu.sh/mddok/6249919d8d.png)

I only hashed my password, not my username when I tried entering my credentials.

Here's my log:
[main.log.txt](https://github.com/Bionus/imgbrd-grabber/files/74556/main.log.txt)

**Comment by Bionus** [comment]
Thank you, logging into Danbooru indeed broke in 4.2.0 version! Sorry about that.
I managed to fix it thanks to the information you provided, so I'll upload 4.2.1 soon, that will include this fix.
