### ISSUE TITLE
Page Limit 100 even with registered Account

### ISSUE THREAD

**Issue by DraGoran** [Bionus/imgbrd-grabber#471]
I have a problem to download more than 100 pages.
Somehow when i search a tag, in this case "slime" it just makes up to 100 Pages visible with pictures.
Which means i can also only download the Pictures which are shown right after i searched the tag and got the thumbnail results. Basiclly it downloads the Pages , but only up to 100 Pages and so for each page 1% till it completes to 100% then it shows fastly running through the other Pages while the Bar still stays at 100 %. When all Pages are done loading which are 336 Pages then it starts to download BUT only the 100 Pages of Pictures.
I know i have to click Get All and then Download All inside the `Downloads´ tab and i limited my Source to chan.sankakucomplex.com to make sure it only displays sankaku results.
I also made sure to login with my Account inside the Site Options of chan.sankakucomplex.com.

I put in all Information which was needed and the Test button said Success!
This goes for both Credentials and Login tab i also put in my __cfduid cookie in the cookies together with the Source code. I tried both Methods POST and GET and both showed Sucess but still the same problem, currently it is set on GET.

I tried the https connection option but still get limited pages.

It would be nice if someone could help me, I´m out of ideas to fix this problem.

Thank you

**Comment by Bionus** [comment]
Indeed, the current source settings for Sankaku does not hash passwords.

I'll include the fix in the next release. Since it's a minor modification, you can also just replace the "model.xml" file located in "C:\Users\Nicolas\AppData\Local\%USERNAME%\Grabber\sites\Sankaku" by the one [located here](https://github.com/Bionus/imgbrd-grabber/blob/develop/release/sites/Sankaku/model.xml), and re-set your password (don't forget to hash it through the hash window).
