### ISSUE TITLE
Zerochan doesn't work.

### ISSUE THREAD

**Issue by Lywzc** [Bionus/imgbrd-grabber#482]
It downloads s3.zerochan.net while it should download static.zerochan.net.

**Comment by Bionus** [comment]
What's the problem with it?
The server used (s1 to s7) is decided when the page is loaded and is not fixed by Grabber. And it shouldn't make any real difference as images are available on all of them.

However, if by "not working" you meant that all files were downloaded as something such as ".jpg" (with no filename), make sure you don't use %md5%, %date%, or that kind of token, since they are not supported by Zerochan.

**Comment by Lywzc** [comment]
When it downloads s3.zerochan.net, there is nothing. That means, it will downloads the sample rather than the full image, and when I paste the URL it returns 404.
I download 79 images, only one image is full and others are all samples.
For example http://s3.zerochan.net/Reimia.full.246888.jpg. This returns 404, but if you replace 3 with 2 or 4 it works. But I don't know why the software downloads 3.
Also I use %filename%. That should work.
There is an image but I can't upload it:(

**Comment by Bionus** [comment]
Indeed, that happens for some old images or some who have a certain set of tags, requiring to log in to load the image's details.

To replace all the s1/s2/etc into static, you should replace the `model.xml` file located in "%localappdata%/Bionus/Grabber/sites/Zerochan" by the one [here](https://github.com/Bionus/imgbrd-grabber/blob/e36b7596cca7315b6bce9360e3c564ed7aec9192/release/sites/Zerochan/model.xml).

**Comment by Lywzc** [comment]
It works now. Thanks!
