### ISSUE TITLE
testing new version

### ISSUE THREAD

**Issue by DraGoran** [Bionus/imgbrd-grabber#486]
Hi Bionus
I noticed the new version 4.3.0 was released.

So i downloaded it and checked if the problem #476 was still the case.

It seems that on both sankaku pages , idol.sankakucomplex.com and chan.sankakucomplex.com the pages show up above 100 pages.

<img src="http://pichoster.net/images/2016/02/29/sankaku download bug3.png" alt="sankaku download bug3.png" border="0" />

Though when i download them it still only loads up and downloads 100 pages in that case in idol.sankakucomplex.com only 1247 Pictures.

<img src="http://pichoster.net/images/2016/02/29/sankaku download bug.png" alt="sankaku download bug.png" border="0" />

The Interesting thing is the progression bar shows the real progress how it would look like with the 3367 pictures as you can see in this second screenshot.

<img src="http://pichoster.net/images/2016/02/29/sankaku download bug2.png" alt="sankaku download bug2.png" border="0" />

I made sure to put in the password and hash it before i searched the tag.

The password seems just working to show up the pictures but not download them, thought i would report that to you ones more for further inspections on the problem and test it by yourself.

have a nice day

**Comment by Bionus** [comment]
I just tried when logged in and could not reproduce and properly got the 5488 images list from Sankaku (I admit I didn't download them all though, stopped at the list):
![allsankaku](https://cloud.githubusercontent.com/assets/882719/13723604/534f6842-e86a-11e5-9954-72370b816378.png)

I really doubt it comes from the login however, because even if you could not get past page 100, it would result in 2,000 images, not 1,247. Are you sure you didn't blacklist a lot of these images? Try setting the "get blacklisted" to "true" (all other values mean "false") and see if it still happens.
Also, at the end of the download, it should mark all blacklisted images as "ignored", you can see the resulting count (in your case about 2,120).
