### ISSUE TITLE
Slideshow search results

### ISSUE THREAD

**Issue by femiki** [Bionus/imgbrd-grabber#506]
Any chance that could happen?

Thanks for this great piece of software!

**Comment by Bionus** [comment]
What do you mean exactly by that?
I'm not sure I understand. Having the results going full screen and keyboard controls to go from one to the other?

**Comment by femiki** [comment]
yes! that sounds about right. Plus maybe an option to have it switch between images automatically after a couple seconds?

If it's asking too much, never mind me.

Thank you again!

**Comment by elreymu** [comment]
That would be great because there are not many software that do that.
It would also be nice if it allowed GIFs on full screen (fit to screen) and an option to "let the entire animation play" (which would ignore the time between each image if it's longer than the delay)
And of course, being able to adjust the time between each image.
And the OR operator suggestion aswell (is that going to get implemented?)

**Comment by Bionus** [comment]
I understand the need/request.
However, I'm not sure yet whether this is really in the scope of the
software.

How would you actually use it?
Make a search on one or more sources, then open one of the results, click
some "slideshow" button then it will switch to the next image in the
results window after n seconds?
Should it go to the next page automatically, or just loop on the current
one? (or having an option to choose between both)

@elreymu: as for the OR operator, it seems I forgot to answer at the time I
self-assigned last month. I'll send it right now.
