### ISSUE TITLE
Support for ugoira?

### ISSUE THREAD

**Issue by himselfv** [Bionus/imgbrd-grabber#514]
There's this weird format:
https://danbooru.donmai.us/posts?tags=ugoira+rating:safe

It boils down to being "webm" as a sample, but "zip" for full /data/. It's usually tagged as `ugoira` and XML source gives it `file-ext` = `zip`.

Currently, if it appears in the results, this is what happens:
```
grabber.com -s "danbooru.donmai.us" -t "ugoira" --return-images -i 10 -m 10
https://danbooru.donmai.us/data/e7251b764848df0be07c70f298e78bd6.webm
https://danbooru.donmai.us/data/043f9a27bf37fae794c51cffa83b77c0.webm
...
```

None of those links works because the /data/ version of this thing is `zip`. These would work though:
```
https://danbooru.donmai.us/sample/sample-e7251b764848df0be07c70f298e78bd6.webm
https://danbooru.donmai.us/sample/sample-043f9a27bf37fae794c51cffa83b77c0.webm
```

So I guess the GUI should just stick with sample when it happens upon `zip` in the `file-ext` field?

I've just realized the console part should be fine with Issue #513 fixed, it'll return the correct links now. I'm not sure how the mass-downloader will handle this though.

Sorry for the number of tickets today and thanks for developing this.

**Comment by Bionus** [comment]
> I've just realized the console part should be fine with Issue 513 fixed, it'll return the correct links now. I'm not sure how the mass-downloader will handle this though.

Indeed, the latest commit that fixes issue #513 fixes the download phase for this image format (zip).
As for the mass downloader, it'll just download zips. Maybe I'll add some setting to download the samples during batch downloads instead of zip files (because zip files are inconvenient).

> So I guess the GUI should just stick with sample when it happens upon zip in the file-ext field?

What remains to do is as you suggested for the actual image viewer window, which obviously cannot display zip files (downloading it, extracting it then implementing some kind of player is not really in my plans for now). So indeed, displaying the sample for images with the "zip" sounds like a good idea.

> Sorry for the number of tickets today and thanks for developing this.

No problem, feel free to add as many as you can think of. I can't by myself notice all bugs and all missing features (not downloading animated images myself, I never heard of that zip file thing for example).
