### ISSUE TITLE
add a %url% tag

### ISSUE THREAD

**Issue by andycontrib** [Bionus/imgbrd-grabber#519]
add an available tag for the download url of an image or even the page url (probably not possible). Would be helpful for reference in an external txt file when a download fails to see what *should* have downloaded

**Comment by andycontrib** [comment]
also unrelated but I see that there is a %count% tag available now (thank you!), is it missing from the wiki on purpose?

**Comment by Bionus** [comment]
I added the `%url_file%` and `%url_page%` in the commit 1cc9c8243d455582b0e9ad17d8e079b134341786. It's better used with the external log/text file feature.
It will be included in this weekend's update.

> or even the page url (probably not possible)

Everything is possible. :smile:

> also unrelated but I see that there is a %count% tag available now (thank you!), is it missing from the wiki on purpose?

Yeah, it's missing on purpose because it's not fully implemented yet, and doesn't work in most cases (always returns 0), so I would advice you not to use it as is. I'll update the original issue when it actually works.
