### ISSUE TITLE
chan sankaku limited to 1000 files

### ISSUE THREAD

**Issue by Zzzyyzzyxx** [Bionus/imgbrd-grabber#523]
hello, long time no see,
I am still around, downloading updates, etc
no major bug report, so no post

but here is one : 

Apparently, chan.sankakucomplex.com had its code changed.
If you search any tag that result in over 1000 images,
Grabber will stop at 1000, and will be unable to access the following posts.

The same problem occurred with another images download program (nekopaw)
and it was updated just to fix that problem.
That's why I am pretty sure its a problem related to a change in Chan.sankaku code, or something.

I saw you finally put a timer/delay option,
I waited for that feature for long time 
Thank you ;)

take care, 
see you!

YMI

**Comment by Bionus** [comment]
Hello,

They indeed updated their source and now "Anonymous users can only view 50 pages of results".
To fix this issue, you have to first put your Sankaku credentials in Sankaku's source settings (don't forget to hash your password) so that Grabber can login to fetch pages above 50 (20*50=1000 as indicated in this issue).

You'll also have to update to the next version that I'll release some time during the weekend as there was another bug that didn't allow logging in on Sankaku for batch downloads.

Note however that because of the way Sankaku is designed, to load say page 53, you have to first load page 52, for which you need 51, for which you need page 50, which can be loaded directly. So it's not very convenient for browsing but it allows to batch download.

> I saw you finally put a timer/delay option,
> I waited for that feature for long time
> Thank you ;)

You're welcome :)
