### ISSUE TITLE
Is there a special method required to access chan.sankakucomplex?

### ISSUE THREAD

**Issue by Warriors-Blade** [Bionus/imgbrd-grabber#526]
I see others are able to access it through grabber yet I am having zero luck, anyone care to explain the issue?

**Comment by Bionus** [comment]
There should be nothing to do to access it on a fresh 4.5.1 install (I just tried it).

Install Grabber, run, select it from the sources and voilà.
Maybe you have some old settings from a previous version that don't work since some Sankaku update?

![defaults](https://cloud.githubusercontent.com/assets/882719/15558946/85318972-22de-11e6-88c5-b54281a3a432.png)
*(sorry for the French screenshot, seems like another bug from4.5.0 prevents changing language)*

**Comment by Warriors-Blade** [comment]
Ah, thanks for the info Bionus, il do a fresh install instead of a install-over.

il report back the result.

**Comment by Bionus** [comment]
You can just rename your settings folder in "%localappdata%/Bionus" from "Grabber" to "Grabber.old" so that if it doesn't fix your issue you don't lose everything (or can at least get back your `settings.ini` file).

**Comment by Warriors-Blade** [comment]
Fantastic, the settings were to blame for chan.sankaku for not showing up during a search.

Thanks alot for answer to this long term question.
