### ISSUE TITLE
Token in filename

### ISSUE THREAD

**Issue by TheWebSmith** [Bionus/imgbrd-grabber#529]
In version 4.5.1 the token %website% isn't working anymore. I used **%website%/%id%.%ext%** in **Save > filename: Default** to divide the files downloaded by different sources. If you are be so nice to get it back working it would be even better to make tokens work in **Save: Folder** as well.

Edit:
Possibly the same problem: [Issue 530](https://github.com/Bionus/imgbrd-grabber/issues/530). So it wasn't the token after all, but the slash/backslash. But the suggestion to make tokens work under **Save: Folder** still stands.

**Comment by Drakonas** [comment]
Yeah it's definitely the slashes in the filename. Doing this worked in 4.4.1.

**Comment by Bionus** [comment]
Moving to issue #530.

About the suggestion to allow tokens in the folder, I don't see the point. The folder is supposed to be the common root for all "filenames". Since we can (or at least **should**) use the tokens to create sub-directories using `/` (or `\`) in the filename, I don't see what allowing to use them in the folder add (feel free to tell me if you think otherwise though).
