### ISSUE TITLE
Conditionals on Windows

### ISSUE THREAD

**Issue by hobbes312** [Bionus/imgbrd-grabber#534]
Cannot use conditionals on windows on filenames. Specifically I keep getting the error that < and > signs are forbidden on Windows, even using the built in conditional filename function.

(Unrelated, something to pick up the %species% tag rather than creating a custom token with an exhaustive list of animals on e621 would be nice. Granted I'm not the most technically knowledged to know how feasable that is to implement for 1-2 sites.)

**Comment by Bionus** [comment]
Fixed by commit c1a7321, thanks for the report!
You can still use them even if it says they're forbidden though, but the upcoming update should remove the error messages and fix some problems related to conditionals (see issue #536).

As for the suggestion, it's indeed in my roadmap, along with some other tag types (for zerochan for example), but not as a critical position I'm afraid.
