### ISSUE TITLE
Can't compile on mac osx.

### ISSUE THREAD

**Issue by endy23** [Bionus/imgbrd-grabber#550]
Hello, I m trying to build on osx but failed.

`In file included from ../source/filenamewindow.cpp:2:
../includes/filenamewindow.h:9:11: fatal error: 'Qsci/qsciscintilla.h' file not
      found
        #include <Qsci/qsciscintilla.h>
                 ^
1 error generated.
make[1]: *** [filenamewindow.o] Error 1
make: *** [sub-gui-make_first-ordered] Error 2`

Then i copy the Qsci folder from [here](http://sourceforge.net/projects/pyqt/files/QScintilla2/QScintilla-2.9.2/QScintilla_gpl-2.9.2.tar.gz) and again failed:

`ld: library not found for -lqscintilla2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Grabber.app/Contents/MacOS/Grabber] Error 1
make: *** [sub-gui-make_first-ordered] Error 2`

I trying also to install qsciscintilla with success but Grabber doesn't compile again.
I trying for a week. Please any help is welcomed.

Sorry for my english.

**Comment by Flat** [comment]
Did you install the QT5 version of Qscintilla2?

**Comment by Bionus** [comment]
It seems you didn't install Qscintilla2 properly if you had to download the headers manually from Sourceforge. But it seems there's no package for it on OS X.

Qscintilla is far from necessary (it only provides JS syntax highlighting), so you could just disable it by removing "CONFIG += use_qscintilla" in the `gui/gui.pro` file.

I'm not familiar with compiling stuff on OS X, but since you went and already downloaded the sources, you could as well compile and install them (it's not that long), it's explained how to do so on Max [here](http://pyqt.sourceforge.net/Docs/QScintilla2/).

```
cd Qt4Qt5
qmake qscintilla.pro -spec macx-g++
make
make install
```

**Comment by endy23** [comment]
i simple remove "CONFIG += use_qscintilla" and all well done.

**Comment by barryanders** [comment]
That's what I do too. Don't need it to build.

**Comment by cycledance** [comment]
barryanders is there any way i can contact you? i'd really like to just download the latest release for mac already compiled. please.
