### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by barryanders** [Bionus/imgbrd-grabber#553]
Feel free to close this any time. I was just curious if you had any big plans for a v5.0 or if it's just more stability and you get there when the version gets there.

**Comment by Bionus** [comment]
I do indeed have plans for 5.0, but I also want to first make it more stable before implementing them, in order not to keep adding stuff to the codebase endlessly, leading to a mess of code, like I did the past years.
So my current plans for upcoming versions 4.x are mainly refactoring, bug fixes, and minor features. I'll start working on the new features once I manage to sanitize the codebase and have it unit tested to a sane extent.

In all cases, I won't make a 5.x unless there's a big change, I'd rather do a 4.10.x.

On my roadmap I have stuff such as:
* Gallery based boards (4chan-style, g.e-h.org...)
* Javascript models instead of XML to allow for more advanced sources (instead of having semi-hardcoded stuff)
* Better favorites
* Better CLI
* Auto-update models (and maybe the software)
* Closing as many issues as possible

Things I'm not sure about:
* Add more SFW sources (to give the program a better image)
* Rename the repo to "Grabber" since even I don't know if I should call it imgbrd-grabber (too long) or simply Grabber, but I'm afraid of the negative impact on searches

Except for these, I don't have anything in mind, but that's mainly because I don't know what other things I could add. So feel free to suggest things :smile:

**Comment by barryanders** [comment]
I was mostly just curious, since I've known about Grabber for a long time and I watch the version increase, I wanted to know where it was headed. Having Google images as a source could be cool, which sounds like something like that may be possible in the future. I haven't actually tried it to see if it would work now, but I doubt it would since the program is intended to grab image boards. I don't necessarily think it needs a bunch of more features either, and it seems like all the issues cropping up are contributing to your goal of stability. Thanks for sharing though.

**Comment by barryanders** [comment]
I did think of a feature. In the individual image view, it might be nice to have next and previous buttons, or being able to thumb through with left and right arrow keys. That's just a minor thing though.
