### ISSUE TITLE
download stuck

### ISSUE THREAD

**Issue by xEyad** [Bionus/imgbrd-grabber#567]
it looks like either its only me who have this problem or simply everyone just temp. solve it and ignore the fact it is a problem.

sometimes when iam downloading at any rate (usually 1000 image) the download stuck at random image (this happens with konachan and yande.re) and its only fix is to skip that image -if i tried to pause then resume it just stops at the same percent) and the end result is something like this (my download rate 4mbits/sec i.e. 400Kb/s
![capture](https://cloud.githubusercontent.com/assets/13967345/17270123/aae93f6a-565b-11e6-9844-45d3a4ad6c1c.JPG)

**Comment by Bionus** [comment]
If I understood correctly, since the Skip button won't allow to retry these images at the end of the download, the only solution afterwards it to re-launch the batch download? Which is slow.

One solution would be to have the option to retry skipped images at the end of a download.

> if i tried to pause then resume it just stops at the same percent

This is quite strange, as clicking pause *aborts* any download and clicking resume restarts them from the very beginning. If you re-start the very same batch download (after skipping the image for example), does the same thing always happens on that image? Or does it fixes itself magically eventually?

**Comment by xEyad** [comment]
i think i didn't explain my self clearly -sorry for that-
i mean that when it stops, i have one of two options.
1- is to skip that image
2- is to pause and then resume the download (using the pause button next to skip and cancel)

solution 1 works of course that means i don't have a chance to find and re-download that image
solution 2 if i paused a download while its not finished the download will stop, resuming it will force the program to start the download of this image from the beginning (which is not a bad thing) but the download of this image will stop at the same percent again. rendering this solution useless as it won't how many times i try it the image will not download eventually so i will have to use solution 1

note* pause resume technique DON'T restart the whole batch download it just restarts the download of image iam stuck at. so  its not a big deal.
but my complain is whenever this happen the whole batch download process stops untill i manually resolve the problem by skipping the stuck image. so if you can implement a mechanism to check if the download stuck at an image and just automatically skip it.

**Comment by Bionus** [comment]
Ok so just to be sure before I start coding the feature, this kind of stuck image is to be discarded and ignored right? Not retried as it would yield the same result?

The problem with detecting "stickiness" is that there are so many factors involved that it could come from something else (network issue). I'll see what I can do so that it automatically skips the stuck images.

**Comment by xEyad** [comment]
exactly sir.
it looks like that no one talked about this issue before so it maybe something on my own network. so if you want me to do some tests on my end and send you results, i may do that as well :D

**Comment by xEyad** [comment]
i noticed that this issue happens when a new download starts by any device in the network (mobile or other pc) tho iam not sure about this, i thought its better to tell you anyway as it might help you.
i will do some more testing about this and inform you about the result.
my internet speed is 4mbps --> 400KB/s
