### ISSUE TITLE
Seems E621 to not be working

### ISSUE THREAD

**Issue by Falord** [Bionus/imgbrd-grabber#571]
It only loads up the number of pages and the number of images under that tag, but no images. But sometimes for me it loads images when the page numbering loads like "page 1 of ? (42 of ?)" for some reason.

**Comment by FrostyDynamic** [comment]
Looking at the xmls for Danbooru and e621, it seems like e621's format is slightly different. Danbooru uses the <source> tag for the actual image, while e621 uses it for the page it came from. e621 uses <file_url> for the image. As well e621 is closer to Danbooru 2.0 rather than the original Danbooru, but grabber defaults it to Danbooru. This is all just a guess though

**Comment by Bionus** [comment]
Indeed, it seems that E621 is a fork using some mix between Danbooru 1 and 2.
For now, I'll adapt the code for Danbooru, but it seems on the long term it will need its own source.
