### ISSUE TITLE
Zerochan does not work after page 100

### ISSUE THREAD

**Issue by arukom** [Bionus/imgbrd-grabber#581]
so i wanted to download a tag/search from chan.sankakucomplex.com but after i clicked on "download all" after HOURS of waiting for downloading pages, it downloads 1700 pages but not the correct amount of pictures.. 
the problem is just that it doesnt download the correct amount.  after it downloaded THE WRONG AMOUNT the status stays blue and nothing happens, also the progress bar just stops in the middle.
sorry if my english is bad

EDIT: ok its not only chan.sankakucomplex.com, zerochan also doesnt work and downloads 10k less from 11k...  do i need to change my settings?
http://i.imgur.com/n6eK2qh.png
http://i.imgur.com/4fwFc3H.png

**Comment by Bionus** [comment]
Sankaku is indeed limited to 1,000 images for non-authenticated users. You cannot go further than the 50th page: afterwards, it only results in an error message:

> Error: Anonymous users can only view 50 pages of results - sign in to view more!

You have to create an account on Sankaku (if you don't already have one) then put your credentials in the "Credentials" tab in Sankaku's source settings. Don't forget to hash your password.

Same thing for Zerochan, after page 100, it only returns:

> Page number too high.

I don't know if logging in fixes this one, but it's worth a try.

**Comment by arukom** [comment]
oh, now it works. except for the zerochan one. 
http://i.imgur.com/s7UmD1A.png
http://i.imgur.com/HckO6ou.png

do you know how i could solve this? 

thanks for your help, youre a great person

**Comment by Bionus** [comment]
Zerochan is not limited at 100 pages for batch downloads and one-by-one browsing (that is, if you want to go to page 103, you have to come from page 102, to access 102 you need to come from page 101, and finally from page 100 that is accessible directly). However, it seems that Grabber's feature to use the `o` parameter instead of the page after page 100 is broken, so I'll keep this issue open.

As for Sankaku, see issue #602.
