### ISSUE TITLE
[bug] MD5/Hash check for existing files in save folder does not work

### ISSUE THREAD

**Issue by CloudyChess** [Bionus/imgbrd-grabber#593]
I was testing Grabber's detection of existing files and noticed that Grabber, at the present time, appears to only check the filename of files in the user specified save folder to detect if a file already exists and not the MD5/hash of the file. 

**Problem:** 
Grabber does not use hash checking like the options --> save menu says it does to detect existing files. 

**Grabber version:** 4.6.0

**Procedure to reproduce:** 
1) Find a file on a booru, download, and make a copy of it
2) Delete original file and rename the copy something different 
3) Check hash value, should be the same
4) Attempt to download the file again from the booru using Grabber, it will download even though the copy has the same hash and should count as an existing file. 

If you rename the copy to the same name as the original, Grabber correctly detects that it's a existing file. 

**OR** 

1) Find a file on a booru and download it, copy the filename and then delete it
2) copy a totally different file to the save directory 
3) rename totally different file to the same as original 
4) open up the image on the booru using Grabber's image viewer and notice that it changed to the totally different file's image rather than the correct one from the booru. Grabber also detects the wrong file as an existing copy of the correct one from the booru. 

Implementing proper existing file hash checking would be a great feature to have :D

**Comment by Bionus** [comment]
The fact is that Grabber has some kind of internal map of "filename to MD5". That's why as soon as you move a file, unless you re-run the "MD5 list fixer" tool (which checks all the images in your save folder, then try to get their MD5 either from their filename or using the algorithm, and update the list), it will "break". Each time an image is saved, it saves both its MD5 and location in that list.

The reason for this is that checking *all* the files in the save folder at every start and running the MD5 algorithm on them would be too intensive I believe, especially for people with millions of images in their collection. If the MD5 was always in the filename, it wouldn't be such a bad thing (as it wouldn't have to use the algorithm to get the hash), but for many people it isn't, or they just don't always use the same filename.

I didn't find a good solution to this problem myself. Except for parsing all the files in your save folder every time the program starts or the save directory changes (which could be resource intensive and slow depending on how many images you have).

Any suggestions?

**Comment by CloudyChess** [comment]
Ahh, I see. So that's how Grabber's file checking works. That's a bit of an odd way to go about it (defaulting to using filename to MD5, instead of the actual hash first), but it does make sense from a speed perspective. Having Grabber use its own internal list would be the easiest / quickest way to do it. 

Thanks for pointing out the MD5 list fixer tool, that's a good solution to the problem and what I'm looking for... except it doesn't appear to be working. 

**Problem:** 
MD5 list fixer does not appear to correctly either parse and/or add the MD5 of a file to Grabber's own internal list 

**Steps to reproduce:** 
1) download an image from a booru and place it in your Grabber save directory. Rename it something different. 
2) Run the MD5 list fixer tool with 'force MD5 calculation' option on
3) Go to a booru and open up the same image in Grabber's viewer, Grabber won't recognize that you already have the file and give you the option to save it again. 

Perhaps I'm going about it wrong? Here's the scenario I'm trying to accomplish: I've got some tags that I would like to grab all the images from a booru, but I've already downloaded some of the images and renamed them via other means. Instead of re-downloading them, I'd like to just place them in Grabber's save folder, use the MD5 fixer to tell Grabber they exist and be able to skip a whole bunch of downloads.

**Comment by Flat** [comment]
Just a suggestion regarding the storing of MD5 hashes. Instead of storing the MD5 as the MD5 and the path of the saved image, would it be possible/better to store the MD5 and the image URL? This would prevent the image from being downloaded if it had already been. If this route is taken it might also be necessary to include a way to edit the stored MD5's in case an image is deleted however.
