### ISSUE TITLE
Super small images

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#623]
### What steps will reproduce the problem?

average use with all sources selected.
### What is the expected behavior? What do you get instead?

I expect large images i get hundreds of small ones.
### What version of the program are you using? On what operating system?

4.7.0 win 10
### Please provide any additional information below

http://i.imgur.com/qNMDsEy.png

**Comment by Bionus** [comment]
It seems you have the "Interface > Resize previews instead of cropping them" setting enabled (I believe it's the default setting).

If you don't want the program to automatically "resize to fit" images but crop them, for example if you usually load lots of thumbnails, you can just uncheck the setting.

**Comment by brodycas3** [comment]
It still doesn't really help even with the option disabled.

http://i.imgur.com/mmzK0Bz.jpg

**Comment by Bionus** [comment]
Sow what would you suggest in that case?
Without scrolling, it's not like you can fit more pictures in there. Or do I understand that you suggest to add vertical scrolling to the results page?

**Comment by brodycas3** [comment]
sure that might work but then it would have so many photos to load. I just want to be able to use the application and see the photos I searched for. I also want to know if you can add arrows on the sides of this so we can scroll through them. http://i.imgur.com/GjgMFmW.png
