### ISSUE TITLE
tag count is (20 of ?) for chan.sankakucomplex

### ISSUE THREAD

**Issue by bluegoat25x** [Bionus/imgbrd-grabber#644]
### What steps will reproduce the problem?

Searched for short_hair  and got 
![grab](https://cloud.githubusercontent.com/assets/22950557/19551600/d71623d8-9660-11e6-9879-31eea4329b78.png)

Then I searched short_hair uncensored and got 
![grab2](https://cloud.githubusercontent.com/assets/22950557/19551603/dc2dd960-9660-11e6-86bf-5f5091e2e23e.png)
### What is the expected behavior? What do you get instead?

I wanted to get the total number of images for short_hair uncensored got a "?" instead.
### What version of the program are you using? On what operating system?

I'm using 4.8.3 and my operating system is windows 10

**Comment by Bionus** [comment]
It's actually a non-fixable problem: Sankaku does not provide any way to get the number of results (or last page) when there is more than one tag in the search or zero tag. The reason the count is here for single tag searches is because Grabber check the count for that given tag in the sidebar:

![image](https://cloud.githubusercontent.com/assets/882719/20024523/819aa30a-a2e7-11e6-86e0-b2380e8de84a.png)

There is no way to do the same thing with two tags unfortunately: even if we have the count for both of them separately, they are just maximums for that search.

Feel free to re-open if another solution is added in the future to fix this issue, or if you already have some workaround for it.
