### ISSUE TITLE
Too-small elements in settings window

### ISSUE THREAD

**Issue by Sfencer09** [Bionus/imgbrd-grabber#651]
### What is the expected behavior? What do you get instead?

The box enclosing the menu of options on the left of the options window is too small, causing much of the text in the box to be cut off. It would also be nice to make it, and other elements of the UI such as text boxes, manually resizable rather than having a fixed size, which can be inconveniently small.

### What version of the program are you using? On what operating system?

Grabber version 4.8.3, Windows 10 Home

### Please provide any additional information below

Issue may be related to the fact that my computer has a 4K screen resolution, as that has also caused minor display issues in other programs.

**Comment by Bionus** [comment]
Just to be sure we're talking about the same thing: this issue is about the left panel of the settings window (screenshot below), and on your 4K system, the fonts are upscaled but not the white box, so they do not fit in them anymore?

![image](https://cloud.githubusercontent.com/assets/882719/20020092/c5e9a3a2-a2cf-11e6-8940-b0e123cf8a00.png)

Do you have a screenshot of this problem so I could see how to fix it elegantly?

**Comment by brodycas3** [comment]
Sounds like a weird issue.

**Comment by Sfencer09** [comment]
Here's a screenshot:
![screenshot 1](https://cloud.githubusercontent.com/assets/23100679/20020819/7fd60188-a2a9-11e6-9e71-4b207498ebe0.png)

**Comment by brodycas3** [comment]
you seem to get a lot of problems with 4K resolution

**Comment by Bionus** [comment]
Yes, every time in the code where there is something non-standard or non-adaptive (such as here the 160px size of the left block) there are issues with 4K or the high contrast mode, unfortunately.
