### ISSUE TITLE
unclear qmake command

### ISSUE THREAD

**Issue by glop102** [Bionus/imgbrd-grabber#652]
I was installing this tonight and ran into the issue that i had qt4 as my default on my gentoo system. I think that it will probably be a good idea that to change the instructions to list the steps as `qmake -qt=5` so that qmake explicitly uses the proper major version.

**Comment by Bionus** [comment]
I have no objections, thanks for the info. :smile:

**Comment by Bionus** [comment]
Seems to be a feature provided by `qtchooser`, aliased as `qmake`.

**Comment by Bionus** [comment]
Since I didn't find any information or guarantee of the presence of `qtchooser` when installing Qt, and that the real `qmake` fails when given the `-qt=5` argument, I went with the environment variable solution instead (see the [new build file](https://github.com/Bionus/imgbrd-grabber/blob/c92f362e67be085ad834c56e9b216254ca7e3f60/build.sh)).

**Comment by glop102** [comment]
Nice, glad to see this added.
Also, glad that you seem to be quite active with this project. I have had other projects that seemed rather dead.
Also, should I close this issue or are you wanting to keep it open until you merge the branch back into master?

**Comment by Bionus** [comment]
> Also, glad that you seem to be quite active with this project. I have had other projects that seemed rather dead.

Thanks, I'm doing my best to fix issues as fast as my agenda allows me, as well as updating the now pretty old codebase. Many projects are dead indeed, but from what I remember some are still getting updates, such as https://github.com/Nandaka/DanbooruDownloader.

> Also, should I close this issue or are you wanting to keep it open until you merge the branch back into master?

Since it will be closed automatically and that the main readme on the project's homepage is not updated yet, I prefer to wait for the merge in master.

There will be a new release this week-end, that shouldn't take long. :smile:

**Comment by glop102** [comment]
:) to you too~~
