### ISSUE TITLE
Translation tools missing

### ISSUE THREAD

**Issue by sanddudu** [Bionus/imgbrd-grabber#664]
I have read the wiki page, but there are no translation tools download link anymore.
So how can I get the translation tools for now?

**Comment by Bionus** [comment]
I just added them here:
https://github.com/Bionus/imgbrd-grabber/releases/download/v4.9.1/translation-tools.zip

And the `YourLanguage.ts` file here:
https://raw.githubusercontent.com/Bionus/imgbrd-grabber/develop/languages/YourLanguage.ts

Note that the default language is now English, so you don't have to open `English.ts` anymore. I'll update the wiki page tomorrow, but nothing much is changed for the actual editing.

Feel free to ask here if you have more questions, or if there are some problems with the original translation.

**Comment by sanddudu** [comment]
As I think the one issue can only to use for one question, I will open another issue for translation progress.
By the way, when I open the linguist.exe, it shows:
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".
Reinstalling the application may fix this problem.

How can I solve this problem?

**Comment by Bionus** [comment]
Strange, I made sure to check they run before uploading them (even passed them through dependency walker).

I'll add the missing DLLs tonight, in the meantime, you can either copy all DLLs (and folders) from Grabber's installation folder (C:/Program Files (x86)/Grabber) as they use the same DLLs. Or you can also just copy the `linguist.exe` file there.

That particular "platform plugin windows" DLL can be found in "C:/Program Files (x86)/Grabber/platforms/qwindows.dll".

**Comment by sanddudu** [comment]
@Bionus I found linguist.exe online somewhere else, so it's fine now.
But it's weird that after I translate all String and release, all I can get is an interface with French and Chinese mixed.
I will upload my file later.

**Comment by Bionus** [comment]
Yes, since you're using the `YourLanguage.ts` from the develop branch you'll also need to use the develop program version.

The 4.9.1 uses French as the base language for translations, while the develop version (likely 4.10.0) uses English (much more convenient than French). This change relates to issue #657. Since `YourLanguage.ts` uses English as base language, you can't use it with 4.9.1.

You can find the compiled version of the develop branch here: [Grabber.zip](https://github.com/Bionus/imgbrd-grabber/files/595540/Grabber.zip).
Since there's no major changes since 4.9.1, you can simply replace your Grabber.exe file with this one.

I tried your translation with it, and it seems to be running perfectly! (as far as I can tell from my basic understanding of the Chinese language)

![chinese](https://cloud.githubusercontent.com/assets/882719/20359751/7822a176-ac31-11e6-87d5-8c7f4536027b.png)

**Comment by sanddudu** [comment]
The conversation now move to #667
