### ISSUE TITLE
Image view navigation with right/left buttons

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#669]
Could you give it arrows like this that I added crudely to get my point across. http://i.imgur.com/Dg7Eekb.png I'm sure you could make them look better than this, This is just an example.

They would let us go to the next image without us having to close that window and git the next one.
Make it fade in once your cursor gets to that side of the image. and then fade out once the cursor leaves.

**Comment by Bionus** [comment]
So somehow like suggestion from issue #568, but with buttons instead of using the keyboard arrows to navigate through the images?

It's indeed on my roadmap for the program.

Not quite sure about custom-looking buttons hovering the image though, as I try to avoid custom widgets as much as possible for cross-platform and accessibility. Maybe normal buttons at the bottom as a first step?

**Comment by brodycas3** [comment]
the keyboard would work but like I said to make the buttons appear on it only when the mouse gets near it then fade away like this, https://www.juicebox.net/demos/lite/full/

**Comment by brodycas3** [comment]
updated comment with better URL
