### ISSUE TITLE
Idol.sankaku is using incorrect subdomain for full resolution images

### ISSUE THREAD

**Issue by Tyllyna** [Bionus/imgbrd-grabber#686]
### What steps will reproduce the problem?

When trying to load full resolution image (whether for viewing, single download or batch download), the subdomain used for fetching the image is `iss.sankakucomplex.com`. While it “works”, it is not actually the address that contains the full resolution images: that's the `is.sankakucomplex.com` subdomain. I'm honestly not even sure where does the `iss.sankakucomplex.com` come from when by studying the JSON source, it always links to the `is.sankakucomplex.com` subdomain.

At any rate, according to the log tab, Grabber tries to find to fetch the full resolution image from the `iss.` subdomain with `.jpg`, `.png`, `.gif`, `.jpeg`, `.webm` and `.swf` extensions and eventually falls back to `.jpg` while at the same time prepending the filename with `sample-` and changing subdomain to `is.`. Only on that address the image is found and downloaded, but at that point it's not the highest resolution available.

### What is the expected behavior? What do you get instead?

Using `is.sankakucomplex.com` subdomain for fetching full resolution images. By setting up a local proxy with rule to rewrite `iss.sankakucomplex.com` to `is.sankakucomplex.com`, I can fool Grabber to actually fetch the correct resolution images. Please note that this problem only truly manifests for images that are really high-resolution, I'd guesstimate that the image must be at least 2000 pixels in one dimension. On smaller images, the “sample” and “full resolution” images are the same. FWIW, the rewrite of the subdomain was really enough to fix the problem locally, meaning the rest of the URL can stay the same and work just fine.

### What version of the program are you using? On what operating system?

Grabber 5.0.0 on Windows XP. Don't laugh, it was the only system I had available for virtualization 😃

**Comment by Bionus** [comment]
> While it “works”, it is not actually the address that contains the full resolution images

It doesn't seem to work from here though?
- Thumbnail: https://i.sankakucomplex.com/data/preview/0a/f0/0af025da02bd6e4ec881ec19490186e1.jpg
- Full-size: https://is.sankakucomplex.com/data/0a/f0/0af025da02bd6e4ec881ec19490186e1.jpg

Trying to load "https://iss.sankakucomplex.com/data/0a/f0/0af025da02bd6e4ec881ec19490186e1.jpg" (full-size url with the "iss" subdomain instead of "is") results in a 404.

> I'm honestly not even sure where does the iss.sankakucomplex.com come from when by studying the JSON source, it always links to the is.sankakucomplex.com subdomain.

It comes from the Regex parsing: Grabber takes the thumbnail url and applies two transformations on it: replace "/preview/" by "/" and ".sankakucomplex" by "s.sankakucomplex". The second one actually means "add a S to the subdomain". The problem here is that these transformations should not break already-good urls.

An easy fix before the update is simply changing the tranformation from ".sankakucomplex->s.sankakucomplex" to "i.sankakucomplex->is.sankakucomplex" in Sankaku's model.xml file that can be found in "C:\Users\%username%\AppData\Local\Bionus\Grabber\sites\Sankaku".

> At any rate, according to the log tab, Grabber tries to find to fetch the full resolution image from the iss. subdomain with .jpg, .png, .gif, .jpeg, .webm and .swf extensions and eventually falls back to .jpg while at the same time prepending the filename with sample- and changing subdomain to is.. Only on that address the image is found and downloaded, but at that point it's not the highest resolution available.

Yes, in case of 404, Grabber tries other possible extensions if he is not confident in the one he is using. Then, if all fails, it fallbacks to the sample url.

> By setting up a local proxy with rule to rewrite iss.sankakucomplex.com to is.sankakucomplex.com, I can fool Grabber to actually fetch the correct resolution images.

Kudos on that trick :smile:

> Grabber 5.0.0 on Windows XP. Don't laugh, it was the only system I had available for virtualization 😃

At least it proves that Grabber still works on XP!
But why do you need virtualization to run Grabber? If you're on Linux or OS X, Grabber is pretty straight-forward to build (as long as you don't mind installing the Qt dependencies).

**Comment by Tyllyna** [comment]
> It doesn't seem to work from here though?

Apologies, I think I expressed myself poorly there. It “works” in the sense that Grabber tries to access the `iss.` subdomain several times, then falls back to `is.` but prepends the filename itself with `sample-`, therefore downloading at least something, but not the thing people would probably want. Nothing ever gets downloaded from the `iss.` subdomain, that's true 😄 

> An easy fix before the update is simply changing the tranformation from ".sankakucomplex->s.sankakucomplex" to "i.sankakucomplex->is.sankakucomplex" in Sankaku's model.xml file that can be found in "C:\Users%username%\AppData\Local\Bionus\Grabber\sites\Sankaku".

I'll try that once I have few minutes of a time!

> Kudos on that trick 😄 

Thank you 😄 

> But why do you need virtualization to run Grabber? If you're on Linux or OS X, Grabber is pretty straight-forward to build (as long as you don't mind installing the Qt dependencies).

That's exactly the thing, it didn't seem all that smart to install the Qt dependency for just one program, especially since I've got a fairly fresh and clean installation of the system. Isolating it to VM that I can delete once I have obtained what I need seemed more reasonable.

Thank you so much for looking into this, by the way. I've got one more issue regarding tags being ignored during large batch download and everything getting put into one huge `misc copyright/unknown character` folder but I need to first do some more research on that topic before I open an issue for that – plus I've seen that several people had this issue in the past so I need to go through their tickets first and see if I can resolve it by myself.
