### ISSUE TITLE
Images Detailed Filesize some issues

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#688]
There are in details window some troubles with showing file size
1. Maybe wrong translation in english, looks like it must be "b, Kb, Mb, Gb" but not "Mio" and etc.
2. It might be worth a round to 2-3 decimal places
![29112016_160929_mastercore](https://cloud.githubusercontent.com/assets/22294259/20711799/837dd9a2-b652-11e6-9480-6eb5aa75e6d0.png)
3. From most of all sources in details filesize - unknown, filesize shows only for yande.re and ichijou.org, i think it is not normal.
![29112016_181045_mastercore](https://cloud.githubusercontent.com/assets/22294259/20715300/cc44e2d6-b65f-11e6-9144-a5b493ada457.png)

P.S.
I think there are good idea to show filesize and image resolution directly in preview window(in section where tags are displayed) because this is very useful information if you decide to save picture or not.
![29112016_180246_mastercore](https://cloud.githubusercontent.com/assets/22294259/20714948/a7d64940-b65e-11e6-9b5c-3f9a363cd95c.png)

**Comment by Bionus** [comment]
1. It should indeed be "B" and not "o" in the units. The "i", however, is correct. KB is an ambiguous unit as it could either mean 1024 bytes (B) or 1000 bytes. KiB (kibibyte) is explicit and always mean 1024 bytes. That's why hard drives showing 1000 GB on the package actually show at 931 GB (GiB) in Windows.
2. Indeed.
3. It depends on the source actually, not all of them provide this information. But after seeing issue, I checked and some sources that **do** provide it still have it at "unknown". Plus, when the full-size image is already downloaded for the display (and not the sample), the size could be set automatically.

>  I think there are good idea to show filesize and image resolution directly in preview window(in section where tags are displayed) because this is very useful information if you decide to save picture or not.

Why not indeed, even if I myself don't see advantage.
However, if it works in your example with the tags on the left, what about when the tags are above the image? Adding a new line would highly reduce the height of the image:

![image](https://cloud.githubusercontent.com/assets/882719/20726290/31761002-b675-11e6-8ef9-94e3cb83a959.png)

**Comment by MasterPetrik** [comment]
>  Adding a new line would highly reduce the height of the image

File Size and resolution does not occupy too much space on the screen, it occupy as much space as 2 average tags, but unlike tags this text in most cases have a fixed length and you will always know how many space was occupied. Much bigger problem is when the tags are above the image, there are much less space for them anyway. Not rarely situations, when all tags fits perfect on the left, but in the top tag view scroll bar appears... almost all boorus places tags on the left for this reason.

Here are some solutions for you:
![31761002-b675-11e6-8ef9-94e3cb83a959](https://cloud.githubusercontent.com/assets/22294259/20737816/30a535e0-b6c0-11e6-915c-144997ac7725.png)
![31761002-b675-11e6-8ef9-94e3cb83a959 3](https://cloud.githubusercontent.com/assets/22294259/20737825/3e2d9036-b6c0-11e6-879b-1da1d7d94c63.png)
![31761002-b675-11e6-8ef9-94e3cb83a959 2](https://cloud.githubusercontent.com/assets/22294259/20737828/43b4080a-b6c0-11e6-809a-15d9f108bde2.png)

**Comment by brodycas3** [comment]
the last one is interesting

**Comment by Bionus** [comment]
The last one also looks interesting, and reminds me of how many browsers and image viewers do. The second one takes too much space, while if the first one is also a good suggestion, I'm afraid that this information may be lost in a tag mess when there's a lot of tags.

> Much bigger problem is when the tags are above the image, there are much less space for portrait images(as you know, most of all images from boorus have portrait orientation). Not rarely situations, when all tags fits perfect on the left, but in the top tag view image heigh will be redused

That's why I added the "Auto" setting: with portrait images, the tags are on the side, while in landscape they are above, giving as much space as possible to the images. It's far from perfect though, as it considers the window as a square.

The other reasons are also very correct though.
