### ISSUE TITLE
Next image with scrollwheel

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#691]
Could you make it so when we scroll with the mouse wheel it goes to the next picture, Kinda like how win 10 photo viewer did it before they removed it? Since you added it, it should be properly implemented.

http://i.imgur.com/7BV3wIl.png
http://b.reich.io/kmzwow.mp4

**Comment by Bionus** [comment]
I was going to reply your email but I'll reply here instead.

Isn't the scroll wheel above an image usually linked to zoom in UX? I've never seen image navigation with the scroll wheel except for Irfanview. Is there other programs doing this?

**Comment by brodycas3** [comment]
The window photo viewer used to do it, and some websites do it. I reposted
here because i thought the email had been lost.

**Comment by Hrxn** [comment]
XnView, Irfanview, Fast Picture Viewer and FastStone viewer all use the scroll wheel for navigation by default..

**Comment by Bionus** [comment]
In that case it makes sense to add it indeed.

**Comment by brodycas3** [comment]
good

**Comment by MasterPetrik** [comment]
Well, it would be a really good function, of course if it will be optional

**Comment by brodycas3** [comment]
Enabled by default and have the option to disable. There are probably so
many people who don't know about features because they are disabled by
default like the preloading images.

**Comment by MasterPetrik** [comment]
there are a little problem why this function will be not so convenient in THIS programm how it be in common image viewers. In image viewers all pics placed on your PC and delay when you scrolling images with mousewheel is minimal, but Grabber need to download every image, for me even with 100mb/s internet still need a 0,5-1,5 sec for loading every image, so it will be not so fast as you can expect, but if you miss click by mouse weel you will need to wait several seconds(because when you turn wheel you can scroll many images at onse) to return to required image

**Comment by brodycas3** [comment]
That's why we have the option to enable preloading images.

**Comment by MasterPetrik** [comment]
Damn good, just enabled preloading, thanks man, thanks Bionus, then I have no objections anymore
