### ISSUE TITLE
Image scrolling issue

### ISSUE THREAD

**Issue by Zekken01** [Bionus/imgbrd-grabber#698]
When using the buttons to move between images and you get to the last image it wraps around back to the first image instead of going to the first image of the next page.

Removed link.

I started on the last image and when I pressed next it went to the first image.

**Comment by MasterPetrik** [comment]
Not good. In many countries(and mine too) goverment will block all github site only for one your gif with loli shota. Please, if you want to reproduce a bug use if you can neutral search request -_____-

But anyway I confirm strange behavior of ">"(next image) button in Preview window, while "<" button seems to work normal.
For example here I shown what happens in you open first image and go ">" to the next images, its a really weird way, and in some moment it will show images that isn't shown on this page images instead of go in cycle and go back to first image...
And yes, on step 10 grabber for some reason changes its direction and go straightly opposite way
![02122016_062604_mastercore](https://cloud.githubusercontent.com/assets/22294259/20822319/c71706ca-b85a-11e6-9ed7-7a08b9db908f.png)
I know that it looks like comletely madness, but I swear, this is how it was!
All that steps I reprodused in this video:
https://youtu.be/ITFORhcr0s0

**Comment by brodycas3** [comment]
Ok, I removed the link.  btw why do you have so many open windows?

**Comment by MasterPetrik** [comment]
i'm trying to organize my image folders, and i feel uncomfortable if I'm not keep 1934 tabs in chromr open... ^__^

**Comment by Bionus** [comment]
Wow. As you say, it's indeed amazing. Especially that it only happens with the ">" button.

I just tried to reproduce however, with no success. I'll try in more detail tomorrow and see if I find a way to reproduce and to fix the issue. I have an idea of what might be the problem but I have to make sure that's it first.

> Not good. In many countries(and mine too) goverment will block all github site only for one your gif with loli shota. Please, if you want to reproduce a bug use if you can neutral search requests -_____-

Indeed. I'm not even sure Github itself allows it. In any case, it's better to keep every screenshot safe, or at least "questionable" (to keep boorus' vocabulary). Best option is to screenshot results for the search "rating:safe" (and from "classical" sources, if applicable).
