### ISSUE TITLE
Idol.sankaku tag issues during mass download

### ISSUE THREAD

**Issue by Tyllyna** [Bionus/imgbrd-grabber#717]
### What steps will reproduce the problem?

When attempting to download large amount of images from `idol.sankakucomplex.com` with `%search%/%copyright%/%character%/%md5%.%ext%` naming scheme, a suspicious amount of images get lumped together in `<searchterm>/misc/unknown/<filename>.<ext>` folder, indicating that either the image doesn't have copyright and character tags or Grabber was unable to find them (or – grasping at straws here, but maybe it was able to find them, just not in time? I believe I've found a mention of similar bug with similar underlying cause when searching the issue tracker.)

Anyhow, upon further inspection, it seems that both cases are true – and while first case is obviously problem of the image not being tagged and Grabber is behaving correctly, in many cases the image has all the tags yet Grabber doesn't recognize them and that's obviously an issue. For example, when downloading search term `akitsu_honoka`, [this](https://idol.sankakucomplex.com/post/show/529667) image was downloaded into the `akitsu_honoka/misc/unknown` folder even though it should be saved into `akitsu_honoka/puella_magi_madoka_magica/group` folder as that particular image has one copyright tag and two character tags.

Just to make sure it's not just problem of misconfiguration on my side, Grabber is configured to set `copyright` to `misc` if empty and to `crossover` in case of multiple tags; similarly, Grabber was instructed to set `character` to `unknown` if empty and `group` in case of multiple characters.

The download log mentions obtaining tags (`Tags received`) anytime the image is received, if that's an interesting information. In fact, for each image downloaded, there's always three entries in this exact order: `Tags received`, `Loading image from <url>` followed by `Image received from <url>`. As far as I can see, these lines never appear in any other order.

### What is the expected behavior? What do you get instead?

Grabber should always recognize all tags. But in many cases, it doesn't do that – on my test mass download of 290 images for the aforementioned search term, 120 of them were put into the `misc/unknown` folder and while some are definitely legitimate cases, many are definitely not. I was unfortunately unable to observer any discernible pattern that would explain Grabber's erratic behaviour but I'm definitely willing to help sorting this issue in any way possible.

### What version of the program are you using? On what operating system?

Grabber 5.0.1 on Windows XP. Keep not laughing, it was the only system I had available for virtualization 😃

**Comment by Nomahd** [comment]
Seconded. Tags for chan.sankaku not working as well. This occurs after applying the temporary fix to issue [#709](https://github.com/Bionus/imgbrd-grabber/issues/709)

**Comment by Bionus** [comment]
First, thanks for the detailed issue!
It seems there's indeed an ongoing issue with Sankaku's tags not being recognized. I'll start another bunch of investigations on it and try to push a fix ASAP.

> or – grasping at straws here, but maybe it was able to find them, just not in time? I believe I've found a mention of similar bug with similar underlying cause when searching the issue tracker

Thanks to the information you gave, it's pretty sure the problem does not come from that, since you always get the `Tags received` message first (thanks a lot for that information BTW, it will speed up my investigation).

**Comment by Bionus** [comment]
After investigation, it seems to come from the throttling not working properly for tags loading, causing HTTP 429 errors: `Too many requests - please slow down...`.

**Comment by Bionus** [comment]
I just pushed a fix that will be included in the next release, adding throttling to the details loading.

By default, it only applies a 60s freeze after a HTTP 429 error to wait for the limit to reset, but you can configure everything in Sankaku's source settings, for example adding a 3 seconds throttling for the details and page, to slow everything down, but without big breaks. You can experiment and find the best values, but going full speed then waiting for the limit (the default) **is usually slower**. It also makes sense to disable simultaneous downloads (set it to 1) if you usually download from Sankaku.

My manual test resulted in the expected 49 "misc/unknown" images for the 300 first results of "akitsu_honoka" on idol.sankaku.

Note that the newly introduced throttling will make batch downloads seem much slower, since with the fix it will wait for the limit to reset after ~3 minutes instead of continuing downloading without tags. You can if you wish change your filename to not include special tags information (`%artist%` & co), as in that case the detailed tags are not loaded at all. But in most cases waiting is not really an issue.

**Comment by Tyllyna** [comment]
Thank you so much for the fix and apologies for very late reply – all the Christmas madness has only now finally started to settle down. I really appreciate this fix and can't wait to try out the 5.1.0 version when it's released!

However, and please please don't take this the wrong way, I am just wondering if the throttling is really needed – or better said, if fetching the individual pages for each image is necessary. The reason for asking this is following: I understand that mass downloading is… sort of a three-stage process in which Grabber first loads basic information about each image, then fetches detailed information about each image and forms a download queue based on the detailed information and finally downloads the images from queue. Well, I haven't looked at the code but on the outside, it looks like this is roughly what's happening.

However, when looked at the basic information obtained in first step – in the case of idol.sankaku, data obtained from the `GET /post/index.json?login=<redacted>&password_hash=<redacted>&appkey=<redacted>&limit=200&page=1&tags=akitsu_honoka HTTP/1.1` API call – it seems that the received information is actually pretty detailed, you can have a look at it [here](https://gist.github.com/Tyllyna/9d59d1de518809b8b3a0b57ce8132da2) (captured with local proxy server again; be warned, it's a very long JSON).

Quick note about the limit parameter, it seems that maximum number of images idol.sankaku is willing to return is 250. Any more than that gets cut off from the response. Setting the limit to something between 200-250 greatly reduces the number of requests you have to make, even though the more demanding requests take significantly longer to complete.

Back to the JSON: for each image, I see a `file_url` entry (which I assume is the link to the image in maximum possible resolution – but this assumption of mine needs some checking first) but I also see the `tags` array already! These tags are even annotated by their type, for example type 4 seems to indicate `character`, type 3 looks like `copyright` and so on. I assume these are the same types that are used everywhere else.

So I don't know how difficult this would be to implement but maybe some data sources (such as JSON data source for idol.sankaku) could effectively skip fetching the detailed page for each image because everything that's needed can be obtained from the very first request. I can also imagine this being pretty much impossible to implement due to how different sources and sites can vary but I just thought that this would be an interesting information to mention :)

Thank you for your hard work and I wish you all the best in 2017!

**Comment by Bionus** [comment]
> I really appreciate this fix and can't wait to try out the 5.1.0 version when it's released!

The planned release date is sometime this week, likely Saturday or Sunday.

> I understand that mass downloading is… sort of a three-stage process in which Grabber first loads basic information about each image, then fetches detailed information about each image and forms a download queue based on the detailed information and finally downloads the images from queue

That's pretty much it, except that the step 2 "fetches detailed information about each image" is only done when necessary, that is when the detailed tags are not already available.

> but I also see the tags array already! These tags are even annotated by their type, for example type 4 seems to indicate character, type 3 looks like copyright and so on

Well that's news to me. Sankaku always used to only return the basic tag information as a space-separated string, without any information about tag types. Since it seems that as you say they improved their API, the program should be updated to use said tag information instead of making an unnecessary request.

> Quick note about the limit parameter, it seems that maximum number of images idol.sankaku is willing to return is 250.

Same here, they used to block anything which wasn't 20 (our 42

**Comment by Tyllyna** [comment]
> That's pretty much it, except that the step 2 "fetches detailed information about each image" is only done when necessary, that is when the detailed tags are not already available (or unnecessary if the filename does not need them).

Oh sweet, so Grabber was pretty much ready for this situation! That's good to hear 😄 

I'm glad I could help!
