### ISSUE TITLE
Add Pixiv source

### ISSUE THREAD

**Issue by Zekken01** [Bionus/imgbrd-grabber#738]
I know this isn't a suggestion about a booru but I was wondering if you could add a Pixiv downloader to grabber. I'm sure a lot of people would get usage out of it. I'm sure you could pull it off in a magnificent way.

**Comment by MasterPetrik** [comment]
please describe in more details how this Pixiv downloader should looks like

**Comment by brodycas3** [comment]
Well, I was thinking you could add a new tab for it. You might be able to use this to build off.
https://github.com/Nandaka/PixivUtil2
IDK I'm sure Bionus could figure it out, He is pretty smart.

**Comment by Bionus** [comment]
How is Pixiv different from any other source?
Why does it need a separate tab?

**Comment by MasterPetrik** [comment]
Well, Pixiv in most cases is the original source of content for all boorus, many of them even have direct pixiv link as source of their images. Moreover you can see on many boourus tags like "Pixiv_id#####" instead of artist tag, because, as I said they mostly uses content from Pixiv, which technically isn't booru site, but more like social network for artists(like deviantart in europe) 

So it will be very cool to add searching on Pixiv, but adding new tab for it... hmm Isn't adding it to sources will not be enough(but It could not be possible because Pixiv is not a booru site and have(is he?) a different api) in that case separated tab for it will be necesery.

Anyway, Bionus, take a close look on Pixiv and tell us what you will decide.

**Comment by brodycas3** [comment]
Well, Pixiv like MasterPetrix said isn't a booru site. The tagging system also doesn't work the same way as in a normal Booru. It would make more sense to allow it to have its own tab.

**Comment by MasterPetrik** [comment]
As you can see, boorus are very pixiv related
![08012017_231317_mastercore](https://cloud.githubusercontent.com/assets/22294259/21753197/9c0e1e08-d5f8-11e6-9606-bca791c9aaa7.png)

**Comment by Bionus** [comment]
Yeah I know that.

What I fail to grasp is why would Pixiv need a special tab instead of just using the usual one with the tag search? The only major difference I see is the way uploaded images are closely linked to their users.

**Comment by MasterPetrik** [comment]
If you can add it to source menu it will be more logical, but, at first, as I know pixiw shows HD images only to loggined users, and many other troubles can appear while integration, but if you can, do it in normal way, then special tab isn't needed, I guess

**Comment by brodycas3** [comment]
It only shows images to logged in users.

**Comment by MasterPetrik** [comment]
Overusage can lead to Pixiv blocking your IP for a few hours. Nice for bath download)

**Comment by brodycas3** [comment]
>>Overusage can lead to Pixiv blocking your IP for a few hours. Nice for batch download)

After using pixiv downloader I don't believe this is true, I have downloaded thousands of images non stop without any problem totaling 100gb
