### ISSUE TITLE
%all% line without size,format,res and so on in external text file

### ISSUE THREAD

**Issue by CuddleBear92** [Bionus/imgbrd-grabber#749]
as the title says: %all% line without size,format,res and so on in external text file.
meaning a way to write %all% without having the size of the file, the format of the file and the extension.
so just the tags.

on a sidenote, anyway to write tokens only when its available? and one token:tag per line aswell? 

reason i and a few others users want this is cause Hydrus imports all lines, one line as a whole as a tag. meaning it will import the formats and size (something we dont need and will actually just waste resources in the system on out side).

if it was tags and just tags then it will import smoothly.

**Comment by Fillyosopher** [comment]
To add detail to this, the prefer hydrus format is namespace;tag on individual lines, with general tags having no namespace.  For namespaces, it uses creator instead of artist, and series instead of copyright.  Despite many attempts messing with the options, it doesn't seem possible to have grabber generate a text file in this format, especially since it converts all ':' to '_' in the text file.

In the mean time %all% plus some text replacement is a decent, if annoying, replacement process.
