### ISSUE TITLE
Some issues with the downloads of images and the searching.

### ISSUE THREAD

**Issue by BlazeDarkan** [Bionus/imgbrd-grabber#759]
Good morning, afternoon, or night, the problem is the following, sometimes when the program finishes downloading the images, in some cases when the message "I finish downloading all the images" appears, it also appears that not so many images were downloaded Because they already existed:
![captura](https://cloud.githubusercontent.com/assets/25396162/22393124/dd10cd84-e4cf-11e6-9987-bf5c2848d160.PNG)

But when I check the gallery of images that I was downloading, I go to the end of this and I realize that you have to download the images manually that do not detect the program or that according to this already exist, in some galleries the solution is simple, go to end of this and download the images that do not download the program that sometimes can be 3 or 4, but it is not always so, in other cases although the program says that we can miss the last four images, it does not refer precisely to the last four Of the previous case, but refers to missing four that are scattered throughout the gallery that has downloaded, in a few words look for the images one at a time until you find it.

The other problem is that the program does not detect some authors or does not detect some searches, for example look for affect3d or gureko rouman and it appears that there are no results:

![captura7](https://cloud.githubusercontent.com/assets/25396162/22393401/c4287674-e4d3-11e6-9594-9742534aac79.PNG)

Some other information would be that I use chan.sankakucomplex.com to perform the downloads.

One suggestion to add to the program on file formats would be .swf if I'm not that bad for flash-like formats.

And a doubt I have, why sometimes in the tags appear some in blue? Because when I check the sankaku page the tag appears in another color like pink or coffee.

Now to finish I want to tell you how much I thank you for having developed the program because I know that doing this type of project can be exhausting, thank you very much, I believe that if my knowledge of programming were more advanced I would help you, the only thing that I can say thanks for all that dedication and for the time you take to develop this project.

**Comment by BlazeDarkan** [comment]
Forget to say I use win10 anniversary version and grabber 5.1.0

**Comment by Bionus** [comment]
For your main issue with the "4 already existing images", I believe that's because Sankaku puts the top 4 images on the first page? So Grabber first download the top 4 images, then the remaining 20*number of pages images. However, in these images will definitely be the top 4 ones, as duplicates, so Grabber will skip them because it already downloaded them at the beginning.

I'm not sure I understand what you mean by downloading them manually however. Wouldn't trying to do so only cause them to be skipped once more?

> The other problem is that the program does not detect some authors or does not detect some searches, for example look for affect3d or gureko rouman and it appears that there are no results

These two tags yield no results on chan.sankaku unless you're logged in. Did you specify your credentials in Sankaku's source settings?

> One suggestion to add to the program on file formats would be .swf if I'm not that bad for flash-like formats.

What do you mean? SWF is already supported and can be downloaded. It can't be played however, and it's unlikely it ever will. Integrating a flash player is too much. However, in 5.1.0, you can double click it, and if you have flash installed, it will open it in the official Adobe flash player.

> And a doubt I have, why sometimes in the tags appear some in blue? Because when I check the sankaku page the tag appears in another color like pink or coffee.

You can change the colors in "Options > Interface > Coloring". Blue is for circles on Sankaku. I used the original colors when I first added it, but maybe they changed them later on.

> Now to finish I want to tell you how much I thank you for having developed the program because I know that doing this type of project can be exhausting, thank you very much, I believe that if my knowledge of programming were more advanced I would help you, the only thing that I can say thanks for all that dedication and for the time you take to develop this project.

Thanks! I'm always happy to have satisfied users! It indeed is a lot of work, but reporting detailed issues is already a lot of help for me (as I don't have to search too long to find the root cause). :smile:

**Comment by BlazeDarkan** [comment]
Sorry for the delay in answering I had a few weeks hard, you're right I assumed that just connecting to sankaku could download all the images, not connecting to the program, my error, sorry.
