### ISSUE TITLE
not enough information

### ISSUE THREAD

**Issue by maskkulin** [Bionus/imgbrd-grabber#774]
When I download like 1000 images of a tag and the next day I want to continue exactly where I left, then I need to know which was the last downloaded page, but there is no page count. I would also like to know why an image was ignored

**Comment by maskkulin** [comment]
can you invent an option so that one can see the main.log live? I mean without having to reopen it every time I want to see what changed, it should be fused with grabber

**Comment by Bionus** [comment]
> When I download like 1000 images of a tag and the next day I want to continue exactly where I left, then I need to know which was the last downloaded page, but there is no page count.

I'm not sure what you mean by that. If you download the first 20 pages of a tag by batch download for example, you could keep it in Grabber, and it will be here again next time you open the program. Then you would know where you were when you left off. Grabber downloads from `page` to `page + (image limit / images per page)`. It's not always obvious indeed, but saying "from page 1 to 10" is not always either, since most imageboards have different counts of images per page.

> I would also like to know why an image was ignored

How would you want to see it? I think there's currently a line in the log for every ignored image as well as a short explanation. What kind of UI would you rather have?

> can you invent an option so that one can see the main.log live? I mean without having to reopen it every time I want to see what changed, it should be fused with grabber

There should already be a "Log" tab in the main window showing the log. Maybe it's been disabled in your settings?

**Comment by maskkulin** [comment]
>  If you download the first 20 pages of a tag by batch download for example, you could keep it in Grabber, and it will be here again next time you open the program.

Why do you say that? I thought the batch download progress will not be saved. Only the data I typed into the group fields. Like I started with page 1 and downloaded 20 pages, but the group is static, the progress I did within the batch download and the things I typed in before starting the batch download, are totally separate from each other. next time I open it, it will still show  page 1, so I need to keep track of it by myself.

But it's not mandatory. Would just be more convenient, not having to do the math myself.
