### ISSUE TITLE
Opinions welcome: changes in the batch download process

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#785]
A suggestion for the download process.
Feel free to comment and voice your opinion.

## Download all pages first (current process)

1. Download all pages, store metadata for all images
2. Filter images (blacklists, etc)
3. For each image:
    1. Download it
    2. Generate the filename according to the metadata
    3. Delete the metadata

✅ Easy to implement
✅ Easy to understand for the user
✅ Can copy and paste the list of urls to download it in another software
❌ Takes a lot of RAM as it keeps all metadata in memory
❌ Long preparation phase during which no image is downloaded

## Download pages progressively

1. For every pack of `n` pages (with `n` from `1` to `images limit / images per page`)
    1. Download the pages, store metadata for all images
    2. Filter images (blacklists, etc)
    3. For each image:
        1. Download it
        2. Generate the filename according to the metadata
        3. Delete the metadata

✅ The amount of RAM used is pretty much constant
ℹ️ Keep metadata available during download step
❌ Complicated to implement
❌ Cannot copy the urls since there is only a limited subset of them available at a given time

## Don't keep metadata

1. Download all pages, generate a map of `url` to `filename` pairs for non-filtered images
2. For each pair:
    1. Download the file at the given url
    2. Delete the pair

✅ Less RAM used than now (two strings instead of possibly a lot of metadata)
✅ Easy to implement
ℹ️ No metadata available during download step
❌ Can still take all RAM if the download is big enough
❌ Long preparation phase during which no image is downloaded

## Don't keep metadata, progressively

1. For every pack of `n` pages (with `n` from `1` to `images limit / images per page`)
    1. Download the pages, generate a map of `url` to `filename` pairs for non-filtered images
    2. For each pair, download the file at the given url

✅ Constant very low RAM usage
ℹ️ No metadata available during download step
❌ Complicated to implement
❌ Cannot copy the urls since there is only a limited subset of them available at a given time

**Comment by Bionus** [comment]
Why not all?
There could be a setting to choose which process we want to use, defaulting to "Don't keep metadata, progressively".

**Comment by barryanders** [comment]
If these become options in settings, I would request that their respective descriptions be carried over so that users know what they are choosing and how it may effect their download. Otherwise, I'd probably forget as I'm sure others wouldn't know what it means from the option titles above. I know when I first used Grabber years ago, I didn't know about the RAM limitations like a lot of these other users and I thought Grabber was just crashing due to bugs. Obviously not the case, but I'm glad to see this being looked at. Your production quality keeps going up.

I typically do one image at a time, so this doesn't really impact me, but if I were ever to try and download tons of images, I could see how it might be nice for the program to either automatically favor low RAM usage methods, or to pop up with a statement saying something like, "Warning: you are downloading more than 20,000 images. This batch process may use more memory that your computer has available. If this happens, Grabber will crash. Would you like to continue using Grabber's low memory download method (this will limit your access to metadata)." And then let the choose yes, no, and whether or not to display this warning again. Of course, if they already have a setting selected to favor low memory use, then this popup wouldn't appear.

Just an idea, trying to help brainstorm improvements. Definitely don't take this as a request if it sounds like a headache. I'm just thinking from a user standpoint what sounds nice to me. For me though, I'd be happy with just choosing the mode through settings. Still, some sort of warning on larger downloads might be nice to combat crashes.

**Comment by MasterPetrik** [comment]
Download pages progressively(with or without metadata) is the most proper way to download anything. 
Sooner or later, but I guess that you should use this method. Because question of resource usage of software is the main question for any programm, and if you CAN reduce resource usage, you should do it.
Yes, it will be complicated to implement and will cause more new bugs, but you should do it anyway. 
While development you can do progressive download as an optional mode, addition to current, but when it will be comleted and tested, replace current mode with progressive mode.

>  **Keep metadata available** during download step

> **Takes a lot of RAM** as it keeps all metadata in memory
**Long preparation phase** during which no image is downloaded

Does metadata so important for users? I dont think so. Did they really need it? Hmm...
Did they really agree to sacrifice they RAM, time and ability to download as many images as they want only for keeping metadata? Of course not!

> Can copy and paste the list of urls to download it in another software

Considering how many resurses it cost, maybe could be better to do it a separate function instead of doing it while download? Because obviously almost nobody uses it while download. So I guess it will be not a big deal to separate this function(if somebody still use it) or remove it from download process, and Download pages progressively.

**Comment by Bionus** [comment]
Ok, so the "Download pages progressively" will be implemented in the 5.2.0 release. :smile:
It will very likely change into "Don't keep metadata, progressively" later on, as as MasterPetrik said, since metadata is a technical thing, **if possible** it should be removed to save RAM.

> If these become options in settings, I would request that their respective descriptions be carried over so that users know what they are choosing and how it may effect their download. Otherwise, I'd probably forget as I'm sure others wouldn't know what it means from the option titles above.

Indeed, else that would be another setting users don't know anything about.

> I know when I first used Grabber years ago, I didn't know about the RAM limitations like a lot of these other users and I thought Grabber was just crashing due to bugs. Obviously not the case, but I'm glad to see this being looked at. Your production quality keeps going up.

Actually, me too. When I started on this project, I was a total beginner at C++, so the first versions sucked and always crashed because of memory errors. Now that I've got more experience, all that's left is clean up this legacy mess. :smile:

> I typically do one image at a time, so this doesn't really impact me, but if I were ever to try and download tons of images, I could see how it might be nice for the program to either automatically favor low RAM usage methods, or to open a popup

Since the only downside to using the low RAM option is that you cannot copy the urls to the images and that the download process may look more complicated to new users, wouldn't it be even simplier to always enable it, whatever the size of the download?

> Does metadata so important for users? I dont think so. Did they really need it? Hmm...
Did they really agree to sacrifice they RAM, time and ability to download as many images as they want only for keeping metadata? Of course not!

More than whether they want it or not, it's a kind of technical limitation. In my example, I mention making a `url` to `local filename` pair. But that doesn't work if you add the SQL commands or separate text files in the equation. In these two cases, one should either pre-calculate everything (so it wouldn't be a pair anymore, more like a set with the url, local file, content of the separate text file, sql commands, etc.), or keep the metadata to generate it when necessary.

So I'll try to move towards this goal to save even more RAM, but I just tried the new progressive download feature, and it already cut the RAM usage greatly. Whatever the number of images you download, it will take as much RAM as if you only downloaded 1,000 images.

> Considering how many resurses it cost, maybe could be better to do it a separate function instead of doing it while download? Because obviously almost nobody uses it while download. So I guess it will be not a big deal to separate this function(if somebody still use it) or remove it from download process, and Download pages progressively.

Indeed, if it turns out to be a requested feature, it could be added separately. And if it turns out nobody or very few people want the urls, they can use to CLI as what they want is a non-standard usage (from my knowledge of the user base, but well, I don't know all users).

**Comment by MasterPetrik** [comment]
> Ok, so the "Download pages progressively" will be implemented in the 5.2.0 release. 

Changes in Preview GUI, in downloads method... And many minor features... looks enough for 6.0.0?

**Comment by barryanders** [comment]
Based on previous versioning, `5.X.X` will be around for awhile.

**Comment by Bionus** [comment]
Indeed. This is not a big enough change to deserve a major version, especially since most of it is technical.

One such change would be the Javascript sources + adding a bunch of SFW sources.
Another would be a full revamp of the favorites area, with for example automatic download of images containing a favorited tag.

> P.S. Tell me please, when you expect to release next update, even approximately? If it will be not very soon, then I will post some issues for this update or I leave for the next update.

I planned to do it this week-end, maybe Sunday. Given the fact I release around every month these days, if you want those things done within the next two days, you'd better post them now so they can be included (if possible) in the update. Else you may need to wait for a while.

**Comment by MasterPetrik** [comment]
Thanks for the explanation. I much better understand version system now.

**Comment by Bionus** [comment]
If you want more info, I'm trying to follow [Semantic Versioning ](http://semver.org/).

**Comment by MasterPetrik** [comment]
Thank you! Very helpful info.
