### ISSUE TITLE
dumb behavior

### ISSUE THREAD

**Issue by maskkulin** [Bionus/imgbrd-grabber#786]
why does this program looks what pics I have downloaded in my other folders?? Look this program skips images that are in my test folder, this is from the log: `MD5 "6476913b8bd8a5a99e384137ccccfdb6" of the image https://cs.sankakucomplex.com/data/64/76/6476913b8bd8a5a99e384137ccccfdb6.png already found in file J:\Hentai\Yuri\Sankaku Complex\test\`
that's an extremely retarded move because that folder has nothing to do with my current folder

**Comment by Bionus** [comment]
Quite aggressive here.

That's because your you set "If a file already exists" to "Don't save" (in the "Save" part of the options window). By default, it's "Save" which will create duplicates depending on where the file is saved.

If you don't want this feature, just set it back to "Save".

**Comment by maskkulin** [comment]
yeah sorry, because now I have to download everything again..
damn I thought this option was only meant for the current folder, since I don't want multiple duplicates in one folder, you should've described it better

**Comment by Bionus** [comment]
It will only download the pages twice, the actual images don't need to be downloaded again and will be skipped. You can also set it to "copy" and it won't even download the images again, just copy the ones already downloaded in your other folder.

**Comment by maskkulin** [comment]
okay I will try
Hey I have one question. I just tried to delete the other folders and there were pics which filename is too long, I cant delete them. Can't your program prevent too long filenames?

**Comment by Bionus** [comment]
>  Hey I have one question. I just tried to delete the other folders and there were pics which filename is too long, I cant delete them. Can't your program prevent too long filenames?

It should already have such security. Can you give me a few examples of such filenames? (from "C:" to the end of the filename) So I can see why the security didn't work. Did you change the "Max length" setting in the save area? (by default it's 0)

**Comment by maskkulin** [comment]
I can't copy the filename or the path. No I didn't change "max length". The only thing I changed on all tokens is "keep n tags 4" because I don't want that the tags to change their name when they are too long, or is there a better alternative?

**Comment by Bionus** [comment]
> I can't copy the filename or the path

Not sure I understand. You mean you didn't manage to, or don't want to? If you didn't manage, you can just right-click then "Properties", the full path is there, as well as the filename. And if it's because you don't want, well I'll respect that choice but it's gonna be harder for me to find the root cause. :smile:

Were these files downloaded using a batch download or the image window?

> The only thing I changed on all tokens is "keep n tags 4" because I don't want that the tags to change their name when they are too long, or is there a better alternative?

Not sure I understand what you mean here. You mean that when a filename is too long, it will be truncated? Your settings should have no impact on this.

**Comment by maskkulin** [comment]
No I can't click on properties, I can only move the folder to a different location. When I did that or renamed the folder, I could view it again and delete it. So I think it happened because the path-name was too long 
You can try it yourself, copy one of your folders, it won't let you copy all files  

> Not sure I understand what you mean here. You mean that when a filename is too long, it will be truncated? Your settings should have no impact on this.

default it was set to `if more n tags than 5; replace all tags by e.g. multiple artists`.
I didn't want that, so I changed it that it to always keep 4 tags and don't replace. But I don't think this is relevant here, because the program just cuts the filename if it's too long

**Comment by maskkulin** [comment]
btw
![image](https://puu.sh/u51PU/f602d15e81.png)
do you know what this means? what is this % count ?

**Comment by Bionus** [comment]
Well thankfully I know what it means, since I made it! :smile:

It means that if there is more than `n` tags, something should be appended. Let's say you set it to "Keep 3 tags then add ` (+ %count% others)`".
* `tag1` -> `tag1`
* `tag1 tag2 tag3` -> `tag1 tag2 tag3`
* `tag1 tag2 tag3 tag4 tag5` -> `tag1 tag2 tag3 (+ 2 others)`

You can also use `%total%`, such as "Keep 3 tags then add ` (%count% tags ignored, %total% tags total)`":
* `tag1` -> `tag1`
* `tag1 tag2 tag3` -> `tag1 tag2 tag3`
* `tag1 tag2 tag3 tag4 tag5` -> `tag1 tag2 tag3 (2 tags ignored, 5 tags total)`
