### ISSUE TITLE
Shimmie sites having proplems reading and showing tags

### ISSUE THREAD

**Issue by Yarott** [Bionus/imgbrd-grabber#808]
### What steps will reproduce the problem?
Load any images from any shimmie-related site, like paheal. 

### What is the expected behavior? What do you get instead?
After a few images loaded, every other image has the tags broken, and the image stays like a thumbnail. It tends to just load 3 sets of double slashes, the resolution, and then the file size of the image/video/etc when this error happens. The image pretty much loads minutes afterwards, but that's still not OK for a program like this one. Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/17222908/23344230/09ff0f40-fc4f-11e6-8c2d-7b1e86ee87e0.png)

### What version of the program are you using? On what operating system?
Grabber 5.2.2 for Windows.

### Please provide any additional information below
I tried removing my blacklist of tags, to see if that worked, but nothing. I also tried keeping the search empty, to see if it breaks due to choice tags, but also nothing. Same problem keeps happening. I then, finally decided to uninstall the program, and deleted all AppData files related to Grabber, and nothing. Finally, I tried using credentials, with an account, maybe that could've helped (I probably did it wrong there, maybe not), tried and failed. The images taken from shimmie also seem to load really slowly, compared to any other site supported by Grabber. I hope there is a solution found, because I feel clueless about this issue.

**Comment by Bionus** [comment]
Your speed issue might actually be the cause you are seeing this. `rule34.paheal.net` is blazing fast for me, so I indeed see the problem you describe, but only for a split second before the `//` mess gets replaced by the proper values.

Seems like the Regex parsing has some issues, so I'll push a fix for that. Nothing I can really do about the loading speed though, since I can't reproduce any speed problems the problems might be your connection to the site. Is it fast when browsing it online?

**Comment by Yarott** [comment]
Yeah, the speed is back. It was probably server side, since the load speed issues were only going wrong for that site. But the tags still appear briefly broken, as you realized. I'll wait for your update. Thanks for the response to the matter!
