### ISSUE TITLE
dark mode?

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#813]
Is there any way to get a dark mode? Or for us to make our own themes and upload them? I think that would be really cool. I'm sure some power user would be able to do something really cool with that power.

**Comment by MasterPetrik** [comment]
Seriously? I mean, grabber doesn't have its own interface, it uses OS interface, different for Windows, Linux and Mac, that's much better then use own interface, because I guess there are will be needed to fully rebuilt all GUI only for custom skins? Is it really worth it? Do you dislike your OS interface so much?

**Comment by Bionus** [comment]
Well, if you're good at CSS, all of Grabber's UI can be customized by, as you say, a power-user.

I can provide a way to set Grabber's global stylesheet, but I don't think I'd want to spend the time myself to make a dark theme. That would mean a big work at the beginning to have it work everywhere in Grabber's interface, plus for every UI change update it if it's broken.

As MasterPetrik said, I try to keep everything as close to the OS as possible by default, so that the looks are coherent depending on which OS you use. Plus, I've never been a big fan of custom interfaces either, given how they're usually broken for people with handicap, or simply when a new version of the OS comes out. Old java applications are a good example of what's the result of doing this.

So I'll add a way to set your own CSS, but I can't guarantee much more.

Documentation for how to use it can be found here:
https://doc.qt.io/qt-5/stylesheet-reference.html

**Comment by brodycas3** [comment]
How do I add CSS? Where is the file?

**Comment by barryanders** [comment]
The color menu seems like a good place to start at least. There doesn't seem to be any mention in the program of using CSS, but I didn't look very long.

![screen shot 2017-03-21 at 9 05 38 am](https://cloud.githubusercontent.com/assets/5648875/24151040/9b190c42-0e15-11e7-96ec-18df3a455e1f.png)

**Comment by Bionus** [comment]
You can find documentation on how to add a new theme in the wiki:
https://github.com/Bionus/imgbrd-grabber/wiki/Themes

Once you created your theme, you can find it in the "Interface" part of the options window.

**Comment by brodycas3** [comment]
😄 
![image](https://cloud.githubusercontent.com/assets/19770864/24154603/0439d618-0e28-11e7-9221-1b6ff4e07cd3.png)

I just used this style sheet. https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/qdarkstyle/style.qss

**Comment by brodycas3** [comment]
Thank you for implementing this. ❤️ ❤️ ❤️ ❤️

**Comment by MasterPetrik** [comment]
my tags coloring if you want:
![image](https://cloud.githubusercontent.com/assets/22294259/24164386/91961016-0e7e-11e7-8a95-18eb9a7330a0.png)

**Comment by brodycas3** [comment]
I thought you were against theming. Now you're using it? lol. Those colors are good. Thankyou

**Comment by MasterPetrik** [comment]
It was just a try. Anyway, in fact, I wasn't against themes, I was afraid that it will require to rebuilt all gui from the beginning, but it turned out that QT supports custom themes on CSS by default, so it is a very good.

**Comment by brodycas3** [comment]
I'm not going to lie, This is the second program I got to support custom
themes with CSS.
