### ISSUE TITLE
0.00B/s when downloading

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#814]
### What steps will reproduce the problem?

Download every image on every source

### What is the expected behavior? What do you get instead?

It will show me the speed

### What version of the program are you using? On what operating system?

v5.2.2 on win 10

### Please provide any additional information below

http://i.imgur.com/s0qY5Ol.gifv

**Comment by MasterPetrik** [comment]
I don't see a problem here. Grabber works normal. "0.00B/s" shows not when downloading, but when IGNORING already existed images, grabber isn't download anything and that's why in these moments speed is 0.00B/s. As you can see in your gif, when grabber REALLY download images, it shows speed properly, so this is not a bug
