### ISSUE TITLE
Crash when doing nothing

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#829]
### What steps will reproduce the problem?

Idk, I was doing nothing and it crashed.

### What version of the program are you using? On what operating system?

v5.2.2

### Please provide any additional information below
[Crash.zip](https://github.com/Bionus/imgbrd-grabber/files/818120/Crash.zip)

**Comment by MasterPetrik** [comment]
lol

**Comment by MasterPetrik** [comment]
I see that there are many crashes issues without clear cause or with too poor description or without dump file, and all that with main thing - not reproducable. These reports can't be very helpful. And because of it they can't be fixed, so they exist here as dead weight. 
Maybe will be better to do one Issue for all uncertain crash reports, and, if they are too old(and crash may be already fixed or bug reporter didn't ansvered for mounths, move his inclear bugreport in one issue as new comment and close original issues. 

I guess that will clean opened issues from not reproducable crashes.

**Comment by MrCrackR** [comment]
Try to delete _tabs.txt_ in _%userprofile%\AppData\Local\Bionus\Grabber_ and start it again.
