### ISSUE TITLE
Change build system from QMake to CMake

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#838]
Using QMake pretty much limits developers to Qt Creator to get decent support.

Moving to CMake would allow developers to use CLion, XCode or Visual Studio C++ more easily, while keeping support for Qt Creator (although not as good support as with QMake).

**Comment by Bionus** [comment]
Making this change made build faster, and this plus including the -j8 build flag to Travis reduced the CI time from ~17 minutes (5:30 linux, 11:30 mac) to ~9 minutes (3:30 linux, 5:30 mac).

Note that some install features may have been broken by this (especially on some unix distributions). However, using CMake should make re-implementing them easier.

**Comment by Bionus** [comment]
Left to port from QMake:

<details>
<summary>Grabber.pro</summary>

```
# Setup script for Linux
unix:!macx{
	isEmpty(PREFIX){
		PREFIX = /usr/local
	}

	config.path = $$PREFIX/share/Grabber
	config.extra = touch release/settings.ini
	config.files = release/sites release/words.txt release/settings.ini

	languages.path = $$PREFIX/share/Grabber
	languages.files = release/languages

	desktop.path = $$PREFIX/share/applications
	desktop.files += release/Grabber.desktop

	icon.path = $$PREFIX/share/pixmaps
	icon.extra = install -D -m644 resources/icon.png $(INSTALL_ROOT)/$$PREFIX/share/pixmaps/Grabber.png

	INSTALLS += desktop icon config languages
}
```
</details>

<details>
<summary>Grabber.pri</summary>

```
# Target WinXP
Release:win32 {
	QMAKE_LFLAGS_WINDOWS = /SUBSYSTEM:WINDOWS,5.01
	QMAKE_LFLAGS_CONSOLE = /SUBSYSTEM:CONSOLE,5.01
	DEFINES += _ATL_XP_TARGETING
	QMAKE_CFLAGS += /D _USING_V110_SDK71
	QMAKE_CXXFLAGS += /D _USING_V110_SDK71
	LIBS *= -L"%ProgramFiles(x86)%/Microsoft SDKs/Windows/7.1A/Lib"
	INCLUDEPATH += "%ProgramFiles(x86)%/Microsoft SDKs/Windows/7.1A/Include"
}
```
</details>

**Comment by Bionus** [comment]
Code coverage fixed.

**Comment by ItsSohma** [comment]
Just curious, how does this effect the build process? Do you just do cmake instead of qmake and everything else is the same? That didn't seem to work on my end.

**Comment by Bionus** [comment]
Not really, unless you want to mess up your local copy.
The classic way of building with cmake is:

```
mkdir build
cd build
cmake ..
make
cd ..
```

**Comment by Bionus** [comment]
I just tried and indeed you'll need a few more steps.

If you want to use OpenSSL (else you'll have to remove the "USE_SSL" part in CMakeLists):
```
export OPENSSL_ROOT_DIR=/usr/local/opt/openssl/
```

Then (because else cmake doesn't seem to find qt properly)

```
brew link --force qt5
ln -s /usr/local/Cellar/qt5/5.4.0/mkspecs /usr/local/mkspecs
ln -s /usr/local/Cellar/qt5/5.4.0/plugins /usr/local/plugins
```

**Comment by FichteFoll** [comment]
I'm trying to package this for Arch and the paths are kind of confusing currently. The only thing I managed do to is make the gui binary show "No source found. Do you have a configuration problem? Try to reinstall the program." and the cli binary consistently shows

cli binary print the help message for any args that are not `-v` and the gui 

---

Anyway, for packing a release, so far I think I need to:

1. copy the `release/` folder (without the .exe)
2. copy `build/gui/gui`
3. create `settings.ini` file

The problem now is that I have no idea where I should copy these to while maintaining the FHS.
Currently, I try to package everything in `/opt/imgbrd-grabber` and add symlinks in `/usr/bin`.

I have a few questions, however:

1. Is that everything that I need? Do I need `build/lib/liblib.a` or is it linked statically? CrashReporter? What about the `cli/cli` binary? 
1. Will it save user preferences in `$HOME` or in the `settings.ini` in the same dir (which is "write-protected" since the file will be owned by root with mode 644)?
1. In [the wiki](https://github.com/Bionus/imgbrd-grabber/wiki/GettingStarted#linux-configuration) there is something about copying files to `~/.Grabber`. I do wonder why it doesn't do that by itself, but either way I have no idea what these files are since there is no "example" directory in the source

Overall, this is very version-specific and I'd rather call a make target rather than specify all this in my `PKGBUILD`, so that I don't need to worry about updating a `-git` package every other week.

**Comment by Flat** [comment]
#998 will allow `make DESTDIR="$pkdir" install` or even `make install` for that matter on Linux.

**Comment by Bionus** [comment]
> Is that everything that I need? Do I need build/lib/liblib.a or is it linked statically? CrashReporter? What about the cli/cli binary?

I'm not very good with linux, but wouldn't that be a `.so` file if it was dynamically linked?
CrashReporter is only useful if your package includes Google Crashpad. The `cli` binary should be kept I believe, for users that do not have any GUI and wish to run Grabber headless. While the `-c` flag disables the GUI, the `gui` binary still has dependencies on X.

> Will it save user preferences in $HOME or in the settings.ini in the same dir (which is "write-protected" since the file will be owned by root with mode 644)?

There's a long list of priorities for the `settings.ini` file, the higher one being in the local directory if it exists. So it shouldn't be owned by root. At best, it should be removed and Grabber will create it itself.

> In the wiki there is something about copying files to ~/.Grabber. I do wonder why it doesn't do that by itself, but either way I have no idea what these files are since there is no "example" directory in the source

That's actually the `release` folder.

> #998 will allow make DESTDIR="$pkgdir" install or even make install for that matter on Linux.

I'll take a look :smile:
