### ISSUE TITLE
Multiple download bugs

### ISSUE THREAD

**Issue by Impervox** [Bionus/imgbrd-grabber#841]
### What steps will reproduce the problem?
1. If I have 2 bulk downloads qeued up and I select 1, press download selected and when that's done I only select 2 and press download selected, it will also download 1....again even if I already deleted 1 from the list.

2. If I run the exact same download again instead of saying "* files already existed" it just says that it downloaded them all or ignored them while it didn't download anything because it already existed.

### What is the expected behavior? What do you get instead?
It used to create for example "10 files already existed" and "0 files downloaded" but now it gives "0 files already existed" and "10 files downloaded" (doesn't actually download them again).

### What version of the program are you using? On what operating system?
tried 5.2.0, 5.2.1 and 5.2.2. I think the problem occured today when I finally updated the program. Might be that my version when it still worked was pre 5.20. Running on windows 10, note that it used to work fine. When I pressed "download selected" it would indeed download selected and not all or the selected + previous. It also would actually show "* files already existed" if the files did indeed already exist.

### Please provide any additional information below
Sorry if it's unclear, just let me know if you need anything or if I should explain better.

**Comment by Bionus** [comment]
Both these issues will be fixed in 5.2.3. In the meantime, it seems it will be necessary to download batches all at once or restart the program between each of them in order to not re-download the previously downloaded ones.

As for the "ignored" images, it came from images that were already existing, but not necessarily in the same destination folder (using MD5 check). They should now also be marked as "already existing".

Thanks for the detailed report! :smile:
