### ISSUE TITLE
Wrong images count for merged results

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#847]
## **nonmerged request:**
![2017-03-14_032518 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23880699/52cbd6b8-0866-11e7-981c-efa2d329fb4b.png)

## **merged request:**
![2017-03-14_032458 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/23880701/58b5edfc-0866-11e7-9477-d64571dece72.png)

you can see here that max image number for merged results is displayed wrong. It shows number of ALL images for that request from all sites, but it should show count of unique images from all sites. Or it just will not make any sence.

in fact, for this example in merged results there are ~286 unique images, but it shows 878...

100% repeatability
it happens ~from v5.0.0 and of course in current version too.

**Comment by Bionus** [comment]
Grabber can't guess which images are duplicates in the remaining pages without loading them all and checking all the MD5s. Who knows, maybe all the images won't be unique in the next pages? In that case, you'll indeed have ~878 images. If they're all duplicates, you'll indeed have ~300 images. But it can't be known without loading every page for every source.

That's why it's written "max", it can't be more than this, but it could be less.

**Comment by MasterPetrik** [comment]
> Who knows, maybe all the images won't be unique in the next pages? In that case, you'll indeed have ~878 images. If they're all duplicates, you'll indeed have ~300 images. But it can't be known without loading every page for every source.

Obviously, grabber correctly calculate pages count for merged results but can't calculate images count? Ok. Then we can just divide 878 / 15 = 58.2 , so it could be full 15 pages with 58 images? Hmm...

> Grabber can't guess which images are duplicates in the remaining pages without loading them all and checking all the MD5s.

Merged results system works now not very optimal, I guess... and it is just one of these signs.
Btw, how grabber gets md5 for comparement? Is there some request on server to get directly md5, or you need to download both images and then get md5s and compare?

**Comment by Bionus** [comment]
> Obviously, grabber correctly calculate pages count for merged results but can't calculate images count? Ok. Then we can just divide 878 / 15 = 58.2 , so it could be full 15 pages with 58 images? Hmm...

The page count is easy, it's just the max of all pages count from all sources.
- Source A: 20 / 400 images, 1 / 20 pages
- Soruce B: 50 / 100 images, 1 / 2 pages
Merged results: 60 images (10 duplicates), 1 / 20 pages.

How would you calculate an exact merged images count from this information? Maybe there won't be any more duplicates, then it would be 490 images total. And if there's only duplicates left, that would be 60 images. There's no way to know without loading all remaining pages. That's why Grabber just writes the max possibility.

> Merged results system works now not very optimal, I guess... and it is just one of these signs.
> Btw, how grabber gets md5 for comparement? Is there some request on server to get directly md5, or you need to download both images and then get md5s and compare?

It just loads the page for all sources, gets the result, remove duplicates based on the MD5 of the images, either given in the listing page or taken from the thumbnail URL. There's no download during the page loading step.

**Comment by MasterPetrik** [comment]
Ok then, I will create another issue about merged results system possible improvement. 
In fact, discussion about merged results system changes is the remaining non GUI issue that I want to discuss.
So I guess I can close this issue.
