### ISSUE TITLE
can't download after hitting pause

### ISSUE THREAD

**Issue by ROdoka** [Bionus/imgbrd-grabber#855]
### What steps will reproduce the problem?

hitting pause button while downloading

### What is the expected behavior? What do you get instead?

continue where it was paused

### How often does this problem occur?

everytime

### What version of the program are you using? On what operating system?

5.2.3

**Comment by Fillyosopher** [comment]
Pausing cancels the download, making it impossible to continue where paused.  All that can be done is restart.  If you set your automatic redownload to 1, it will go back and retry the images you paused on after it finishes the rest of the download.
![image](https://cloud.githubusercontent.com/assets/6576295/24322877/a25088ac-1142-11e7-9dc5-4a9f0a3057bd.png)
Suggestion for Bionus-dev though, have it restart the current picture on a resume rather than skipping and starting the next image.

**Comment by ROdoka** [comment]
alright, I'll try that, it was set to 0 here

but, IIRC, it worked in an earlier version of Grabber, didn't it? Because I remember that I used the pause button before (for example when I went to bed and hibernated the PC, just to continue the next day)

**Comment by Bionus** [comment]
> but, IIRC, it worked in an earlier version of Grabber, didn't it? Because I remember that I used the pause button before (for example when I went to bed and hibernated the PC, just to continue the next day)

Indeed, that's why I'm flagging this issue as bug and not suggestion/enhancement since it's supposed to be like this in the first place.
