### ISSUE TITLE
suggestion: MD5 database to prevent redownloading of deleted images

### ISSUE THREAD

**Issue by ROdoka** [Bionus/imgbrd-grabber#857]
I don't know if others might find this useful, but wouldn't it be helpful to have some kind of md5 database which could be used to prevent downloading images that already have been downloaded?

I for, example, don't want to see images I've already seen and deleted (or images I keep in a different folder), so I wrote me a program to store their sha256 hash into a database. I use it to scan and kick out downloaded images before I go to view them.
I might be nice to already prevent the download of these images using a Grabber included database/text file(?) which contains all already downloaded images.

**Comment by Bionus** [comment]
I love that kind of suggestions, because it's somehow already implemented in Grabber. All downloaded MD5 are kept in order to not re-download images if you already did.

You have to enable it in the settings, in "Options > Save", at the bottom you have a "if a file already exists" option. This feature uses the list of all previously downloaded files in Grabber to not re-download the ones that already were.

Since it sounds like you already downloaded a bunch of images, you can also pre-complete this MD5 list yourself, either from your program by writing to `C:/Users/%USERNAME%/AppData/Local/Bionus/Grabber/md5s.txt`, or using the built-in "MD5 list fixer" tool (in the "Tools" menu).

The only difference with your suggestion, is that if a file has been removed, it will be downloaded again.

**Comment by ROdoka** [comment]
> The only difference with your suggestion, is that if a file has been removed, it will be downloaded again.

That's what I tried to say, if it has been removed (which I do with images from a batch download) it might be downloaded again if I start a new search with the same tag(s) or with a new tag that also applies for an already downloaded image.

The downside of such a database is: there are tons of images and the DB will be very big after a while :)

**Comment by MasterPetrik** [comment]
@Bionus , I know, how to solve this problem. I guess it wouldn't be too hard to add a sertain checkbox in settings with "Don't remove md5 from list for deleted files" caption.

**Comment by barryanders** [comment]
I'm all for allowing the MD5 data to be kept for deleted files. That way in a batch download, you won't get them all again. If someone deletes 100 images and then does another batch, the last thing they want is to have to delete them all again.
