### ISSUE TITLE
Ideas needed: increasing visibility of Grabber

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#859]
I just did a search for "downloader" on the biggest boorus I know of and almost never was Grabber mentioned. A lot of command-line tools have been created though, either necessitating bash to be installed, running python, or downloading them from dead or random servers. I'm not saying that those tools don't work or anything, but just that I'm very surprised so few people know of Grabber.

I also checked on Google, and the project has very strange SEO for some searches, for example "danbooru downloader" where Grabber's link doesn't even appear for some reason, but [this one](http://www.shootingstardreamer.com/2014/07/useful-danbooru-image-grabber.html) describing Grabber usage is, and gives us a lot of traffic.

So I'm looking for suggestions to improve the visibility of the project, because it looks like this program could help more people with their mass-downloading needs, and I have a feeling Grabber is somehow too hard to find for potential users.

Or am I just overestimating the number of potential users?

**Comment by Bionus** [comment]
Bonus question: how did you find Grabber?

**Comment by larry-he** [comment]
I found Grabber when looking for a booru downloader, but I don't remember the search terms I used.

Maybe change the first sentence in the description "Imageboard/booru downloader which can download thousands of images from multiple boorus very easily. It can either be used through its graphical user intertface or command-line." to explicitly mention the most popular boorus it can work with. I imagine most people will look up downloading images from a specific booru like "how to download gelbooru images." Consider deemphasizing the "imageboard" element or changing the project name. I didn't know "imgbrd" stood for imageboard when I first heard about your project.

**Comment by larry-he** [comment]
Looking up "promote open source project" gives lots of potentially useful ideas.

For example, from https://news.ycombinator.com/item?id=7531170:
Post to domain-specific forums where I thought people would be interested.

Anime fan communities on reddit like r/touhou could work. But remember accounts only for self-promotion are not allowed on reddit. You could try dipping into parts of 4chan like /g/ or the more lurid sections of the site.

**Comment by Hrxn** [comment]
> Bonus question: how did you find Grabber?

I think purely by accident in my case..

**Comment by MasterPetrik** [comment]
I'm just searched google for booru downloader software in russian internet, and I guess someone mentioned Grabber in answers in one of Q&A sites, and that's how I get here)

**Comment by WilluG** [comment]
Was looking for a sankaku downloader
Found yours by mere luck tbh..given i had given up on finding a proper  bulk downloader. 
But unless i hadnt known about "github" i wouldnt of found this grabber
So you should  get the search related to "github" & "grabber" maybe add "booru" too.
Thats all i could say :)) 
Just make it simple but quite related to the essence  of it

**Comment by Tragedian-HLife** [comment]
I found this project by googling "booru downloader". It's the first result, for me.

> Or am I just overestimating the number of potential users?

I guess one thing to keep in mind is that grabber is really a power-user's tool. There are plenty of general-purpose mass downloaders (many of which are simple browser plugins) that I imagine a lot of people have been using since before grabber was made and on more sites than grabber supports.

Stuff like DownloadThemAll work fine, if you just want to scrape a page's images into a local folder. Grabber's usefulness lies in grabbing metadata and doing processing on all those images. I think it's a minority use-case, by far.

The only reason I use grabber over a general scraper is because I already had a booru-esque server that I could use to better organize images than my old method of nesting tons of folders. Otherwise, I'd still be using a simpler tool, most likely (since I'd have never searched for a more advanced one).

--

Not to ask the obvious, but have you tried old-fashioned grass-roots marketing? For instance, making threads on boorus' forums or places like /h/ to promote grabber? I know /h/ frequently has "tools" threads where people discuss everything from site scrappers to gallery software.

Not sure how receptive a booru's forum would be, since they may frown upon you increasing their server load, but it'd be worth a try.

In the end, things like google results are weighted by traffic stats. Getting more people to view the repository will move it up in the results.

**Comment by barryanders** [comment]
I don't think you are overestimating users. I found it years ago on Google code which was due to a Google search for a batch downloader. I since followed it and was glad to see it transfer to GitHub. I'm guessing there are many potential users who simply aren't looking for a program because they haven't thought about it, and this may be because they aren't considering the benefits of using a program over the source website (no ads, uniformity). Here's a few thoughts.

**1. What part of Grabber's branding could potentially be improved?**
The only thing I can really think of is the icon.
![readme-icon](https://cloud.githubusercontent.com/assets/5648875/24710109/bc0b8132-19e1-11e7-8790-ed52af728987.png)

**2. Is Grabber on websites that list programs or review them?**
Ex. alternativeto.net, lifehacker.com are both places I've found new apps to suit my needs.

You may look for popular articles about downloaders and then contact the author about adding Grabber to it. You may even suggest how Grabber is better than one on their list.

**3. Website for Grabber?**
I know you have it on your site, but it may be useful to have a site specifically for Grabber. You might win users who don't understand GitHub or don't even know what it is. Even though you have direct downloads on GitHub, it may be helpful to have a giant download button for users. I suspect you could link it to the latest GitHub release so you don't have to update it all the time.

**Comment by brodycas3** [comment]
Yeah, That icon could use an update. also @MasterPetrik It's not just about mass downloading. I use it as a replacement when looking for images rather than the sites. I like how you can merge results and search many places at once.

**Comment by MasterPetrik** [comment]
Suddenly I figured out that other users have the same vision with me. Very good.  

Here is 3 things to improve Grabber popularity that I wanted to suggest many times ago. But some of them are already been mentioned today. Just allow me to describe them in more details:

## **1.  Changing Grabber logo.** 
![bc0b8132-19e1-11e7-8790-ed52af728987](https://cloud.githubusercontent.com/assets/22294259/24722975/5edd94b0-1a4e-11e7-9efd-3408e7293774.png)
Current logo isn't bad, but it's not related to Grabber and don't describe anything. Because you will use Grabber not for downloading images of landscapes obviously. So changing Grabber logo to something anime-related will be very recomended. You can trust me, that users will more likely use the programm if it will remind them about it anime origin.
If you agree with that I can create issue about new icon, can help with design, and discuss it in more details. 

## **2. Centering on making another Killer-feature, addition to "powerful naming features".**
>  I like how you can merge results and search many places at once.

I'm talking about unique function, that now exist only in Grabber - Merged results (all in one boorus search + view).
This can be your Killer-feature... if you will make some improovments in it, of course. 
Many users will come if they will know about that function. Nobody like to see duplicates images on different boorus. Moreover if you search boorus from grabber, you will not see any advertisementыб that exists almost on every boorus.

Current merged results feature is can be VERY useful for many people, espessially for these guys, who don't need mass downloader, but need a proggramm to view many boorus at once. This is can be second Killer-feature of Grabber - multibooru viewer. Current preview window functions allows user to do all actions, that he can do on boorus - favourites, black\whitelist, two types of save buttons, direct search from taglist, etc.  It is enough useful and convenient for replacement typical boorus preview pages.

But current merged results search still needs some rework, I will make Issue about it today.


## **3. Right describing Grabber features.**
In current state you describe grabber mainly as software with powerful naming features, but It have much more useful functions, If you little improove them it can be new Killer features. Because for some people naming feature is unimportant, but for example very important multibooru search feature. So you don't need to focus only on that feature to improve Grabber popularity, I guess.

As I see, there are should be these main features (I guess you can describe them more correct):

- Search images on all boorus together
- Merged results mode(I don't know how to describe it in one sentence)
- Simple and native viewer with support of mouse actions
- Powerful naming features

The most important thing - all features should be shown as list, not a wall of text, that will help to find and read it more easily for new users.

**Comment by Bionus** [comment]
Lots of very useful feedback here, thanks a lot everyone!

I'll try to comment on what everything says below. :smile:

> Maybe change the first sentence in the description "Imageboard/booru downloader which can download thousands of images from multiple boorus very easily. It can either be used through its graphical user intertface or command-line." to explicitly mention the most popular boorus it can work with. I imagine most people will look up downloading images from a specific booru like "how to download gelbooru images."
>
> Consider deemphasizing the "imageboard" element or changing the project name. I didn't know "imgbrd" stood for imageboard when I first heard about your project, and I feel the main draw to Grabber is mass downloading images from boorus, not imageboards.

Right. I'm not even sure Grabber support any imageboard that isn't a booru.

> https://news.ycombinator.com/item?id=7531170

Good read indeed. :+1: I'll try to follow some advice that's given in there.

> Posting on anime fan communities on reddit like r/touhou could work. But remember accounts only for self-promotion are not allowed on reddit. You could try dipping into parts of 4chan like /g/ or the more lurid sections of the site.

The problem with 4chan and reddit is that threads are pretty short-lived there. Wouldn't that just cause a few spikes in users while the thread is pretty active, and have the impact be nullified once the thread moves away from the main page?

I'm not very familiar with Reddit though.

> Clean out old issues from your issues tracker; 100 issues is a bit much.

Crashes are often duplicated and could be closed, and some bugs are not valid any more and could be closed, to lessen this number that make the program look less mature than it is.
But many are still valid suggestions, is it really all right to just close them like this? Even though if they're not closed, they might stay here forever (e.g. 4chan support and that kind of suggestions that are pretty far down in the backlog).

> A short video/gif demo would be a nice way for people to quickly understand what Grabber is capable of. Emphasize how few clicks it takes to download and how little user involvement there is. I think most people are looking for something that's easy to use and just works.

:+1:

Are video really a good medium though? I know I hate them and personally prefer following screenshots, such as those on the [GettingStarted](https://github.com/Bionus/imgbrd-grabber/wiki/GettingStarted) wiki page. Should I make a video for each use case and put it directly on the main page?

> Anyway, considering your stars\forks\downloads and other community activity, looks like your Grabber is one of the most popular software for "this type of people" who downloads mass of images from boorus, like a maniacs.

And yet there are lots of new small scripts that pop every now and then on booru's forums, to do exactly what Grabber is already good at (modulo specific crashes): mass downloading images. :sad:

> The only proggram, that I can compare with grabber by popularity and user activity is Hidrus Network.

I'll have to take a look at it more in detail someday, to see if there are some features it has that could fit Grabber.

Or if someone already has a few suggestions from, I'm all ears. The preview panel (instead of Grabber's popup) looks pretty interesting.

> Was looking for a sankaku downloader
> Found yours by mere luck tbh..given i had given up on finding a proper bulk downloader.
> But unless i hadnt known about "github" i wouldnt of found this grabber
> So you should get the search related to "github" & "grabber" maybe add "booru" too.

Isn't Grabber first result for "Sankaku downloader" on Google though?

I'll see to improve the keywoards of the readme, thanks.

> The only reason I use grabber over a general scraper is because I already had a booru-esque server that I could use to better organize images than my old method of nesting tons of folders. Otherwise, I'd still be using a simpler tool, most likely (since I'd have never searched for a more advanced one).

So you mean maybe I should emphasis the local board support?
- https://github.com/Bionus/imgbrd-grabber/wiki/MyImouto
- https://github.com/Bionus/imgbrd-grabber/wiki/Gelbooru
- https://github.com/Bionus/imgbrd-grabber/wiki/Shimmie

> Not to ask the obvious, but have you tried old-fashioned grass-roots marketing? For instance, making threads on boorus' forums or places like /h/ to promote grabber? I know /h/ frequently has "tools" threads where people discuss everything from site scrappers to gallery software.

I haven't tried anything yet. Only google has been bringing traffic and users since the beginning of the project.

I had a few posts on booru's forums, but they don't bring much traffic, and sometimes get simply deleted by the mods.

About /h/, I pretty much never post to 4chan, so no I haven't. Do you have examples of such tools threads? From the incoming traffic reports I have, it doesn't seem like Grabber was ever mentioned in some thread there. And as said above, wouldn't the impact of such thread be very short-lived with a pretty high work/conversion ratio?

> Not sure how receptive a booru's forum would be, since they may frown upon you increasing their server load, but it'd be worth a try.

Yep, that's my problem. Many mods/admins of those sites aren't really wishing for this kind of tool to get more popular, even if many users could get interest in it. When I see new forum posts asking if such software exists, I try to put a link but that's pretty much all I do now.

> I don't think you are overestimating users. I found it years ago on Google code which was due to a Google search for a batch downloader. I since followed it and was glad to see it transfer to GitHub.

Wow, I didn't know you were such an old-timer. :wow:

I thought I lost everyone when moving to github. :smile:

> 1. What part of Grabber's branding could potentially be improved?
> The only thing I can really think of is the icon.

I have to agree here, I chose this icon at the beginning because I needed one and never really updated it.
It's something that should be done but I'm no designer so the result would definitely not be great. :sweaty_smile:

> 2. Is Grabber on websites that list programs or review them?
> Ex. alternativeto.net, lifehacker.com are both places I've found new apps to suit my needs.

There's two or three articles out there talking about Grabber, but I never put them anywhere by myself.

> You may look for popular articles about downloaders and then contact the author about adding Grabber to it. You may even suggest how Grabber is better than one on their list.

I'll check that indeed. Do you have any of those articles in mind? Else I'll just google "booru downloader" and check all articles.

> 3. Website for Grabber?
> I know you have had it on your site, but it may be useful to have a site specifically for Grabber.

Are you talking about [www.bionus.fr.cr](www.bionus.fr.cr)?
If so it seems like it disappeared at some point, but it wasn't really anything useful anyway (even though it was at the beginning, before I decided to move everything to github).

> You might win users who don't understand GitHub or don't even know what it is. Even though you have direct downloads on GitHub, it may be helpful to have a giant download button for users. I suspect you could link it to the latest GitHub release so you don't have to update it all the time.

Indeed, even though that sounds like a lot of initial work, in the long run that could help attract more "casual" users.
Especially since the fact that Grabber is too "power-user" centric seems to be recurring in this thread.

> It's not just about mass downloading. I use it as a replacement when looking for images rather than the sites. I like how you can merge results and search many places at once.

Which is indeed pretty much overlooked in the description. I'll try to add more details about how it's also a very useful program for browsing, too.

> 1. Changing Grabber logo.
>
> Current logo isn't bad, but it's not related to Grabber and don't describe anything. Because you will use Grabber not for downloading images of landscapes obviously. So changing Grabber logo to something anime-related will be very recomended. You can trust me, that users will more likely use the programm if it will remind them about it anime origin.
> If you agree with that I can create issue about new icon, can help with design, and discuss it in more details.

Seems like everyone agrees on this one, so feel free to create an issue.
The problem with the icon is that it should show the main features of Grabber and not only one: browsing, downloading, etc.

I still suck at design though (as in "design thinking", not the technical part of using Photoshop).

> 2. Centering on making another Killer-feature, addition to "powerful naming features".
>
> I'm talking about unique function, that now exist only in Grabber - Merged results (all in one boorus search + view).
> This can be your Killer-feature... if you will make some improovments in it, of course.
> Many users will come if they will know about that function. Nobody like to see duplicates images on different boorus.

To be honest, I've never really took a look at this feature. I added it a few years ago and that's pretty much it.

I didn't really give it a thought, but it indeed has some big potential to attract new users and to be improved upon.

> Moreover if you search boorus from grabber, you will not see any advertisement that exists almost on every boorus.

While that's true, I'm not really sure about publicly bragging about it, as ad revenue is what makes many boorus pay their hosting, which can be pretty expensive due to the high storage space and high bandwidth required.

> But current merged results search still needs some rework, I will make Issue about it today.

Unfortunately yes, using it gives some real big UI lags, plus the grid system makes it that there can be a lot of unused space while still having lots of scroll. Plus, there's no gradual show of the pictures as soon as pages are loaded.

Looking forward to your suggestions about it. :smile:

> 3. Right describing Grabber features.
>
> In current state you describe grabber mainly as software with powerful naming features, but It have much more useful functions, If you little improove them it can be new Killer features. Because for some people naming feature is unimportant, but for example very important multibooru search feature. So you don't need to focus only on that feature to improve Grabber popularity, I guess.
>
> For example, as I see, there are could be these main features (I guess you can describe them more correct):
>
> Search images on all boorus together
> Merged results mode(I don't know how to describe it in one sentence)
> Simple and native viewer with support of mouse actions
> Powerful naming features
>
> The most important thing - all features should be shown as list, not a wall of text, that will help to find and read it more easily for new users.

Isn't that what the [main features](https://github.com/Bionus/imgbrd-grabber#main-features) part of the readme already does somehow? Or is that still too much text in your opinion?

**Comment by barryanders** [comment]
Speaking of merged results, I wonder what it would take to remove duplicate images and only show the unique images in the merged view. I wouldn't use it much side by side by a true merger where you can't see the source from the main window would be way more useful to me.

**Comment by Tragedian-HLife** [comment]
> Do you have examples of such tools threads? 

http://boards.4chan.org/h/thread/4586836/collection-management-hentai-resources-general
https://archived.moe/h/thread/3503475/#3503475

Usually, either people ask for tips on managing their huge collections of media or other people are offering advice on how they do it. For a tool like this, it'd easily fit into the kinds of software /h/ would be interested in. Just about every week that someone has a sadpanda tutorial.

I think the benefit would be larger than you'd think. For one, /h/ is a lot slower than /b/. Your thread or post would likely be around for at least a few days (depending on how often it's replied to). But your target demographic is also highly concentrated in that area. It's basically the same reason businesses go to conventions and expos. The short-term presence of the event is offset by how surgically targeted it is.

Plus, it's free and easy. Just bring some /h/ images as gifts and the mods won't care.

**Comment by barryanders** [comment]
I would also like to add that I have gone through some of the old issues, and would be glad to formulate a list of closable ones. Feel free to provide any criteria on that. By making a list, you could do a commit that closes them all at once.

**Comment by MasterPetrik** [comment]
> Isn't that what the main features part of the readme already does somehow? Or is that still too much text in your opinion?

I guess it will be optimal to separate current features list to "Main features" list with more bigger text and 3-4 killer features, and "Other features" list below with smaller text and all other features in it. 
It would be easy to understand for new users. Even I'm too lazy to read current full features list -___-.

> The only proggram, that I can compare with grabber by popularity and user activity is Hidrus Network.

> I'll have to take a look at it more in detail someday, to see if there are some features it has that could fit Grabber.

well, to tell the truth, I suggested many features from Hidrus Network to grabber, like preview window mouse controls, or white preview bg, or centering images in preview etc. But anyway it was just an example. Your programms are have too different purposes.

> And yet there are lots of new small scripts that pop every now and then on booru's forums, to do exactly what Grabber is already good at (modulo specific crashes): mass downloading images. :sad:

They have scripts? Hah! You have GUI! Don't underastimating power of good user-friendly interface!

> While that's true, I'm not really sure about publicly bragging about it, as ad revenue is what makes many boorus pay their hosting, which can be pretty expensive due to the high storage space and high bandwidth required.

So funny, that you mentioned it. Well, In fact, missing advertisements isn't their main problem. In fact, even existing of grabber killing their business, Because alive user even don't visiting their sites using grabber. In fact, user can gibe them his traffic for years looking images one by one, but, meh... Just download all booru archive via grabber in one day and cause server overload instead. I'm happy that they are not judged you yet)

> The problem with the icon is that it should show the main features of Grabber and not only one: browsing, downloading, etc.

There is no problem here, because programm logo isn't nessesery show all it's main features. In fact, it's not even needed for multifeatures software. If you see to another programms icons, that you will see that most of them(60%) shows only one programm feature on the icon, another one just use beautiful non related to proggram destination icons(30%) and remaining 10% of icons are just show a bunch of unrecognizable crap on it. 
What about grabber, I think that the best logo we can made is some anime character portrait. Anyway your grabber more anime-related then downloading-related software, and I guess, users would be happy to see something like that too. Just a suggestion though.

> Clean out old issues from your issues tracker; 100 issues is a bit much.

Yes, It would be nice to close some solved questions and some very old not repeated problems from much earlier versions. For example, bugs with functions, that are not exists in Grabber anymore etc.

> Crashes are often duplicated and could be closed, and some bugs are not valid any more and could be closed, to lessen this number that make the program look less mature than it is.

Many of that 100 opened issues are bugreports, many of these bugreports are just topic with one post, often even with not full data about crash. These crash reports can be easyly moved to one Topic with all poor-described crash reports. This will save a lot of space in issues list.  

> But many are still valid suggestions, is it really all right to just close them like this? Even though if they're not closed, they might stay here forever

Valid suggestions should stay, of course, that's out of the question. But anyway you need to review all these issues, maybe some of them already implemented in grabber.

**Comment by brodycas3** [comment]
I think a new anime related icon/logo would be good. Nothing over the top/too detailed because it also needs to be a desktop icon.

**Comment by Bionus** [comment]
Thanks everyone for the feedback. I'll close the thread to reduce the issue count, but if anyone has anything to add, feel free to post. :smile:

I took note and everything and am acting on it these days, I hope the results will show.

The only thing I can't really do is the logo. I'll try to make something, but well I suck at making image stuff.

> http://boards.4chan.org/h/thread/4586836/collection-management-hentai-resources-general
> https://archived.moe/h/thread/3503475/#3503475

Thanks. Reading those (especially the first one) helped me see what's up with the community. If I see a post like this next time I'm lurking 4chan I'll do my little advertisement.

> I would also like to add that I have gone through some of the old issues, and would be glad to formulate a list of closable ones. Feel free to provide any criteria on that. By making a list, you could do a commit that closes them all at once.

I don't even need to commit to close issues. That's just what I usually do because when fixing bugs, implementing suggestions, there's always some code to go with it, so they get closed automatically when I do a release. As for a criteria, I'm trying to close duplicated issues, unclosable ones (old crashes without dumps/logs, etc. as mentioned by MasterPetrik) as well as completely deprecated ones. I think there's not many left but I may missed some.

> I guess it will be optimal to separate current features list to "Main features" list with more bigger text and 3-4 killer features, and "Other features" list below with smaller text and all other features in it.
It would be easy to understand for new users. Even I'm too lazy to read current full features list -___-.

I tried to follow this advice on the website and I believe it worked out pretty well, thanks :+1:
