### ISSUE TITLE
New website for Grabber: optinions and suggestions

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#878]
Following issue #859, I created a website for Grabber.

You can find it here:
https://bionus.github.io/imgbrd-grabber/

If you have any suggestions or opinions about it (good or bad), either about the looks or the content itself, I'm all ears. As I'm going to use it for advertising Grabber as suggested in #859, I'm trying to make it as good as I can.

_PS: the old [bionus.fr.cr](http://bionus.fr.cr/) url will be redirected to the new website too._
_PPS: I hope I'm not being too annoying with this self-created issues. I'm trying to get more opinions from the community, as I realized in the past months that my usage of the program is clearly not representative of all users._

**Comment by MasterPetrik** [comment]
Looks Great! 

P.S.
I guess we can help you with multilanguage version of this page?

**Comment by Bionus** [comment]
> I guess we can help you with multilanguage version of this page?

I think it's better to wait a few days until the page is more mature. I'm afraid that it might still change a lot in the next days since it's new, so any translation would become obsolete. Afterwards with pleasure though, I'd be glad to have it translated in other languages too. :smile:

**Comment by MasterPetrik** [comment]
ok, when you will think it done, you can ask me in any time!

P.S.
Please take a look at https://github.com/Bionus/imgbrd-grabber/issues/877

**Comment by barryanders** [comment]
I like it.

**Comment by TheGho7t** [comment]
I like it a lot! 

Honestly, I don't really know if you need to change it too much more. People are so impatient and have such short attention spans, it's best to have it be short and sweet on that front page. Although obviously, if you mean like changing it so there's more info on certain spots than yeah that's fine, otherwise that's practically perfect. 

Maybe in the future a minute video showing it off? Like a little montage of sorts. That'd be pretty nice. I know I'm a sucker for montages. 

The only other thing I could suggest would be some scrolling info of sorts. I cannot think of a website off the top of my head that does it, but instead of scrolling down a lot, you can just have it be front and center and you can click left and right to see what it can do. (Hopefully that made sense)

Looking forward to seeing it be edited in the future! (This makes it sound like I hate it right now smh I mean it as I'm happy to follow this and see where it goes)

**Comment by brodycas3** [comment]
Maybe you could have clicking the sources take you to their home page.

**Comment by MasterPetrik** [comment]
> The only other thing I would say would be some scrolling info of sorts. I can not think of a website, I can not do it right now. (Hopefully that made sense)

I do not think that this is really necessary, horisontal scrolling works fine for sites with big images and minimum text. I'm never seen that someone used horisontal scrolling for software site.

I'm fully support Clickable sources!

**Comment by TheGho7t** [comment]
I don't know what it's called, and I honestly cannot say if I've ever seen it for software either, but that doesn't make a difference really what you're selling or showing off. I don't really care if every single person agrees, I just gave a suggestion, goodness. To me I would personally rather it be like that as to be simpler was all. I'm an oddity when it comes to reading things and looking up stuff. Most people who are wanting to save a bunch of hentai and photos they wouldn't show their parents, aren't gonna be wanting to know every exact detail. It's even fine to have that, I don't want to argue, but wow. It's just a different look was all. Sorry you don't agree.

**Comment by MasterPetrik** [comment]
Calm down, dude. It's just a discussion. Take it easy.

**Comment by Bionus** [comment]
> Maybe you could have clicking the sources take you to their home page.

The issue I had with clickable sources is the possible negative impact it could have on the SEO or on the "safe search" rating of the website, for having external links to 18+ websites.

**Comment by MasterPetrik** [comment]
Btw, it's not the new idea, but you could add kind on "safe button\checkbox" in Grabber settings, and show it while first set options dialog after installation too. Because some people are coming to boorus for safe art only, so would be logical to do some kind of safe mode, where only NSFW sites will be excluded from search, and for all other sources, that support rating system, send search requests to server with invisible  "rating:safe" tag. So users, that just want safe searcn no needed to do that all manually. Because they rather uninstall Grabber, than figure out how to set right settings.

**Comment by barryanders** [comment]
![screen shot 2017-04-11 at 2 51 18 pm](https://cloud.githubusercontent.com/assets/5648875/24927978/656df870-1ec6-11e7-85a4-a79ded2b8679.png)
Two places to consider using your new site instead of the Github repo.

**Comment by barryanders** [comment]
Two places to consider using your new site instead of the GitHub repo.

![screen shot 2017-04-11 at 2 53 10 pm](https://cloud.githubusercontent.com/assets/5648875/24928049/9fcac9bc-1ec6-11e7-9ff7-e61ae2f45b99.png)

**Comment by MasterPetrik** [comment]
In help menu will be logical to remain all links lines:

- Project website(link to the new site)
- Project Github page
- Report an issue

What about "About" window, it obviously need to rework. Look, text even don't fits in the window, lol

**Comment by Bionus** [comment]
I'll be closing this issue.
Thanks everyone for the feedback. :+1:

> Btw, it's not the new idea, but you could add kind on "safe button\checkbox" in Grabber settings

Yes, it's on my roadmap for a future major version (major as in 6.x.x).
