### ISSUE TITLE
Make clickable image areas more obvious in grabber

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#884]
# First of all, a simple question:
![2017-04-11_234235 win7 mastercoregf](https://cloud.githubusercontent.com/assets/22294259/24933511/623b190e-1f1f-11e7-95fc-b4759938398b.png)

Well, in fact, you don't know for certain. And this is bad, because this is unpredictable. GUI must be logical and predictable. And if you click far away from image, you are not expecting that this will open that image as result. All users, who used at least one of image-stored sites, know for sure that if you teoreticly draw in mind a squere frame around the image and make it on 5-10px bigger, you will get this image clickable area. And between images in normal grid exist some free space, clicking on it will not result opening any image. This space is really needed, it also prevent misclicks. And clickable image borders shouldn't be depending of number of images in a row(as in current version). It should be fixed constant value.

Btw, not obvious clickable image area also exist in wreview window, but I don't think that there it might cause a misclicks or another problems. So it's not a big deal.

# Current clickable image areas

![2017-04-11_234235 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24933519/67b4013e-1f1f-11e7-9ba0-2885312e642f.png)

# More obvious suggested clickable image areas

![2017-04-11_234235 win7 mastercore](https://cloud.githubusercontent.com/assets/22294259/24933523/6bc96eb2-1f1f-11e7-8a7e-968822127d28.png)

**Comment by Bionus** [comment]
Actually there's space in the current version, so it's like:

![image](https://cloud.githubusercontent.com/assets/882719/24979701/82895d40-1fd5-11e7-9e6a-53c5315ae95c.png)

Your suggestion is good for when there's a lot of blank space or when images are square, but what about landscape images?

![image](https://cloud.githubusercontent.com/assets/882719/24979824/f8f46d3a-1fd5-11e7-9c1d-4f948b4c7bf1.png)

With your suggestion, there's two solutions:

1. ![image](https://cloud.githubusercontent.com/assets/882719/24979860/259ba48e-1fd6-11e7-851c-afa89406218a.png)
2. ![image](https://cloud.githubusercontent.com/assets/882719/24979884/35b49b5a-1fd6-11e7-93de-56dc0ec34e62.png)

First has unnecessary white space, second is even more "unpredictable" than the current solution.

Since you suggested a new grid with fixed 150x150 images (issue #883), this will already be implemented as all images in "fixed grid mode" will have fixed size (and so it will do as in option 1).

**Comment by MasterPetrik** [comment]
With your wide image example, my original solution isn't look optimal amymore...
But anyway, I like your second variant:

![35b49b5a-1fd6-11e7-93de-56dc0ec34e62](https://cloud.githubusercontent.com/assets/22294259/25024581/23261f82-20a7-11e7-9289-da05c9142a26.png)

First variant is not make sence, because it will be exectly fixed grid mode. But second varians is very obvious, as I think, and, more important, it solves main problem - misclicks. So it's anyway better then current one.

**Comment by MasterPetrik** [comment]
Since fixed grid mode was added, I'm using only it, so more obvious  image areas in flow grid mode is not actual for me now. 

But! there is another place in Grabber, that need more obvious image areas in it's grid - favourites.
