### ISSUE TITLE
Bionus are you sure sankakucomplex really works after page 1000

### ISSUE THREAD

**Issue by maskkulin** [Bionus/imgbrd-grabber#890]
have you personally tested it? I'm stuck on 20k images, I can't get more. I type page 1200 to make sure I really don't have those images already, but it doesn't increase. I looked what images get downloaded, it are only pics I already have that were uploaded like 8 days ago on sankakucomplex, actually I should get pics from 2014. Batch download doesn't even start when image limit is 20. I set it to 21, only 4 images are downloaded.. ![why](https://puu.sh/vnoIO/f1ba7359c4.png)

**Comment by Bionus** [comment]
On latest versions, you have to disable image packing to download images post page 1,000, did you do that? I said how to on some other thread about sankaku.

And you cannot start your download at a page after 1,000, you have to start your download before the limit. Because after page 1,000 you have to load the previous page to know the url of the next page. So even if you only want to start at page 1,200, you still have to load the 200 pages before it to get the URL of page ,1200.

The 4 images you downloaded are probably the top 4 images at the top of the page that sankaku adds sometimes.

**Comment by maskkulin** [comment]
wow that's really a bummer :( I don't want to leave the program open for days.. Guess I stick to my date method then

**Comment by Bionus** [comment]
That's a limitation by Sankaku and most other boorus: can't go further than page 1,000, afterwards they switch to an alternate paging system, little I can do. However, if you already have the images downloaded, it's only 200 pages more to load, so it shouldn't take days. But yeah, still annoying. 😕
