### ISSUE TITLE
Nothing loads from any shimmie sites in v5.2.4, but they load in v5.0.0a1

### ISSUE THREAD

**Issue by cewok** [Bionus/imgbrd-grabber#893]
When I load anything from and/or add sources from simmie sites (v5.2.4) they don't show any images, tags sometimes show up but still no images.

I tried using an older version (v5.0.0a1) and it worked perfectly. Could it be a bug?

First time posting here, thanks.

**Comment by barryanders** [comment]
Oh really? Maybe that explains my issue over at #558 as of 11 days ago.

**Comment by Bionus** [comment]
It indeed sounds like a bug, especially if it affects the Shimmie boards included in the release (r34, shishnet, etc.). However I could not reproduce on my end.

So that I can be sure we're talking about the same websites, on which boards did you try exactly?

Did you try a clean install? (i.e. deleting the contents of `C:\Users\%USERNAME%\AppData\Local\Bionus\Grabber` and installing again) I know of people having non-working Sankaku for whom this fixed the issue.

> Perhaps it's worth noting that the Wiki says Shimmie is supported but not 100%.

Yeah, because lots of Shimmie have custom stuff going on, and there's custom Shimmie versions around which are not compatible with the original version.

The Grabber supports mainly the official one, that is the one here:
http://shimmie.shishnet.org/v2/

But I don't mind adding semi-custom code to support big boards that made small modifications.
