### ISSUE TITLE
"Save selected images" as context menu option in result list

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#898]
When right clicking an image in the result list, there should be an option to directly "save" it to save time (you won't have to open the window, then click "save and close" and wait for the image to load).

If multiple images are selected using <kbd>Ctrl</kbd>, it should download them all.

A visual indicator on top of the thumbnail should show the download progress, and changing the page should **not** abort the download ("fire and forget" mode). The download status (success / already exists / ignored / etc.) could be indicated by an icon overlay after the download is finished.

**Comment by brodycas3** [comment]
I think there should be an option to *Open in browser* for easier access.

**Comment by MasterPetrik** [comment]
# Complete rightclick menu variant

### with all these suggestions:
> When right clicking an image in the result list, there should be an option to directly "save" it to save time (you won't have to open the window, then click "save and close" and wait for the image to load).

> I think there should be an option to Open in browser for easier access.

> Maybe it will be a good idea to add in rightclick menu an ability to search THIS image md5 in new grabber tab.

> I guess that not very convinient to each time open preview window and only then revers search.

some of them I get from https://github.com/Bionus/imgbrd-grabber/issues/754, but now you made a separate issue about rightclick menu for results grid, so I moved these suggestions here.

## Here is the final variant:
![d26e1ca8-e53b-11e6-94ee-5d230ce74b5d](https://cloud.githubusercontent.com/assets/22294259/25417249/74602890-2a4b-11e7-9d19-352fb6ed1248.png)

description:
1. Autosave mode. like a "save and close" action.
2. "Save as" mode, like a classic save dialog with custom name and folder
3. MD5 search. - search THIS image md5 in new grabber tab.
4. Open in browser - open in default browser page with this image(not image, but page of booru with this image, with similars and tags and other info)
5. Search in intertet for this image. Opens in browser.
6. Copy file - image as file
7. Copy data - image as hmm...image

I don't think that lines 6-7 is really needed, but all others are compleatly needed. And should be placed in this order. I even draw some icons in paint, heh)

**Comment by brodycas3** [comment]
I have an idea to improve it, Instead of having the image search be called
Search in web, Have it called Reverse image search, Also Waifu2x should not
be in there, it should be its own thing preferably underneath of *Reverse
Image Search* since it doesn't really search the web.

**Comment by brodycas3** [comment]
Also, You should just directly save and use the favicon for the site [Yandex](https://yandex.st/lego/_/rBTjd6UOPk5913OSn5ZQVYMTQWQ.ico) and [Waifu2x](https://raw.githubusercontent.com/nagadomi/waifu2x/master/assets/favicon.ico)
Both favicons linked,

**Comment by MasterPetrik** [comment]
> I have an idea to improve it, Instead of having the image search be called
> Search in web, Have it called Reverse image search, Also Waifu2x should not
> be in there, it should be its own thing preferably underneath of *Reverse
> Image Search* since it doesn't really search the web.

Oh man, I'm just showed how it would look like, this image is not about design, but about menu functional. And I know that Waifu x2 isn't search engine, but nobody will make separate category only for it. Bionus even  doesn't sure in it's usefulness. Moreover this is not so popular tool to built it as separated category. In fact there are only two ways to solve this:
1. Forget about Waifu x2, because it doesn't fit in current menu.
2. Rename this category to "Web servises" so there are will be no misunderstanding anymore. Plus in the future Bionus could add another services in this menu.
![d26e1ca8-e53b-11e6-94ee-5d230ce74b5d](https://cloud.githubusercontent.com/assets/22294259/25421406/661a715e-2a65-11e7-8eff-cc7146d4781b.png)

> Also, You should just directly save and use the favicon for the site Yandex and Waifu2x
> Same thing with the Google favicon.

Dude, please stop harrasing my Paint work, it's just an image, I repainted it from my old sample, and I just showing how it would looks like, similar colors in icon enough for Paint sample.
And if you open your Grabber, you will see that both Google and Yandex ALREADY have their normal icons. So your second post is no longer relevant.
![image](https://cloud.githubusercontent.com/assets/22294259/25420657/c4626ba8-2a61-11e7-9b54-17633923689f.png)
P.S.
thumb up your own post... very clever -___-'

**Comment by MasterPetrik** [comment]
May I sak you, why you desided not to add "save as" options?

**Comment by brodycas3** [comment]
That would be a nice feature to have.

**Comment by Bionus** [comment]
Oversight it seems.
