### ISSUE TITLE
Not grabbing all images from Derpibooru

### ISSUE THREAD

**Issue by CarlAeon** [Bionus/imgbrd-grabber#907]
### What steps will reproduce the problem?

Downloading from Derpibooru with an API key, with the user images per page setting on the site set to a value above 15.
Alternatively, downloading more than 1000 pictures at once (see below).

### What is the expected behavior? What do you get instead?

When trying to grab a somewhat sizable amount (~2000) images from Derpibooru, Grabber only gets around ~600. I'm using my API key on the site and I think the problem is, that I have the amount of images per page set to 50 as opposed to the default 15, which would explain, why it only gets around exactly 30% (give or take, because of the last page). I tried setting "Images per page" in grabber on the tag search screen to 50, but it won't let me. If I add it to the Downloads and set it to 50 there, it does allow me to, but then not only does it not download even ~30%, it downloads nothing.
To combat this, I tried setting my images per page setting on the site to 15 and then start downloading, which seems to have Grabber get all images from the pages, but then it only grabs exactly 67 pages, or 1005 images.

### How often does this problem occur?

I've tried multiple times, but I've always ran into this problem.

### What version of the program are you using? On what operating system?

5.2.4, Windows 8.1

**Comment by SvyraCosmix** [comment]
I have no idea why the hell they STILL haven't fixed this issue, it's been what, four or more years now and grabber all images from derpibooru is still a problem, like fucking seriously. I'd give Bionus 50 dollars to fix this issue like today.

**Comment by SvyraCosmix** [comment]
Guess bionus didn't want my 50 bucks, oh well.

**Comment by Bionus** [comment]
> Downloading from Derpibooru with an API key, with the user images per page setting on the site set to a value above 15.

I'll see if there's a way to set it to something else than 15, and if it's impossible I'll force the value to 15 in next release. In the meantime, forcing it to 15 is a workaround (as you noted).

> Alternatively, downloading more than 1000 pictures at once

It looks like there's some limiting, I'll see if there's a way to bypass this in some way. I'll be back after some investigation on my end.

> I have no idea why the hell they STILL haven't fixed this issue

I'll take that "they" is me. The reason is that I have little free time and I prioritize issues depending on user usage/requests.

> it's been what, four or more years now and grabbing all images from derpibooru is still a problem, like fucking seriously

Note that the program is free open-source software. BTW I don't see where that "4 years" come from, given your original issue is 7 months old (which is still old indeed).

> I'd give Bionus 50 dollars to fix this issue like today

https://www.bountysource.com/issues/44893938-not-grabbing-all-images-from-derpibooru

> Guess bionus didn't want my 50 bucks, oh well.

You're a funny guy, being aggressive in order to get your issue fixed on an open-source project you didn't pay anything to use.

**Comment by Bionus** [comment]
> To combat this, I tried setting my images per page setting on the site to 15 and then start downloading, which seems to have Grabber get all images from the pages, but then it only grabs exactly 67 pages, or 1005 images.

Did you try to actually finish the download?

In the latest versions, Grabber will download images by batches of ~1,000 images: it will download the 1-67 pages, then the 1,005 images it found, then go on to pages 68-134, download their 1,005 images, etc. It's done in order to save RAM on big downloads. You can see issue #785 for details. It seems that I really need to make this clearer in the UI (or make 1-page batches).

I just tried to download 3,000 images from Derpibooru and it worked like a charm on the latest version (it downloaded 3 batches: 1005 + 1005 + 990).

**Comment by SvyraCosmix** [comment]
Thank bionus for fixing the derpibooru problem, now I just need to figure out how to place the api key so I can see the explicit images.

**Comment by SvyraCosmix** [comment]
Everything is good now. I am actually inclined to give you a donation for finally fixing the problem, I will when I have the money, you know how bills are.

**Comment by SvyraCosmix** [comment]
Just downloaded all 66,000 pictures of Luna from derpibooru and it did great, granted it took two days, but still did it. It's downloading at one file per second that's 18.3 hours, I left my computer on all night just so it could finish downloading. XD

**Comment by SvyraCosmix** [comment]
Though I do have an issue with how you can only use one open window of grabber at a time I tried to do two that would download into separate place but I had problems with one downloading into the same folder of the other it's difficult to explain, it wouldn't differentiate between the two open windows. My solution was Actual Multiple Monitors, like having two desktops running on one computer and they are actually separate but you can go between the two monitors as if it weren't and download to the same hard drive and everything except since it's separate desktops there's no problem with having two windows of grabber running cause on "separate desktops" it can differentiate between the two windows and download to separate locations. I'd open an issue about it but I can't image what goes into being able to make the grabber program run separately of each other each window of you open up, like if I wanted six windows of grabber open all downloading to separate locations it won't do that.
