### ISSUE TITLE
Improve MD5 list system

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#933]
> That also changes the way MD5s have to be stored 

You will need to built more complex MD5 list system anyway. Because current md5 list is a too much simple, it works for little md5 amount in the list, but with big amount of MD5 in the list  it will be very bad and slow.
 I mean that you need to make MD5 list as DataBase file with diffetent lists in it, according to first md5 character. So it will be 16 lists inside[0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F], so when you get new md5, you can use it's 1 char to search only in list of MD5 which started with this char. So it will make MD5 comparing almost 1600% faster and use in 16 times less memory for it. If list fo one of first chars became too big, then auto separate it to new 16 sublists according to second char... etc.
But that's for global MD5 list. Looks like separate suggestion)

**Comment by MasterPetrik** [comment]
Indeed, and a very good one for people having big MD5 lists (good memory-wise, given the current structure is already O(1) fast, being an hash map). Note that a the "database" you're suggesting is called a trie, a structure used for example to give suggestions in phone books or dictionaries.
![68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f622f62652f547269655f6578616d706c652e7376672f3132303070782d547269655f6578616d706c652e7376672e706e67](https://cloud.githubusercontent.com/assets/22294259/26459237/6e04f24c-417e-11e7-9265-d0bfdbd93848.png)

**Comment by Bionus** [comment]
What you're suggesting (as I said) is a trie.

In our case, it's not necessary to use a trie over a hashmap:
![](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Hash_table_5_0_1_1_1_1_1_LL.svg/450px-Hash_table_5_0_1_1_1_1_1_LL.svg.png)

It has an equivalent memory footprint, and O(1) complexity lookup.

Actually, I thought what Grabber used was a hash map but it turns out after double-checking that it uses a red-black tree, which is much slower. Quite the critical issue here, given adding an entry or looking up the existence of a key in a red-black tree is much slower than in a hash map for big collections:
![](https://woboq.com/blog/qmap_qhash_benchmark/bench-5.png)

So I'll fix this by replacing the current red-black tree-based map ([QMap](https://doc.qt.io/qt-5/qmap.html)) by a hash map ([QHash](https://doc.qt.io/qt-5/qhash.html)).
