### ISSUE TITLE
Compilation of CLI-Version

### ISSUE THREAD

**Issue by MrCrackR** [Bionus/imgbrd-grabber#947]
### What steps will reproduce the problem?
Follow the tutorial about the compilation on Linux ([here](https://github.com/Bionus/imgbrd-grabber/wiki/Compilation#linux)). In the section about the console usage it says that in order to use the console-version I should add _CONFIG += use_cli_ somewhere or remove the # in front of it. I searched through **every** file of the project and couldn't find the line. Compiling it without changing anything is successfull but results in an _QXcbConnection: Could not connect to display_ error, which is perfectly fine, because I'm starting it from console. Adding  _CONFIG += use_cli_ in Grabber.pri below _CONFIG += use_ssl_ or Graber.pro below _CONFIG  += ordered_ doesn't seem to make it compile as a console-version.

By the way, I didn't need to comment the lines for _QScintilla_ and _Google Breakpad_. The compilation was successfull even though I didn't download the required files.

### What is the expected behavior? What do you get instead?
Expected: Console version of grabber
Got: QXcbConnection: Could not connect to display
Aborted

### What version of the program are you using? On what operating system?
Raspbian GNU/Linux 8 (jessie)

### Please provide any additional information below
I'm new to the QT environment so it is possible that I'm doing making a very stupid mistake.
I've got two additional questions:

1. Does Grabber use the settings.ini when running a command in console?
2. Is there a way to use the restore.igl as a download-query?

**Comment by Bionus** [comment]
Ah yeah, this tutorial is not up-to-date, my bad.

A recent refactoring changed the way Grabber is built. It's now divided in three projects:
* Lib (shared logic for downloading & stuff)
* Gui (if you have an X server available)
* Cli (console version)

The Gui project, even if it can be used in the command-line with the `-c` switch, will still load things that may require an X environment.

If you build the whole project, or simply the Lib then the Cli project, there should be another binary created in `cli/build/release`. This one has no dependency on any user interface thing.

> By the way, I didn't need to comment the lines for QScintilla and Google Breakpad. The compilation was successfull even though I didn't download the required files.

Maybe you built the project in debug mode. QScintilla and Google Breakpad are only included when building it in release mode.

> Does Grabber use the settings.ini when running a command in console?

Yes, the same as the Gui version. Just make sure to put it in the correct folder so that Grabber can find it.

On Linux, it is:
* ./settings.ini (relative to the binary location)
* ./settings.ini (relative to where you run it from)
* ~/Grabber/settings.ini
* ~/.Grabber/settings.ini
* PREFIX/share/Grabber/settings.ini

So the most easy way is just to put it in the same folder as the `cli` binary file.

> Is there a way to use the restore.igl as a download-query?

You can't feed IGL files to the CLI program for the moment, no. But the IGL format is simple JSON, so you could do a small script in python to do it for you.

**Comment by MrCrackR** [comment]
Thank you so much. It is working now.

> You can't feed IGL files to the CLI program for the moment, no. But the IGL format is simple JSON, so you could do a small script in python to do it for you.


I will create a python script that fetches everything from a mysql database and feed that database over a web-interface.
