### ISSUE TITLE
Nightly versions

### ISSUE THREAD

**Issue by Bionus** [Bionus/imgbrd-grabber#967]
For some power users, or for users with critical issues which were fixed on the development version but not released yet, it could be convenient to have some way to have a the latest build available at any time.

Those versions would be built every commit on the `develop` branch and made available as a separate "Nightly" pre-release, that should be used with caution (as it could be broken at any moment).

**Comment by Bionus** [comment]
I just implemented it using the AppVeyor CI :tada:

You can therefore find the latest build automatically released here:
https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly

As written in the description though, **USE AT YOUR OWN RISK**.
These releases are triggered every time I commit something in the repo and could very well be broken.

**Comment by MasterPetrik** [comment]
> For some power users, or for users with critical issues which were fixed on the development version but not released yet, it could be convenient to have some way to have a the latest build available at any time.

I've been waiting for this for so long! Thanks!

**Comment by brodycas3** [comment]
As are were allot of us.

**Comment by MasterPetrik** [comment]
![image](https://user-images.githubusercontent.com/22294259/27518248-1d6482ca-59e4-11e7-9cda-bd7956663ed8.png)
My browser and my Win7 dislike your nightly .exe, I think it's because of missing digital signature. Do you nave no way to sign nightly files? Or it possible?

Anyway when I try to open .exe, there is an error, that tell me, that "it can't start because of Qt5Multimedia.dll is missing on my computer. Try to reinstall the programm."
![image](https://user-images.githubusercontent.com/22294259/27518261-79551e32-59e4-11e7-82f6-96a8074d4179.png)

**Comment by Bionus** [comment]
You actually have to put this file in the Grabber install folder, replacing the existing "Grabber.exe" file there.
