### ISSUE TITLE
How do I login on Grabber

### ISSUE THREAD

**Issue by ghost** [Bionus/imgbrd-grabber#976]
Grabber isn't showing hidden images which gold accounts can see.

**Comment by Bionus** [comment]
What source are you talking about?

Did you check this wiki page?
https://github.com/Bionus/imgbrd-grabber/wiki/WebsiteLogin

**Comment by Tsubasaza** [comment]
It's not showing hidden images that you can view with gold accounts on the website when you login on Grabber.

**Comment by MasterPetrik** [comment]
Once again, What website are you talking about?

**Comment by Tsubasaza** [comment]
Danbooru

**Comment by Bionus** [comment]
Did you make sure to hash the password?

The password field is supposed to contain the *hashed* password for Danbooru, and you have a hash button right beside it to generate said hash.

![image](https://user-images.githubusercontent.com/882719/27981508-f694dd36-638c-11e7-8cfc-83cf85cdba97.png)

Because AFAIK (I don't have a gold Danbooru account myself) it's been reported working by a few users.

**Comment by Tsubasaza** [comment]
Yeah I've done that and it's not showing hidden tags
