### ISSUE TITLE
Text file settings now crash in 5.4.0

### ISSUE THREAD

**Issue by Herkules97** [Bionus/imgbrd-grabber#983]
### What steps will reproduce the problem?
Adding a text file to go along with each image saved in 5.4.0

### What is the expected behavior? What do you get instead?
That it saves the setting, but instead it crashes

### How often does this problem occur?
Every time in 5.4.0

### What version of the program are you using? On what operating system?
5.4.0 /Windows 10 Pro

### Please provide any additional information below
Works fine in 5.3.3

**Comment by Bionus** [comment]
Indeed, some oversight on my part, it crashes when you add the very first external text file, I didn't realize because I have a few myself. Thanks!

I just fixed it, so you can either wait for the next update, use the latest nightly, or keep 5.4.0 and edit your `settings.ini` file manually: add this at the end of the file so that there is a dummy entry inserted:

```ini
[LogFiles]
0\content=%all%
0\filename=
0\locationType=2
0\name=Test
0\path=
0\suffix=.txt
0\uniquePath=
```

You'll then be able to edit it in the UI normally (just make sure not to delete it unless you add another first).
