### ISSUE TITLE
Can't choose install location?

### ISSUE THREAD

**Issue by brodycas3** [Bionus/imgbrd-grabber#987]
This is my second time actually installing grabber on this PC.
![huis3ec](https://user-images.githubusercontent.com/19770864/28020156-5631e750-6551-11e7-98a9-8caeadfcb147.gif)

**Comment by brodycas3** [comment]
So if you get rid of a drive after the first install it seems you can't install it to a second location.

**Comment by brodycas3** [comment]
Oh, It looks like you have to uninstall it from the control panel.

**Comment by Bionus** [comment]
So this happened when you installed Grabber on a drive, then removed the drive and tried to install Grabber again?

**Comment by brodycas3** [comment]
Yeah, exactly.

**Comment by Bionus** [comment]
In that case, while it could fall under the "won't fix" case since it's more of an InnoSetup bug, since it's already happened before I'll try to do something. The best solution would be not to try to "guess" the install location but always ask for a directory.

http://www.jrsoftware.org/ishelp/index.php?topic=setup_disabledirpage
