### ISSUE TITLE
e621(Danbooru) model is extremely unfriendly to the servers

### ISSUE THREAD

**Issue by zwagoth** [Bionus/imgbrd-grabber#995]
### What steps will reproduce the problem?
Download by tag or search on e621.net

### What is the expected behavior? What do you get instead?
One request to the .json or .xml API to obtain tags and file urls per page of results.

One request to the html, xml, json AND atom endpoints per page of results, and then one redundant request to /post/show for every post within the results. All requests occur over HTTP despite forced HTTPS redirects.

### How often does this problem occur?
Several times a week.

### What version of the program are you using? On what operating system?
User reported 5.4.2 as the version running. Said that application appeared to have corrupted a download entry and inserted wildcards.

### Please provide any additional information below
As the developer on e621.net I am trying to narrow down why this tool is making one request to /post/show for every image requested for some users and not for others. The tool seems very capable of pulling the information from the XML or JSON copies and when behaving normally, it appears to do this. When it malfunctions it makes hundreds of thousands of redundant requests without a rate limit and seems to go totally wild and download everything and anything, often repeatedly.

Ideally I'd have been able to block a specific version of it through the user agent and get users to upgrade, but the choice of a static browser impersonating user agent prevented that. e621 would really prefer it if automated tools like this used a unique user agent with the program name and version so that better access controls can be put in place if the programs are behaving in a manner that is causing problems.

I haven't been able to figure out why some users copies of this are making requests to /post/show and others are not. In local testing I haven't been able to come up with a conclusive reason. If this was fixed in a previous version, I'll deal with this issue by making an announcement and trying to encourage users to upgrade. If nothing else, I'd strongly appreciate it if you would change the user agent so that it identifies the tool and has a version number that follows the releases, as it would make my life significantly easier. It took me a long time to even track down what tool was causing this pattern of abusive requests.

**Comment by Bionus** [comment]
> One request to the .json or .xml API to obtain tags and file urls per page of results.
>
> One request to the html, xml, json AND atom endpoints per page of results, and then one redundant request to /post/show for every post within the results.

Gabber only uses one API for getting results for downloads (unless they fail in which case there's a waterfall system to the next API). JSON API is the first in the list for Danbooru so it will only use the /posts.json URL to get the list of results.

During "browsing" It also does an additional query to the HTML endpoint to get related tags information, wiki, etc.

> User reported 5.4.2 as the version running. Said that application appeared to have corrupted a download entry and inserted wildcards.

I don't really understand this sentence. What do you mean it corrupted a download entry?

> As the developer on e621.net I am trying to narrow down why this tool is making one request to /post/show for every image requested for some users and not for others. The tool seems very capable of pulling the information from the XML or JSON copies and when behaving normally, it appears to do this. When it malfunctions it makes hundreds of thousands of redundant requests without a rate limit and seems to go totally wild and download everything and anything, often repeatedly.

Grabber bases itself **a lot** on tag types (general, artist, copyright, species, etc) and those are not provided on the API endpoint. However, I agree that it is still possible to get this information by other means than a request for every image to download, by having for example a local database of tag types. But that leaves the case of tag type changes and new tags. Since this logic was implemented almost 5 years ago I simply went with the simplest solution at the time but I'd gladly change it if necessary.

The reason Grabber only sometimes does this queries is depending on the download filename format (more info here: https://github.com/Bionus/imgbrd-grabber/wiki/Filename). If the information to generate the filename is already available through the API (ex: the default `%md5%.%ext%` filename) this second call won't be done.

Since you must know the API better than me do you have any suggestion on how to achieve this without having a too big impact on the servers? I know that Nandaka's Danbooru Downloader program makes a few hundred of calls to the tags API endpoint on first launch to generate the tag information database to avoid this issue. Maybe I could do the same on my end, or bundle a not-so-up-to-date tag information with the program during installation?

> Ideally I'd have been able to block a specific version of it through the user agent and get users to upgrade, but the choice of a static browser impersonating user agent prevented that. e621 would really prefer it if automated tools like this used a unique user agent with the program name and version so that better access controls can be put in place if the programs are behaving in a manner that is causing problems.

If that can help, I can include "Grabber/X.Y.Z" in the default user-agent. The "impersonating" thing isn't really to try to bypass security, more that it was required by some servers so I just put the one I was using at the time: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0".

Would "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0 Grabber/X.Y.Z" be all right with you?

You also mention HTTPS a few times and while it's only a setting away it should indeed be enabled by default, especially if there's a forced redirect, so I'll do just that. :+1:

I really don't want to cause trouble to the site owners or start any war here, so let's summarize:
* [ ] Use HTTPS on e621 by default
* [ ] Include the version number in the user-agent
* [ ] Include a local database of tag information to not have to load the `/posts/{id}` page for every image if the filename contains `%artist%` or something of the sort
* [ ] If a tag is not present in the database, a call to either the tags API endpoint or to `/posts/{id}` will be required to get its information, **then store it and remember it for next time**

I can put those at my next top priorities for the next release and push other features for later. Would that do? Then, you'd be able to block all requests from Grabber from previous versions that make too many requests.

With this, the downloads would proceed exactly as you mentioned in your post: "one request to the .json or .xml API to obtain tags and file urls per page of results".

Lastly, I'd like to thank you for opening a ticket here and not simply blocking the program altogether :+1:
I'll do my best to develop all this ASAP and release an update (5.5.0 I guess) to reduce the load on e621 (and other sources') servers.

**Comment by zwagoth** [comment]
I'm not entirely sure what they meant by a corrupted download entry either. I am passing the information along as it was provided to me.

Having Grabber/X.Y.Z in the user agent anywhere is totally acceptable, and I understand that some sites have strange user agent requirements. I appreciate you adding it.

For tags, if artist is the tag that is required, the e621.net API actually offers this as a field when using the JSON API. It provides a distinct field that is represented as an array of strings. The XML API also offers this however I am not 100% certain what format it is provided in off hand. I don't know if this is true for other Danbooru sites or not, as e6 has deviated some from the mainline.

Other tag type information is not presented as cleanly. I can work with you to provide something more meaningful. It's been tossed around a few times serializing the most popular tags into a format and using that to provide search auto completion, but the work hasn't been done yet. Grabbing the first few pages for each tag type would be acceptable, as tag types rarely change, if that was an approach you thought would be roughly adequate.

The /post/show pages use a different method to obtain tag information for posts. It works quite efficiently for single posts but isn't appropriate for the bulk listings that the API offers, so it isn't used in that area. Overall /post/show tends to be slightly heavier hitting 

I'd much prefer it if tools like this existed. It's a service to the sites to allow users to do the actions they deem important. As long as they are performed with a non-disruptive amount of resource usage I give it a big thumbs up.

**Comment by Bionus** [comment]
> I'm not entirely sure what they meant by a corrupted download entry either. I am passing the information along as it was provided to me.

I guess we'll never know then. 🤷‍♂️

> Having Grabber/X.Y.Z in the user agent anywhere is totally acceptable, and I understand that some sites have strange user agent requirements. I appreciate you adding it.

Done, for all source on the default user-agent (following your comment on dcf94cfadee861aa84ec311a23440b34b8c66efa) - abc35c787a2fe0c4a730fcf1e1907171daab91f0

> For tags, if artist is the tag that is required, the e621.net API actually offers this as a field when using the JSON API. It provides the artist field that is represented as an array of strings. The XML API also offers this however I am not 100% certain what format it is provided in off hand. I don't know if this is true for other Danbooru sites or not, as e6 has deviated some from the mainline.

I took the "artist" tag type as an example, but that's actually for all tag types. For example, Danbooru provides one field for each tag category ([exemple](https://danbooru.donmai.us/posts.xml?tags=rating:safe)):
```xml
<post>
    ...
    <tag-string>1girl bloodnspice blush cape dark_pit fire_emblem fire_emblem:_akatsuki_no_megami fire_emblem:_kakusei fire_emblem:_souen_no_kiseki gloves headband hood ike link long_hair lucina male_focus male_my_unit_(fire_emblem:_kakusei) monochrome multiple_boys my_unit_(fire_emblem:_kakusei) short_hair sleeping smile super_smash_bros. the_legend_of_zelda the_legend_of_zelda:_the_wind_waker toon_link weapon wings</tag-string>
    <tag-string-artist>bloodnspice</tag-string-artist>
    <tag-string-character>dark_pit ike link lucina male_my_unit_(fire_emblem:_kakusei) my_unit_(fire_emblem:_kakusei) toon_link</tag-string-character>
    <tag-string-copyright>fire_emblem fire_emblem:_akatsuki_no_megami fire_emblem:_kakusei fire_emblem:_souen_no_kiseki super_smash_bros. the_legend_of_zelda the_legend_of_zelda:_the_wind_waker</tag-string-copyright>
    <tag-string-general>1girl blush cape gloves headband hood long_hair male_focus monochrome multiple_boys short_hair sleeping smile weapon wings</tag-string-general>
    ...
</post>
```
Thanks to this, no local database or second call is needed, as tags are already "typed" when using the API.

> Other tag type information is not presented as cleanly. I can work with you to provide something more meaningful. It's been tossed around a few times serializing the most popular tags into a format and using that to provide search auto completion, but the work hasn't been done yet. Grabbing the first few pages for each tag type would be acceptable, as tag types rarely change, if that was an approach you thought would be roughly adequate.

That's what I did. I myself made a few hundred calls to the tags endpoint and saved all tags in a local SQLite database that I will provide with the program (you can download a draft here: [tags.zip](https://github.com/Bionus/imgbrd-grabber/files/1157604/tags.zip)).

This way, Grabber can simply check the tags of the images returned by the API inside this database, and properly type the tags if they are present in the database. Then, when downloading, if all tags are "typed" Grabber will not do the second call to `/post/show`. I tested it locally and it was working well.

All that's left to do is update the database every time a new unknown tag is found. :smile:

**Comment by zwagoth** [comment]
Unfortunately I can't enable something like tag lists by type as an unconditional thing as it would break existing API clients, I can however look into exposing it with a URL/POST param.

**Comment by zwagoth** [comment]
I've put together a typed tags API mode. Right now the output looks akin to:

`<tags>
<general type="array">
<tag>male/male</tag>
<tag>male</tag>
<tag>anthro</tag>
<tag>blue_eyes</tag>
<tag>red_eyes</tag>
<tag>brown_hair</tag>
<tag>hair</tag>
<tag>comic</tag>
<tag>dialogue</tag>
<tag>duo</tag>
<tag>english_text</tag>
<tag>text</tag>
<tag>feral</tag>
<tag>interacial</tag>
<tag>onomatopoeia</tag>
<tag>sound_effects</tag>
<tag>open_mouth</tag>
<tag>sitting</tag>
<tag>size_difference</tag>
<tag>slit</tag>
<tag>speech_bubble</tag>
<tag>surprise</tag>
<tag>teeth</tag>
<tag>wide_eyed</tag>
</general>
<artist type="array">
<tag>herr_aardy</tag>
</artist>
<copyright type="array">
<tag>patreon</tag>
</copyright>
<character type="array">
<tag>kiwi_(herr_aardy)</tag>
<tag>tino</tag>
</character>
<species type="array">
<tag>bat</tag>
<tag>mammal</tag>
<tag>lizard</tag>
<tag>reptile</tag>
<tag>scalie</tag>
<tag>vampire</tag>
</species>
</tags>`

 for XML and the JSON is roughly the same with:
`"tags":{"general":["anus","\u003C3","2016","female","cute","fur","carpricorn","fish_tail","open_mouth","open_eye","horn","hair","chibi","tears","anthro","simple_background","blush"],"artist":["senz"],"copyright":[],"character":[],"species":["goat","caprine","mammal"]}`

I'll roll out a test run of it on e926.net later on tonight. It can be accessed by adding `typed_tags=true` to the URL parameters.

**Comment by Bionus** [comment]
Hello,

Sorry for the small delay in answering, I was away from the computer in the last few days.

> Unfortunately I can't enable something like tag lists by type as an unconditional thing as it would break existing API clients, I can however look into exposing it with a URL/POST param.

But isn't the same way Danbooru chose totally backward compatible?

Having the "tags" string remain as-is while adding new additional fields for each type of tag. Old clients use the old "tags" field, and new ones the new fields to access more complete tag information.

But I have to admit that implies providing redundant information, which is far from perfect for an API.

> I've put together a typed tags API mode.

Looks great! I'll myself do a few tries with it tonight with Grabber to be able to have neither a local tag list nor do any additional requests!

If that format is final, I can even make a release to have an immediate effect on e621 servers. And if it's not, I'll wait for your go :)

**Comment by zwagoth** [comment]
It currently isn't available on e621 itself. e9 is being used as a canary in this case. The format shouldn't change between it moving from e9 to e6. I don't have a set time frame on release yet, but I will add a reply here when I am certain.

**Comment by zwagoth** [comment]
The tag types change is now live on e621.net

**Comment by Bionus** [comment]
Great! I just added support for them in Grabber, which should therefore be included in the next release (or directly in the nightly version). :+1:

I'll try to finish the tag database too before releasing though, as it would also greatly benefit other sources that do not have typed tags (and users too).

**Comment by zwagoth** [comment]
I know it isn't related to the given issue, but I should make you aware that really large results sets are going to fail to load using the current code. There is a cap on the number of pages that can be accessed, and it is currently set to 750. However you can always access all content if you use `before_id`. To use `before_id` you omit `before_id` from the first request, and then take the lower post id from the result set and use that as the `before_id` parameter in the next request. As a sanity check it's a good idea to make sure that the `before_id` is decreasing on each iteration, or something is going wrong(this helps detect situations where an infinite loop would otherwise occur.) The bonus of this method is that you will always see the full result set, and posts won't move around between pages as a result of new/deleted posts. The caveat is that it negates any sorting orders applied. The end check condition, as before is an error, or an empty result set.

**Comment by Bionus** [comment]
Ah yeah, it's actually already done for some other sources (notably Gelbooru and Danbooru 2.0). I just added some changes to have it working on Danbooru 1.0 too, thanks. :+1:

I also noticed that even if you provide both a `before_id` parameter, if you also give a page above 750, you'll get an error.

**Comment by Bionus** [comment]
Actually this issue got closed by that commit but the "tag database" system is still under construction.
Moving the tag database-related discussion to #1033.
